Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2018-11, with the labels that each got.

#164 fix invalid chain id error
  src/wallets/web3-provider/methods/eth_sendTransaction.js
  src/wallets/web3-provider/methods/eth_signTransaction.js
  src/wallets/web3-provider/methods/utils.js
Labels: Bug, Hotfix, Ready

#166 Bug/too many decimal
  CHANGELOG.md
  src/contracts/contract-abi-eth.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/GenerateInfo/GenerateInfo.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/GenerateTx/GenerateTx.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/TxSpeedInput/TxSpeedInput.vue
  src/tokens/tokens-eth.json
  vue.config.js
Labels: Bug, Ready

#176 bug/account-balance
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.spec.js
Labels: Bug, Ready

#175 Bug/adding custom token
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Bug, Ready

#173 Bug/button missing
  CHANGELOG.md
  src/layouts/CreateWalletLayout/components/TutorialModal/TutorialModal-desktop.scss
Labels: Bug, Ready

#178 devop/replace-heroku-links
  CHANGELOG.md
  package-lock.json
  src/builds/configs/base-routes.js
  src/containers/HeaderContainer/HeaderContainer.vue
  src/dapps/BuySubdomain/routes.js
  src/dapps/RegisterDomain/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/RegisterDomain/containers/FinalizeContainer/FinalizeContainer.vue
  src/dapps/RegisterDomain/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/RegisterDomain/containers/NameForbiddenENSContainer/NameForbiddenENSContainer.vue
  src/dapps/RegisterDomain/routes.js
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/HomeLayout/components/Promo/Promo.vue
  src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.vue
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.scss
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.vue
  src/router/index.js
  src/tokens/tokens-eth.json
  vue.config.js
  yarn.lock
Labels: Devop, Ready
