Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2018-08, with the labels that each got.

#28 Design/additional pages
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/exclamation.png
  src/assets/images/icons/explanation.svg
  src/assets/images/icons/explanation2.svg
  src/components/PopOver/PopOver.scss
  src/components/PopOver/PopOver.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.scss
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/GenerateTx/GenerateTx.scss
  src/layouts/InterfaceLayout/components/GenerateTx/GenerateTx.vue
  src/layouts/InterfaceLayout/components/InformationBlock.scss
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.vue
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.vue
  src/layouts/InterfaceLayout/components/TxSpeedInput/TxSpeedInput.scss
  src/layouts/InterfaceLayout/components/TxSpeedInput/TxSpeedInput.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.scss
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.scss
  src/layouts/InterfaceLayout/containers/RegisterDomainContainer/RegisterDomainContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.scss
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.scss
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.scss
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.vue
  src/layouts/InterfaceLayout/containers/WalletNotFoundContainer/WalletNotFoundContainer.vue
  src/main.js
  src/translations/gb.js
  src/translations/popover/cn-sim.js
  src/translations/popover/cn-tr.js
  src/translations/popover/de.js
  src/translations/popover/es.js
  src/translations/popover/fi.js
  src/translations/popover/gb.js
  src/translations/popover/gr.js
  src/translations/popover/ht.js
  src/translations/popover/hu.js
  src/translations/popover/id.js
  src/translations/popover/ir.js
  src/translations/popover/it.js
  src/translations/popover/jp.js
  src/translations/popover/kr.js
  src/translations/popover/nl.js
  src/translations/popover/no.js
  src/translations/popover/pl.js
  src/translations/popover/pt.js
  src/translations/popover/rs.js
  src/translations/popover/th.js
  src/translations/popover/tr.js
  src/translations/popover/vn.js
Labels: Enhancement, Ready

#29 Ui/footer update
  CHANGELOG.md
  src/containers/FooterContainer/FooterContainer.scss
  src/containers/FooterContainer/FooterContainer.vue
  src/scss/GlobalVariables.scss
  src/translations/footer/gb.js
Labels: Devop, Ready

#27 Feature/custom tokens and networks
  CHANGELOG.md
  package-lock.json
  package.json
  src/App.vue
  src/configs/networks/nodes/rop-mew.js
  src/configs/networks/types/ROP.js
  src/configs/networks/types/index.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.scss
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.scss
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.scss
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/index.js
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/store/state.js
  src/translations/popover/cn-sim.js
  src/translations/popover/cn-tr.js
  src/translations/popover/de.js
  src/translations/popover/es.js
  src/translations/popover/fi.js
  src/translations/popover/gb.js
  src/translations/popover/gr.js
  src/translations/popover/ht.js
  src/translations/popover/hu.js
  src/translations/popover/id.js
  src/translations/popover/ir.js
  src/translations/popover/it.js
  src/translations/popover/jp.js
  src/translations/popover/kr.js
  src/translations/popover/nl.js
  src/translations/popover/no.js
  src/translations/popover/pl.js
  src/translations/popover/pt.js
  src/translations/popover/rs.js
  src/translations/popover/th.js
  src/translations/popover/tr.js
  src/translations/popover/vn.js
Labels: Feature, Ready

#34 devop/sync-repo
  package.json
Labels: Devop, Ready

#70 Devop/setup stale
  .github/stale.yml
  .travis.yml
  CHANGELOG.md
  package-lock.json
Labels: Devop, Ready

#74 Translations to json
  crowdin.yml
  src/translations/access-wallet/en_US.js
  src/translations/access-wallet/en_US.json
  src/translations/common/en_US.js
  src/translations/common/en_US.json
  src/translations/create-wallet/en_US.js
  src/translations/create-wallet/en_US.json
  src/translations/footer/en_US.js
  src/translations/footer/en_US.json
  src/translations/header/en_US.js
  src/translations/header/en_US.json
  src/translations/home/en_US.js
  src/translations/home/en_US.json
  src/translations/interface/en_US.js
  src/translations/interface/en_US.json
  src/translations/popover/en_US.js
  src/translations/popover/en_US.json
  src/translations/privacy-policy/en_US.js
  src/translations/privacy-policy/en_US.json
  src/translations/team/en_US.js
  src/translations/team/en_US.json
  src/translations/terms-of-conditions/en_US.js
  src/translations/terms-of-conditions/en_US.json
Labels: Devop, Ready

#77 Devop/compress img
  CHANGELOG.md
  package-lock.json
  package.json
  vue.config.js
Labels: Devop, Ready

#76 Feature/secalot cleanup
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/misc.js
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/wallets/hardware/secalot/secalotEth.js
  src/wallets/hardware/secalot/secalotWallet.js
  vue.config.js
Labels: Feature, Ready
