Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2018-12, with the labels that each got.

#183 devop/replace-token-contract
  CHANGELOG.md
  package-lock.json
  package.json
  src/contracts/contract-abi-eth.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/SendTx/SendTx.vue
  src/tokens/tokens-eth.json
Labels: Devop, Ready

#185 devop/fix-send-and-dapps
  CHANGELOG.md
  src/contracts/contract-abi-eth.json
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
  src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.vue
  src/tokens/tokens-eth.json
  src/wallets/web3-provider/methods/eth_getTransactionCount.js
  src/wallets/web3-provider/methods/eth_sendTransaction.js
Labels: Devop, Ready

#216 add support for ledger live paths
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/wallets/bip44/ledgerPaths.js
  src/wallets/hardware/ledger/index.js
Labels: Ready

#206 reimplement chainid calculation and update for bitbox v5
  CHANGELOG.md
  src/wallets/WalletInterface.js
  src/wallets/hardware/bitbox/digitalBitboxEth.js
  src/wallets/hardware/bitbox/digitalBitboxUsb.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/index.js
  src/wallets/hardware/trezor/index.js
  src/wallets/hybrid/MEWconnect/index.js
  src/wallets/software/mnemonic/index.js
  src/wallets/utils.js
Labels: Devop, Ready

#261 Safe external links and meta descriptions
  CHANGELOG.md
  public/index.html
  src/components/Buttons/HelpCenterButton/HelpCenterButton.vue
  src/components/CustomerSupport/CustomerSupport.vue
  src/components/FaqContents/BalancesNotLoadingOrShowingOnMyEtherWallet.vue
  src/components/FaqContents/CheckTheCurrentBlockNumberOnMyEtherWallet.vue
  src/components/FaqContents/CouldntEverybodyPutInRandomPrivateKeys.vue
  src/components/FaqContents/DoesMyEtherWalletSupportBitcoinOrOtherCoins.vue
  src/components/FaqContents/EthOrTokensSentToOrFromExchangeHaventShownUp.vue
  src/components/FaqContents/HowDoIInteractWithAMultisigContract.vue
  src/components/FaqContents/WhatHappensIfMyEtherWalletGoesDown.vue
  src/components/FaqContents/WhatIsAnIco.vue
  src/components/FaqContents/WhereCanIBuySellTradeExchangeMyEthOrTokens.vue
  src/components/FaqContents/WhyDontYouMakeMeMoveMyMouseToGenerateASeed.vue
  src/components/FaqContents/WithdrawingDAOTokens.vue
  src/components/FeedbackModal/FeedbackModal.vue
  src/components/InterfaceBottomText/InterfaceBottomText.vue
  src/components/Notification/Notification.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.vue
  src/containers/FaqsContainer/FaqsContainer.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/dapps/RegisterDomain/components/FinalizeModal/FinalizeModal.vue
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/GettingStarted/components/Congratulations/Congratulations.vue
  src/layouts/GettingStarted/components/SomeHelpfulTips/SomeHelpfulTips.vue
  src/layouts/GettingStarted/components/WhereAreMyFundsStored/WhereAreMyFundsStored.vue
  src/layouts/HelpCenterLayout/components/LinkBlock/LinkBlock.vue
  src/layouts/HomeLayout/components/Social/Social.vue
  src/layouts/InformationPages/AdvancedToolsLayout/AdvancedToolsLayout.vue
  src/layouts/InformationPages/ExtensionsLayout/ExtensionsLayout.vue
  src/layouts/TxStatusLayout/TxStatusLayout.vue
  src/wallets/hardware/bitbox/digitalBitboxEth.js
  tests/unit/specs/src/components/InterfaceBottomText/InterfaceBottomText.spec.js
Labels: Devop, Ready

#262 Bug/token fetching
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/RegisterDomain/RegisterDomain.vue
  src/helpers/sortByBalance.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/tokens/tokens-eth.json
  tests/unit/specs/src/layouts/HomeLayout/components/Social/Social.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
  tests/unit/specs/src/partners/kyber/kyber.spec.js
Labels: Bug, Ready

#255 bug/network-modal
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.scss
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/networks/nodes/aka-rpc.js
  src/networks/nodes/etc-epool.js
  src/networks/nodes/eth-giveth.js
  src/networks/nodes/etsc.js
  src/networks/nodes/exp.js
  src/networks/nodes/index.js
  src/networks/nodes/tomo.js
  src/networks/types/ETSC.js
  src/networks/types/index.js
  src/store/actions.js
  src/store/state.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
  tests/unit/specs/src/dapps/RegisterDomain/containers/EnsBidContainer/EnsBidContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.spec.js
Labels: Bug, Ready

#280 Travis Release Setup
  .dockerignore
  .gitignore
  .travis.yml
  CHANGELOG.md
  deploy.sh
  ipfs-host.pem.enc
  release.sh
  ssh-keys.tar.enc
Labels: Devop, Ready

#279 hotfix/remove-type
  .dockerignore
  .eslintrc.js
  .gitignore
  .travis.yml
  CHANGELOG.md
  Dockerfile
  deploy.sh
  ipfs-host.pem.enc
  package-lock.json
  package-test.js
  package.json
  release.sh
  src/builds/configs/index.js
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/networks/types/EXP.js
  src/networks/types/index.js
  src/wallets/hardware/bitbox/digitalBitboxEth.js
  src/wallets/web3-provider/methods/eth_sendTransaction.js
  ssh-keys.tar.enc
  tests/unit/specs/src/containers/FaqsContainer/FaqsContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomain/containers/EnsBidContainer/EnsBidContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
  vue.config.js
Labels: Bug, Ready

#302 devop/green-keeper-changes
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/RegisterDomain/containers/EnsBidContainer/EnsBidContainer.vue
  src/tokens/tokens-eth.json
Labels: Devop, Ready

#276 Ui/GitHub fixes
  CHANGELOG.md
  package-lock.json
  src/components/Buttons/ButtonWithQrCode/ButtonWithQrCode.vue
  src/components/IssueLogModal/IssueLogModal.scss
  src/components/IssueLogModal/IssueLogModal.vue
  src/components/IssueLogModal/index.js
  src/components/Notification/Notification.scss
  src/components/Notification/Notification.vue
  src/components/NotificationsModal/NotificationsModal.vue
  src/components/StandardInput/StandardInput.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmModal.scss
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.vue
  src/containers/FooterContainer/FooterContainer-desktop.scss
  src/containers/FooterContainer/FooterContainer-mobile.scss
  src/containers/FooterContainer/FooterContainer-tablet.scss
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.scss
  src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer-mobile.scss
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer-tablet.scss
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/GenerateTx/GenerateTx.scss
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/GenerateTx/GenerateTx.vue
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/tokens/tokens-eth.json
  src/translations/common/en_US.json
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.spec.js
Labels: Devop, Ready

#291 Adding RSK networks
  package-lock.json
  src/assets/images/networks/rsk.svg
  src/contracts/contract-abi-rsk-test.json
  src/contracts/contract-abi-rsk.json
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/networks/nodes/index.js
  src/networks/nodes/rsk-public.js
  src/networks/nodes/rsk-test-public.js
  src/networks/types/RSK.js
  src/networks/types/RSKTEST.js
  src/networks/types/index.js
  src/tokens/tokens-rsk-test.json
  src/tokens/tokens-rsk.json
Labels: Enhancement, Ready

#308 cleanup unused files, fixes #187
  src/components/ConfirmationModal/ConfirmationModal.scss
  src/components/ConfirmationModal/ConfirmationModal.vue
  src/components/ConfirmationModal/index.js
  src/layouts/TxStatusLayout/TxStatusLayout.scss
  src/layouts/TxStatusLayout/TxStatusLayout.vue
  src/layouts/TxStatusLayout/index.js
  vue.config.js
Labels: Ready

#287 Ui/fix settings modal
  CHANGELOG.md
  package-lock.json
  src/builds/web/app.vue
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.vue
  src/scss/CustomModal-desktop.scss
  src/scss/CustomModal-mobile.scss
  src/scss/CustomModal-tablet.scss
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/scss/Global-tablet.scss
Labels: Hotfix, Ready

#307 devop/remove-etc
  CHANGELOG.md
  package-lock.json
  src/assets/images/icons/acknowledge.png
  src/assets/images/icons/arrow.png
  src/builds/web/app.vue
  src/components/Buttons/StandardButton/StandardButton.scss
  src/components/Buttons/StandardButton/StandardButton.vue
  src/components/ConfirmationModal/ConfirmationModal.scss
  src/components/ConfirmationModal/ConfirmationModal.vue
  src/components/ConfirmationModal/index.js
  src/components/LogoutWarningModal/LogoutWarningModal.scss
  src/components/LogoutWarningModal/LogoutWarningModal.vue
  src/components/LogoutWarningModal/index.js
  src/components/ScrollUpButton/ScrollUpButton.scss
  src/components/ScrollUpButton/ScrollUpButton.vue
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
  src/components/TxTopMenuPopup/TxTopMenuPopup.scss
  src/components/TxTopMenuPopup/TxTopMenuPopup.vue
  src/components/TxTopMenuPopup/components/TxInfoBlock/TxInfoBlock.scss
  src/components/TxTopMenuPopup/components/TxInfoBlock/TxInfoBlock.vue
  src/components/TxTopMenuPopup/components/TxInfoBlock/index.js
  src/components/TxTopMenuPopup/index.js
  src/components/UserReminderButton/UserReminderButton.scss
  src/components/UserReminderButton/UserReminderButton.vue
  src/components/UserReminderButton/index.js
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/contracts/contract-abi-rsk-test.json
  src/contracts/contract-abi-rsk.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.vue
  src/layouts/TxStatusLayout/TxStatusLayout.scss
  src/layouts/TxStatusLayout/TxStatusLayout.vue
  src/layouts/TxStatusLayout/index.js
  src/networks/nodes/etc-etccoop.js
  src/networks/nodes/index.js
  src/scss/CustomModal-desktop.scss
  src/scss/CustomModal-mobile.scss
  src/scss/CustomModal-tablet.scss
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/scss/Global-tablet.scss
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  vue.config.js
Labels: Devop, Ready
