Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-02, with the labels that each got.

#538 Devop/fixes
  CHANGELOG.md
  package-lock.json
  src/assets/images/icons/domain-hov.svg
  src/assets/images/icons/domain-sale-hov.svg
  src/components/Buttons/StandardButton/StandardButton.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/dapps/RegisterDomain/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/index.js
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.scss
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/store/state.js
  src/translations/dapps/en_US.json
  src/translations/dapps/es_ES.json
  src/translations/dapps/ja_JP.json
  src/translations/dapps/ko_KR.json
  src/translations/dapps/ru_RU.json
  src/translations/dapps/zh_CN.json
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/FinalizeContainer/FinalizeContainer.vue
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/ManageENSContainer/ManageENSContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/ManageENSContainer/ManageENSContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/DappButtons/DappButtons.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.spec.js
Labels: Devop, Ready

#536 Devop/interact w contract
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/dapps/RegisterDomain/components/JsonStringModal/JsonStringModal.vue
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.scss
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.scss
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/networks/nodes/etc-gastracker.js
  src/networks/nodes/index.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
Labels: Devop, Ready

#529 devop/logout-text
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/domain-hov.svg
  src/assets/images/icons/domain-sale-hov.svg
  src/components/Buttons/StandardButton/StandardButton.vue
  src/components/LogoutModal/LogoutModal.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/dapps/RegisterDomain/components/JsonStringModal/JsonStringModal.vue
  src/dapps/RegisterDomain/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/index.js
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.scss
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.scss
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.scss
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/networks/nodes/etc-gastracker.js
  src/networks/nodes/index.js
  src/store/actions.js
  src/store/state.js
  src/translations/dapps/en_US.json
  src/translations/dapps/es_ES.json
  src/translations/dapps/ja_JP.json
  src/translations/dapps/ko_KR.json
  src/translations/dapps/ru_RU.json
  src/translations/dapps/zh_CN.json
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/FinalizeContainer/FinalizeContainer.vue
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/ManageENSContainer/ManageENSContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/ManageENSContainer/ManageENSContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/DappButtons/DappButtons.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
Labels: Devop, Ready

#551 Devop/babel jest update delay
  package-test.js
Labels: Ready

#559 enable custom chain id when adding a custom network
  package-lock.json
  package-test.js
  package.json
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
Labels: Ready

#550 Devop/complete custom hd paths
  CHANGELOG.md
  package-lock.json
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/store/actions.js
  src/store/mutations.js
  src/translations/access-wallet/en_US.json
Labels: Ready

#571 Feature/welcome to mew
  CHANGELOG.md
  src/builds/web/app.vue
  src/components/WelcomeModal/WelcomeModal.scss
  src/components/WelcomeModal/WelcomeModal.vue
  src/components/WelcomeModal/index.js
  src/darklist/address-darklist.json
  src/translations/home/en_US.json
  src/translations/home/es_ES.json
  src/translations/home/ja_JP.json
  src/translations/home/ko_KR.json
  src/translations/home/ru_RU.json
  src/translations/home/zh_CN.json
Labels: Feature, Ready

#569 Ui dev/fix getting started
  CHANGELOG.md
  src/darklist/address-darklist.json
  src/layouts/GettingStarted/GettingStarted-mobile.scss
  src/layouts/GettingStarted/GettingStarted.vue
  src/layouts/GettingStarted/components/BlockWithProgressBar-desktop.scss
  src/layouts/GettingStarted/components/BlockWithProgressBar-mobile.scss
  src/layouts/GettingStarted/components/BlockWithProgressBar-tablet.scss
Labels: Ready

#566 Fix access my wallet icons
  CHANGELOG.md
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer-tablet.scss
Labels: Ready

#573 Devop/setup sentry
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchEthListData.js
  package-lock.json
  package.json
  src/components/IssueLogModal/IssueLogModal.scss
  src/components/IssueLogModal/IssueLogModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/darklist/address-darklist.json
  src/helpers/errorHandler.js
  src/helpers/index.js
  src/helpers/messageUtil.js
  src/helpers/notificationFormatters/formatters.js
  src/helpers/notificationFormatters/utils.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/components/MnemonicPasswordModal/MnemonicPasswordModal.vue
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/main.js
  src/partners/bity/bity.js
  src/partners/changelly/changelly.js
  src/wallets/hardware/bitbox/index.js
  src/workers/wallet.worker.js
Labels: Devop, Ready

#561 devop/byte-32
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Notification/components/NotificationTypes/TransactionNotification/TransactionNotification.vue
  src/components/Notification/components/config.js
  src/darklist/address-darklist.json
  src/helpers/misc.js
  src/helpers/notificationFormatters/config.js
  src/helpers/notificationFormatters/formatters.js
  src/helpers/solidityTypes.js
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.scss
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/translations/common/en_US.json
  src/translations/header/en_US.json
Labels: Devop, Ready

#575 hotfix/multiple-fixes
  CHANGELOG.md
  ENV_VARS.js
  package-lock.json
  package.json
  src/darklist/address-darklist.json
  src/layouts/GettingStarted/GettingStarted.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/main.js
  src/partners/simplex/simplex.js
Labels: Ready

#579 Ui dev/fix swap provider ui
  CHANGELOG.md
  package-lock.json
  package.json
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProviderInfoList/ProviderInfoList.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProviderInfoList/ProviderInfoList.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.scss
  src/tokens/tokens-eth.json
Labels: Ready

#580 Devop/swap simplex revisions
  CHANGELOG.md
  package-lock.json
  package.json
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/main.js
  src/partners/partners.js
  src/partners/simplex/simplex.js
  src/tokens/tokens-eth.json
Labels: Ready

#554 Supply gasPrice to estimateGas
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
Labels: Ready

#581 Devop/keepkey affiliate and mew connect link
  CHANGELOG.md
  src/assets/images/etc/mewconnect.jpeg
  src/assets/images/etc/mewconnectad.png
  src/builds/web/app.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/darklist/address-darklist.json
  src/layouts/GettingStarted/GettingStarted.vue
  src/layouts/GettingStarted/components/Congratulations/Congratulations.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
  src/store/state.js
  src/tokens/tokens-eth.json
  src/tokens/tokens-rop.json
Labels: Devop, Ready

#564 Ui dev/fix mobile menu
  CHANGELOG.md
  package-lock.json
  src/assets/images/icons/balance.svg
  src/assets/images/icons/qr-code-white.svg
  src/assets/images/icons/wallet.svg
  src/components/AddressQrcodeModal/AddressQrcodeModal.scss
  src/components/AddressQrcodeModal/AddressQrcodeModal.vue
  src/components/AddressQrcodeModal/index.js
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileAddressBlock/MobileAddressBlock.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileAddressBlock/MobileAddressBlock.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileAddressBlock/index.js
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/index.js
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/index.js
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuButton/MobileMenuButton.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuButton/MobileMenuButton.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuButton/index.js
  src/containers/HeaderContainer/components/MobileMenu/components/MobileNetworkBlock/MobileNetworkBlock.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileNetworkBlock/MobileNetworkBlock.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileNetworkBlock/index.js
  src/containers/HeaderContainer/components/MobileMenu/index.js
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/InterfaceLayout-desktop.scss
  src/layouts/InterfaceLayout/InterfaceLayout-mobile.scss
  src/layouts/InterfaceLayout/InterfaceLayout-tablet.scss
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InformationBlock.scss
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.scss
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.vue
  src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.vue
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.scss
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.vue
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.scss
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.scss
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/index.js
  src/scss/GlobalVariables.scss
  src/translations/common/en_US.json
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.spec.js
Labels: Ready

#583 Devop/refactor custom tokens
  CHANGELOG.md
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Devop, Ready

#589 Devop/sentry fixes and ENS Test Integration
  CHANGELOG.md
  jest.config.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/beta.png
  src/assets/images/icons/hardware-disable.svg
  src/assets/images/icons/metamask-disable.svg
  src/assets/images/icons/mewconnect-disable.svg
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/dapps/RegisterDomain/ABI/deedContractAbi.js
  src/dapps/RegisterDomain/ABI/fifsRegistrarAbi.js
  src/dapps/RegisterDomain/ABI/registrarAbi.js
  src/dapps/RegisterDomain/ABI/registryAbi.js
  src/dapps/RegisterDomain/ABI/resolverAbi.js
  src/dapps/RegisterDomain/RegisterDomain.vue
  src/dapps/RegisterDomain/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/RegisterDomain/containers/EnsBidContainer/EnsBidContainer.vue
  src/dapps/RegisterDomain/containers/FifsBuyContainer/FifsBuyContainer.scss
  src/dapps/RegisterDomain/containers/FifsBuyContainer/FifsBuyContainer.vue
  src/dapps/RegisterDomain/containers/FifsBuyContainer/index.js
  src/dapps/RegisterDomain/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/dapps/RegisterDomain/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/RegisterDomain/routes.js
  src/dapps/index.js
  src/darklist/address-darklist.json
  src/helpers/misc.js
  src/helpers/registrarAbi.js
  src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.vue
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/networks/ensAbis/index.js
  src/networks/ensAbis/rin.js
  src/networks/ensAbis/rop.js
  src/networks/types/ETH.js
  src/networks/types/GOERLI.js
  src/networks/types/RIN.js
  src/networks/types/ROP.js
  src/networks/types/RSK.js
  src/store/mutations.js
  src/store/state.js
  src/translations/dapps/en_US.json
  src/wallets/hardware/ledger/errorHandler.js
  tests/unit/helpers/mockStore.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/EnsBidContainer/EnsBidContainer.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/InterfaceLayout.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.spec.js
Labels: Ready

#596 update internal partner currency lists
  CHANGELOG.md
  src/dapps/index.js
  src/darklist/address-darklist.json
  src/partners/changelly/config/currencies.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/partnersConfig/EthereumTokens.js
Labels: Ready

#597 Fix/safe send
  CHANGELOG.md
  src/dapps/SecureTransaction/SecureTransaction.scss
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/dapps/index.js
Labels: Ready

#598 Add link
  CHANGELOG.md
  src/components/WelcomeModal/WelcomeModal.vue
Labels: Devop

#590 Devop/fetch errors
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/partners/bity/bity-calls.js
  src/partners/bity/bity.js
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly-calls.js
  src/partners/changelly/changelly.js
  src/partners/helpers/utils.js
  src/partners/kyber/kyber-api.js
  src/partners/kyber/kyber-calls.js
  src/partners/kyber/kyber.js
  src/partners/simplex/simplex-api.js
  src/partners/simplex/simplex.js
Labels: Ready

#600 Release Prep
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/mew-screen.png
  src/components/WelcomeModal/WelcomeModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/dapps/BuySubdomain/BuySubdomain.vue
  src/dapps/SecureTransaction/SecureTransaction.scss
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/dapps/index.js
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/partners/bity/bity-calls.js
  src/partners/bity/bity.js
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly-calls.js
  src/partners/changelly/changelly.js
  src/partners/helpers/utils.js
  src/partners/kyber/kyber-api.js
  src/partners/kyber/kyber-calls.js
  src/partners/kyber/kyber.js
  src/partners/simplex/simplex-api.js
  src/partners/simplex/simplex.js
  src/translations/dapps/en_US.json
  src/wallets/web3-provider/providers/ws-provider.js
  tests/unit/__mocks__/worker-timers.js
  tests/unit/helpers/index.js
  vue.config.js
Labels: Ready

#602 Release v5.0.0 (Venus)
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/mew-screen.png
  src/components/WelcomeModal/WelcomeModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/dapps/BuySubdomain/BuySubdomain.vue
  src/dapps/SecureTransaction/SecureTransaction.scss
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/dapps/index.js
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/partners/bity/bity-calls.js
  src/partners/bity/bity.js
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly-calls.js
  src/partners/changelly/changelly.js
  src/partners/helpers/utils.js
  src/partners/kyber/kyber-api.js
  src/partners/kyber/kyber-calls.js
  src/partners/kyber/kyber.js
  src/partners/simplex/simplex-api.js
  src/partners/simplex/simplex.js
  src/translations/dapps/en_US.json
  src/wallets/web3-provider/providers/ws-provider.js
  tests/unit/__mocks__/worker-timers.js
  tests/unit/helpers/index.js
  vue.config.js
Labels: Ready, Release

#611 Fix Access my wallet -> Access by Mnemonic Phrase 12/24 radio button
  CHANGELOG.md
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal.vue
  tests/unit/__mocks__/worker-timers.js
Labels: Ready

#619 devop/fix-foreach-issue
  CHANGELOG.md
  src/components/SettingsModal/SettingsModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
Labels: Devop, Ready

#618 Devop/disable hws when unsupported
  CHANGELOG.md
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
Labels: Devop, Ready

#616 Ui/fix mew connect modal
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-desktop.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-mobile.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
Labels: Ready

#615 Ui/fix getting started
  CHANGELOG.md
  src/components/Buttons/StandardButton/StandardButton.scss
  src/layouts/GettingStarted/GettingStarted-desktop.scss
  src/layouts/GettingStarted/GettingStarted.vue
  src/layouts/GettingStarted/components/BlockWithProgressBar-desktop.scss
  src/layouts/GettingStarted/components/Congratulations/Congratulations.vue
  tests/unit/specs/src/layouts/GettingStarted/GettingStarted.spec.js
Labels: Ready

#613 Fix/bugs and more
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/mouse.svg
  src/components/Buttons/StandardButton/StandardButton.scss
  src/components/Notification/Notification.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-desktop.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-mobile.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/ConvertUnits/components/DropDownUnitSelector/DropDownUnitSelector.vue
  src/layouts/GettingStarted/GettingStarted-desktop.scss
  src/layouts/GettingStarted/GettingStarted.vue
  src/layouts/GettingStarted/components/BlockWithProgressBar-desktop.scss
  src/layouts/GettingStarted/components/Congratulations/Congratulations.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/tokens/tokens-eth.json
  src/translations/common/en_US.json
  src/wallets/hardware/bitbox/digitalBitboxUsb.js
  src/wallets/hardware/bitbox/errorHandler.js
  src/wallets/hardware/secalot/errorHandler.js
  src/wallets/hardware/secalot/secalotUsb.js
  src/wallets/web3-provider/providers/etherscan-provider.js
  src/wallets/web3-provider/providers/ws-provider.js
  src/wallets/web3-provider/providers/ws-web3-provider.js
  tests/unit/specs/src/layouts/GettingStarted/GettingStarted.spec.js
  vue.config.js
Labels: Ready

#636 Update foorter padding size
  CHANGELOG.md
  src/containers/FooterContainer/FooterContainer-mobile.scss
  src/darklist/address-darklist.json
  src/tokens/tokens-eth.json
Labels: Ready

#629 Responsive UI update for Network and Address model [5.0.2]
  CHANGELOG.md
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-mobile.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-tablet.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/scss/Global-mobile.scss
  src/tokens/tokens-eth.json
Labels: Ready

#631 Devop/enable mew connect for other browsers [5.0.2]
  CHANGELOG.md
  package-lock.json
  src/components/LogoutWarningModal/LogoutWarningModal.vue
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
Labels: Devop, Ready

#632 Fix welcome modal [5.0.2]
  CHANGELOG.md
  src/components/WelcomeModal/WelcomeModal.scss
  src/components/WelcomeModal/WelcomeModal.vue
  src/darklist/address-darklist.json
Labels: Ready

#647 Fix modal UI for Access my wallet
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.scss
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-desktop.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-mobile.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-tablet.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
Labels: Ready

#644 Fix Send ETH & Tokens UI
  CHANGELOG.md
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/containers/InterfaceContainer.scss
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.scss
Labels: Ready

#646 Bug/custom token send and balance load
  .gitignore
  CHANGELOG.md
  package-lock.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.spec.js
Labels: Bug, Ready

#649 Mandatory password input for Get a New Wallet -> Mnemonic Phrase
  CHANGELOG.md
  src/darklist/address-darklist.json
  src/layouts/CreateWalletLayout/components/CreateWalletInput/CreateWalletInput.vue
Labels: Ready

#651 Fix mobile settings [5.0.2]
  CHANGELOG.md
  src/components/Buttons/StandardButton/StandardButton.scss
  src/components/Buttons/StandardButton/StandardButton.vue
  src/components/FullWidthDropdownMenu/FullWidthDropdownMenu.scss
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
Labels: Ready

#617 Feature/error toast [5.0.2]
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/toast-err.svg
  src/assets/images/icons/toast-success.svg
  src/assets/images/icons/toast-warn.svg
  src/builds/web/app.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.vue
  src/dapps/BuySubdomain/BuySubdomain.vue
  src/dapps/RegisterDomain/RegisterDomain.vue
  src/dapps/RegisterDomain/containers/EnsBidContainer/EnsBidContainer.vue
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/darklist/address-darklist.json
  src/helpers/errorHandler.js
  src/helpers/index.js
  src/helpers/messageUtil.js
  src/helpers/responseHandler/index.js
  src/helpers/responseHandler/responseEvents.js
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/components/MnemonicPasswordModal/MnemonicPasswordModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.vue
  src/layouts/HomeLayout/HomeLayout.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/main.js
  src/partners/bity/bity.js
  src/partners/changelly/changelly.js
  src/registerServiceWorker.js
  src/scss/Global-desktop.scss
  src/scss/GlobalVariables.scss
  src/toast.config.js
  src/tokens/tokens-eth.json
  src/wallets/hardware/bitbox/errorHandler.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/keepkey/errorHandler.js
  src/wallets/hardware/ledger/errorHandler.js
  src/wallets/hardware/secalot/errorHandler.js
  src/wallets/hardware/trezor/errorHandler.js
  src/wallets/hybrid/MEWconnect/errorHandler.js
  src/wallets/software/mnemonic/errorHandler.js
  src/wallets/software/web3wallet/errorHandler.js
Labels: Feature, Ready

#658 Devop/minor fixes
  CHANGELOG.md
  package-lock.json
  package.json
  src/darklist/address-darklist.json
  src/toast.config.js
Labels: Devop, Ready

#682 bug/fix-nan-in-settings
  CHANGELOG.md
  src/components/SettingsModal/SettingsModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/darklist/address-darklist.json
  src/wallets/web3-provider/methods/eth_sendTransaction.js
Labels: Bug, Ready

#684 Dev/fix logout warning modal
  CHANGELOG.md
  src/builds/web/app.vue
  src/components/LogoutWarningModal/LogoutWarningModal.scss
  src/components/LogoutWarningModal/LogoutWarningModal.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/wallets/web3-provider/methods/eth_sendTransaction.js
Labels: Ready

#679 Update notification dot
  CHANGELOG.md
  src/components/Notification/Notification.scss
  src/components/Notification/Notification.vue
Labels: Ready

#677 Ui/update frontpage ui
  CHANGELOG.md
  src/containers/AboutContainer/AboutContainer-tablet.scss
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-tablet.scss
  src/scss/Global-desktop.scss
Labels: Ready

#660 devop/include-sw-error
  CHANGELOG.md
  src/builds/web/app.vue
  src/registerServiceWorker.js
Labels: Devop, Ready

#661 devop/send-offline-fix
  CHANGELOG.md
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
Labels: Devop, Ready

#676 Fix popover UI bug
  CHANGELOG.md
  package-lock.json
  src/components/PopOver/PopOver-desktop.scss
  src/components/PopOver/PopOver-mobile.scss
  src/components/PopOver/PopOver-tablet.scss
  src/darklist/address-darklist.json
  src/layouts/CreateWalletLayout/CreateWalletLayout-desktop.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout-mobile.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout-tablet.scss
Labels: Ready

#665 devop/update-access-buttons
  CHANGELOG.md
  src/assets/images/icons/button-hardware-disabled.svg
  src/assets/images/icons/button-metamask-disabled.svg
  src/assets/images/icons/button-mewconnect-disabled.svg
  src/assets/images/icons/button-software-disabled.svg
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/tokens/tokens-eth.json
Labels: Devop, Ready

#663 Ui/fix send offline helper
  CHANGELOG.md
  package-lock.json
  src/components/AccordionMenu/AccordionMenu.scss
  src/components/AccordionMenu/AccordionMenu.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.scss
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Ready

#672 Devop/add missing nodes
  CHANGELOG.md
  package-lock.json
  src/assets/images/icons/button-hardware-disabled.svg
  src/assets/images/icons/button-metamask-disabled.svg
  src/assets/images/icons/button-mewconnect-disabled.svg
  src/assets/images/icons/button-software-disabled.svg
  src/components/PopOver/PopOver-desktop.scss
  src/components/PopOver/PopOver-mobile.scss
  src/components/PopOver/PopOver-tablet.scss
  src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout-desktop.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout-mobile.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout-tablet.scss
Labels: Devop, Ready

#669 Devop/swap ui improvements
  CHANGELOG.md
  compileBaseSwapOptions.js
  package-lock.json
  package.json
  src/components/Buttons/StandardButton/StandardButton.vue
  src/components/Notification/Notification.vue
  src/components/Notification/components/NotificationTypes/SwapDetails/SwapDetails.vue
  src/layouts/InterfaceLayout/components/InterfaceContainerTitle/InterfaceContainerTitle.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/partners/bity/bity.js
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly-calls.js
  src/partners/changelly/changelly.js
  src/partners/changelly/config/config.js
  src/partners/changelly/config/currencies.js
  src/partners/helpers/utils.js
  src/partners/index.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/partners.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/OtherCoins.js
  src/partners/partnersConfig/index.js
  src/translations/header/en_US.json
  src/translations/interface/en_US.json
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
Labels: Ready

#694 Fix Send TX confirmation modal
  CHANGELOG.md
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.scss
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
Labels: Ready

#702 Devop/fix test branch
  jest.config.js
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  tests/unit/helpers/mockStore.js
  tests/unit/helpers/setupTooling.js
  tests/unit/specs/src/components/DropDownAddressSelector/DropDownAddressSelector.spec.js
  tests/unit/specs/src/components/Notification/Notification.spec.js
  tests/unit/specs/src/components/PopOver/PopOver.spec.js
  tests/unit/specs/src/components/ScrollUpButton/ScrollUpButton.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/ConfirmationContainer.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.spec.js
  tests/unit/specs/src/containers/FaqsContainer/FaqsContainer.spec.js
  tests/unit/specs/src/containers/FooterContainer/FooterContainer.spec.js
  tests/unit/specs/src/containers/HeaderContainer/HeaderContainer.spec.js
  tests/unit/specs/src/dapps/BuySubdomain/BuySubdomain.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/RegisterDomainContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/components/FinalizeModal/FinalizeModal.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/EnsBidContainer/EnsBidContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/ManageENSContainer/ManageENSContainer.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/AccessWalletLayout.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/CreateWalletLayout.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/components/CreateWalletInput/CreateWalletInput.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/components/TutorialModal/TutorialModal.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.spec.js
  tests/unit/specs/src/layouts/GettingStarted/GettingStarted.spec.js
  tests/unit/specs/src/layouts/GettingStarted/components/Congratulations/Congratulations.spec.js
  tests/unit/specs/src/layouts/HomeLayout/HomeLayout.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/DappButtons/DappButtons.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.spec.js
Labels: Devop, Ready

#710 devop/add-noscript
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-test.js
  public/google-fonts.css
  public/img/spaceman.png
  public/index.css
  public/index.html
  src/darklist/address-darklist.json
  src/tokens/tokens-eth.json
Labels: Devop, Ready

#698 Update Inteface side menu button UI
  CHANGELOG.md
  src/components/Buttons/RoundButton/RoundButton.scss
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.scss
Labels: Ready, UI

#704 devop/optimized batch tx [5.0.4]
  CHANGELOG.md
  CODEOWNERS
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/store/actions.js
  src/wallets/web3-provider/providers/ws-provider.js
Labels: Devop, Ready

#701 Fix header UI bug
  CHANGELOG.md
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
Labels: Ready, UI

#693 Fix Information block UI
  CHANGELOG.md
  package-lock.json
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/components/InformationBlock.scss
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.scss
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.scss
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.vue
  src/tokens/tokens-eth.json
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.spec.js
Labels: Ready, UI

#712 Make staging and gh-pages-history identical [5.0.4]
  .travis.yml
  CHANGELOG.md
  package-test.js
Labels: Devop, Ready

#720 Feature/dapp sort
  CHANGELOG.md
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.scss
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
Labels: Feature, Ready

#691 Ui/add faqs animation
  CHANGELOG.md
  package-lock.json
  src/containers/FaqsContainer/FaqsContainer-desktop.scss
  src/containers/FaqsContainer/FaqsContainer-mobile.scss
  src/containers/FaqsContainer/FaqsContainer-tablet.scss
  src/containers/FaqsContainer/FaqsContainer.scss
  src/containers/FaqsContainer/FaqsContainer.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/darklist/address-darklist.json
  src/layouts/InterfaceLayout/components/InformationBlock.scss
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.scss
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.scss
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.vue
  src/tokens/tokens-eth.json
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.spec.js
Labels: Ready, UI

#709 Devop/update keepkey
  CHANGELOG.md
  package-lock.json
  package.json
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/tokens/tokens-eth.json
  src/translations/errors-global/en_US.json
  src/translations/errors-global/es_ES.json
  src/translations/errors-global/ja_JP.json
  src/translations/errors-global/ko_KR.json
  src/translations/errors-global/ru_RU.json
  src/translations/errors-global/zh_CN.json
  src/translations/interface/en_US.json
Labels: Devop, Ready

#711 Devop/swap improvements
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/Notification/Notification.vue
  src/components/Notification/components/NotificationTypes/SwapDetails/SwapDetails.vue
  src/components/Notification/components/NotificationTypes/TransactionNotification/TransactionNotification.vue
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/partners/bity/bity.js
  src/partners/changelly/changelly.js
  src/partners/changelly/config/config.js
  src/partners/helpers/utils.js
  src/partners/index.js
  src/partners/kyber/config/config.js
  src/partners/kyber/config/index.js
  src/partners/kyber/kyber-api.js
  src/partners/kyber/kyber.js
  src/partners/partners.js
  src/partners/simplex/simplex.js
  src/translations/header/en_US.json
Labels: Ready

#539 New Crowdin translations
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ja_JP.json
  src/translations/access-wallet/ko_KR.json
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/dapps/es_ES.json
  src/translations/dapps/ja_JP.json
  src/translations/dapps/ko_KR.json
  src/translations/dapps/ru_RU.json
  src/translations/dapps/zh_CN.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/translations/header/es_ES.json
  src/translations/header/ja_JP.json
  src/translations/header/ko_KR.json
  src/translations/header/ru_RU.json
  src/translations/header/zh_CN.json
  src/translations/home/es_ES.json
  src/translations/home/ja_JP.json
  src/translations/home/ko_KR.json
  src/translations/home/ru_RU.json
  src/translations/home/zh_CN.json
  src/translations/interface/es_ES.json
  src/translations/interface/ja_JP.json
  src/translations/interface/ko_KR.json
  src/translations/interface/ru_RU.json
  src/translations/interface/zh_CN.json
  src/translations/without-wallet/es_ES.json
  src/translations/without-wallet/ja_JP.json
  src/translations/without-wallet/ko_KR.json
  src/translations/without-wallet/ru_RU.json
  src/translations/without-wallet/zh_CN.json
Labels: Ready, Strings

#723 reverse the batch txs on web3_Wallet
  CHANGELOG.md
  package-lock.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/translations/header/es_ES.json
  src/translations/header/ja_JP.json
  src/translations/header/ko_KR.json
  src/translations/header/ru_RU.json
  src/translations/header/zh_CN.json
  src/translations/without-wallet/es_ES.json
Labels: Ready

#721 Fix Mnemonic Phrase print page UI
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/darklist/address-darklist.json
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer-tablet.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/MnemonicTableToDisplay.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/MnemonicTableToDisplay.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/index.js
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToPrint/MnemonicTableToPrint.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToPrint/MnemonicTableToPrint.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToPrint/index.js
  src/tokens/tokens-eth.json
Labels: Ready, UI

#703 Mewconnect connection investigation
  package-lock.json
  package-test.js
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/darklist/address-darklist.json
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/wallets/hybrid/MEWconnect/index.js
Labels: Ready

#725 minor fixes for 5.0.4
  .travis.yml
  fetchLists/lists/tokens.json
  package-lock.json
  public/google-fonts.css
  public/index.css
  public/index.html
  src/darklist/address-darklist.json
  src/tokens/tokens-eth.json
Labels: Ready

#733 Ui/update interface address block
  CHANGELOG.md
  src/assets/images/short-hand-logo-white.png
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.scss
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.scss
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/index.js
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.scss
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/index.js
Labels: Ready, UI

#666 Update success modal for transaction and swap
  CHANGELOG.md
  package-lock.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.scss
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/translations/confirmation/en_US.json
  tests/unit/specs/src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.spec.js
Labels: Ready, UI

#700 Update notification dot animation
  CHANGELOG.md
  src/components/Notification/Notification.scss
Labels: Ready, UI
