Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-10, with the labels that each got.

#1457 Fix login to metamask
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
Labels: Bug, Ready

#1453 devop/update-greenkeeper
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1465 Devop/font fix
  CHANGELOG.md
  package-lock.json
  public/index.css
  public/index.html
  src/assets/google-fonts.css
  src/components/FaqContents/FaqContents.scss
  src/components/Notification/components/NotificationTypes/NotificationDetails/Notification.scss
  src/components/Notification/components/NotificationTypes/SwapDetails/SwapDetails.scss
  src/components/NotificationsModal/components/NotificationDropdownMenu/NotificationDropdownMenu.scss
  src/dapps/MakerDai/MakerDai.scss
  src/dapps/MakerDai/containers/MakerHome/MakerHome.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/main.js
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/scss/Global-tablet.scss
Labels: Devop, Ready

#1403 Devop/custom nft
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/defaultToken.png
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NFTSideMenu/NFTSideMenu.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NFTSideMenu/NFTSideMenu.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomAddModal/NftCustomAddModal.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomAddModal/NftCustomAddModal.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomAddModal/index.js
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomConfirmRemove/NftCustomConfirmRemove.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomConfirmRemove/NftCustomConfirmRemove.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomConfirmRemove/index.js
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/index.js
  src/translations/dapps/en_US.json
  src/translations/interface/en_US.json
Labels: Ready

#1460 feature/network-query
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/translations/interface/en_US.json
  src/translations/interface/es_ES.json
  src/translations/interface/ja_JP.json
  src/translations/interface/ko_KR.json
  src/translations/interface/ru_RU.json
  src/translations/interface/zh_CN.json
  src/translations/interface/zh_TW.json
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
Labels: Feature, Ready

#1474 devop/update-packages
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/SliderBar/SliderBar.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.scss
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
Labels: Devop, Ready

#1482 Remove Aldo from team page
  CHANGELOG.md
  package-lock.json
  src/assets/images/team/Aldo.jpg
  src/layouts/TeamLayout/TeamLayout.vue
Labels: Ready

#1488 bug/goerli-error
  CHANGELOG.md
  package-lock.json
  package.json
  src/networks/nodes/index.js
  src/networks/nodes/kov-mew-ws.js
  src/networks/types/GOERLI.js
  src/networks/types/index.js
Labels: Bug, Ready

#1507 Devop/remove etc nodes
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/networks/nodes/etc-ethereumcommonwealth-geth.js
  src/networks/nodes/etc-ethereumcommonwealth-parity.js
  src/networks/nodes/index.js
Labels: Devop, Ready, Waiting

#1501 Devop/update package
  package-lock.json
  package.json
Labels: Devop, Ready

#1502 Fix/estimate with value
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
Labels: Ready

#1506 bug/mnemonic-phrase-validation
  CHANGELOG.md
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.vue
Labels: Bug, Ready

#1521 Feature/ens multi coin support
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/components/WelcomeModal/WelcomeModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/dapps/ManageENS/ABI/resolverAbi.js
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.scss
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/supportedCoins.js
  src/helpers/ENSMultiCoin.js
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/translations/dapps/en_US.json
  src/translations/home/en_US.json
  src/translations/home/es_ES.json
  src/translations/home/ja_JP.json
  src/translations/home/ko_KR.json
  src/translations/home/ru_RU.json
  src/translations/home/zh_CN.json
  src/translations/home/zh_TW.json
  tests/unit/specs/src/dapps/ManageENS/ManageENS.spec.js
  tests/unit/specs/src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.spec.js
  tests/unit/specs/src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.spec.js
Labels: Feature, Ready

#1518 Move State of dapp text
  CHANGELOG.md
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/DappSubmissionLayout/DappSubmissionLayout.scss
  src/layouts/DappSubmissionLayout/DappSubmissionLayout.vue
  src/layouts/DappSubmissionLayout/components/MewSupportComponent/MewSupportComponent.scss
  src/layouts/DappSubmissionLayout/components/SOTDComponent/SOTDComponent.scss
  src/layouts/DappSubmissionLayout/components/SOTDComponent/SOTDComponent.vue
  src/layouts/DappSubmissionLayout/containers/AboutYourDappContainer/AboutYourDappContainer.scss
  src/layouts/DappSubmissionLayout/containers/AboutYourDappContainer/AboutYourDappContainer.vue
  src/layouts/DappSubmissionLayout/containers/AboutYourDappTeamContainer.scss
  src/layouts/DappSubmissionLayout/containers/SummaryContainer/SummaryContainer.vue
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/translations/footer/zh_TW.json
Labels: Feature, Ready

#1522 quietly handle changelly rate timeout
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/partners/changelly/changelly.js
Labels: Ready

#1531 Dev/fix static buttons
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  src/components/DecisionTree/DecisionTree.scss
  src/components/DecisionTree/DecisionTree.vue
  src/components/ScrollUpButton/ScrollUpButton.scss
  src/components/ScrollUpButton/ScrollUpButton.vue
  src/components/ScrollUpButton/index.js
  src/components/UserReminderButton/UserReminderButton.scss
  src/components/UserReminderButton/UserReminderButton.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  tests/unit/specs/src/components/ScrollUpButton/ScrollUpButton.spec.js
  tests/unit/specs/src/components/StandardDropdown/StandardDropdown.spec.js
  tests/unit/specs/src/containers/HeaderContainer/HeaderContainer.spec.js
  tests/unit/specs/src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.spec.js
  tests/unit/specs/src/partners/changelly/changelly.spec.js
  vue.config.js
Labels: Ready

#1538 bug/ropsten-transfer-domain
  CHANGELOG.md
  src/dapps/ManageENS/ManageENS.vue
Labels: Bug, Ready

#1547 ens subdomain fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/ManageENS/ManageENS.vue
Labels: Fixed, Ready

#1549 devop/update-packages-from-scratch
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/networks/nodes/egem.js
Labels: Devop, Ready

#1550 Fix total nft issue
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
Labels: Bug, Ready

#1551 support new BTC encoding and add new currency types
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/supportedCoins.js
  src/helpers/ENSMultiCoin.js
Labels: Fixed, Ready

#1558 Update ledger packages
  package-lock.json
  package.json
Labels: Devop, Ready

#1553 release/v5.1.8
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/supportedCoins.js
  src/helpers/ENSMultiCoin.js
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/networks/nodes/egem.js
Labels: Ready, Release

#1567 hotfix/missing-contract-addresses
  CHANGELOG.md
  fetchLists/index.js
  fetchLists/lists/contracts.json
  package-lock.json
  package.json
Labels: Hotfix, Ready, Release

#1573 Fix/ENS empty address
  CHANGELOG.md
  src/dapps/ManageENS/ManageENS.vue
Labels: Bug, Fixed, Ready

#1561 devop/update-packages
  CHANGELOG.md
  fetchLists/index.js
  fetchLists/lists/contracts.json
  package-lock.json
  package-test.js
  package.json
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
Labels: Devop, Ready

#1574 Remove functional component
  CHANGELOG.md
  package-lock.json
  src/dapps/ScheduleTransaction/ScheduleTransaction.vue
Labels: Bug, Ready

#1559 Feature/txt records
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/supportedTxt.js
  src/translations/dapps/en_US.json
Labels: Feature, Ready

#1552 keep the selected provider active over rate refresh cycles
  CHANGELOG.md
  fetchLists/lists/contracts.json
  src/containers/NotificationsContainer/components/NotificationTypes/SwapNotification/SwapNotification.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/partners/bity/bity-calls.js
  src/partners/changelly/changelly.js
  src/partners/partners.js
Labels: Devop, Ready

#1577 Develop
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/NotificationsContainer/components/NotificationTypes/SwapNotification/SwapNotification.vue
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/supportedTxt.js
  src/dapps/ScheduleTransaction/ScheduleTransaction.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/partners/bity/bity-calls.js
  src/partners/changelly/changelly.js
  src/partners/partners.js
  src/translations/dapps/en_US.json
Labels: Ready, Release

#1580 Add vulnerability reporting to readme
  CHANGELOG.md
  README.md
Labels: Devop, Ready
