Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-06, with the labels that each got.

#1117 sync with exact timestamp
  .travis.yml
  CHANGELOG.md
Labels: Ready

#1125 Bug/various fixes
  CHANGELOG.md
  package.json
  src/helpers/misc.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/translations/errors-trezor/en_US.json
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/trezor/errorHandler.js
Labels: Bug, Ready

#1154 bug/getting-started
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/GettingStarted/components/SomeHelpfulTips/SomeHelpfulTips.vue
Labels: Bug, Ready

#1184 Devop/update packages
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/dapps/MakerDai/MakerDai.scss
  src/dapps/ScheduleTransaction/components/ScheduledSuccess.vue
  src/helpers/commonGenerator.js
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/networks/index.js
  src/store/state.js
  src/wallets/WalletInterface.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/index.js
  src/wallets/hardware/trezor/index.js
  src/wallets/hybrid/MEWconnect/index.js
  src/wallets/software/mnemonic/index.js
Labels: Devop, Ready

#1185 release/v5.0.14-hotfix.1
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/dapps/MakerDai/MakerDai.scss
  src/dapps/ScheduleTransaction/components/ScheduledSuccess.vue
  src/helpers/commonGenerator.js
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/networks/index.js
  src/store/state.js
  src/wallets/WalletInterface.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/index.js
  src/wallets/hardware/trezor/index.js
  src/wallets/hybrid/MEWconnect/index.js
  src/wallets/software/mnemonic/index.js
Labels: Ready, Release

#1203 devop/merge-branches
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Notification/components/NotificationTypes/TransactionNotification/TransactionNotification.vue
  src/dapps/BuySubdomain/domains.json
  src/networks/index.js
  src/store/state.js
  src/wallets/WalletInterface.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/index.js
  src/wallets/hardware/trezor/index.js
  src/wallets/hybrid/MEWconnect/index.js
  src/wallets/software/mnemonic/index.js
Labels: Devop, Ready

#1204 release/v5.0.14-hotfix.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Notification/components/NotificationTypes/TransactionNotification/TransactionNotification.vue
  src/dapps/BuySubdomain/domains.json
  src/networks/index.js
  src/store/state.js
  src/wallets/WalletInterface.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/index.js
  src/wallets/hardware/secalot/secalotEth.js
  src/wallets/hardware/trezor/index.js
  src/wallets/hybrid/MEWconnect/index.js
  src/wallets/software/mnemonic/index.js
Labels: Ready, Release
