Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-05, with the labels that each got.

#1021 Ui/update software modal ui
  CHANGELOG.md
  src/components/WarningMessage/WarningMessage.scss
  src/components/WarningMessage/WarningMessage.vue
  src/components/WarningMessage/index.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal-desktop.scss
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal-mobile.scss
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal-tablet.scss
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/scss/GlobalVariables.scss
  src/translations/access-wallet/en_US.json
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ja_JP.json
  src/translations/access-wallet/ko_KR.json
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  vue.config.js
Labels: Ready, UI

#1025 Devop/fix hardware icons
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  vue.config.js
Labels: Devop, Ready

#1027 Devop/build fix
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1028 Devop/build fix
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1042 devop/prep-release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1030 PWA/name change
  CHANGELOG.md
  src/builds/web/public/manifest.json
Labels: Devop, Ready

#1029 UI fix for mnemonic phrase key verification modal
  CHANGELOG.md
  package-lock.json
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-desktop.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-tablet.scss
Labels: Ready

#1031 change form target to _blank
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SwapContainer/components/CheckoutForm/CheckoutForm.vue
Labels: Devop, Ready

#1063 Fix promievent not getting called properly on web3 wallets
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/wallets/web3-provider/methods/eth_sendTransaction.js
Labels: Bug, Ready

#1054 Permanent registrar owner check fix
  CHANGELOG.md
  src/dapps/ManageENS/ABI/baseRegistrarAbi.js
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
Labels: Devop, Ready

#1081 feature/ledger-web-usb
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/wallets/hardware/ledger/index.js
  src/wallets/web3-provider/providers/http-request-manager.js
Labels: Feature, Ready

#1036 Update Richie's profile.
  CHANGELOG.md
  src/layouts/TeamLayout/TeamLayout.vue
Labels: Ready

#1037 devop/ledger-custom-paths
  CHANGELOG.md
  src/helpers/index.js
  src/helpers/pathHelper.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/LedgerAppModal/LedgerAppModal.scss
  src/layouts/AccessWalletLayout/components/LedgerAppModal/LedgerAppModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/wallets/hardware/ledger/appPaths.js
Labels: Devop, Ready

#1091 bug/ledger-error
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/translations/errors-ledger/en_US.json
  src/translations/errors-ledger/es_ES.json
  src/translations/errors-ledger/ja_JP.json
  src/translations/errors-ledger/ko_KR.json
  src/translations/errors-ledger/ru_RU.json
  src/translations/errors-ledger/zh_CN.json
  src/translations/errors-ledger/zh_TW.json
  src/wallets/hardware/ledger/errorHandler.js
Labels: Bug, Ready

#1100 bug/ledger-issues
  CHANGELOG.md
  package-lock.json
  package.json
  src/wallets/hardware/ledger/index.js
Labels: Bug, Ready

#1102 Devop/random error fix
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
Labels: Devop, Ready

#1101 Release v5.0.12-hotfix.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/wallets/hardware/ledger/index.js
Labels: Ready, Release

#1103 Fix ENS migrate owner check
  CHANGELOG.md
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/TransferRegistrarsContainer.vue
Labels: Bug, Ready

#1108 Bug/mnemonic password
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/TransferRegistrarsContainer.vue
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal.vue
Labels: Bug, Ready

#1109 Release v5.0.12-hotfix.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/TransferRegistrarsContainer.vue
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal.vue
Labels: Ready, Release
