Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-08, with the labels that each got.

#1301 devop/update-version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1302 Update new members
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/team/Aldo.jpg
  src/assets/images/team/Semaja.jpg
  src/assets/images/team/_blank_.jpg
  src/layouts/TeamLayout/TeamLayout.vue
  vue.config.js
Labels: Ready

#1304 Update team info and pictures
  CHANGELOG.md
  src/assets/images/team/Brittany.jpg
  src/assets/images/team/Gage.jpg
  src/assets/images/team/Jack.jpg
  src/layouts/TeamLayout/TeamLayout.vue
  src/translations/team/en_US.json
  src/translations/team/ko_KR.json
Labels: Ready

#1305 set all transaction gasprice to global value
  CHANGELOG.md
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/wallets/hardware/ledger/appPaths.js
  src/wallets/web3-provider/methods/eth_sendTransaction.js
Labels: Devop, Ready

#1306 devop/xss-toast-issue
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/team/Brittany.jpg
  src/assets/images/team/Gage.jpg
  src/assets/images/team/Jack.jpg
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/layouts/TeamLayout/TeamLayout.vue
  src/toast.config.js
  src/translations/team/en_US.json
  src/translations/team/ko_KR.json
  src/wallets/hardware/ledger/appPaths.js
  src/wallets/web3-provider/methods/eth_sendTransaction.js
Labels: Devop, Ready

#1307 release/v5.0.16-hotfix.1
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/team/Brittany.jpg
  src/assets/images/team/Gage.jpg
  src/assets/images/team/Jack.jpg
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/layouts/TeamLayout/TeamLayout.vue
  src/toast.config.js
  src/translations/team/en_US.json
  src/translations/team/ko_KR.json
  src/wallets/hardware/ledger/appPaths.js
  src/wallets/web3-provider/methods/eth_sendTransaction.js
Labels: Ready, Release

#1320 Devop/prep release
  CHANGELOG.md
  README.md
  index.html
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#1333 Fix UI: "Scan to Download" mobile UI update
  CHANGELOG.md
  README.md
  src/layouts/CreateWalletLayout/components/ScanToDownloadModal/ScanToDownloadModal.scss
Labels: Ready

#1326 Devop/extend xss
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/misc.js
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/MnemonicTableToDisplay.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToPrint/MnemonicTableToPrint.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/router/index.js
  src/toast.config.js
Labels: Devop, Ready

#1332 Update UI: frontpage FAQs content box
  CHANGELOG.md
  src/containers/FaqsContainer/FaqsContainer.scss
Labels: Ready

#1329 Fix text translations
  CHANGELOG.md
  src/components/Notification/components/config.js
  src/translations/confirmation/en_US.json
Labels: Ready

#1344 Devop/update packages
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/main.js
Labels: Devop, Ready

#1347 Get a New Wallet > By Mnemonic Phrase layout bug fix
  CHANGELOG.md
  src/components/WarningMessage/WarningMessage.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/MnemonicTableToDisplay.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-desktop.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-tablet.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.vue
  src/main.js
Labels: Ready

#1195 Update Swap Api
  CHANGELOG.md
  package-lock.json
  src/components/StandardInput/StandardInput.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/components/CloseCdpModal/CloseCdpModal.vue
  src/dapps/MakerDai/components/DepositModal/DepositModal.vue
  src/dapps/MakerDai/components/PaybackModal/PaybackModal.scss
  src/dapps/MakerDai/components/PaybackModal/PaybackModal.vue
  src/dapps/MakerDai/containers/ManageCDP/ManageCDP.scss
  src/dapps/MakerDai/containers/ManageCDP/ManageCDP.vue
  src/dapps/index.js
  src/layouts/InterfaceLayout/components/BackButton/BackButton.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/buyEthAd/buyEthAd.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/buyEthAd/buyEthAd.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/index.js
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/mewConnectAd/index.js
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/mewConnectAd/mewConnectAd.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/mewConnectAd/mewConnectAd.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/staticAd/staticAd.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonNftManager/ButtonNftManager.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonNftManager/ButtonNftManager.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NFTSideMenu/NFTSideMenu.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/containers/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/StandardDropdown/StandardDropdown.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/StandardDropdown/StandardDropdown.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/StandardDropdown/index.js
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/main.js
  src/partners/bity/bity-calls.js
  src/partners/bity/bity.js
  src/partners/bity/config.js
  src/partners/changelly/changelly.js
  src/partners/kyber/kyber.js
  src/partners/partners.js
  src/partners/simplex/simplex.js
  src/translations/common/en_US.json
  src/translations/dapps-maker/en_US.json
  src/translations/interface/en_US.json
  src/translations/team/en_US.json
  src/translations/team/ko_KR.json
Labels: Devop, Ready

#1352 Devop/maker ui fixes
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/MakerDai/MakerCDP.js
  src/dapps/MakerDai/MakerDai.scss
  src/dapps/MakerDai/MakerDai.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
Labels: Ready

#1353 Add hovering effect to dashboard -> swap buttons
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
Labels: Ready

#1346 Devop/remove safesend
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/SecureTransaction/SecureTransaction.scss
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/dapps/SecureTransaction/config.js
  src/dapps/SecureTransaction/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/common/zh_TW.json
  src/translations/dapps/en_US.json
  src/translations/dapps/es_ES.json
  src/translations/dapps/ja_JP.json
  src/translations/dapps/ko_KR.json
  src/translations/dapps/ru_RU.json
  src/translations/dapps/zh_CN.json
  src/translations/dapps/zh_TW.json
Labels: Devop, Ready

#1355 Bug/squash bugs
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/partners/changelly/changelly.js
  src/partners/simplex/simplex.js
  src/translations/common/en_US.json
  tests/unit/specs/src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.spec.js
Labels: Fixed

#1357 release/v5.1.1-hotfix.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/MakerDai/MakerCDP.js
  src/dapps/MakerDai/MakerDai.scss
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/SecureTransaction/SecureTransaction.scss
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/dapps/SecureTransaction/config.js
  src/dapps/SecureTransaction/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/partners/changelly/changelly.js
  src/partners/simplex/simplex.js
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/common/zh_TW.json
  src/translations/dapps/en_US.json
  src/translations/dapps/es_ES.json
  src/translations/dapps/ja_JP.json
  src/translations/dapps/ko_KR.json
  src/translations/dapps/ru_RU.json
  src/translations/dapps/zh_CN.json
  src/translations/dapps/zh_TW.json
  src/translations/interface/en_US.json
  src/translations/interface/es_ES.json
  src/translations/interface/ja_JP.json
  src/translations/interface/ko_KR.json
  src/translations/interface/ru_RU.json
  src/translations/interface/zh_CN.json
  tests/unit/specs/src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.spec.js
Labels: Ready, Release

#1358 Fix scroll up animation glitch on mobile
  CHANGELOG.md
  src/components/ScrollUpButton/ScrollUpButton.vue
Labels: Ready

#1363 Add "Please wait while we generate your keystore file..." to keystore…
  CHANGELOG.md
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer-desktop.scss
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.vue
Labels: Ready

#1361 Fix Buy Eth to Buy ETH
  CHANGELOG.md
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
Labels: Ready

#1367 Update UI custom token modal
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.scss
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.vue
Labels: Ready

#1366 Update address qrcode ui
  CHANGELOG.md
  src/components/AddressQrcodeModal/AddressQrcodeModal.scss
Labels: Ready

#1348 Switch to web3.js 1.2.1
  .devcontainer.json
  .travis.yml
  .travis.yml-bak
  .vscode/extensions.json
  CHANGELOG.md
  Dockerfile
  jest.config.js
  package-lock.json
  package-test.js
  package.json
  tests/unit/__mocks__/networksMock.js
  tests/unit/helpers/mockStore.js
  tests/unit/helpers/setupTooling.js
  tests/unit/specs/src/dapps/BuySubdomain/BuySubdomain.spec.js
  vue.config.js
Labels: Devop, Ready

#1364 Add warning message to HTTP Basic Access Authentication
  CHANGELOG.md
  package.json
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.scss
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
Labels: Ready

#1365 Actions & Swap button opacity update
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonNftManager/ButtonNftManager.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.scss
Labels: Ready

#1368 Devop/revise swap
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/partners/bity/bity.js
  src/partners/changelly/changelly-calls.js
  src/partners/changelly/changelly.js
  src/partners/changelly/config/currencies.js
  src/partners/kyber/config/config.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/kyber/config/gasLimits.js
  src/partners/kyber/kyber-calls.js
  src/partners/kyber/kyber.js
  src/partners/partners.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/OtherCoins.js
  src/partners/simplex/simplex.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ErrorModal/ErrorModal.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
  tests/unit/specs/src/partners/bity/bity.spec.js
  tests/unit/specs/src/partners/changelly/changelly.spec.js
  tests/unit/specs/src/partners/kyber/kyber.spec.js
  tests/unit/specs/src/partners/partners.spec.js
  tests/unit/specs/src/partners/simplex/simplex.spec.js
  vue.config.js
Labels: Ready

#1376 Ui/fix dashboard buttons
  CHANGELOG.md
  src/assets/images/ads/mewconnect.jpeg
  src/assets/images/ads/mewconnect.jpg
  src/assets/images/ads/mewconnect.png
  src/components/Buttons/StandardButton/StandardButton.scss
  src/components/Buttons/StandardButton/StandardButton.vue
  src/layouts/InterfaceLayout/InterfaceLayout-desktop.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/buyEthAd/buyEthAd.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/buyEthAd/buyEthAd.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/mewConnectAd/mewConnectAd.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/mewConnectAd/mewConnectAd.vue
  src/scss/GlobalVariables.scss
Labels: Ready

#1383 Update vue cli packages
  package-lock.json
  package.json
Labels: Devop, Ready
