Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-07, with the labels that each got.

#1209 BitBox bugfixes: U2F communication; displaying error messages
  CHANGELOG.md
  src/translations/errors-bitbox/en_US.json
  src/translations/errors-bitbox/es_ES.json
  src/translations/errors-bitbox/ja_JP.json
  src/translations/errors-bitbox/ko_KR.json
  src/translations/errors-bitbox/ru_RU.json
  src/translations/errors-bitbox/zh_CN.json
  src/translations/errors-bitbox/zh_TW.json
  src/wallets/hardware/bitbox/digitalBitboxEth.js
  src/wallets/hardware/bitbox/digitalBitboxUsb.js
  src/wallets/hardware/bitbox/errorHandler.js
  src/wallets/hardware/bitbox/index.js
Labels: Ready

#1227 devop/fix-release
  .travis.yml
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/translations/buy-hardware-wallet/es_ES.json
  src/translations/buy-hardware-wallet/ja_JP.json
  src/translations/buy-hardware-wallet/ko_KR.json
  src/translations/buy-hardware-wallet/ru_RU.json
  src/translations/buy-hardware-wallet/zh_CN.json
Labels: Devop, Ready

#1248 Develop
  .travis.yml
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/MakerDai/MakerCDP.js
  src/translations/buy-hardware-wallet/es_ES.json
  src/translations/buy-hardware-wallet/ja_JP.json
  src/translations/buy-hardware-wallet/ko_KR.json
  src/translations/buy-hardware-wallet/ru_RU.json
  src/translations/buy-hardware-wallet/zh_CN.json
Labels: Ready, Release

#1285 Add custom networks on send offline helper
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#1273 dont use webworker if origin is null
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.vue
Labels: Bug, Ready

#1297 feature/logout-navigation
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  src/builds/web/app.vue
  src/components/LogoutModal/LogoutModal.vue
  src/components/LogoutWarningModal/LogoutWarningModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/store/actions.js
Labels: Bug, Ready

#1275 devop/mewtopia
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Devop, Ready

#1293 fix custom network adding
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  src/components/Notification/Notification.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/store/mutations.js
  src/store/state.js
Labels: Bug, Ready

#1260 Show Advanced fields if data / gas limit is preset
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
Labels: Bug, Ready

#1250 bug/dapp-buttons-rename-subdomain-dapp
  CHANGELOG.md
  src/dapps/BuySubdomain/BuySubdomain.vue
  src/dapps/BuySubdomain/routes.js
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/dapps/index.js
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/translations/interface/en_US.json
  src/translations/interface/es_ES.json
  src/translations/interface/ja_JP.json
  src/translations/interface/ko_KR.json
  src/translations/interface/ru_RU.json
  src/translations/interface/zh_CN.json
  src/translations/interface/zh_TW.json
  tests/unit/specs/src/layouts/InterfaceLayout/components/DappButtons/DappButtons.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.spec.js
Labels: Bug, Ready

#1295 Devop/sentry fixes
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/builds/web/app.vue
  src/components/AddressQrcodeModal/AddressQrcodeModal.vue
  src/components/LogoutModal/LogoutModal.vue
  src/components/LogoutWarningModal/LogoutWarningModal.vue
  src/components/Notification/Notification.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/main.js
  src/store/actions.js
  src/translations/errors-ledger/en_US.json
  src/wallets/hardware/ledger/errorHandler.js
  src/wallets/web3-provider/providers/http-request-manager.js
Labels: Devop, Ready

#1251 Additional makerCDP related updates
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/MakerDai/MakerCDP.js
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/components/MoveCdpModal/MoveCdp.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/translations/dapps-maker/en_US.json
  tests/unit/specs/src/partners/kyber/kyber.spec.js
Labels: Ready
