Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-09, with the labels that each got.

#1389 Ui/image compression
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/assets/images/ads/mewconnect.png
  src/assets/images/buttons/nft-manager/crypto-kitties.png
  src/assets/images/etc/finney.png
  src/assets/images/etc/phones.png
  src/assets/images/home/big-spaceman.png
  src/assets/images/icons/button-metamask-fox.png
  src/assets/images/icons/button-metamask-fox.svg
  src/assets/images/icons/question.png
  src/assets/images/icons/slack.png
  src/assets/images/icons/up.svg
  src/components/PopupHelper/PopupHelper.scss
  src/components/PopupHelper/PopupHelper.vue
  src/components/PopupHelper/index.js
  src/dapps/MakerDai/containers/ManageCDP/ManageCDP.vue
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.scss
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/buyEthAd/buyEthAd.scss
  tests/unit/specs/src/layouts/CreateWalletLayout/components/CreateWalletInputFooter/CreateWalletInputFooter.spec.js
Labels: Ready

#1392 Ui/fix finney modal layout
  CHANGELOG.md
  package-lock.json
  src/assets/images/etc/finney.png
  src/assets/images/modal/finney/finney-bg.jpg
  src/layouts/AccessWalletLayout/components/FinneyModal/FinneyModal.scss
  src/layouts/AccessWalletLayout/components/FinneyModal/FinneyModal.vue
Labels: Ready

#1396 Fix the bug when user expend the token list, footer breaks.
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
Labels: Ready

#1419 Updating packages
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/layouts/AccessWalletLayout/components/FinneyModal/FinneyModal.scss
Labels: Devop, Ready

#1409 Bug/ens
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/hourglass.svg
  src/assets/images/icons/orange-warn.png
  src/dapps/BuySubdomain/BuySubdomain.scss
  src/dapps/BuySubdomain/BuySubdomain.vue
  src/dapps/BuySubdomain/domains.json
  src/dapps/ManageENS/ABI/registrarAbi.js
  src/dapps/ManageENS/ManageENS.scss
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/components/FinalizeModal/FinalizeModal.scss
  src/dapps/ManageENS/components/FinalizeModal/FinalizeModal.vue
  src/dapps/ManageENS/components/FinalizeModal/index.js
  src/dapps/ManageENS/components/JsonStringModal/JsonStringModal.scss
  src/dapps/ManageENS/components/JsonStringModal/JsonStringModal.vue
  src/dapps/ManageENS/components/JsonStringModal/index.js
  src/dapps/ManageENS/components/PrintModal/PrintModal.scss
  src/dapps/ManageENS/components/PrintModal/PrintModal.vue
  src/dapps/ManageENS/components/PrintModal/index.js
  src/dapps/ManageENS/components/Timer/Timer.scss
  src/dapps/ManageENS/components/Timer/Timer.vue
  src/dapps/ManageENS/components/Timer/index.js
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.scss
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/EnsBidContainer/EnsBidContainer.scss
  src/dapps/ManageENS/containers/EnsBidContainer/EnsBidContainer.vue
  src/dapps/ManageENS/containers/EnsBidContainer/index.js
  src/dapps/ManageENS/containers/FifsBuyContainer/FifsBuyContainer.scss
  src/dapps/ManageENS/containers/FinalizeContainer/FinalizeContainer.scss
  src/dapps/ManageENS/containers/FinalizeContainer/FinalizeContainer.vue
  src/dapps/ManageENS/containers/FinalizeContainer/index.js
  src/dapps/ManageENS/routes.js
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.config.js
  src/translations/dapps/en_US.json
  src/translations/dapps/es_ES.json
  src/translations/dapps/ja_JP.json
  src/translations/dapps/ko_KR.json
  src/translations/dapps/ru_RU.json
  src/translations/dapps/zh_CN.json
  src/translations/dapps/zh_TW.json
  tests/unit/specs/src/dapps/ManageENS/ManageENS.spec.js
  tests/unit/specs/src/dapps/ManageENS/components/FinalizeModal/FinalizeModal.spec.js
  tests/unit/specs/src/dapps/ManageENS/components/FinalizeModal/FinalizeModal.vue
  tests/unit/specs/src/dapps/ManageENS/components/JsonStringModal/JsonStringModal.spec.js
  tests/unit/specs/src/dapps/ManageENS/components/Timer/Timer.spec.js
  tests/unit/specs/src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.spec.js
  tests/unit/specs/src/dapps/ManageENS/containers/EnsBidContainer/EnsBidContainer.spec.js
  tests/unit/specs/src/dapps/ManageENS/containers/FinalizeContainer/FinalizeContainer.spec.js
Labels: Bug, Ready

#1394 Devop/sentry fixes
  CHANGELOG.md
  package-test.js
  src/components/Notification/Notification.vue
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal.vue
  src/networks/nodes/index.js
  src/partners/kyber/kyber.js
  src/store/actions.js
  src/translations/errors-ledger/en_US.json
  src/translations/errors-trezor/en_US.json
  src/wallets/hardware/ledger/errorHandler.js
  src/wallets/hardware/trezor/errorHandler.js
  src/wallets/hardware/trezor/index.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.spec.js
  tests/unit/specs/src/partners/changelly/changelly.spec.js
  tests/unit/specs/src/partners/partners.spec.js
Labels: Ready

#1386 restrict gas price lower limit to 1 Gwei
  CHANGELOG.md
  src/components/SettingsModal/SettingsModal.vue
Labels: Ready

#1384 bug/match metamask network on wallet unlock
  CHANGELOG.md
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/store/actions.js
Labels: Ready

#1424 bug/prep-release-fixes
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/SettingsModal/SettingsModal.vue
  src/networks/nodes/etc-ethereumclassiccooperative-parity-classic.js
Labels: Bug, Ready

#1434 bug/gas-price-not-saving
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/translations/dapps/zh_CN.json
  src/translations/errors-ledger/es_ES.json
  src/translations/errors-ledger/ja_JP.json
  src/translations/errors-ledger/ko_KR.json
  src/translations/errors-ledger/ru_RU.json
  src/translations/errors-ledger/zh_CN.json
  src/translations/errors-trezor/es_ES.json
  src/translations/errors-trezor/ja_JP.json
  src/translations/errors-trezor/ko_KR.json
  src/translations/errors-trezor/ru_RU.json
  src/translations/errors-trezor/zh_CN.json
  src/translations/interface/es_ES.json
  src/translations/interface/ja_JP.json
  src/translations/interface/ko_KR.json
  src/translations/interface/ru_RU.json
  src/translations/interface/zh_CN.json
  src/wallets/hardware/bitbox/digitalBitboxEth.js
  src/wallets/hardware/bitbox/digitalBitboxUsb.js
Labels: Bug, Ready

#1437 devop/prep-release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1439 Bug/generate mnemonic
  CHANGELOG.md
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.vue
  src/partners/kyber/config/currenciesETH.js
  src/partners/partnersConfig/EthereumTokens.js
  tests/unit/specs/src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.spec.js
Labels: Bug, Ready

#1436 release/v5.1.4
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.vue
  src/partners/kyber/config/currenciesETH.js
  src/partners/partnersConfig/EthereumTokens.js
  src/translations/dapps/zh_CN.json
  src/translations/errors-ledger/es_ES.json
  src/translations/errors-ledger/ja_JP.json
  src/translations/errors-ledger/ko_KR.json
  src/translations/errors-ledger/ru_RU.json
  src/translations/errors-ledger/zh_CN.json
  src/translations/errors-trezor/es_ES.json
  src/translations/errors-trezor/ja_JP.json
  src/translations/errors-trezor/ko_KR.json
  src/translations/errors-trezor/ru_RU.json
  src/translations/errors-trezor/zh_CN.json
  src/translations/interface/es_ES.json
  src/translations/interface/ja_JP.json
  src/translations/interface/ko_KR.json
  src/translations/interface/ru_RU.json
  src/translations/interface/zh_CN.json
  tests/unit/specs/src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.spec.js
Labels: Ready, Release
