Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-01, with the labels that each got.

#324 bug/ens-resolver-placement
  CHANGELOG.md
  package-lock.json
  src/directives/EnsResolver.js
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/GenerateTx/GenerateTx.vue
  tests/unit/specs/src/partners/kyber/kyber.spec.js
Labels: Bug, Ready

#322 devop/green-keeper-update
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#323 bug/fix-qr-code
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/etc/qr-code-apple.png
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/CreateWalletLayout/components/ScanToDownloadModal/ScanToDownloadModal.scss
  src/layouts/CreateWalletLayout/components/ScanToDownloadModal/ScanToDownloadModal.vue
  src/tokens/tokens-eth.json
Labels: Bug, Ready

#336 devop/realign-pricebar
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.scss
Labels: Devop, Ready

#338 Devop/change animation
  CHANGELOG.md
  src/components/InfiniteSlider/InfiniteSlider.vue
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.scss
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
Labels: Devop, Ready

#337 devop/resize-team-container
  CHANGELOG.md
  src/layouts/TeamLayout/TeamLayout.scss
  src/layouts/TeamLayout/TeamLayout.vue
Labels: Devop, Ready

#344 Ui/frontend bug fixes
  CHANGELOG.md
  src/components/InfiniteSlider/InfiniteSlider.vue
  src/components/ScrollUpButton/ScrollUpButton.vue
  src/components/UserReminderButton/UserReminderButton.scss
  src/containers/AboutContainer/AboutContainer-desktop.scss
  src/containers/AboutContainer/AboutContainer-mobile.scss
  src/containers/AboutContainer/AboutContainer-tablet.scss
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.scss
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.scss
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout-mobile.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout-tablet.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/CreateWalletLayout/components/CreateWalletInput/CreateWalletInput.vue
  src/layouts/CreateWalletLayout/components/CreateWalletInputFooter/CreateWalletInputFooter.scss
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer-tablet.scss
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/FinishModal/FinishModal.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/FinishModal/FinishModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-desktop.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-tablet.scss
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-mobile.scss
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/scss/Global-tablet.scss
  src/translations/footer/en_US.json
Labels: Bug, Ready

#341 bug/top-nav-issue
  CHANGELOG.md
  src/builds/web/app.vue
  src/components/ScrollUpButton/ScrollUpButton.vue
  src/components/UserReminderButton/UserReminderButton.scss
  src/containers/AboutContainer/AboutContainer-desktop.scss
  src/containers/AboutContainer/AboutContainer-mobile.scss
  src/containers/AboutContainer/AboutContainer-tablet.scss
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.scss
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/helpers/misc.js
  src/layouts/CreateWalletLayout/CreateWalletLayout-mobile.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout-tablet.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/CreateWalletLayout/components/CreateWalletInput/CreateWalletInput.vue
  src/layouts/CreateWalletLayout/components/CreateWalletInputFooter/CreateWalletInputFooter.scss
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer-tablet.scss
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/FinishModal/FinishModal.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/FinishModal/FinishModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-desktop.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-mobile.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal-tablet.scss
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-mobile.scss
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.scss
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/scss/Global-tablet.scss
  src/translations/footer/en_US.json
Labels: Bug, Ready

#435 devop/faster-travis-builds
  .travis.yml
  CHANGELOG.md
  package.json
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
  vue.config.js
Labels: Devop, Ready

#459 Feature/ens print
  CHANGELOG.md
  src/dapps/RegisterDomain/components/PrintModal/PrintModal.scss
  src/dapps/RegisterDomain/components/PrintModal/PrintModal.vue
  src/dapps/RegisterDomain/components/PrintModal/index.js
  src/dapps/RegisterDomain/containers/EnsBidContainer/EnsBidContainer.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
Labels: Feature, Ready

#473 bug/make-send-clickable
  CHANGELOG.md
  package-lock.json
  package.json
  src/contracts/contract-abi-eth.json
  src/dapps/RegisterDomain/containers/EnsBidContainer/EnsBidContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.vue
  src/tokens/tokens-eth.json
  src/wallets/hardware/bitbox/digitalBitboxEth.js
Labels: Bug, Ready

#461 add RSK checksum validation
  CHANGELOG.md
  jsconfig.json
  package-lock.json
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue
  src/dapps/RegisterDomain/containers/ManageENSContainer/ManageENSContainer.vue
  src/helpers/addressUtils.js
  src/helpers/misc.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/GenerateInfo/GenerateInfo.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/GenerateTx/GenerateTx.vue
  src/wallets/WalletInterface.js
  src/wallets/web3-provider/etherscan-proxy.js
  src/wallets/web3-provider/web3Calls.js
  tests/unit/specs/src/components/DropDownAddressSelector/DropDownAddressSelector.spec.js
Labels: Ready

#469 Bug/interact with contract
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.spec.js
Labels: Bug, Ready

#483 Add MEW Websocket node
  CHANGELOG.md
  package-lock.json
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/networks/nodes/eth-mew-ws.js
  src/networks/nodes/index.js
  vue.config.js
Labels: Enhancement, Ready

#484 hotfix/logout-buttons
  CHANGELOG.md
  package-lock.json
  src/components/LogoutModal/LogoutModal.scss
  src/components/LogoutModal/LogoutModal.vue
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.vue
Labels: Bug, Ready

#494 Devop/fix sidemenu
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.spec.js
Labels: Devop, Ready

#499 devop/redo-send-transaction-container
  CHANGELOG.md
  src/directives/EnsResolver.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
  vue.config.js
Labels: Devop, Ready

#325 Feature/swap exit to fiat
  CHANGELOG.md
  compileBaseSwapOptions.js
  package-lock.json
  package.json
  src/assets/images/currency/coins/asFont/cryptocoins.css
  src/assets/images/currency/coins/asFont/cryptocoins.eot
  src/assets/images/currency/coins/asFont/cryptocoins.json
  src/assets/images/currency/coins/asFont/cryptocoins.less
  src/assets/images/currency/coins/asFont/cryptocoins.svg
  src/assets/images/currency/coins/asFont/cryptocoins.symbol.svg
  src/assets/images/currency/coins/asFont/cryptocoins.ttf
  src/assets/images/currency/coins/asFont/cryptocoins.woff
  src/assets/images/currency/coins/asFont/cryptocoins.woff2
  src/assets/images/etc/bitybeta.png
  src/components/AccordionMenu1/AccordionMenu1.scss
  src/components/AccordionMenu1/AccordionMenu1.vue
  src/components/AccordionMenu1/index.js
  src/components/Buttons/StandardButton/StandardButton.vue
  src/components/StandardDropdown/StandardDropdown.scss
  src/components/StandardDropdown/StandardDropdown.vue
  src/components/StandardDropdown/index.js
  src/components/StandardInput/StandardInput.vue
  src/helpers/notificationFormatters/config.js
  src/helpers/notificationFormatters/formatters.js
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/index.js
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/partners/bity/bity-calls.js
  src/partners/bity/bity.js
  src/partners/bity/config.js
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly.js
  src/partners/changelly/config/config.js
  src/partners/changelly/config/currencies.js
  src/partners/changelly/config/index.js
  src/partners/helpers/utils.js
  src/partners/kyber/config/config.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/kyber/config/index.js
  src/partners/kyber/kyber.js
  src/partners/partners.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/config.js
  src/partners/partnersConfig/index.js
  src/translations/common/en_US.json
  src/translations/confirmation/en_US.json
  src/translations/header/en_US.json
  src/translations/interface/en_US.json
Labels: Ready

#511 devop/refactor-access-options
  CHANGELOG.md
  src/components/Notification/Notification.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/dapps/BuySubdomain/BuySubdomain.vue
  src/dapps/RegisterDomain/RegisterDomain.vue
  src/dapps/RegisterDomain/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal-desktop.scss
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/AccessWalletLayout/components/WalletOption/index.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/store/mutations.js
  src/store/state.js
  tests/unit/helpers/mockStore.js
  tests/unit/helpers/setupTooling.js
  tests/unit/specs/src/components/Notification/Notification.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/ConfirmationContainer.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.spec.js
  tests/unit/specs/src/containers/FooterContainer/FooterContainer.spec.js
  tests/unit/specs/src/dapps/BuySubdomain/BuySubdomain.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/RegisterDomainContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/components/FinalizeModal/FinalizeModal.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/EnsBidContainer/EnsBidContainer.spec.js
  tests/unit/specs/src/dapps/RegisterDomainContainer/containers/ManageENSContainer/ManageENSContainer.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/AccessWalletLayout.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.spec.js
  tests/unit/specs/src/layouts/HomeLayout/HomeLayout.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/InterfaceLayout.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceNetwork/InterfaceNetwork.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
Labels: Devop, Ready

#516 Bug/balance error
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
Labels: Bug, Ready

#521 Feature/darklist addr
  CHANGELOG.md
  fetchEthListData.js
  package-lock.json
  package.json
  src/assets/images/icons/ethereum-icon.png
  src/darklist/address-darklist.json
  src/directives/EnsResolver.js
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/store/getters.js
  src/store/mutations.js
  src/store/state.js
Labels: Feature, Ready

#534 set server side headers for develop
  CHANGELOG.md
  vue.config.js
Labels: Ready
