Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-12, with the labels that each got.

#1687 Bug/mewconnect path issue
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/builds/configs/base-routes.js
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
Labels: Bug, Ready

#1288 devop/mewconnect-migration
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/wallets/hybrid/MEWconnect/index.js
Labels: Devop, Ready

#1704 Add in TOS link
  CHANGELOG.md
  src/translations/terms-of-conditions/en_US.json
Labels: Bug, Ready

#1706 bug/resolver-fix
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.vue
  src/directives/AddrResolver.js
  src/directives/EnsResolver.js
  src/layouts/HomeLayout/components/TopBanner/TopBanner-desktop.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-mobile.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-tablet.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/main.js
  src/partners/bity/bity.js
  src/translations/dapps-ens/en_US.json
  src/translations/home/en_US.json
  src/translations/terms-of-conditions/en_US.json
  tests/unit/helpers/setupTooling.js
Labels: Hotfix, Ready

#1710 Devop/merge back master
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.vue
  src/directives/AddrResolver.js
  src/directives/EnsResolver.js
  src/layouts/HomeLayout/components/TopBanner/TopBanner-desktop.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-mobile.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-tablet.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/main.js
  src/partners/bity/bity.js
  src/translations/dapps-ens/en_US.json
  src/translations/home/en_US.json
  src/translations/terms-of-conditions/en_US.json
  tests/unit/helpers/setupTooling.js
Labels: Devop, Ready

#1713 Fix clear and translations
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/dapps/ManageENS/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/translations/dapps-ens/en_US.json
Labels: Bug, Ready

#1714 Fix/custom network ens
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
Labels: Fixed, Ready

#1719 sign message result not showing
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
Labels: Bug, Fixed, Hotfix, Ready

#1720 Devop/prep release
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
Labels: Devop, Ready

#1723 Bug/clear switching currencies
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
Labels: Bug, Ready

#1724 bug/nft-send-fix
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
Labels: Bug, Ready

#1721 release/v5.2.6
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/dapps/ManageENS/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/translations/dapps-ens/en_US.json
Labels: Ready, Release

#1732 Translations refactor
  CHANGELOG.md
  package.json
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.vue
  src/layouts/HardwaresLayout/HardwaresLayout.vue
  src/translations/access-wallet/en_US.json
  src/translations/create-wallet/en_US.json
  src/translations/dapps-ens/en_US.json
  src/translations/dapps-maker/en_US.json
  src/translations/dapps-schedule-tx/en_US.json
  src/translations/dapps-submission/en_US.json
  src/wallets/software/mnemonic/index.js
Labels: Devop, Ready

#1715 Fix/top banner buttons
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/layouts/HomeLayout/components/TopBanner/TopBanner-desktop.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-mobile.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-tablet.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner.vue
  src/scss/Global-desktop.scss
  src/translations/home/en_US.json
Labels: Bug, Ready

#1733 bug/issue-modal-errors-cx
  CHANGELOG.md
  src/builds/configs/base-routes.js
  src/layouts/ExtensionBrowserAction/components/ImportMnemonicModal/ImportMnemonicModal.vue
Labels: Bug, Ready

#1729 bug/verify-message
  CHANGELOG.md
  src/components/VerifyMessageInput/VerifyMessageInput.vue
Labels: Bug, Ready

#1700 devop/update-packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1735 release/v5.2.7
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/builds/configs/base-routes.js
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.vue
  src/layouts/ExtensionBrowserAction/components/ImportMnemonicModal/ImportMnemonicModal.vue
  src/layouts/HardwaresLayout/HardwaresLayout.vue
  src/layouts/HomeLayout/components/TopBanner/TopBanner-desktop.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-mobile.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-tablet.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner.vue
  src/layouts/PrivacyPolicyLayout/PrivacyPolicyLayout.scss
  src/layouts/TermsOfService/TermsOfService.vue
  src/scss/Global-desktop.scss
  src/translations/access-wallet/en_US.json
  src/translations/create-wallet/en_US.json
  src/translations/dapps-ens/en_US.json
  src/translations/dapps-maker/en_US.json
  src/translations/dapps-schedule-tx/en_US.json
  src/translations/dapps-submission/en_US.json
  src/translations/home/en_US.json
  src/wallets/software/mnemonic/index.js
Labels: Ready, Release

#1737 Update maker translations
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/HomeLayout/components/TopBanner/TopBanner-desktop.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-mobile.scss
  src/layouts/HomeLayout/components/TopBanner/TopBanner-tablet.scss
  src/scss/Global-desktop.scss
  src/translations/dapps-maker/en_US.json
Labels: Devop, Ready

#1756 devop/update-changelog
  README.md
  fetchLists/lists/tokens.json
  package-lock.json
Labels: Devop, Ready

#1744 devop/update-packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1747 Fix the Drop down menu on /#/interface/dapps/schedule-transaction
  CHANGELOG.md
  package-lock.json
  src/components/StandardDropdown/StandardDropdown.scss
  src/components/StandardDropdown/StandardDropdown.vue
Labels: Bug, Ready

#1754 Bug/dai savings withdraw
  CHANGELOG.md
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
Labels: Bug, Fixed, Ready

#1749 bug/token-search
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/translations/interface/en_US.json
  tests/unit/specs/src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
Labels: Bug, Ready

#1764 Update packages from greenkeeper
  package-lock.json
  package.json
Labels: Devop, Ready

#1741 Bug/chainid for send offline helper
  CHANGELOG.md
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#1730 Ui fix/chrome ex
  CONTRIBUTING.md
  DAPP_INTEGRATION.md
  src/assets/images/icons/button-software-no-padding.svg
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/data/DecisionTree/md/_suggestions.md
  src/data/DecisionTree/md/_swap_error.md
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/AccessWalletButton/AccessWalletButton.scss
  src/layouts/ExtensionBrowserAction/components/AccessWalletButton/AccessWalletButton.vue
  src/layouts/ExtensionBrowserAction/components/AccessWalletButton/index.js
  src/layouts/ExtensionBrowserAction/components/CxFooter/CxFooter.scss
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.scss
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.scss
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/components/WalletSideMenu/WalletSideMenu.scss
  src/layouts/ExtensionBrowserAction/containers/ExtensionAddWalletContainer/ExtensionAddWalletContainer.scss
  src/layouts/ExtensionBrowserAction/containers/ExtensionAddWalletContainer/ExtensionAddWalletContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/ExtensionNotification.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.scss
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionPopup/ExtensionPopup.scss
  src/layouts/ExtensionPopup/components/NetworkComponent/NetworkComponent.vue
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.vue
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainerBtabs.scss
  src/layouts/ExtensionPopup/containers/WelcomeContainer/WelcomeContainer.scss
  src/layouts/ExtensionPopup/containers/WelcomeContainer/WelcomeContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout-desktop.scss
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.scss
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
  src/scss/Global-desktop.scss
  src/translations/mew-cx/en_US.json
  src/translations/mew-cx/es_ES.json
  src/translations/mew-cx/ja_JP.json
  src/translations/mew-cx/ko_KR.json
  src/translations/mew-cx/ru_RU.json
  src/translations/mew-cx/zh_CN.json
Labels: Devop, Ready

#1763 bug/receive-function-standard-bug
  CHANGELOG.md
  README.md
  package-lock.json
  src/components/Buttons/StandardButton/StandardButton.vue
  src/components/DisconnectedModal/DisconnectedModal.vue
  src/components/IssueLogModal/IssueLogModal.vue
  src/components/LogoutWarningModal/LogoutWarningModal.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/dapps/MakerDai/components/CloseCdpModal/CloseCdpModal.vue
  src/dapps/MakerDai/components/DaiConfirmationModal/DaiConfirmationModal.vue
  src/dapps/MakerDai/components/MoveCdpModal/MoveCdp.vue
  src/dapps/MakerDai/components/PaybackModal/PaybackModal.vue
  src/dapps/MakerSai/components/CloseCdpModal/CloseCdpModal.vue
  src/dapps/MakerSai/components/DaiConfirmationModal/DaiConfirmationModal.vue
  src/dapps/MakerSai/components/MoveCdpModal/MoveCdp.vue
  src/dapps/MakerSai/components/PaybackModal/PaybackModal.vue
  src/dapps/routes.js
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal.vue
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/GettingStarted/GettingStarted.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/buyEthAd/buyEthAd.vue
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomConfirmRemove/NftCustomConfirmRemove.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  tests/unit/specs/src/components/DisconnectedModal/DisconnectedModal.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.spec.js
Labels: Bug, Ready

#1774 bug/addr-resolver-not-resolving-for-tokens
  CHANGELOG.md
  src/directives/AddrResolver.js
Labels: Bug, Ready

#1773 bug/convert-null-to-object
  CHANGELOG.md
  src/layouts/InterfaceLayout/InterfaceLayout.vue
Labels: Bug, Ready

#1775 bug/nft-error-catch
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
Labels: Bug, Ready

#1781 Hotfix/schedule view
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
Labels: Hotfix, Ready

#1782 Devop/sync develop with master
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
Labels: Devop, Ready

#1790 hotfix/fix send offline helper error
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Fixed, Hotfix, Ready

#1791 Fix header items for other languages
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/containers/HeaderContainer/HeaderContainer.vue
  src/scss/Global-desktop.scss
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  tests/unit/specs/src/containers/HeaderContainer/HeaderContainer.spec.js
Labels: Ready
