Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-11, with the labels that each got.

#1588 Bug/dashboard buttons not working
  CHANGELOG.md
  package-lock.json
  src/builds/mewcx/public/README.md
  src/builds/web/public/img/icons/icon192.png
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonNftManager/ButtonNftManager.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.vue
Labels: Bug, Ready

#1591 Patch up master
  CHANGELOG.md
  package-lock.json
  src/builds/mewcx/public/README.md
  src/builds/web/public/img/icons/icon192.png
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonNftManager/ButtonNftManager.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.vue
Labels: Devop, Ready

#1590 Bug/send offline copy tx
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/SignedTxModal/SignedTxModal.vue
Labels: Bug, Ready

#1589 bug/network-address-show-custom-first
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/wallets/bip44/ledgerPaths.js
Labels: Bug, Ready

#1585 Dapp submission ui updates
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/DappSubmissionLayout/DappSubmissionLayout.vue
  src/layouts/DappSubmissionLayout/components/BannerSubmitComponent/BannerSubmitComponent.scss
  src/layouts/DappSubmissionLayout/components/BannerSubmitComponent/BannerSubmitComponent.vue
  src/layouts/DappSubmissionLayout/components/MewSupportComponent/MewSupportComponent.scss
  src/layouts/DappSubmissionLayout/components/MewSupportComponent/MewSupportComponent.vue
  src/layouts/DappSubmissionLayout/components/SOTDComponent/SOTDComponent.scss
  src/layouts/DappSubmissionLayout/components/SocialAcctModal/SocialAcctModal.scss
  src/layouts/DappSubmissionLayout/components/StrengthOfInfoComponent/StrengthOfInfoComponent.scss
  src/layouts/DappSubmissionLayout/components/TagComponent/TagComponent.scss
  src/layouts/DappSubmissionLayout/containers/AboutYourDappContainer/AboutYourDappContainer.scss
  src/layouts/DappSubmissionLayout/containers/AboutYourDappContainer/AboutYourDappContainer.vue
  src/layouts/DappSubmissionLayout/containers/AboutYourDappTeamContainer.scss
  src/layouts/DappSubmissionLayout/containers/AboutYourTeamContainer/AboutYourTeamContainer.scss
  src/layouts/DappSubmissionLayout/containers/AboutYourTeamContainer/AboutYourTeamContainer.vue
Labels: Devop, Ready, UI

#1586 Devop/update packages
  CHANGELOG.md
  package-lock.json
  package.json
  src/translations/dapps/es_ES.json
  src/translations/dapps/ja_JP.json
  src/translations/dapps/ko_KR.json
  src/translations/dapps/ru_RU.json
  src/translations/dapps/zh_CN.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
Labels: Devop, Ready

#1594 Bug/cx bugs
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/assets/images/HelpCenter/category-send.svg
  src/assets/images/HelpCenter/category-support.svg
  src/assets/images/buttons/send-tx/send-tx-left.png
  src/assets/images/buttons/send-tx/send-tx-right.png
  src/assets/images/buttons/send-tx/send-tx-spaceman.png
  src/assets/images/etc/access-spaceman.png
  src/assets/images/icons/button-web3-disabled.svg
  src/assets/images/icons/button-web3.svg
  src/assets/images/icons/swap-widget.svg
  src/assets/images/networks/eth-logo.svg
  src/builds/mewcx/cxHelpers/backgroundEvents/web3-get-gas.js
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/AccessWalletLayout/components/Web3WalletModal/Web3WalletModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/ConvertUnits/components/UnitInput/UnitInput.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/MnemonicTableToDisplay.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToPrint/MnemonicTableToPrint.vue
  src/layouts/ExtensionBrowserAction/components/RemoveWalletModal/RemoveWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionWeb3Popup/components/AddressSelectionComponent/AddressSelectionComponent.vue
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.vue
  src/layouts/HelpCenterLayout/components/Categories/Categories.vue
  src/layouts/InformationPages/PrivacyPolicyLayout/PrivacyPolicyLayout.vue
  src/layouts/InformationPages/TermsAndConditionsLayout/TermsAndConditionsLayout.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/networks/types/ETH.js
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/translations/footer/zh_TW.json
  src/translations/terms-of-conditions/en_US.json
  src/translations/terms-of-conditions/es_ES.json
  src/translations/terms-of-conditions/ja_JP.json
  src/translations/terms-of-conditions/ko_KR.json
  src/translations/terms-of-conditions/ru_RU.json
  src/translations/terms-of-conditions/zh_CN.json
  src/translations/terms-of-conditions/zh_TW.json
  src/wallets/web3-provider/cx-web3-methods/eventHandler.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.spec.js
Labels: Bug, Ready

#1441 feature/ambrpay_integration
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/dapps/ambrpay.png
  src/dapps/Ambrpay/Ambrpay.scss
  src/dapps/Ambrpay/Ambrpay.vue
  src/dapps/Ambrpay/AmbrpayGlobal.scss
  src/dapps/Ambrpay/AmbrpayModified.js
  src/dapps/Ambrpay/components/ManageFundsModal/ManageFundsModal.scss
  src/dapps/Ambrpay/components/ManageFundsModal/ManageFundsModal.vue
  src/dapps/Ambrpay/components/ManageFundsModal/index.js
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.scss
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.vue
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/index.js
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.scss
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.vue
  src/dapps/Ambrpay/containers/SubscriptionForm/index.js
  src/dapps/Ambrpay/routes.js
  src/dapps/BuySubdomain/routes.js
  src/dapps/MakerDai/routes.js
  src/dapps/ManageENS/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/layouts/InterfaceLayout/components/BackButton/BackButton.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/translations/dapps-ambrpay/en_US.json
  src/translations/en_US.js
  src/workers/wallet.worker.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.spec.js
  tests/unit/specs/src/dapps/Ambrpay/ManageFundsModal/ManageFundsModal.spec.js
  tests/unit/specs/src/dapps/Ambrpay/ManageSubscriptionsModal/ManageSubscriptionsModal.spec.js
  tests/unit/specs/src/dapps/Ambrpay/SubscriptionForm/SubscriptionForm.spec.js
Labels: Feature, Ready, Waiting

#1605 increase ens wait time
  CHANGELOG.md
  src/dapps/ManageENS/ManageENS.vue
Labels: Bug, Fixed, Hotfix, Ready

#1609 XWallet Integration
  CHANGELOG.md
  package-lock.json
  src/assets/images/icons/HardwareWallet/xwallet.svg
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-desktop.scss
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-mobile.scss
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-tablet.scss
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal.vue
  src/layouts/AccessWalletLayout/components/XwalletModal/index.js
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/translations/access-wallet/en_US.json
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ja_JP.json
  src/translations/access-wallet/ko_KR.json
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/access-wallet/zh_TW.json
  src/wallets/bip44/walletTypes.js
Labels: Ready

#1610 Release v5.2.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/HardwareWallet/xwallet.svg
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-desktop.scss
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-mobile.scss
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal-tablet.scss
  src/layouts/AccessWalletLayout/components/XwalletModal/XwalletModal.vue
  src/layouts/AccessWalletLayout/components/XwalletModal/index.js
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/translations/access-wallet/en_US.json
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ja_JP.json
  src/translations/access-wallet/ko_KR.json
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/access-wallet/zh_TW.json
  src/wallets/bip44/walletTypes.js
Labels: Ready, Release

#1618 Add rel="noopener noreferrer" to links
  CHANGELOG.md
  package-lock.json
  src/components/BottomHelpLink/BottomHelpLink.vue
  src/components/DecisionTree/DecisionTree.vue
  src/components/FaqContents/BalancesNotLoadingOrShowingOnMyEtherWallet.vue
  src/components/SettingsModal/SettingsModal.vue
  src/components/WarningMessage/WarningMessage.vue
  src/data/DecisionTree/md/_Find_Trezor.md
  src/data/DecisionTree/md/_Find_other.md
  src/data/DecisionTree/md/_Forgot_pass_access.md
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/CreateWalletLayout/containers/ByJsonFileContainer/ByJsonFileContainer.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.vue
  src/layouts/DappSubmissionLayout/components/MewSupportComponent/MewSupportComponent.vue
  src/layouts/DappSubmissionLayout/components/SOTDComponent/SOTDComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionDappContainer/ExtensionDappContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionDappsContainer/ExtensionDappsContainer.vue
  src/layouts/ExtensionWeb3Popup/components/PasswordModalComponent/PasswordModalComponent.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/mewConnectAd/mewConnectAd.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/SignedTxModal/SignedTxModal.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
Labels: Devop, Ready

#1614 Devop/update web3 icons
  CHANGELOG.md
  src/assets/images/icons/button-web3-disabled.svg
  src/assets/images/icons/button-web3.svg
Labels: Devop, Ready

#1616 bug/mew-cx-error-on-login
  CHANGELOG.md
  src/builds/mewcx/public/favicon.png
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
Labels: Bug, Ready

#1619 Devop/dapp order
  CHANGELOG.md
  src/assets/images/icons/dapps/ambrpay-disabled.png
  src/assets/images/icons/dapps/makerdai-disabled.svg
  src/assets/images/new-label.png
  src/dapps/index.js
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/DappButtons/DappButtons.spec.js
Labels: Devop, Ready

#1612 devop/update-packages
  package-lock.json
  package.json
  src/components/FaqContents/index.js
  src/components/SwapWidget/index.js
  src/dapps/MakerDai/MakerCDP.js
  src/dapps/MakerDai/MakerDai.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/partners/kyber/config/kyberNetwork.abi.js
Labels: Devop, Ready

#1613 Bug/web3 modal behavior
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/button-web3-disabled.svg
  src/assets/images/icons/button-web3.svg
  src/assets/images/icons/dapps/ambrpay-disabled.png
  src/assets/images/icons/dapps/makerdai-disabled.svg
  src/assets/images/new-label.png
  src/builds/mewcx/public/favicon.png
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/dapps/index.js
  src/layouts/AccessWalletLayout/components/Web3WalletModal/Web3WalletModal.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/translations/access-wallet/en_US.json
  tests/unit/specs/src/layouts/InterfaceLayout/components/DappButtons/DappButtons.spec.js
Labels: Bug, Ready

#1617 Devop/add translations checkbox
  CHANGELOG.md
  DAPP_INTEGRATION.md
  PULL_REQUEST_TEMPLATE.md
Labels: Devop, Ready

#1636 devop/update-ens-character-limit
  CHANGELOG.md
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/translations/dapps/en_US.json
Labels: Devop, Ready

#1637 bug/generate-offline-tx
  CHANGELOG.md
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#1640 Bug/handle user rejection on access
  CHANGELOG.md
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-fetch-accounts.js
  src/builds/mewcx/cxHelpers/contentScript.js
  src/builds/mewcx/cxHelpers/cxWeb3.js
  src/wallets/web3-provider/providers/mew-cx-web3.js
Labels: Bug, Ready

#1641 Devop/swap revision 5
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/partners/bity/bity.js
  src/partners/kyber/config/config.js
  src/partners/kyber/kyber.js
  src/partners/simplex/simplex.js
  src/translations/swap/en_US.json
Labels: Devop, Ready

#1649 Sync develop with master
  CHANGELOG.md
  package.json
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
Labels: Ready

#1658 fix/toBuffer
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  src/helpers/misc.js
  src/wallets/WalletInterface.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/secalotEth.js
  src/wallets/hardware/trezor/index.js
  src/wallets/hybrid/MEWconnect/index.js
  src/wallets/software/mnemonic/index.js
Labels: Bug, Ready

#1650 bug/dashboard-dapp-featured
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/translations/access-wallet/en_US.json
Labels: Bug, Ready

#1659 hotfix/v5.2.3-hotfix.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  src/dapps/Ambrpay/AmbrpayModified.js
  src/dapps/ManageENS/ABI/permanentRegistrarController.js
  src/dapps/ManageENS/ManageENS.vue
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/Web3WalletModal/Web3WalletModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/translations/access-wallet/en_US.json
  src/wallets/WalletInterface.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/secalotEth.js
  src/wallets/hardware/trezor/index.js
  src/wallets/hybrid/MEWconnect/index.js
  src/wallets/software/mnemonic/index.js
  src/wallets/web3-provider/cx-web3-methods/eth_sendTransaction.js
  src/wallets/web3-provider/providers/given-provider.js
Labels: Ready, Release

#1669 Update packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1568 New ETH Endpoints
  CHANGELOG.md
  package-lock.json
  package.json
  src/builds/configs/types.js
  src/helpers/misc.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/networks/index.js
  src/networks/nodes/eth-mew.js
  src/registerServiceWorker.js
  src/router/index.js
  src/store/actions.js
  src/store/state.js
Labels: Ready

#1675 Add mewconnect link
  CHANGELOG.md
  src/containers/FooterContainer/FooterContainer.vue
  src/translations/footer/en_US.json
Labels: Feature, Ready

#1674 devop/use-token-symbols
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/ExtensionBrowserAction/components/TotalBalanceContainer/index.js
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.spec.js
Labels: Devop, Ready

#1651 Refactor/translations
  CHANGELOG.md
  src/components/EnterPinNumberModal/EnterPinNumberModal.vue
  src/components/ExpandingOption/ExpandingOption.vue
  src/components/NotificationsModal/NotificationsModal.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/dapps/Ambrpay/Ambrpay.vue
  src/dapps/Ambrpay/components/ManageFundsModal/ManageFundsModal.vue
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.vue
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.vue
  src/dapps/MakerDai/components/SelectCdpEntry/SelectCdpEntry.vue
  src/dapps/MakerDai/components/WithdrawModal/WithdrawModal.vue
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/dapps/MakerDai/containers/ManageCDP/ManageCDP.vue
  src/dapps/MakerDai/containers/ProxyMigrateCDP/ProxyMigrateCDP.vue
  src/layouts/AccessWalletLayout/components/FinneyModal/FinneyModal.vue
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal-desktop.scss
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal-mobile.scss
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal-tablet.scss
  src/layouts/AccessWalletLayout/components/MnemonicModal/MnemonicModal.vue
  src/layouts/AccessWalletLayout/components/MnemonicModal/components/CreateWalletInput/CreateWalletInput.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/CreateWalletLayout/components/CreateWalletInputFooter/CreateWalletInputFooter.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/ByMnemonicContainer.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/MnemonicTableToDisplay.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToPrint/MnemonicTableToPrint.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.scss
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/VerificationModal/VerificationModal.vue
  src/layouts/DappSubmissionLayout/components/SOTDComponent/SOTDComponent.vue
  src/layouts/ExtensionBrowserAction/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/ExtensionNotification.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/components/NotificationTypes/NotificationDetails/TransactionDetails.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/components/NotificationTypes/SwapDetails/SwapDetails.vue
  src/layouts/ExtensionWeb3Popup/containers/SignTxContainer/SignTxContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
  src/layouts/ViewWalletInfoLayout/components/ViewPrivateKey/ViewPrivateKey.vue
  src/translations/access-wallet/en_US.json
  src/translations/common/en_US.json
  src/translations/create-wallet/en_US.json
  src/translations/dapps-ambrpay/en_US.json
  src/translations/dapps-ens/en_US.json
  src/translations/dapps-maker/en_US.json
  src/translations/dapps-submission/en_US.json
  src/translations/en_US.js
  src/translations/errors-keepkey/en_US.json
  src/translations/header/en_US.json
  src/translations/home/en_US.json
  src/translations/notifications/en_US.json
  src/translations/send-tx/en_US.json
  src/translations/welcome-message/en_US.json
  tests/unit/specs/src/containers/ConfirmationContainer/ConfirmationContainer.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
Labels: Devop, Ready

#1647 Feature/address book
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AccordionMenu/AccordionMenu.scss
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/FullWidthDropdownMenu/FullWidthDropdownMenu.scss
  src/components/FullWidthDropdownMenu/FullWidthDropdownMenu.vue
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
  src/dapps/Ambrpay/AmbrpayGlobal.scss
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.vue
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.vue
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
  src/directives/EnsResolver.js
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.scss
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/scss/GlobalVariables.scss
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  src/translations/dapps-ens/en_US.json
  src/translations/interface/en_US.json
  src/translations/swap/en_US.json
  tests/unit/specs/src/dapps/Ambrpay/SubscriptionForm/SubscriptionForm.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.spec.js
Labels: Feature, Ready

#1668 update makerDAO dai branding
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/currency/coins/AllImages/DAI.svg
  src/assets/images/currency/coins/AllImages/SAI.svg
  src/partners/changelly/config/currencies.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/OtherCoins.js
  src/partners/partnersConfig/haveIcon.js
Labels: Devop, Ready

#1673 Feature/clear
  CHANGELOG.md
  package-lock.json
  src/components/StandardDropdown/StandardDropdown.vue
  src/components/StandardInput/StandardInput.vue
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  src/dapps/Ambrpay/Ambrpay.scss
  src/dapps/Ambrpay/Ambrpay.vue
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.vue
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.scss
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.vue
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.scss
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/scss/Global-tablet.scss
  src/translations/common/en_US.json
  src/translations/dapps-ambrpay/en_US.json
  tests/unit/specs/src/components/StandardDropdown/StandardDropdown.spec.js
  tests/unit/specs/src/dapps/Ambrpay/ManageSubscriptionsModal/ManageSubscriptionsModal.spec.js
  tests/unit/specs/src/dapps/Ambrpay/SubscriptionForm/SubscriptionForm.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.spec.js
Labels: Feature, Ready

#1681 feature/display-label
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/translations/en_US.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
Labels: Feature, Ready

#1682 Update Translations
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  src/layouts/HomeLayout/components/Social/Social.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/layouts/VerifyMessageLayout/VerifyMessageLayout.vue
  src/translations/help-center/en_US.json
  src/translations/home/en_US.json
  src/translations/other/verify-message/en_US.json
  src/translations/without-wallet/en_US.json
Labels: Devop, Ready

#1684 Bug/ens
  CHANGELOG.md
  src/components/Buttons/StandardButton/StandardButton.vue
  src/components/CustomerSupport/CustomerSupport.vue
  src/components/DisconnectedModal/DisconnectedModal.vue
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.scss
  src/containers/AboutContainer/AboutContainer.vue
  src/containers/NotificationsContainer/NotificationsContainer.vue
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.vue
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
  src/directives/EnsResolver.js
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToDisplay/MnemonicTableToDisplay.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/components/MnemonicTableToPrint/MnemonicTableToPrint.vue
  src/layouts/DappSubmissionLayout/components/SOTDComponent/SOTDComponent.vue
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.scss
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.scss
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonNftManager/ButtonNftManager.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/ViewWalletInfoLayout/components/ViewPrivateKey/ViewPrivateKey.vue
  src/translations/access-wallet/en_US.json
  src/translations/common/en_US.json
  src/translations/create-wallet/en_US.json
  src/translations/interface/en_US.json
Labels: Bug, Ready

#1685 feature/tnc-update
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/builds/configs/base-routes.js
  src/components/EnterPinNumberModal/EnterPinNumberModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/components/Web3WalletModal/Web3WalletModal.vue
  src/layouts/ExtensionBrowserAction/components/CxFooter/CxFooter.vue
  src/layouts/ExtensionWeb3Popup/components/PasswordModalComponent/PasswordModalComponent.vue
  src/layouts/GettingStarted/GettingStarted.vue
  src/layouts/PrivacyPolicyLayout/PrivacyPolicyLayout.vue
  src/layouts/TermsAndConditionsLayout/TermsAndConditionsLayout.vue
  src/layouts/TermsAndConditionsLayout/index.js
  src/layouts/TermsOfService/TermsOfService.scss
  src/layouts/TermsOfService/TermsOfService.vue
  src/layouts/TermsOfService/index.js
  src/translations/en_US.js
  src/translations/terms-of-conditions/en_US.json
Labels: Feature, Ready

#1686 Fix isValidAddress, merge clear n dropdown
  CHANGELOG.md
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/dapps/Ambrpay/containers/SubscriptionForm/SubscriptionForm.vue
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready
