Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-04, with the labels that each got.

#881 Clean up for release
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/assets/images/team/kosala.jpeg
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/KYCModal/KYCModal.scss
  src/containers/HeaderContainer/components/KYCModal/KYCModal.vue
  src/containers/HeaderContainer/components/KYCModal/helpers.js
  src/containers/HeaderContainer/components/KYCModal/index.js
  src/layouts/HomeLayout/HomeLayout.vue
Labels: Devop, Ready

#880 devop/prep-release
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/team/kosala.jpeg
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/KYCModal/KYCModal.scss
  src/containers/HeaderContainer/components/KYCModal/KYCModal.vue
  src/containers/HeaderContainer/components/KYCModal/helpers.js
  src/containers/HeaderContainer/components/KYCModal/index.js
  src/layouts/HomeLayout/HomeLayout.vue
Labels: Devop, Ready

#882 Develop
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/team/kosala.jpeg
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/KYCModal/KYCModal.scss
  src/containers/HeaderContainer/components/KYCModal/KYCModal.vue
  src/containers/HeaderContainer/components/KYCModal/helpers.js
  src/containers/HeaderContainer/components/KYCModal/index.js
  src/layouts/HomeLayout/HomeLayout.vue
Labels: Ready, Release

#860 allow zero as send offline nonce
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
Labels: Bug, Ready

#861 bug/spinner-reset
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/wallets/hardware/ledger/index.js
Labels: Bug, Ready

#890 Fix hardware wallet scroll bug
  CHANGELOG.md
  fetchLists/lists/contracts.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
Labels: Bug, Ready

#867 feature/metamask-safari-catch
  CHANGELOG.md
  src/assets/images/browser/brave.png
  src/assets/images/browser/chrome.png
  src/assets/images/browser/firefox.png
  src/assets/images/browser/opera.png
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.scss
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
  tests/unit/specs/src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.spec.js
Labels: Feature, Ready

#873 Ui/limit notification to 5
  CHANGELOG.md
  package-lock.json
  src/scss/Global-desktop.scss
Labels: Ready, UI

#893 Sentry fixes
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/wallets/hardware/bitbox/errorHandler.js
Labels: Devop, Ready

#887 Change mobile side menu button title from "Change" to "Menu"
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceContainerTitle/InterfaceContainerTitle.vue
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/common/zh_TW.json
Labels: Ready, UI

#852 Bug/parse adding token
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.scss
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.spec.js
Labels: Bug, Ready

#897 Ui/add network icon background
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.scss
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
Labels: Bug, Ready, UI

#896 Fix side menu bugs
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/LogoutWarningModal/LogoutWarningModal.vue
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.config.js
Labels: Bug, Ready

#809 Add currency symbol to configuration, keep using network name if not defined
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.vue
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/components/InterfaceBalance/InterfaceBalance.vue
  src/layouts/InterfaceLayout/components/InterfaceBalanceModal/InterfaceBalanceModal.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/networks/types/AKA.js
  src/networks/types/ATH.js
  src/networks/types/CLO.js
  src/networks/types/EGEM.js
  src/networks/types/ELLA.js
  src/networks/types/ESN.js
  src/networks/types/ETC.js
  src/networks/types/ETH.js
  src/networks/types/ETHO.js
  src/networks/types/EXP.js
  src/networks/types/GO.js
  src/networks/types/GOERLI.js
  src/networks/types/IOLITE.js
  src/networks/types/KOV.js
  src/networks/types/MIX.js
  src/networks/types/MUSIC.js
  src/networks/types/PIRL.js
  src/networks/types/POA.js
  src/networks/types/REOSC.js
  src/networks/types/RIN.js
  src/networks/types/ROP.js
  src/networks/types/RSK.js
  src/networks/types/RSKTEST.js
  src/networks/types/TOMO.js
  src/networks/types/TT.js
  src/networks/types/UBQ.js
  src/networks/types/WEB.js
  tests/unit/helpers/mockStore.js
Labels: WIP

#803 Feature/parse url params
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/team/kosala.jpeg
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/KYCModal/KYCModal.scss
  src/containers/HeaderContainer/components/KYCModal/KYCModal.vue
  src/containers/HeaderContainer/components/KYCModal/helpers.js
  src/containers/HeaderContainer/components/KYCModal/index.js
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/router/index.js
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
  src/store/state.js
  tests/unit/helpers/mockStore.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
Labels: Feature, Ready

#862 feature/add-hardware-page
  CHANGELOG.md
  src/assets/images/affiliates/bitbox.jpg
  src/assets/images/affiliates/finney.jpg
  src/assets/images/affiliates/keepkey.jpg
  src/assets/images/affiliates/ledger.jpg
  src/assets/images/affiliates/secalot.jpg
  src/assets/images/affiliates/trezor.jpg
  src/builds/configs/base-routes.js
  src/containers/FooterContainer/FooterContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-mobile.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-tablet.scss
  src/layouts/HardwaresLayout/HardwaresLayout.scss
  src/layouts/HardwaresLayout/HardwaresLayout.vue
  src/layouts/HardwaresLayout/index.js
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProviderInfoList/ProviderInfoList.scss
  src/scss/Global-desktop.scss
  src/scss/Global-mobile.scss
  src/scss/Global-tablet.scss
  src/scss/GlobalVariables.scss
Labels: Feature, Ready

#898 Ui/add monospace font
  CHANGELOG.md
  src/assets/fonts/QldKNThLqRwH-OJ1UHjlKGlW5qhWxg.woff2
  src/assets/fonts/QldKNThLqRwH-OJ1UHjlKGlX5qhWxg.woff2
  src/assets/fonts/QldKNThLqRwH-OJ1UHjlKGlZ5qg.woff2
  src/assets/fonts/QldXNThLqRwH-OJ1UHjlKGHiw71m5_zIDQ.woff2
  src/assets/fonts/QldXNThLqRwH-OJ1UHjlKGHiw71n5_zIDQ.woff2
  src/assets/fonts/QldXNThLqRwH-OJ1UHjlKGHiw71p5_w.woff2
  src/assets/google-fonts.css
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/scss/Global-desktop.scss
Labels: Ready, UI

#899 Fix/hw wallet binary msg sign
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/orange-warn.png
  src/builds/configs/base-routes.js
  src/components/VerifyMessageInput/VerifyMessageInput.scss
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  src/components/VerifyMessageInput/index.js
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmModal.scss
  src/containers/FooterContainer/FooterContainer.vue
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/components/PrintModal/PrintModal.scss
  src/dapps/ManageENS/components/PrintModal/PrintModal.vue
  src/helpers/index.js
  src/helpers/messageUtil.js
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/components/SignatureModal/SignatureModal.scss
  src/layouts/InterfaceLayout/components/SignatureModal/SignatureModal.vue
  src/layouts/InterfaceLayout/components/SignatureModal/index.js
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.scss
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.vue
  src/layouts/VerifyMessageLayout/VerifyMessageLayout.scss
  src/layouts/VerifyMessageLayout/VerifyMessageLayout.vue
  src/layouts/VerifyMessageLayout/index.js
  src/scss/Global-desktop.scss
  src/scss/GlobalVariables.scss
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/translations/footer/zh_TW.json
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/secalotEth.js
  src/wallets/hardware/trezor/index.js
  src/wallets/software/mnemonic/index.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.spec.js
Labels: Bug, Ready

#906 Update text and modal for hardware affiliates
  CHANGELOG.md
  src/builds/configs/base-routes.js
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal-desktop.scss
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal-desktop.scss
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/HardwaresLayout/HardwaresLayout.vue
Labels: Devop, Ready

#865 Add TX history menu
  CHANGELOG.md
  package-lock.json
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/filters/Capitalize.js
  src/helpers/misc.js
  src/scss/Global-desktop.scss
Labels: Feature, Ready

#908 Bug/fixes for release
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/router/index.js
Labels: Bug, Ready

#909 Devop/data catch
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/router/index.js
Labels: Devop, Ready

#920 Bug/fix interface layout bugs
  CHANGELOG.md
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/networks/types/TOMO.js
Labels: Bug, Ready

#934 Feature/add virus total
  .travis.yml
  CHANGELOG.md
  package-lock.json
Labels: Devop, Feature, Ready

#935 Fix/mewcx build
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  public/index.css
  public/index.html
  src/builds/mewcx/public/img/icons/icon128.png
  src/builds/mewcx/public/img/icons/icon16.png
  src/builds/mewcx/public/img/icons/icon192.png
  src/builds/mewcx/public/img/icons/icon32.png
  src/builds/mewcx/public/img/icons/icon48.png
  src/builds/mewcx/public/manifest.json
  src/builds/web/public/img/icons/android-chrome-192x192.png
  src/builds/web/public/img/icons/android-chrome-512x512.png
  src/builds/web/public/img/icons/apple-touch-icon-120x120.png
  src/builds/web/public/img/icons/apple-touch-icon-152x152.png
  src/builds/web/public/img/icons/apple-touch-icon-180x180.png
  src/builds/web/public/img/icons/apple-touch-icon-60x60.png
  src/builds/web/public/img/icons/apple-touch-icon-76x76.png
  src/builds/web/public/img/icons/apple-touch-icon.png
  src/builds/web/public/img/icons/favicon-16x16.png
  src/builds/web/public/img/icons/favicon-32x32.png
  src/builds/web/public/img/icons/msapplication-icon-144x144.png
  src/builds/web/public/img/icons/mstile-150x150.png
  src/builds/web/public/img/icons/safari-pinned-tab.svg
  src/builds/web/public/img/spaceman.png
  src/builds/web/public/manifest.json
  src/builds/web/public/robots.txt
  src/builds/web/storage/index.js
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/networks/types/TOMO.js
  src/networks/types/WEB.js
  vue.config.js
Labels: Devop, Fixed, WIP

#922 Devop/sentry migrate
  CHANGELOG.md
  Dockerfile
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/App.scss
  src/dapps/ScheduleTransaction/routes.js
  src/main.js
  src/wallets/web3-provider/methods/eth_sign.js
Labels: Devop, Ready

#960 vscode chrome debug settings added
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  CHANGELOG.md
  fetchLists/lists/tokens.json
  jsconfig.json
  package-lock.json
  package.json
  vue.config.js
Labels: Feature, Ready

#938 devop/metamask-integration
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/MetamaskModal/MetamaskModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
Labels: Devop, Ready

#923 feature/hardware-modal-options
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal-desktop.scss
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  vue.config.js
Labels: Feature, Ready

#905 update rates after user amount input
  CHANGELOG.md
  src/assets/images/currency/coins/AllImages/MEW.png
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.vue
  src/partners/changelly/config/currencies.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/partners.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/OtherCoins.js
Labels: Devop, Ready

#910 Bug/ledger app support
  .vscode/extensions.json
  CHANGELOG.md
  package-lock.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/LedgerAppModal/LedgerAppModal.scss
  src/layouts/AccessWalletLayout/components/LedgerAppModal/LedgerAppModal.vue
  src/layouts/AccessWalletLayout/components/LedgerAppModal/index.js
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/networks/types/GOERLI.js
  src/networks/types/MIX.js
  src/scss/Global-desktop.scss
  src/wallets/bip44/ledgerPaths.js
  src/wallets/bip44/paths.js
  src/wallets/hardware/ledger/appPaths.js
  vue.config.js
Labels: Bug, Ready

#925 Add gas amount to Send TX page
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.scss
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
Labels: Devop

#973 Local Node Support
  CHANGELOG.md
  package.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/wallets/web3-provider/providers/http-provider.js
  src/wallets/web3-provider/providers/http-request-manager.js
Labels: Feature, Ready

#976 Bug/web3 wallet support
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Notification/components/NotificationTypes/SwapDetails/SwapDetails.vue
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.vue
  src/containers/FaqsContainer/FaqsContainer.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/FooterContainer/affiliates.js
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/HardwaresLayout/HardwaresLayout.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/PrivacyPolicyLayout/PrivacyPolicyLayout.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/translations/confirmation/en_US.json
  src/translations/footer/en_US.json
Labels: Bug, Ready

#985 add presale and old mew wallet support
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/index.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/workers/wallet.worker.js
Labels: Fixed, Ready

#982 Bug/send offline nonce
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
Labels: Bug, Ready

#977 Add DEXON network support
  src/assets/images/networks/dexon.svg
  src/networks/nodes/dexon.js
  src/networks/nodes/index.js
  src/networks/types/DXN.js
  src/networks/types/index.js
  src/scss/GlobalVariables.scss
  src/wallets/bip44/keepkeyPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
Labels: Devop, Ready

#465 Custom regular and minimum gas price
  src/components/SettingsModal/SettingsModal.vue
  src/store/state.js
Labels: Ready

#1015 Fixes/sentry
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.vue
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/translations/errors-trezor/en_US.json
  src/wallets/hardware/trezor/errorHandler.js
Labels: Fixed, Ready

#1020 Devop/ledger paths
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/wallets/hardware/ledger/appPaths.js
Labels: Devop, Ready

#928 Adding Metadium network
  src/assets/images/networks/meta.svg
  src/networks/nodes/index.js
  src/networks/nodes/meta.js
  src/networks/types/META.js
  src/networks/types/index.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
Labels: Ready

#957 Add Solidum Support
  src/assets/images/networks/sum.svg
  src/networks/nodes/index.js
  src/networks/nodes/sum.js
  src/networks/types/SUM.js
  src/networks/types/index.js
  src/scss/GlobalVariables.scss
  src/wallets/bip44/keepkeyPaths.js
  src/wallets/bip44/ledgerPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
Labels: Ready

#987 Testing/initial setup
  jest.config.js
  package-audit.js
  package-lock.json
  package.json
  tests/unit/helpers/mockStore.js
  tests/unit/helpers/setupTooling.js
  tests/unit/specs/src/components/AddressQrcodeModal.spec.js/AddressQrcodeModal.spec.js
  tests/unit/specs/src/components/CustomerSupport/CustomerSupport.spec.js
  tests/unit/specs/src/components/DisconnectedModal/DisconnectedModal.spec.js
  tests/unit/specs/src/components/DropDownBidCurrencySelector/DropDownBidCurrencySelector.spec.js
  tests/unit/specs/src/components/Notification/Notification.spec.js
  tests/unit/specs/src/dapps/ManageENS/containers/EnsBidContainer/EnsBidContainer.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/CurrencyPicker/CurrencyPicker.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.spec.js
Labels: Devop, Ready

#969 update kyber apis
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/partners/bity/bity-calls.js
  src/partners/bity/config.js
  src/partners/kyber/config/config.js
  src/partners/kyber/config/index.js
  src/partners/kyber/kyber-calls.js
  src/partners/kyber/kyber.js
  src/partners/partnersConfig/config.js
Labels: Devop, Ready

#1014 private key improvement
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal.vue
Labels: Devop, Ready

#1016 Bug/address whitespace
  CHANGELOG.md
  src/dapps/SecureTransaction/SecureTransaction.vue
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.spec.js
Labels: Bug, Ready
