Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2019-03, with the labels that each got.

#752 devop/prep-hotfix
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/CustomerSupport/CustomerSupport.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.scss
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/filters/ConcatAddr.js
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-tablet.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/ConvertUnits/components/UnitInput/UnitInput.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout-desktop.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.scss
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.vue
  src/scss/Global-desktop.scss
  src/translations/create-wallet/en_US.json
  src/translations/create-wallet/es_ES.json
  src/translations/create-wallet/ja_JP.json
  src/translations/create-wallet/ko_KR.json
  src/translations/create-wallet/ru_RU.json
  src/translations/create-wallet/zh_CN.json
Labels: Devop, Ready

#759 Devop/sync develop
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/CustomerSupport/CustomerSupport.vue
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.scss
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/filters/ConcatAddr.js
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-tablet.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/ConvertUnits/components/UnitInput/UnitInput.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout-desktop.scss
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SignMessageContainer/SignMessageContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.scss
  src/layouts/InterfaceLayout/containers/VerifyMessageContainer/VerifyMessageContainer.vue
  src/scss/Global-desktop.scss
  src/translations/create-wallet/en_US.json
  src/translations/create-wallet/es_ES.json
  src/translations/create-wallet/ja_JP.json
  src/translations/create-wallet/ko_KR.json
  src/translations/create-wallet/ru_RU.json
  src/translations/create-wallet/zh_CN.json
Labels: Devop, Ready

#767 Bug/mobile block number
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/CustomerSupport/CustomerSupport.vue
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/networks/nodes/poa.js
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
  src/store/state.js
  src/translations/errors-secalot/en_US.json
  src/translations/errors-secalot/es_ES.json
  src/translations/errors-secalot/ja_JP.json
  src/translations/errors-secalot/ko_KR.json
  src/translations/errors-secalot/ru_RU.json
  src/translations/errors-secalot/zh_CN.json
  src/translations/popover/en_US.json
  src/translations/popover/es_ES.json
  src/translations/popover/ja_JP.json
  src/translations/popover/ko_KR.json
  src/translations/popover/ru_RU.json
  src/translations/popover/zh_CN.json
  src/wallets/hardware/secalot/errorHandler.js
  src/wallets/hardware/secalot/secalotEth.js
  src/wallets/hardware/secalot/secalotUsb.js
Labels: Bug, Ready

#713 DAPP/Chronologic Schedule [5.0.6]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/icons/eac-hov.svg
  src/assets/images/icons/eac.svg
  src/assets/images/scheduling/eac-logo.svg
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.scss
  src/dapps/ScheduleTransaction/ScheduleHelpers.js
  src/dapps/ScheduleTransaction/ScheduleTransaction.scss
  src/dapps/ScheduleTransaction/ScheduleTransaction.vue
  src/dapps/ScheduleTransaction/components/ScheduledSuccess.scss
  src/dapps/ScheduleTransaction/components/ScheduledSuccess.vue
  src/dapps/ScheduleTransaction/components/ScheduledTransactionExplorerLink.vue
  src/dapps/ScheduleTransaction/containers/ScheduleView.scss
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
  src/dapps/ScheduleTransaction/containers/ScheduleViewUnscoped.scss
  src/dapps/ScheduleTransaction/routes.js
  src/dapps/index.js
  src/dapps/routes.js
Labels: Feature

#774 Release 5.0.6
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/icons/eac-hov.svg
  src/assets/images/icons/eac.svg
  src/assets/images/scheduling/eac-logo.svg
  src/components/CustomerSupport/CustomerSupport.vue
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/dapps/ScheduleTransaction/ScheduleHelpers.js
  src/dapps/ScheduleTransaction/ScheduleTransaction.scss
  src/dapps/ScheduleTransaction/ScheduleTransaction.vue
  src/dapps/ScheduleTransaction/components/ScheduledSuccess.scss
  src/dapps/ScheduleTransaction/components/ScheduledSuccess.vue
  src/dapps/ScheduleTransaction/components/ScheduledTransactionExplorerLink.vue
  src/dapps/ScheduleTransaction/containers/ScheduleView.scss
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
  src/dapps/ScheduleTransaction/containers/ScheduleViewUnscoped.scss
  src/dapps/ScheduleTransaction/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/networks/nodes/poa.js
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
  src/store/state.js
  src/translations/confirmation/es_ES.json
  src/translations/confirmation/ja_JP.json
  src/translations/confirmation/ko_KR.json
  src/translations/confirmation/ru_RU.json
  src/translations/confirmation/zh_CN.json
  src/translations/errors-secalot/en_US.json
  src/translations/errors-secalot/es_ES.json
  src/translations/errors-secalot/ja_JP.json
  src/translations/errors-secalot/ko_KR.json
  src/translations/errors-secalot/ru_RU.json
  src/translations/errors-secalot/zh_CN.json
  src/translations/popover/en_US.json
  src/translations/popover/es_ES.json
  src/translations/popover/ja_JP.json
  src/translations/popover/ko_KR.json
  src/translations/popover/ru_RU.json
  src/translations/popover/zh_CN.json
  src/translations/privacy-policy/es_ES.json
  src/translations/privacy-policy/ja_JP.json
  src/translations/privacy-policy/ko_KR.json
  src/translations/privacy-policy/ru_RU.json
  src/translations/privacy-policy/zh_CN.json
  src/wallets/hardware/secalot/errorHandler.js
  src/wallets/hardware/secalot/secalotEth.js
  src/wallets/hardware/secalot/secalotUsb.js
Labels: Ready, Release

#782 Devop/finney modal
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/etc/finney.png
  src/assets/images/icons/button-finney-hover.png
  src/assets/images/icons/button-finney.png
  src/assets/images/networks/thundercore.svg
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/AccessWalletLayout/components/FinneyModal/FinneyModal.scss
  src/layouts/AccessWalletLayout/components/FinneyModal/FinneyModal.vue
  src/layouts/AccessWalletLayout/components/FinneyModal/index.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/networks/nodes/index.js
  src/networks/nodes/thundercore.js
  src/networks/types/TT.js
  src/networks/types/index.js
  src/scss/GlobalVariables.scss
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/wallets/bip44/keepkeyPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
Labels: Feature, Ready

#820 Add zh_TW (Traditional Chinese) translation [5.0.8]
  CHANGELOG.md
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.vue
  src/translations/access-wallet/zh_TW.json
  src/translations/common/zh_TW.json
  src/translations/confirmation/zh_TW.json
  src/translations/create-wallet/zh_TW.json
  src/translations/dapps/zh_TW.json
  src/translations/errors-bitbox/zh_TW.json
  src/translations/errors-global/zh_TW.json
  src/translations/errors-keepkey/zh_TW.json
  src/translations/errors-ledger/zh_TW.json
  src/translations/errors-secalot/zh_TW.json
  src/translations/errors-trezor/zh_TW.json
  src/translations/footer/zh_TW.json
  src/translations/getting-started/zh_TW.json
  src/translations/header/zh_TW.json
  src/translations/home/zh_TW.json
  src/translations/index.js
  src/translations/interface/zh_TW.json
  src/translations/popover/zh_TW.json
  src/translations/privacy-policy/zh_TW.json
  src/translations/team/zh_TW.json
  src/translations/terms-of-conditions/zh_TW.json
  src/translations/without-wallet/zh_TW.json
  src/translations/zh_TW.js
Labels: Ready

#813 Testing/initial setup [5.0.8]
  fetchLists/lists/tokens.json
  package-lock.json
  tests/unit/specs/src/components/Notification/Notification.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/ConfirmationContainer.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/CreateWalletLayout.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/components/CreateWalletInput/CreateWalletInput.spec.js
  tests/unit/specs/src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.spec.js
  tests/unit/specs/src/partners/kyber/kyber.spec.js
Labels: Ready

#825 fix success modal not linking to unlock wallet page [5.0.8]
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
Labels: Ready

#814 Better Ipad catch [5.0.8]
  CHANGELOG.md
  LICENSE
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/InformationPages/PrivacyPolicyLayout/PrivacyPolicyLayout.vue
  src/layouts/InformationPages/TermsAndConditionsLayout/TermsAndConditionsLayout.vue
  src/layouts/TeamLayout/TeamLayout.vue
  src/translations/common/en_US.json
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/translations/terms-of-conditions/en_US.json
  src/translations/terms-of-conditions/ja_JP.json
  tests/unit/specs/src/components/Notification/Notification.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/ConfirmationContainer.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/CreateWalletLayout.spec.js
  tests/unit/specs/src/layouts/CreateWalletLayout/components/CreateWalletInput/CreateWalletInput.spec.js
  tests/unit/specs/src/partners/kyber/kyber.spec.js
Labels: Bug, Ready

#841 kyber fix
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/partners/bity/bity.js
  src/partners/changelly/changelly.js
  src/partners/kyber/kyber.js
Labels: Hotfix, Ready

#843 fix no success modal showing after batch send
  CHANGELOG.md
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
Labels: Ready
