Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-05, with the labels that each got.

#2319 Devop/lock only install [v5]
  checklockconflicts.sh
  package.json
Labels: Devop, Ready

#2315 MEW wallet banner
  CHANGELOG.md
  src/components/WalletLaunchedBanner/WalletLaunchedBanner.scss
  src/components/WalletLaunchedBanner/WalletLaunchedBanner.vue
  src/translations/home/en_US.json
Labels: Devop, Ready, v5

#2312 Devop/update web3
  package-lock.json
  package.json
Labels: Devop, Ready

#2321 devop/update-packages
  compileBaseSwapOptions.js
  package-lock.json
  package.json
Labels: Devop, Ready

#2305 Fix mobile menu icons
  CHANGELOG.md
  package.json
  src/assets/images/sidemenu/contract-active.svg
  src/assets/images/sidemenu/contract.svg
  src/assets/images/sidemenu/dapps-active.svg
  src/assets/images/sidemenu/dapps.svg
  src/assets/images/sidemenu/dashboard-active.svg
  src/assets/images/sidemenu/dashboard.svg
  src/assets/images/sidemenu/message-active.svg
  src/assets/images/sidemenu/message.svg
  src/assets/images/sidemenu/send-active.svg
  src/assets/images/sidemenu/send.svg
  src/assets/images/sidemenu/swap-active.svg
  src/assets/images/sidemenu/swap.svg
Labels: Ready

#2328 Bug/remove custom networks on online
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
Labels: Bug, Ready

#2334 devop/remove-legacy-etc-nodes
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/assets/images/networks/ftm.svg
  src/assets/images/networks/perkle.svg
  src/networks/nodes/etc-ethereumclassiccooperative-parity-classic.js
  src/networks/nodes/ftm.js
  src/networks/nodes/ftmscan.js
  src/networks/nodes/index.js
  src/networks/nodes/prkl.js
  src/networks/types/FTM.js
  src/networks/types/PRKL.js
  src/networks/types/index.js
  vueConfig/connections.js
Labels: Devop, Ready

#2323 polishing refinements to dex.ag
  CHANGELOG.md
  compileBaseSwapOptions.js
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/partners/dexAg/dexAg.js
Labels: Devop, Ready, v5

#2314 Disable withdraw/borrow with healthfactor below 1
  CHANGELOG.md
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.scss
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/create-wallet/ru_RU.json
  src/translations/dapps-aave/en_US.json
  src/translations/dapps-aave/es_ES.json
  src/translations/dapps-aave/ja_JP.json
  src/translations/dapps-aave/ko_KR.json
  src/translations/dapps-aave/ru_RU.json
  src/translations/dapps-aave/zh_CN.json
  src/translations/dapps-ambrpay/ru_RU.json
  src/translations/dapps-maker/ru_RU.json
  src/translations/dapps-mcd-maker/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/interface/ru_RU.json
  src/translations/mew-cx/ru_RU.json
  src/translations/notifications/ru_RU.json
  src/translations/sign-message/ru_RU.json
  src/translations/swap/es_ES.json
  src/translations/swap/ja_JP.json
  src/translations/swap/ko_KR.json
  src/translations/swap/ru_RU.json
  src/translations/swap/zh_CN.json
  src/translations/without-wallet/ru_RU.json
  tests/unit/specs/src/dapps/Aave/containers/ActionContainer.spec.js
Labels: Bug, Ready, v5

#2327 Bug/token icons sizing
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.scss
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.scss
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/create-wallet/ru_RU.json
  src/translations/dapps-aave/en_US.json
  src/translations/dapps-aave/es_ES.json
  src/translations/dapps-aave/ja_JP.json
  src/translations/dapps-aave/ko_KR.json
  src/translations/dapps-aave/ru_RU.json
  src/translations/dapps-aave/zh_CN.json
  src/translations/dapps-ambrpay/ru_RU.json
  src/translations/dapps-maker/ru_RU.json
  src/translations/dapps-mcd-maker/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/interface/ru_RU.json
  src/translations/mew-cx/ru_RU.json
  src/translations/notifications/ru_RU.json
  src/translations/sign-message/ru_RU.json
  src/translations/swap/es_ES.json
  src/translations/swap/ja_JP.json
  src/translations/swap/ko_KR.json
  src/translations/swap/ru_RU.json
  src/translations/swap/zh_CN.json
  src/translations/without-wallet/ru_RU.json
  tests/unit/specs/src/dapps/Aave/containers/ActionContainer.spec.js
Labels: Bug, Ready

#2341 devop/prep-release
  package-lock.json
  package.json
Labels: Devop, Ready

#2350 Fix ambrpay sub status
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.scss
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.vue
  src/translations/dapps-ambrpay/en_US.json
  vueConfig/connections.js
Labels: Bug, Ready, v5

#2355 SCD system shutdown
  CHANGELOG.md
  src/dapps/MakerSai/DSProxy.json
  src/dapps/MakerSai/MakerCDP.js
  src/dapps/MakerSai/MakerDai.scss
  src/dapps/MakerSai/MakerDai.vue
  src/dapps/MakerSai/SaiProxyCreateAndExecute.json
  src/dapps/MakerSai/components/CheckBox/CheckBox.scss
  src/dapps/MakerSai/components/CheckBox/CheckBox.vue
  src/dapps/MakerSai/components/CheckBox/index.js
  src/dapps/MakerSai/components/CloseCdpModal/CloseCdpModal.scss
  src/dapps/MakerSai/components/CloseCdpModal/CloseCdpModal.vue
  src/dapps/MakerSai/components/CloseCdpModal/index.js
  src/dapps/MakerSai/components/DaiConfirmationModal/DaiConfirmationModal.scss
  src/dapps/MakerSai/components/DaiConfirmationModal/DaiConfirmationModal.vue
  src/dapps/MakerSai/components/DaiConfirmationModal/index.js
  src/dapps/MakerSai/components/DepositModal/DepositModal.scss
  src/dapps/MakerSai/components/DepositModal/DepositModal.vue
  src/dapps/MakerSai/components/DepositModal/index.js
  src/dapps/MakerSai/components/GenerateModal/GenerateModal.scss
  src/dapps/MakerSai/components/GenerateModal/GenerateModal.vue
  src/dapps/MakerSai/components/GenerateModal/index.js
  src/dapps/MakerSai/components/MoveCdpModal/MoveCdp.scss
  src/dapps/MakerSai/components/MoveCdpModal/MoveCdp.vue
  src/dapps/MakerSai/components/MoveCdpModal/index.js
  src/dapps/MakerSai/components/PaybackModal/PaybackModal.scss
  src/dapps/MakerSai/components/PaybackModal/PaybackModal.vue
  src/dapps/MakerSai/components/PaybackModal/index.js
  src/dapps/MakerSai/components/SelectCdpEntry/SelectCdpEntry.scss
  src/dapps/MakerSai/components/SelectCdpEntry/SelectCdpEntry.vue
  src/dapps/MakerSai/components/SelectCdpEntry/index.js
  src/dapps/MakerSai/components/WithdrawModal/WithdrawModal.scss
  src/dapps/MakerSai/components/WithdrawModal/WithdrawModal.vue
  src/dapps/MakerSai/components/WithdrawModal/index.js
  src/dapps/MakerSai/containers/CreateCDP/CreateCDP.scss
  src/dapps/MakerSai/containers/CreateCDP/CreateCDP.vue
  src/dapps/MakerSai/containers/CreateCDP/index.js
  src/dapps/MakerSai/containers/MakerHome/MakerHome.scss
  src/dapps/MakerSai/containers/MakerHome/MakerHome.vue
  src/dapps/MakerSai/containers/MakerHome/index.js
  src/dapps/MakerSai/containers/ManageCDP/ManageCDP.scss
  src/dapps/MakerSai/containers/ManageCDP/ManageCDP.vue
  src/dapps/MakerSai/containers/ManageCDP/index.js
  src/dapps/MakerSai/containers/ProxyMigrateCDP/ProxyMigrateCDP.scss
  src/dapps/MakerSai/containers/ProxyMigrateCDP/ProxyMigrateCDP.vue
  src/dapps/MakerSai/containers/ProxyMigrateCDP/index.js
  src/dapps/MakerSai/containers/SelectCDP/SelectCDP.scss
  src/dapps/MakerSai/containers/SelectCDP/SelectCDP.vue
  src/dapps/MakerSai/containers/SelectCDP/index.js
  src/dapps/MakerSai/ethersHelpers.js
  src/dapps/MakerSai/helpers.js
  src/dapps/MakerSai/routes.js
  src/dapps/index.js
  src/translations/dapps-maker/en_US.json
Labels: Devop, Ready, v5

#2351 devop/update-packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#2363 add warning to change gas price
  CHANGELOG.md
  src/helpers/responseHandler/responseMatches.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/partners/dexAg/dexAg.js
  src/partners/partners.js
  src/translations/swap/en_US.json
Labels: Ready

#2352 devop/update-v6-packages
  compileBaseSwapOptions.js
  fetchLists/configs.js
  fetchLists/index.js
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/builds/web/app.vue
  src/common/plugins/vuetify.js
  src/main.js
  src/web/containers/HeaderContainer/components/HeaderDesktop/HeaderDesktop.vue
  src/web/views/DashboardView/DashboardView.vue
  src/web/views/LandingPageView/Home/components/TopBanner/TopBanner.vue
  src/web/views/WalletView/WalletView.vue
  src/web/views/WalletView/components/Footer/Footer.vue
  src/web/views/WalletView/components/SideMenu/SideMenu.vue
  src/web/views/WalletView/components/SideMenu/components/AccordionMenu/AccordionMenu.vue
  src/web/views/WalletView/components/SideMenu/components/SystemMenu/SystemMenu.vue
  src/web/views/WalletView/components/SideMenu/components/ThemeSwitch/ThemeSwitch.vue
  src/web/views/WalletView/components/SideMenu/components/Version/Version.vue
  src/web/views/WalletView/components/SideMenu/components/Version/index.js
Labels: Devop, Ready

#2376 Feature/ens manage update
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/dapps/ManageENS/ABI/oldDeedAbi.js
  src/dapps/ManageENS/ABI/oldEnsAbi.js
  src/dapps/ManageENS/ManageENS.scss
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.scss
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/CreateCommitmentContainer/CreateCommitmentContainer.vue
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.scss
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/dapps/ManageENS/containers/EnsMultiManager/index.js
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/routes.js
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/BackButton/BackButton.scss
  src/layouts/InterfaceLayout/components/BackButton/BackButton.vue
  src/layouts/InterfaceLayout/components/ExpiredNamesModal/ExpiredNamesModal.scss
  src/layouts/InterfaceLayout/components/ExpiredNamesModal/ExpiredNamesModal.vue
  src/layouts/InterfaceLayout/components/ExpiredNamesModal/index.js
  src/layouts/InterfaceLayout/expiryAbi.js
  src/networks/types/PRKL.js
  src/networks/types/index.js
  src/translations/dapps-ens/en_US.json
Labels: Feature, Ready

#2372 devop/update-packages [v5]
  package-lock.json
  package-test.js
  package.json
  src/dapps/Ambrpay/components/ManageSubscriptionsModal/ManageSubscriptionsModal.scss
  src/dapps/MakerDai/MakerCDP/MakerCDP.js
  src/dapps/MakerSai/MakerDai.scss
  src/dapps/ManageENS/ManageENS.scss
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.scss
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.scss
  src/layouts/InterfaceLayout/components/ExpiredNamesModal/ExpiredNamesModal.scss
Labels: Devop, Ready

#2338 Feature/combine tb contract with local
  .github/workflows/add-to-sentry-release.yml
  CHANGELOG.md
  README.md
  checklockconflicts.sh
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.scss
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/helpers/misc.js
  src/helpers/solidityTypes.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
  src/main.js
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/dapps-ambrpay/es_ES.json
  src/translations/dapps-ambrpay/ja_JP.json
  src/translations/dapps-ambrpay/ko_KR.json
  src/translations/dapps-ambrpay/ru_RU.json
  src/translations/dapps-ambrpay/zh_CN.json
  src/translations/dapps-ens/en_US.json
  src/translations/dapps-ens/es_ES.json
  src/translations/dapps-ens/ja_JP.json
  src/translations/dapps-ens/ko_KR.json
  src/translations/dapps-ens/ru_RU.json
  src/translations/dapps-ens/zh_CN.json
  src/translations/dapps-maker/es_ES.json
  src/translations/dapps-maker/ja_JP.json
  src/translations/dapps-maker/ko_KR.json
  src/translations/dapps-maker/ru_RU.json
  src/translations/dapps-maker/zh_CN.json
  src/translations/dapps-mcd-maker/ko_KR.json
  src/translations/dapps-mcd-maker/ru_RU.json
  src/translations/interface/ru_RU.json
  src/translations/mew-cx/ru_RU.json
  src/translations/swap/es_ES.json
  src/translations/swap/ja_JP.json
  src/translations/swap/ko_KR.json
  src/translations/swap/ru_RU.json
  src/translations/swap/zh_CN.json
  src/translations/without-wallet/ru_RU.json
  vueConfig/connections.js
Labels: Feature, Ready

#2384 Bug/no tokens
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/translations/dapps-ens/en_US.json
  src/translations/dapps-ens/es_ES.json
  src/translations/dapps-ens/ja_JP.json
  src/translations/dapps-ens/ko_KR.json
  src/translations/dapps-ens/ru_RU.json
  src/translations/dapps-ens/zh_CN.json
Labels: Bug, Ready

#2395 devop/fix sentry release [v5]
  .eslintrc.js
  .github/workflows/add-to-sentry-release.yml
  .github/workflows/build-cx-generate-zip.yml
  .github/workflows/deploy-live.yml
  CHANGELOG.md
  Dockerfile
  ENV_VARS.js
  jest.config.js
  package-lock.json
  package.json
  vueConfig/defaultConfigs.js
Labels: Devop, Ready, v5

#2398 devop/update-packages [v5]
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  vueConfig/mew.js
  vueConfig/mewcx.js
Labels: Devop, Ready

#2394 devop/update-terms [v5]
  CHANGELOG.md
  src/layouts/TermsOfService/TermsOfService.vue
  src/translations/terms-of-conditions/en_US.json
Labels: Devop, Ready

#2388 Fix/sentry kvhnuke [v5]
  CHANGELOG.md
  Dockerfile
  ENV_VARS.js
  package-lock.json
  package.json
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/globalErrorHandler.js
  src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/index.js
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/index.js
  src/main.js
  src/translations/common/en_US.json
  src/translations/errors-coolwallet/en_US.json
  src/translations/errors-global/en_US.json
  src/translations/errors-ledger/en_US.json
  src/wallets/hardware/coolwallet/errorHandler.js
  src/wallets/hardware/ledger/errorHandler.js
  src/wallets/web3-provider/etherscan-proxy.js
  vueConfig/connections.js
  vueConfig/mewcx.js
Labels: Ready, v5

#2399 Devop/v6 update packages
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  vueConfig/mew.js
  vueConfig/mewcx.js
Labels: Devop, Ready

#2389 bug/perkle [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/networks/nodes/prkl.js
  vueConfig/connections.js
Labels: Bug, Ready, v5

#2397 Bug/unable to validate address
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/translations/swap/en_US.json
Labels: Fixed, Ready, v5

#2396 Bug/sentry fixes/jess
  CHANGELOG.md
  package-test.js
  src/dapps/Aave/Aave.scss
  src/dapps/Aave/Aave.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.scss
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/supportedTxt.js
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
Labels: Bug, Ready, v5

#2400 Bug/sentry fixes y [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/supportedCoins.js
  src/dapps/ManageENS/supportedTxt.js
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/BitboxSelectModal/BitboxSelectModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/translations/errors-global/en_US.json
  src/wallets/web3-provider/methods/eth_coinbase.js
Labels: Bug, Ready
