Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-09, with the labels that each got.

#2559 Devop/update gas calculation
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/builds/web/app.vue
  src/components/Card1/Card1.vue
  src/components/SettingsModal/SettingsModal.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/dapps/MakerDai/containers/MigrateCDP/MigrateCDP.vue
  src/dapps/MakerDai/containers/MigrateDai/MigrateDai.vue
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.scss
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/SignedTxModal/SignedTxModal.vue
  src/layouts/PressKit/PressKit.vue
  src/layouts/SecurityPolicy/SecurityPolicy.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/wallets/hardware/bcvault/errorHandler.js
Labels: Devop, Ready

#2560 release/v5.7.7
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/components/Card1/Card1.vue
  src/components/SettingsModal/SettingsModal.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/dapps/MakerDai/containers/MigrateCDP/MigrateCDP.vue
  src/dapps/MakerDai/containers/MigrateDai/MigrateDai.vue
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.scss
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.vue
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/AccessWalletLayout/components/SoftwareModal/SoftwareModal.vue
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/components/SignedTxModal/SignedTxModal.vue
  src/layouts/PressKit/PressKit.vue
  src/layouts/SecurityPolicy/SecurityPolicy.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/wallets/hardware/bcvault/errorHandler.js
Labels: Ready, Release

#2564 devop/sync-develop
  package-audit.js
  package-lock.json
  package.json
Labels: Devop, Ready

#2574 feature/sending-to-contract-address-warning
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.scss
  src/dapps/Aave/components/ActionModal/ActionModal.scss
  src/directives/AddrResolver.js
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal-desktop.scss
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal-mobile.scss
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal-tablet.scss
  src/layouts/ExtensionBrowserAction/components/WalletSideMenu/WalletSideMenu.scss
  src/scss/Global-desktop.scss
  src/translations/errors-global/en_US.json
Labels: Feature, Ready

#2566 Fix gas price calculation
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/translations/getting-started/en_US.json
  src/translations/getting-started/es_ES.json
  src/translations/getting-started/ja_JP.json
  src/translations/getting-started/ko_KR.json
  src/translations/getting-started/zh_CN.json
Labels: Ready, Release

#2573 when using MEW wallet add from to Tx object if missing
  CHANGELOG.md
  src/wallets/hybrid/MEWconnect/index.js
Labels: Bug, Fixed, Ready, v5

#2576 release/v5.7.8
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.scss
  src/dapps/Aave/components/ActionModal/ActionModal.scss
  src/directives/AddrResolver.js
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal-desktop.scss
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal-mobile.scss
  src/layouts/AccessWalletLayout/components/PrivateKeyModal/PrivateKeyModal-tablet.scss
  src/layouts/ExtensionBrowserAction/components/WalletSideMenu/WalletSideMenu.scss
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/scss/Global-desktop.scss
  src/translations/errors-global/en_US.json
  src/translations/getting-started/en_US.json
  src/translations/getting-started/es_ES.json
  src/translations/getting-started/ja_JP.json
  src/translations/getting-started/ko_KR.json
  src/translations/getting-started/zh_CN.json
  src/wallets/hybrid/MEWconnect/index.js
Labels: Ready, Release

#2582 hotfix/add EthVM
  CHANGELOG.md
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/translations/access-wallet/en_US.json
  src/translations/footer/en_US.json
  src/translations/header/en_US.json
Labels: Hotfix, Ready, v5

#2583 Develop
  CHANGELOG.md
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/translations/access-wallet/en_US.json
  src/translations/footer/en_US.json
  src/translations/header/en_US.json
Labels: Ready, Release, v5

#2586 fix for send offline using MEW wallet and ethVM metamask link error
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/store/main/state.js
  src/translations/common/en_US.json
  src/wallets/hybrid/MEWconnect/index.js
Labels: Bug, Hotfix, Ready, v5

#2595 Fix weird interaction
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/helpers/gasMultiplier.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.vue
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly.js
  src/partners/dexAg/dexAg.js
  src/partners/partners.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.spec.js
Labels: Ready, Release

#2597 Release v5.7.9
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/helpers/gasMultiplier.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly.js
  src/partners/dexAg/config/config.js
  src/partners/dexAg/dexAg-calls.js
  src/partners/dexAg/dexAg.js
  src/partners/partners.js
  src/store/main/actions.js
  src/store/main/mutations.js
  src/store/main/state.js
  src/translations/common/en_US.json
  src/translations/errors-global/en_US.json
  src/wallets/hybrid/MEWconnect/index.js
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.spec.js
Labels: Ready, Release

#2603 release/v5.7.9
  CHANGELOG.md
  fetchLists/lists/contracts.json
  package-lock.json
  package.json
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/helpers/gasMultiplier.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/partners/dexAg/config/config.js
  src/partners/dexAg/dexAg-calls.js
  src/partners/dexAg/dexAg.js
  src/store/main/actions.js
  src/store/main/mutations.js
  src/store/main/state.js
  src/translations/errors-global/en_US.json
Labels: Ready, Release
