Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-04, with the labels that each got.

#2197 devop/sync-master [v5]
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/github-release.yml
  CHANGELOG.md
  package.json
  src/layouts/TeamLayout/TeamLayout.vue
Labels: Ready

#2199 devop/update-package [v5]
  package-lock.json
  package.json
Labels: Devop, Ready

#2217 Bug/ui fixes
  package-lock.json
  package-test.js
  src/builds/web/app.vue
  src/containers/HeaderContainer/HeaderContainer.scss
Labels: Bug, Ready

#2218 Unstoppable ui changes [v5]
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/dapps/unstoppable-blue.png
  src/assets/images/icons/dapps/unstoppable.png
  src/dapps/Aave/Aave.vue
  src/dapps/Ambrpay/Ambrpay.vue
  src/dapps/Unstoppable/Unstoppable.scss
  src/dapps/Unstoppable/Unstoppable.vue
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.scss
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.vue
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.scss
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.vue
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.scss
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.vue
  src/dapps/Unstoppable/containers/PaymentMethodContainer/PaymentMethodContainer.scss
  src/dapps/Unstoppable/containers/PaymentMethodContainer/PaymentMethodContainer.vue
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.scss
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.vue
  src/dapps/Unstoppable/routes.js
  src/dapps/index.js
  src/translations/common/en_US.json
  src/translations/dapps-unstoppable/en_US.json
Labels: Feature, WIP, v5

#2227 devop/greenkeeper-packages
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#2203 Bug/current cx bug [v5]
  .github/workflows/generate-cx-zip.yml
  CHANGELOG.md
  package-lock.json
  src/builds/mewcx/cxHelpers/cxWeb3.js
  src/layouts/ExtensionWeb3Popup/containers/SignMsgContainer/SignMsgContainer.vue
  src/layouts/ExtensionWeb3Popup/containers/SignTxContainer/SignTxContainer.vue
  src/wallets/web3-provider/providers/mew-cx-web3.js
  vueConfig/mewcx.js
Labels: Bug, Ready

#2236 devop/sync-master;
  .github/workflows/deploy-live.yml
  CHANGELOG.md
  src/builds/mewcx/cxHelpers/contentScript.js
Labels: Devop, Ready

#2244 devop/update-coolwallet-link [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/contentScript.js
  src/containers/FooterContainer/affiliates.js
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.vue
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
Labels: Devop, Ready

#2243 devop/update-packages [v5]
  .github/workflows/deploy-live.yml
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
Labels: Devop, Ready

#2245 scale AdEx ad to fit screen [v5]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.vue
Labels: Devop, Ready

#2246 release/v5.5.3
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/containers/FooterContainer/affiliates.js
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.vue
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.vue
Labels: Ready, Release

#2237 Devop/cx build workflow [v5]
  .github/workflows/build-cx-generate-zip.yml
  CHANGELOG.md
Labels: Devop, Ready

#2255 devop/update-packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#2229 Unstoppabledomain/develop/translate [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/card.svg
  src/assets/images/icons/crypto.svg
  src/assets/images/icons/dapps/unstoppable-blue.png
  src/assets/images/icons/dapps/unstoppable.png
  src/dapps/Aave/Aave.vue
  src/dapps/Ambrpay/Ambrpay.vue
  src/dapps/Unstoppable/Unstoppable.scss
  src/dapps/Unstoppable/Unstoppable.vue
  src/dapps/Unstoppable/containers/ClaimPendingContainer/ClaimPendingContainer.scss
  src/dapps/Unstoppable/containers/ClaimPendingContainer/ClaimPendingContainer.vue
  src/dapps/Unstoppable/containers/ClaimPendingContainer/index.js
  src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.scss
  src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.vue
  src/dapps/Unstoppable/containers/CompletedContainer/index.js
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.scss
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.vue
  src/dapps/Unstoppable/containers/ConfirmContainer/index.js
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.scss
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.vue
  src/dapps/Unstoppable/containers/CryptoContainer/index.js
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.scss
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.vue
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/index.js
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.scss
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.vue
  src/dapps/Unstoppable/containers/StripeContainer/index.js
  src/dapps/Unstoppable/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/create-wallet/ru_RU.json
  src/translations/dapps-ambrpay/ru_RU.json
  src/translations/dapps-maker/ru_RU.json
  src/translations/dapps-unstoppable/en_US.json
  src/translations/dapps-unstoppable/es_ES.json
  src/translations/dapps-unstoppable/ja_JP.json
  src/translations/dapps-unstoppable/ko_KR.json
  src/translations/dapps-unstoppable/ru_RU.json
  src/translations/dapps-unstoppable/zh_CN.json
  src/translations/en_US.js
  src/translations/footer/ru_RU.json
  src/translations/interface/ru_RU.json
  src/translations/mew-cx/ru_RU.json
  src/translations/notifications/ru_RU.json
  src/translations/sign-message/ru_RU.json
  src/translations/swap/ru_RU.json
  src/translations/without-wallet/ru_RU.json
  vueConfig/connections.js
  vueConfig/defaultConfigs.js
Labels: Feature, Ready, v5

#2205 feature/ens-avatar [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AddressBookModal/AddressBookModal.vue
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/containers/FooterContainer/affiliates.js
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.scss
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/InitialENSStateContainer/InitialENSStateContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/ManageENS/supportedTxt.js
  src/directives/AddrResolver.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/translations/dapps-ens/en_US.json
  vueConfig/defaultConfigs.js
Labels: Feature, Ready

#2273 Dev/mobile top info blocks
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.scss
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceBalance/MobileInterfaceBalance.scss
  src/layouts/InterfaceLayout/components/MobileInterfaceBalance/MobileInterfaceBalance.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceBalance/index.js
  src/layouts/InterfaceLayout/components/MobileInterfaceNetwork/MobileInterfaceNetwork.scss
  src/layouts/InterfaceLayout/components/MobileInterfaceNetwork/MobileInterfaceNetwork.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceNetwork/index.js
Labels: Ready, UI

#2276 Devop/token icons
  CHANGELOG.md
  fetchLists/configs.js
  fetchLists/index.js
  package-lock.json
  package.json
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.scss
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Devop, Ready

#2266 bug/bitbox-box [v5]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
Labels: Bug, Ready

#2271 bug/cx-wallet-when-empty [v5]
  CHANGELOG.md
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-fetch-accounts.js
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionAddWalletContainer/ExtensionAddWalletContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionPopup/containers/QuickSendContainer/QuickSendContainer.vue
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.vue
  src/router/index.js
  src/translations/dapps-unstoppable/en_US.json
Labels: Bug, Ready

#2286 devop/coolwallet-promo
  src/assets/images/affiliates/bcvault.png
  src/assets/images/pre-order-label.png
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.vue
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.scss
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/HardwaresLayout/HardwaresLayout.scss
  src/layouts/HardwaresLayout/HardwaresLayout.vue
  src/translations/other/buy-hardware-wallet/en_US.json
Labels: Devop, Ready

#2254 feature/address-to-explorrer [v5]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/affiliates/coolwallet.png
  src/assets/images/unstoppable-promo.png
  src/containers/FooterContainer/affiliates.js
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal-desktop.scss
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/ExtensionBrowserAction/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/HardwaresLayout/HardwaresLayout.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
Labels: Feature, Ready

#2272 devop/update-packages [v5]
  package-lock.json
  package.json
Labels: Devop, Ready

#2292 Devop/add linter to workflow
  .github/workflows/run-on-pr.yml
  CHANGELOG.md
Labels: Devop, Ready

#2291 Lazy load icon tokens
  CHANGELOG.md
  src/directives/LazyLoad.js
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.scss
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceBalance/MobileInterfaceBalance.scss
  src/layouts/InterfaceLayout/components/MobileInterfaceNetwork/MobileInterfaceNetwork.scss
  src/main.js
  src/translations/other/buy-hardware-wallet/en_US.json
Labels: Feature, Ready

#2311 devop/update-packages-v6
  package-lock.json
  package.json
Labels: Devop, Ready

#2308 devop/remove-promo
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/assets/images/unstoppable-promo.png
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
Labels: Devop, Ready

#2310 devop/update-packages [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
Labels: Devop, Ready

#2099 dex ag [v5]
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-lock.json
  src/assets/images/etc/0x.png
  src/assets/images/etc/0x.svg
  src/assets/images/etc/bancor.png
  src/assets/images/etc/dexag.png
  src/assets/images/etc/dexag.svg
  src/assets/images/etc/dexag_gray.svg
  src/assets/images/etc/oasis.svg
  src/assets/images/etc/photo_2020-04-06_13-49-28.jpg
  src/assets/images/etc/uniswap.svg
  src/containers/NotificationsContainer/components/NotificationTypes/SwapDetails/SwapDetails.scss
  src/containers/NotificationsContainer/components/NotificationTypes/SwapDetails/SwapDetails.vue
  src/containers/NotificationsContainer/components/NotificationTypes/SwapNotification/SwapNotification.scss
  src/containers/NotificationsContainer/components/NotificationTypes/SwapNotification/SwapNotification.vue
  src/helpers/notificationFormatters/formatters.js
  src/helpers/responseHandler/responseMatches.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProviderInfoList/ProviderInfoList.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly-calls.js
  src/partners/changelly/changelly.js
  src/partners/dexAg/config/DexTradingWithCollection.abi.js
  src/partners/dexAg/config/config.js
  src/partners/dexAg/config/currencies.json
  src/partners/dexAg/config/index.js
  src/partners/dexAg/config/weth.abi.js
  src/partners/dexAg/dexAg-calls.js
  src/partners/dexAg/dexAg.js
  src/partners/dexAg/index.js
  src/partners/index.js
  src/partners/kyber/config/config.js
  src/partners/kyber/config/currenciesKOV.js
  src/partners/kyber/config/currenciesROP.js
  src/partners/kyber/config/gasLimits.js
  src/partners/kyber/config/index.js
  src/partners/kyber/config/kyberNetwork.abi.js
  src/partners/kyber/index.js
  src/partners/kyber/kyber-calls.js
  src/partners/kyber/kyber.js
  src/partners/partners.js
  src/partners/partnersConfig/config.js
  src/translations/swap/en_US.json
  tests/unit/specs/src/partners/kyber/kyber.spec.js
  vueConfig/connections.js
Labels: Ready, v5

#2294 Dev/policy and scope
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  security.txt
  src/builds/configs/base-routes.js
  src/layouts/SecurityPolicy/SecurityPolicy.vue
  src/layouts/SecurityPolicy/index.js
Labels: Ready
