Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-01, with the labels that each got.

#1792 Devop/sync develop
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Devop, Ready

#1784 Add RSK dpath to Keepkey
  src/wallets/bip44/keepkeyPaths.js
Labels: Feature, Ready

#1811 Fix maker eth withdraw from CDP
  CHANGELOG.md
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.scss
  src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue
  src/dapps/MakerSai/DSProxy.json
  src/dapps/MakerSai/MakerCDP.js
  src/dapps/MakerSai/MakerDai.vue
  src/dapps/MakerSai/SaiProxyCreateAndExecute.json
  src/dapps/MakerSai/components/PaybackModal/PaybackModal.vue
  src/dapps/MakerSai/ethersHelpers.js
Labels: Bug, Fixed, Ready

#1793 devop/update-packages
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#1800 bug/hide-link-to
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package.json
  src/containers/ConfirmationContainer/components/SuccessModal/SuccessModal.vue
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/ExtensionBrowserAction/components/GenerateWalletModal/GenerateWalletModal.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionAddWalletContainer/ExtensionAddWalletContainer.vue
  vueConfig/mewcx.js
Labels: Bug, Ready

#1787 Ui fix/maker dai
  CHANGELOG.md
  src/components/Card1/Card1.vue
  src/components/Card1/index.js
  src/containers/FaqsContainer/FaqsContainer.vue
  src/dapps/MakerDai/MakerDai.scss
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.scss
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/dapps/MakerDai/containers/MakerHome/MakerHome.scss
  src/dapps/MakerDai/containers/MakerHome/MakerHome.vue
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.scss
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/dapps/MakerDai/containers/ManageCDP/ManageCDP.scss
  src/dapps/MakerDai/containers/MigrateCDP/MigrateCDP.vue
  src/dapps/MakerDai/containers/MigrateDai/MigrateDai.vue
  src/layouts/AccessWalletLayout/components/FinneyModal/FinneyModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/ExtensionBrowserAction/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/components/InterfaceContainerFooter/InterfaceContainerFooter.vue
  src/layouts/InterfaceLayout/components/InterfaceContainerFooter/index.js
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.scss
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/layouts/InterfaceLayout/containers/InterfaceContainer.scss
  src/scss/Global-desktop.scss
  src/translations/dapps-maker/en_US.json
  src/translations/dapps-maker/es_ES.json
  src/translations/dapps-maker/ja_JP.json
  src/translations/dapps-maker/ko_KR.json
Labels: Ready

#1755 Devop/notification pruning
  CHANGELOG.md
  src/dapps/MakerDai/components/CurrencyPicker/CurrencyPicker.vue
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.vue
  src/store/actions.js
Labels: Devop, Ready

#1702 add gasLimit field to batch transactions
  CHANGELOG.md
  src/wallets/hybrid/MEWconnect/index.js
Labels: Devop, Ready

#1813 devop/cx-web3-optimize
  CHANGELOG.md
  package-lock.json
  src/helpers/misc.js
  src/wallets/web3-provider/cx-web3-methods/eth_sendTransaction.js
Labels: Devop, Ready

#1795 Feature/update address book
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/AddressBookModal/AddressBookModal.scss
  src/components/AddressBookModal/AddressBookModal.vue
  src/components/AddressBookModal/index.js
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
  src/translations/interface/en_US.json
Labels: Feature, Ready

#1808 Ui fix/nft manager
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/assets/images/nft/products/Cards.png
  src/assets/images/nft/products/Cryptantcrab.png
  src/assets/images/nft/products/Decentraland.png
  src/assets/images/nft/products/Ethermon.png
  src/assets/images/nft/products/Flowers.png
  src/assets/images/nft/products/Kitties.png
  src/assets/images/nft/products/Stamp.png
  src/containers/NotificationsContainer/components/config.js
  src/layouts/InterfaceLayout/components/ContentBlockTitle/ContentBlockTitle.scss
  src/layouts/InterfaceLayout/components/ContentBlockTitle/ContentBlockTitle.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NFTSideMenu/NFTSideMenu.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftProductCard/NftProductCard.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftProductCard/index.js
  src/translations/nft-manager/en_US.json
Labels: Ready

#1816 Ui update/new issue log design
  CHANGELOG.md
  src/assets/images/home/spaceman-r.png
  src/components/IssueLogModal/IssueLogModal.scss
  src/components/IssueLogModal/IssueLogModal.vue
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  tests/unit/specs/src/components/IssueLogModal/IssueLogModal.spec.js
Labels: Ready

#1819 Bug/swap confirmation
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.scss
Labels: Bug, Ready

#1821 bug/send-offline-data
  CHANGELOG.md
  src/containers/NotificationsContainer/components/config.js
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/translations/send-tx/en_US.json
Labels: Bug, Ready

#1822 Remove Home link from main menu
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/HeaderContainer.vue
Labels: Ready, UI

#1828 Update add book
  CHANGELOG.md
  package-lock.json
  src/components/AddressBookModal/AddressBookModal.vue
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
Labels: Bug, Ready

#1829 Update wording
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/Web3WalletModal/Web3WalletModal.vue
  src/translations/mew-cx/en_US.json
Labels: Bug, Ready

#1831 Change it from always being false
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
Labels: Bug, Ready

#1827 Fix footer spacing
  CHANGELOG.md
  src/containers/FooterContainer/FooterContainer-desktop.scss
  src/containers/FooterContainer/FooterContainer-mobile.scss
  src/containers/FooterContainer/FooterContainer-tablet.scss
  src/containers/FooterContainer/FooterContainer.vue
Labels: Ready

#1833 Change to computed obj w translations
  CHANGELOG.md
  src/components/AddressBookModal/AddressBookModal.vue
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.vue
Labels: Bug, Ready

#1834 Hide languages mobile
  CHANGELOG.md
  package-lock.json
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.vue
  src/containers/HeaderContainer/supportedLang.js
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.scss
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  tests/unit/specs/src/containers/HeaderContainer/HeaderContainer.spec.js
Labels: Bug, Ready

#1837 Fix error log details size
  CHANGELOG.md
  src/components/IssueLogModal/IssueLogModal.scss
  src/components/IssueLogModal/IssueLogModal.vue
Labels: Enhancement, Ready

#1839 Devop/update package
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/networks/ere.svg
  src/assets/images/networks/mintme.svg
  src/assets/images/networks/web.svg
  src/networks/nodes/ere.js
  src/networks/nodes/index.js
  src/networks/nodes/mintme.js
  src/networks/nodes/web.js
  src/networks/types/ERE.js
  src/networks/types/MINTME.js
  src/networks/types/WEB.js
  src/networks/types/index.js
  src/scss/GlobalVariables.scss
  src/wallets/bip44/bitboxPaths.js
  src/wallets/bip44/keepkeyPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
  src/wallets/bip44/trezorPaths.js
  src/wallets/hardware/ledger/appPaths.js
Labels: Devop, Ready

#1852 devop/update-packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1851 Devop/prep release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1845 Document Node 12 incompatibility
  CHANGELOG.md
  README.md
  package.json
Labels: Devop, Ready

#1842 Fix addr checks
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.scss
  src/directives/AddrResolver.js
  src/partners/changelly/config/currencies.js
  src/partners/helpers/canValidate.js
  src/partners/helpers/index.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/OtherCoins.js
Labels: Bug, Ready

#1855 Devop/update etc explorrer
  CHANGELOG.md
  src/networks/types/ETC.js
Labels: Devop, Ready

#1841 release/v5.2.10
  CHANGELOG.md
  README.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/networks/ere.svg
  src/assets/images/networks/mintme.svg
  src/assets/images/networks/web.svg
  src/components/AddressBookModal/AddressBookModal.vue
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/IssueLogModal/IssueLogModal.scss
  src/components/IssueLogModal/IssueLogModal.vue
  src/components/SettingsModal/SettingsModal.scss
  src/components/SettingsModal/SettingsModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.vue
  src/containers/HeaderContainer/supportedLang.js
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/dapps/MakerDai/containers/MakerHome/MakerHome.vue
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/dapps/MakerDai/containers/MigrateCDP/MigrateCDP.vue
  src/dapps/MakerDai/containers/MigrateDai/MigrateDai.vue
  src/directives/AddrResolver.js
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.scss
  src/networks/nodes/ere.js
  src/networks/nodes/index.js
  src/networks/nodes/mintme.js
  src/networks/nodes/web.js
  src/networks/types/ERE.js
  src/networks/types/ETC.js
  src/networks/types/MINTME.js
  src/networks/types/WEB.js
  src/networks/types/index.js
  src/partners/changelly/config/currencies.js
  src/partners/helpers/canValidate.js
  src/partners/helpers/index.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/OtherCoins.js
  src/scss/GlobalVariables.scss
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  src/translations/dapps-mcd-maker/en_US.json
  src/wallets/bip44/bitboxPaths.js
  src/wallets/bip44/keepkeyPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
  src/wallets/bip44/trezorPaths.js
  src/wallets/hardware/ledger/appPaths.js
  tests/unit/specs/src/containers/HeaderContainer/HeaderContainer.spec.js
Labels: Ready, Release

#1856 Bug/remove permanent hide
  CHANGELOG.md
  package-lock.json
  src/components/IssueLogModal/IssueLogModal.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  src/translations/common/en_US.json
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
Labels: Bug, Ready

#1853 remove excess maker wording add to translations
  CHANGELOG.md
  src/dapps/MakerSai/containers/CreateCDP/CreateCDP.vue
  src/translations/dapps-maker/en_US.json
Labels: Bug, Fixed

#1848 Errorize out of date package errors
  CHANGELOG.md
  README.md
  package-test.js
Labels: Devop, Ready

#1863 devop/update-packages
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
Labels: Devop, Ready

#1840 bug/disable-web3-warning
  CHANGELOG.md
  src/builds/mewcx/cxHelpers/cxWeb3.js
Labels: Bug, Ready

#1872 Feature/add vkontakte icon
  CHANGELOG.md
  LICENSE
  src/assets/images/icons/vkontakte.png
  src/components/WelcomeModal/WelcomeModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/HomeLayout/components/Social/Social.vue
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/translations/terms-of-conditions/en_US.json
  src/translations/welcome-message/en_US.json
  src/translations/welcome-message/ru_RU.json
Labels: Feature, Ready

#1859 Devop/compile swap currencies on update
  CHANGELOG.md
  compileBaseSwapOptions.js
  package-lock.json
  package.json
  src/helpers/responseHandler/responseMatches.json
  src/partners/changelly/config/currencies.js
  src/partners/changelly/config/currencies.json
  src/partners/changelly/config/index.js
  src/partners/kyber/config/config.js
  src/partners/kyber/config/currenciesETH.js
  src/partners/kyber/config/currenciesETH.json
  src/partners/kyber/kyber-calls.js
  src/partners/kyber/kyber.js
  src/partners/partners.js
  src/partners/partnersConfig/EthereumTokens.js
  src/partners/partnersConfig/EthereumTokens.json
  src/partners/partnersConfig/OtherCoins.js
  src/partners/partnersConfig/OtherCoins.json
  src/partners/partnersConfig/index.js
  src/translations/swap/en_US.json
Labels: Ready

#1854 bug/cx-fixes
  CHANGELOG.md
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-send-signed-tx.js
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.vue
  src/layouts/ExtensionPopup/containers/QuickSendContainer/QuickSendContainer.vue
Labels: Bug, Ready

#1870 Devop/translations
  CHANGELOG.md
  package-lock.json
  src/builds/web/app.vue
  src/dapps/MakerDai/containers/MakerHome/MakerHome.vue
  src/translations/dapps-mcd-maker/en_US.json
  src/translations/home/en_US.json
Labels: Devop, Ready

#1876 devop/remove-ticker
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/SliderBar/SliderBar.vue
  src/components/SliderBar/index.js
  src/containers/HeaderContainer/HeaderContainer.vue
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.scss
  src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.vue
  src/layouts/AccessWalletLayout/components/PriceBar/index.js
  tests/unit/specs/src/layouts/AccessWalletLayout/AccessWalletLayout.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/PriceBar/PriceBar.spec.js
Labels: Devop, Ready

#1884 Devop/needed ledger update
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1882 Change EtherCore explorer address
  src/networks/types/ERE.js
Labels: Devop, Ready

#1885 Devop/update packages
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
Labels: Devop, Ready

#1891 Set ens in offline helper
  CHANGELOG.md
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#1896 devop/update-packages
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#1888 ENS functionality for address book
  CHANGELOG.md
  package-lock.json
  src/components/AddressBookModal/AddressBookModal.vue
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/components/SettingsModal/SettingsModal.vue
Labels: Feature, Ready

#1899 devop/update-help-to-quickhelp
  CHANGELOG.md
  src/components/DecisionTree/DecisionTree.vue
  src/translations/common/en_US.json
Labels: Devop, Ready

#1886 Ui fix/welcome popup background
  CHANGELOG.md
  package-lock.json
  src/layouts/CreateWalletLayout/components/TutorialModal/TutorialModal-desktop.scss
  src/layouts/CreateWalletLayout/components/TutorialModal/TutorialModal-mobile.scss
  src/layouts/CreateWalletLayout/components/TutorialModal/TutorialModal-tablet.scss
  src/layouts/CreateWalletLayout/components/TutorialModal/TutorialModal.vue
  src/scss/Global-mobile.scss
Labels: Ready, UI

#1889 Ui fix/mew community icons
  CHANGELOG.md
  src/assets/images/icons/vkontakte.png
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/HomeLayout/components/Social/Social.vue
Labels: Ready, UI

#1901 Change translations
  CHANGELOG.md
  src/builds/web/app.vue
  src/directives/AddrResolver.js
  src/translations/common/en_US.json
  src/translations/home/en_US.json
  src/wallets/bip44/paths.js
Labels: Bug, Ready

#1914 Fix quicklhelp translation
  src/components/DecisionTree/DecisionTree.vue
Labels: Bug, Ready

#1918 Fix send tx translation
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/DashboardContainer/components/ButtonSendTx/ButtonSendTx.vue
  src/translations/create-wallet/en_US.json
  src/translations/create-wallet/es_ES.json
  src/translations/create-wallet/ja_JP.json
  src/translations/create-wallet/ko_KR.json
  src/translations/create-wallet/zh_CN.json
  src/translations/send-tx/en_US.json
Labels: Bug, Ready

#1920 Devop/update packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1923 Support for new ENS registry
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/components/IssueLogModal/IssueLogModal.vue
  src/dapps/ManageENS/ABI/deedContractAbi.js
  src/dapps/ManageENS/ABI/registrarAbi.js
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/TransferRegistrarsContainer.scss
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/TransferRegistrarsContainer.vue
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/index.js
  src/dapps/ManageENS/routes.js
  src/helpers/misc.js
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/networks/types/ETH.js
  src/partners/changelly/config/currencies.json
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  src/router/index.js
  src/translations/dapps-ens/en_US.json
  tests/unit/helpers/mockStore.js
Labels: Hotfix, Ready
