Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-03, with the labels that each got.

#2023 Devop/UUID and sync develop [v5]
  CHANGELOG.md
  compileBaseSwapOptions.js
  src/helpers/notificationFormatters/formatters.js
  src/partners/changelly/config/currencies.json
  src/partners/helpers/utils.js
  src/partners/partnersConfig/OtherCoins.json
Labels: Devop, Ready, v5

#2042 devop/greenkeeper-packages [v5]
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package.json
Labels: Devop, Ready, v5

#2022 New Crowdin translations [v5]
  src/translations/nft-manager/es_ES.json
  src/translations/nft-manager/ja_JP.json
  src/translations/nft-manager/ko_KR.json
  src/translations/nft-manager/ru_RU.json
  src/translations/nft-manager/zh_CN.json
Labels: Devop, v5

#2041 Devop/hardcore ru translations [v5]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/components/WelcomeModal/WelcomeModal.vue
  src/partners/changelly/config/currencies.json
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  src/partners/partnersConfig/OtherCoins.json
Labels: Devop, Ready, v5

#2029 Devop/mew mobile integration [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/dapps/Aave/components/SummaryTable/SummaryTable.scss
  src/partners/kyber/kyber.js
Labels: Devop, Ready, v5

#2016 Security/harden csp
  CHANGELOG.md
  vueConfig/connections.js
  vueConfig/defaultConfigs.js
Labels: Ready

#2049 Bug/cx fixes [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/index.js
  src/layouts/ExtensionWeb3Popup/components/AcceptCancelButtons/AcceptCancelButtons.vue
  src/layouts/ExtensionWeb3Popup/components/AddressSelectionComponent/AddressSelectionComponent.vue
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.scss
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.vue
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
  src/translations/mew-cx/en_US.json
Labels: Bug, Ready

#2054 Bug/cx connection issues [v5]
  CHANGELOG.md
  package-lock.json
  src/builds/mewcx/cxHelpers/contentScript.js
  src/dapps/Aave/components/ActionModal/ActionModal.vue
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
  src/wallets/web3-provider/providers/ws-provider.js
  src/wallets/web3-provider/providers/ws-web3-provider.js
Labels: Bug, Ready

#2058 bug/send-offline-helper [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#2050 Release/v5.4.1
  .gitignore
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/contentScript.js
  src/builds/mewcx/index.js
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/components/WelcomeModal/WelcomeModal.vue
  src/containers/ConfirmationContainer/components/ConfirmSignModal/ConfirmSignModal.vue
  src/dapps/Aave/Aave.vue
  src/dapps/Aave/components/ActionModal/ActionModal.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/components/SummaryTable/SummaryTable.scss
  src/helpers/notificationFormatters/formatters.js
  src/layouts/ExtensionWeb3Popup/components/AcceptCancelButtons/AcceptCancelButtons.vue
  src/layouts/ExtensionWeb3Popup/components/AddressSelectionComponent/AddressSelectionComponent.vue
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.scss
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/partners/changelly/config/currencies.json
  src/partners/helpers/utils.js
  src/partners/kyber/config/currenciesETH.json
  src/partners/kyber/kyber.js
  src/partners/partnersConfig/EthereumTokens.json
  src/partners/partnersConfig/OtherCoins.json
  src/partners/simplex/simplex.js
  src/translations/mew-cx/en_US.json
  src/translations/mew-cx/es_ES.json
  src/translations/mew-cx/ja_JP.json
  src/translations/mew-cx/ko_KR.json
  src/translations/mew-cx/ru_RU.json
  src/translations/mew-cx/zh_CN.json
  src/translations/nft-manager/es_ES.json
  src/translations/nft-manager/ja_JP.json
  src/translations/nft-manager/ko_KR.json
  src/translations/nft-manager/ru_RU.json
  src/translations/nft-manager/zh_CN.json
  src/wallets/web3-provider/providers/ws-provider.js
  src/wallets/web3-provider/providers/ws-web3-provider.js
  vueConfig/connections.js
  vueConfig/defaultConfigs.js
Labels: Ready, Release

#2064 hotfix release/v5.4.1-hotfix.1 | fix for mewconnect disconnect
  .travis.yml
  CHANGELOG.md
  Dockerfile
  package-audit.js
  package-lock.json
  package.json
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
  vueConfig/connections.js
Labels: Bug, Ready, v5

#2065 Devop/sync develop to master
  .travis.yml
  CHANGELOG.md
  Dockerfile
  package-audit.js
  package-lock.json
  package.json
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
  vueConfig/connections.js
Labels: Devop, Ready

#2063 Change fee conversion [v5]
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready, v5

#2078 devop/update-greenkeeper-packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#2088 devop/greenkeeper [v5]
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#2082 Add null conditional to address statement [v5]
  CHANGELOG.md
  package-lock.json
  src/dapps/Aave/Aave.vue
  src/layouts/InterfaceLayout/components/MobileInterfaceAddress/MobileInterfaceAddress.vue
  src/partners/changelly/config/currencies.json
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  vueConfig/connections.js
Labels: Bug, Ready, v5

#2090 Fix/ropsten set resolver [v5]
  CHANGELOG.md
  package-audit.js
  src/dapps/ManageENS/ManageENS.vue
  src/wallets/web3-provider/providers/etherscan-provider.js
  src/wallets/web3-provider/providers/etherscan-request-manager.js
Labels: Ready

#2094 Bug/cx fixes
  CHANGELOG.md
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-send-signed-tx.js
  src/helpers/ExtensionHelpers.js
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.vue
Labels: Bug, Ready

#2112 MEW wallet launch modal css changes
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  src/assets/images/icons/close.png
  src/components/WalletLaunchedModal/WalletLaunchedModal.scss
  src/components/WalletLaunchedModal/WalletLaunchedModal.vue
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
Labels: Bug, Ready

#2113 Add GasPrice warning
  CHANGELOG.md
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.scss
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/translations/errors-global/en_US.json
Labels: Feature, Ready

#2107 Update greenkeeper packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#2121 Devop/sync and package update
  package-lock.json
  package.json
Labels: Devop, Ready

#2117 release/v5.4.3
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/icons/close.png
  src/components/WalletLaunchedModal/WalletLaunchedModal.scss
  src/components/WalletLaunchedModal/WalletLaunchedModal.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.scss
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  src/translations/errors-global/en_US.json
Labels: Ready, Release

#2131 devop/update-greenkeeper-packages [v5]
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#2120 Update BitBox logo [v5]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/assets/images/icons/HardwareWallet/bitbox.svg
  src/components/WalletLaunchedModal/WalletLaunchedModal.scss
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/EthereumTokens.json
Labels: Devop, Ready

#2087 Feature/coolwallet [v5]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  jest.config.js
  package-lock.json
  package.json
  src/assets/images/affiliates/coolwallet.png
  src/assets/images/icons/HardwareWallet/coolwallet.svg
  src/containers/FooterContainer/affiliates.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.vue
  src/translations/en_US.js
  src/translations/errors-coolwallet/en_US.json
  src/translations/errors-global/en_US.json
  src/translations/footer/en_US.json
  src/translations/other/buy-hardware-wallet/en_US.json
  src/wallets/bip44/coolWalletPaths.js
  src/wallets/bip44/index.js
  src/wallets/bip44/walletTypes.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/coolwallet/errorHandler.js
  src/wallets/hardware/coolwallet/index.js
  src/wallets/hardware/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/index.js
  src/wallets/hardware/trezor/index.js
  src/wallets/index.js
  tests/unit/specs/src/layouts/AccessWalletLayout/AccessWalletLayout.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.spec.js
Labels: Feature, Ready

#2134 fix exit to fiat
  .gitignore
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/StandardInput/StandardInput.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/StandardDropdown/StandardDropdown.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/StandardDropdown/StandardDropdown.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
Labels: Bug, Fixed

#2140 Security/add security txt [v5]
  CHANGELOG.md
  MEW-PUP-KEY-GPG
  package-lock.json
  security.txt
  vueConfig/mew.js
Labels: Ready

#2150 Feature/coolwallet-update 1
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.vue
  src/wallets/hardware/coolwallet/index.js
Labels: WIP

#1990 feature/hardware-wallets [v5]
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  jest.config.js
  package-lock.json
  package.json
  src/assets/images/affiliates/bcvault.png
  src/assets/images/affiliates/coolwallet.png
  src/assets/images/icons/HardwareWallet/bcvault.svg
  src/assets/images/icons/HardwareWallet/coolwallet.svg
  src/components/DecisionTree/DecisionTree.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/FooterContainer/affiliates.js
  src/containers/HeaderContainer/HeaderContainer.scss
  src/layouts/AccessWalletLayout/AccessWalletLayout.scss
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/layouts/AccessWalletLayout/components/AccessWalletButton/AccessWalletButton.vue
  src/layouts/AccessWalletLayout/components/BcVaultAddressModal/BcVaultAddressModal.scss
  src/layouts/AccessWalletLayout/components/BcVaultAddressModal/BcVaultAddressModal.vue
  src/layouts/AccessWalletLayout/components/BcVaultAddressModal/index.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal-desktop.scss
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.vue
  src/layouts/AccessWalletLayout/components/WalletOption/WalletOption.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer-desktop.scss
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer-mobile.scss
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer-tablet.scss
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.vue
  src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/index.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/store/main/state.js
  src/translations/access-wallet/en_US.json
  src/translations/en_US.js
  src/translations/errors-bcvault/en_US.json
  src/translations/errors-coolwallet/en_US.json
  src/translations/errors-global/en_US.json
  src/translations/footer/en_US.json
  src/translations/other/buy-hardware-wallet/en_US.json
  src/wallets/bip44/coolWalletPaths.js
  src/wallets/bip44/index.js
  src/wallets/bip44/walletTypes.js
  src/wallets/hardware/bcvault/errorHandler.js
  src/wallets/hardware/bcvault/index.js
  src/wallets/hardware/bitbox/index.js
  src/wallets/hardware/coolwallet/errorHandler.js
  src/wallets/hardware/coolwallet/index.js
  src/wallets/hardware/index.js
  src/wallets/hardware/keepkey/index.js
  src/wallets/hardware/ledger/index.js
  src/wallets/hardware/secalot/index.js
  src/wallets/hardware/trezor/index.js
  src/wallets/index.js
  tests/unit/specs/src/layouts/AccessWalletLayout/AccessWalletLayout.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.spec.js
  tests/unit/specs/src/layouts/AccessWalletLayout/containers/AccessMyWalletContainer/AccessMyWalletContainer.spec.js
  vueConfig/connections.js
Labels: Feature, Ready

#2164 Update packages
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-sign-msg.js
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-sign-tx.js
  src/builds/mewcx/cxHelpers/helpers.js
Labels: Devop, Ready

#2169 Release/v5.5.0-hotfix.1
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/builds/mewcx/public/manifest.json
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/translations/access-wallet/en_US.json
Labels: Hotfix, Ready, Release

#2168 CI/GitHub actions [v5]
  .github/workflows/add-to-codecov.yml
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/github-release.yml
  .travis.yml
  CHANGELOG.md
  Dockerfile
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/builds/mewcx/public/manifest.json
  src/layouts/AccessWalletLayout/AccessWalletLayout.vue
  src/translations/access-wallet/en_US.json
  ssh-keys.tar.enc
Labels: Ready

#2167 Add telegram icon
  CHANGELOG.md
  package-lock.json
  src/assets/images/icons/telegram.svg
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/ExtensionBrowserAction/components/CxFooter/CxFooter.vue
  src/layouts/HomeLayout/components/Social/Social.vue
  src/translations/home/en_US.json
Labels: Feature, Ready

#2175 bug/cool-and-bcvault
  CHANGELOG.md
  package-lock.json
  src/layouts/AccessWalletLayout/components/BcVaultAddressModal/BcVaultAddressModal.scss
  src/translations/errors-bcvault/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  src/wallets/hardware/coolwallet/index.js
Labels: Bug, Ready

#2176 devop/update-packages
  package-lock.json
  package.json
Labels: Devop, Ready

#1873 Ui dev/new interface mobile menu
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/assets/images/icons/money.svg
  src/components/CustomerSupport/CustomerSupport.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuButton/MobileMenuButton.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/MobileMenuContent.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/MobileMenuContent.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/index.js
  src/containers/HeaderContainer/components/MobileMenu/components/MobileNetworkBlock/MobileNetworkBlock.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileNetworkBlock/MobileNetworkBlock.vue
  src/layouts/InterfaceLayout/components/InterfaceContainerTitle/InterfaceContainerTitle.scss
  src/layouts/InterfaceLayout/components/InterfaceContainerTitle/InterfaceContainerTitle.vue
  src/layouts/InterfaceLayout/components/InterfaceMobileMenu/InterfaceMobileMenu.scss
  src/layouts/InterfaceLayout/components/InterfaceMobileMenuComponent/InterfaceMobileMenuComponent.scss
  src/layouts/InterfaceLayout/components/InterfaceMobileMenuComponent/InterfaceMobileMenuComponent.vue
  src/layouts/InterfaceLayout/components/InterfaceMobileMenuComponent/index.js
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  src/scss/Global-desktop.scss
  src/translations/common/en_US.json
  tests/unit/specs/src/containers/HeaderContainer/components/MobileMenu/components/MobileBalanceBlock/MobileBalanceBlock.spec.js
  tests/unit/specs/src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuButton/MobileMenuButton.spec.js
  tests/unit/specs/src/containers/HeaderContainer/components/MobileMenu/components/MobileNetworkBlock/MobileNetworkBlock.spec.js
  vueConfig/mew.js
Labels: Devop, Ready

#2119 Add AdEx [V5]
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceAds/InterfaceAds.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.scss
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/AdEx.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/AdEx/index.js
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/index.js
  src/partners/changelly/config/currencies.json
  vueConfig/connections.js
  vueConfig/defaultConfigs.js
Labels: Feature, Ready

#2188 Update access wallet page
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/containers/HeaderContainer/HeaderContainer.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/MobileMenuContent.scss
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/MobileMenuContent.vue
  src/layouts/AccessWalletLayout/AccessWalletLayout.scss
  src/translations/common/en_US.json
Labels: Devop, Ready

#2190 Devop/actually remove galaxy links
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/WalletLaunchedBanner/WalletLaunchedBanner.vue
  src/components/WalletLaunchedModal/WalletLaunchedModal.scss
  src/components/WalletLaunchedModal/WalletLaunchedModal.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/MobileMenuContent.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/CreateWalletLayout/CreateWalletLayout.vue
  src/layouts/CreateWalletLayout/components/ScanToRedirectQR/ScanToRedirectQR.vue
  src/layouts/InterfaceLayout/components/InterfaceAds/adComponents/mewWalletAd/mewWalletAd.vue
  src/layouts/InterfaceLayout/components/InterfaceMobileMenuComponent/InterfaceMobileMenuComponent.scss
Labels: Devop, Ready
