Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-07, with the labels that each got.

#2491 devop/sync-develop-w-master
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/DappSubmissionLayout/DappSubmissionLayout.vue
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/translations/interface/en_US.json
  src/translations/mew-cx/en_US.json
  src/wallets/hardware/keepkey/errorHandler.js
  src/wallets/hybrid/WalletConnect/index.js
  src/workers/wallet.worker.js
  vueConfig/connections.js
Labels: Devop, Ready

#2479 Sentry fixes
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/wallets/hardware/keepkey/errorHandler.js
  src/wallets/hybrid/WalletConnect/index.js
Labels: Bug, Ready, v5

#2500 Bug/tokens
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/ExtensionBrowserAction/components/CxFooter/CxFooter.vue
  src/layouts/HomeLayout/components/Social/Social.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Bug, Ready

#2503 bug/wallet-connect
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Bug, Ready

#2505 release/v5.7.1
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/PasswordModal/PasswordModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/DappSubmissionLayout/DappSubmissionLayout.vue
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/CxFooter/CxFooter.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/HomeLayout/components/Social/Social.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/translations/interface/en_US.json
  src/translations/mew-cx/en_US.json
  src/wallets/hardware/keepkey/errorHandler.js
  src/wallets/hybrid/WalletConnect/index.js
  src/workers/wallet.worker.js
  vueConfig/connections.js
Labels: Ready, Release

#2513 Update homepage
  package-lock.json
  package.json
  src/common/plugins/vuetify.js
  src/web/components/Partners/Partners.vue
  src/web/containers/HeaderContainer/components/HeaderDesktop/HeaderDesktop.vue
  src/web/containers/HeaderContainer/components/HeaderDesktop/components/Menu/Menu.vue
  src/web/views/LandingPageView/Home/components/Features/Features.vue
  src/web/views/LandingPageView/Home/components/WhyMew/WhyMew.vue
Labels: WIP

#2499 Bug/bcvault
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/ExtensionWeb3Popup/ExtensionWeb3Popup.vue
  src/master-file.json
  src/partners/dexAg/dexAg-calls.js
  src/partners/dexAg/dexAg.js
  src/partners/helpers/utils.js
  src/translations/errors-bcvault/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  src/wallets/hardware/bcvault/index.js
  vueConfig/connections.js
Labels: Bug, Ready

#2417 Devop/estimate gas revsion
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/partners/dexAg/dexAg-calls.js
  src/partners/dexAg/dexAg.js
  src/partners/helpers/utils.js
  vueConfig/connections.js
Labels: Devop, Ready, v5

#2517 release/5.7.2
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/ExtensionWeb3Popup/ExtensionWeb3Popup.vue
  src/master-file.json
  src/partners/dexAg/dexAg-calls.js
  src/partners/dexAg/dexAg.js
  src/partners/helpers/utils.js
  src/translations/errors-bcvault/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  src/wallets/hardware/bcvault/index.js
  vueConfig/connections.js
Labels: Ready, Release

#2515 Update create wallet page
  package-lock.json
  package.json
  src/common/plugins/vuetify.js
  src/components/BannerAds/BannerAds.vue
  src/components/Overlays/ChangeAddress/ChangeAddress.vue
  src/components/Overlays/ChangeNetwork/ChangeNetwork.vue
  src/components/Overlays/Notifications/Notifications.vue
  src/components/Overlays/PaperWallet/PaperWallet.vue
  src/components/Overlays/Settings/Settings.vue
  src/components/Overlays/Settings/components/GasPrice/GasPrice.vue
  src/web/components/Common/WhiteSheet/WhiteSheet.vue
  src/web/components/Network/Network.vue
  src/web/components/Swap/Swap.vue
  src/web/containers/DappsContainer/Aave/Aave.vue
  src/web/containers/DappsContainer/ENSManager/ENSManager.vue
  src/web/containers/DappsContainer/MakerDAO/MakerDAO.vue
  src/web/containers/DappsContainer/MakerDAO/components/History/History.vue
  src/web/containers/DappsContainer/UnstoppableDomain/UnstoppableDomain.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/BCVault/BCVault.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/Bitbox/Bitbox.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/CoolWallet/CoolWallet.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/Finney/Finney.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/KeepKey/KeepKey.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/Ledger/Ledger.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/Secalot/Secalot.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/Trezor/Trezor.vue
  src/web/containers/GlobalOverlayContainer/components/AccessWallet/HardwareWallets/XWallet/XWallet.vue
  src/web/containers/SendContainer/NFTManager/NFTManagerContent/NFTManagerContent.vue
  src/web/views/AccessWalletView/components/Hardware/Hardware.vue
  src/web/views/AccessWalletView/containers/HardwareWallets/HardwareWallets.vue
  src/web/views/CreateWalletView/CreateWalletDashboard/CreateWalletDashboard.vue
  src/web/views/CreateWalletView/CreateWalletDashboard/components/MEWwallet/MEWwallet.vue
  src/web/views/CreateWalletView/CreateWalletDashboard/components/Software/Software.vue
  src/web/views/CreateWalletView/KeystoreFile/KeystoreFile.vue
  src/web/views/DashboardView/containers/TokensValue/TokensValue.vue
  src/web/views/LandingPageView/Home/components/Features/Features.vue
  src/web/views/LandingPageView/HowItWorks/components/TabContent/TabContent.vue
  src/web/views/WalletView/components/SideMenu/components/BuyEthButton/BuyEthButton.vue
  src/web/views/WalletView/components/SideMenu/components/SystemMenu/SystemMenu.vue
Labels: WIP

#2520 devop/sync-master
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.scss
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/NotificationsContainer/components/NotificationTypes/NotificationDetails/TransactionDetails.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.scss
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/CreateCommitmentContainer/CreateCommitmentContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/partners/dexAg/dexAg.js
  src/translations/confirmation/en_US.json
  src/translations/errors-coolwallet/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  src/wallets/hardware/coolwallet/errorHandler.js
Labels: Devop, Ready

#2524 add gas check for kyber swaps.
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/partners/dexAg/dexAg.js
Labels: Devop, Ready, v5

#2521 Bug/gas price cw
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.scss
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/translations/confirmation/en_US.json
  src/translations/errors-coolwallet/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  src/wallets/hardware/coolwallet/errorHandler.js
Labels: Bug, Ready

#2527 Bug/bcvault
  CHANGELOG.md
  package-lock.json
  package.json
  src/wallets/hardware/bcvault/index.js
Labels: Bug, Ready

#2526 release/v5.7.3
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.scss
  src/containers/ConfirmationContainer/components/ConfirmCollectionModal/ConfirmCollectionModal.vue
  src/containers/NotificationsContainer/components/NotificationTypes/NotificationDetails/TransactionDetails.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.scss
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/CreateCommitmentContainer/CreateCommitmentContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/partners/dexAg/dexAg.js
  src/translations/confirmation/en_US.json
  src/translations/errors-coolwallet/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  src/wallets/hardware/bcvault/index.js
  src/wallets/hardware/coolwallet/errorHandler.js
Labels: Ready, Release
