Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-08, with the labels that each got.

#2533 hotfix/v5.7.3-hotfix.1
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/builds/web/app.vue
  src/components/TwitterWarningModal/TwitterWarningModal.scss
  src/components/TwitterWarningModal/TwitterWarningModal.vue
  src/components/TwitterWarningModal/index.js
Labels: Ready, Release

#2528 devop/sync-master
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/builds/web/app.vue
  src/components/TwitterWarningModal/TwitterWarningModal.scss
  src/components/TwitterWarningModal/TwitterWarningModal.vue
  src/components/TwitterWarningModal/index.js
  src/data/DecisionTree/md/_suggestions.md
  src/data/DecisionTree/md/_swap_error.md
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/ExtensionWeb3Popup/ExtensionWeb3Popup.vue
Labels: Devop, Ready

#2539 release/v5.7.4
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/components/TwitterWarningModal/TwitterWarningModal.scss
  src/components/TwitterWarningModal/TwitterWarningModal.vue
  src/data/DecisionTree/md/_suggestions.md
  src/data/DecisionTree/md/_swap_error.md
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/ExtensionWeb3Popup/ExtensionWeb3Popup.vue
Labels: Ready, Release

#2544 Fix missed cases for gas price too high
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/partners/dexAg/dexAg.js
  src/translations/swap/en_US.json
Labels: Bug, Ready, v5

#2545 bug/send-offline-tokens
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/presskit/logo-dark.png
  src/assets/images/presskit/logo-dark.svg
  src/assets/images/presskit/logo-kid.png
  src/assets/images/presskit/logo-kid.svg
  src/assets/images/presskit/logo-light.png
  src/assets/images/presskit/logo-light.svg
  src/assets/images/presskit/logo-simple.png
  src/assets/images/presskit/logo-simple.svg
  src/builds/configs/base-routes.js
  src/builds/mewcx/app.vue
  src/builds/mewcx/browserAction/app.vue
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/backgroundEvents/web3-sign-tx.js
  src/components/PageTitleComponent/PageTitleComponent.vue
  src/components/TwitterWarningModal/TwitterWarningModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/PressKit/PressKit.scss
  src/layouts/PressKit/PressKit.vue
  src/layouts/PressKit/index.js
  src/translations/footer/en_US.json
  src/translations/header/en_US.json
  src/wallets/web3-provider/cx-web3-methods/eth_sendTransaction.js
Labels: Bug, Ready

#2547 V5 - Press kit page
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/presskit/logo-dark.png
  src/assets/images/presskit/logo-dark.svg
  src/assets/images/presskit/logo-kid.png
  src/assets/images/presskit/logo-kid.svg
  src/assets/images/presskit/logo-light.png
  src/assets/images/presskit/logo-light.svg
  src/assets/images/presskit/logo-simple.png
  src/assets/images/presskit/logo-simple.svg
  src/builds/configs/base-routes.js
  src/components/PageTitleComponent/PageTitleComponent.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/PressKit/PressKit.scss
  src/layouts/PressKit/PressKit.vue
  src/layouts/PressKit/index.js
  src/translations/footer/en_US.json
Labels: Ready, v5

#2549 Add transaction fee estimate and high gas warning to swap
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/MakerDai/containers/MigrateCDP/MigrateCDP.vue
  src/dapps/MakerDai/makerHelpers/index.js
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/PressKit/PressKit.scss
  src/translations/swap/en_US.json
Labels: Devop, v5

#2550 devop/update-package
  package-lock.json
  package.json
Labels: Devop, Ready

#2548 release/v5.7.6
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/presskit/logo-dark.png
  src/assets/images/presskit/logo-dark.svg
  src/assets/images/presskit/logo-kid.png
  src/assets/images/presskit/logo-kid.svg
  src/assets/images/presskit/logo-light.png
  src/assets/images/presskit/logo-light.svg
  src/assets/images/presskit/logo-simple.png
  src/assets/images/presskit/logo-simple.svg
  src/builds/configs/base-routes.js
  src/builds/mewcx/app.vue
  src/builds/mewcx/browserAction/app.vue
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/backgroundEvents/web3-sign-tx.js
  src/components/PageTitleComponent/PageTitleComponent.vue
  src/components/TwitterWarningModal/TwitterWarningModal.vue
  src/containers/FooterContainer/FooterContainer.vue
  src/dapps/MakerDai/containers/MigrateCDP/MigrateCDP.vue
  src/dapps/MakerDai/makerHelpers/index.js
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/PressKit/PressKit.scss
  src/layouts/PressKit/PressKit.vue
  src/layouts/PressKit/index.js
  src/partners/dexAg/dexAg.js
  src/translations/footer/en_US.json
  src/translations/header/en_US.json
  src/translations/swap/en_US.json
  src/wallets/web3-provider/cx-web3-methods/eth_sendTransaction.js
Labels: Ready, Release

#2518 V6/module ens
  .eslintrc.js
  jest.config.js
  package-audit.js
  package-lock.json
  package.json
  src/modules/name-manager/ABI/baseRegistrarAbi.js
  src/modules/name-manager/ABI/fifsRegistrarAbi.js
  src/modules/name-manager/ABI/oldDeedAbi.js
  src/modules/name-manager/ABI/oldEnsAbi.js
  src/modules/name-manager/ABI/registrarControllerAbi.js
  src/modules/name-manager/ABI/registryAbi.js
  src/modules/name-manager/ABI/resolverAbi.js
  src/modules/name-manager/FifsNameModule.js
  src/modules/name-manager/PermanentNameModule.js
  src/modules/name-manager/configs/multicoins.js
  src/modules/name-manager/configs/textrecords.js
  src/modules/name-manager/helpers.js
  src/modules/name-manager/index.js
  src/modules/name-manager/interface/NameManagerInterface.js
  src/modules/name-manager/interface/registrarInterface.js
  src/modules/name-manager/services/getHashFromFile.js
  src/modules/name-manager/services/services.js
  src/modules/name-manager/services/uploadFileToIpfs.js
  src/modules/name-resolver/helpers.js
  src/modules/name-resolver/index.js
  src/modules/name-resolver/resolvers/cns.js
  src/modules/name-resolver/resolvers/ens.js
  src/modules/name-resolver/tests/name-resolver.spec.js
Labels: Ready, v6

#2494 devop: name-resolver module [v6]
  .eslintrc.js
  jest.config.js
  package-lock.json
  src/modules/name-resolver/helpers.js
  src/modules/name-resolver/index.js
  src/modules/name-resolver/resolvers/cns.js
  src/modules/name-resolver/resolvers/ens.js
  src/modules/name-resolver/tests/name-resolver.spec.js
Labels: Ready, v6

#2551 devop/sync-develop-with-master
  CHANGELOG.md
  package-test.js
  package.json
  src/builds/web/app.vue
Labels: Devop, Ready
