Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-12, with the labels that each got.

#2693 Bug/misc
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/directives/AddrResolver.js
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/translations/dapps-misc/en_US.json
Labels: Devop, Ready

#2676 Bug/fix error on print
  CHANGELOG.md
  package-lock.json
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
Labels: Bug, v5

#2701 chore: update versions
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#2662 feat/staking [v5]
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/dapps/staked-logo.png
  src/assets/images/icons/dapps/staked-logo.svg
  src/assets/images/icons/dapps/staked-upload-icon.svg
  src/assets/images/icons/dapps/staked.png
  src/builds/configs/base-routes.js
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/MobileMenuContent.vue
  src/dapps/Staked/Staked.scss
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.scss
  src/dapps/Staked/components/Stepper/Stepper.vue
  src/dapps/Staked/components/Stepper/steps/Done/Done.scss
  src/dapps/Staked/components/Stepper/steps/Done/Done.vue
  src/dapps/Staked/components/Stepper/steps/InProgress/InProgress.scss
  src/dapps/Staked/components/Stepper/steps/InProgress/InProgress.vue
  src/dapps/Staked/components/Stepper/steps/Review/Review.scss
  src/dapps/Staked/components/Stepper/steps/Review/Review.vue
  src/dapps/Staked/components/Stepper/steps/SetAmount/SetAmount.scss
  src/dapps/Staked/components/Stepper/steps/SetAmount/SetAmount.vue
  src/dapps/Staked/components/Stepper/steps/Upload/Upload.scss
  src/dapps/Staked/components/Stepper/steps/Upload/Upload.vue
  src/dapps/Staked/configs.js
  src/dapps/Staked/helpers/calculateRewards.js
  src/dapps/Staked/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/layouts/GenerateAddressLayout/GenerateAddressLayout.scss
  src/layouts/GenerateAddressLayout/GenerateAddressLayout.vue
  src/layouts/GenerateAddressLayout/components/CreatePassword/CreatePassword.scss
  src/layouts/GenerateAddressLayout/components/CreatePassword/CreatePassword.vue
  src/layouts/GenerateAddressLayout/components/MnemonicPhrase/MnemonicPhrase.scss
  src/layouts/GenerateAddressLayout/components/MnemonicPhrase/MnemonicPhrase.vue
  src/layouts/GenerateAddressLayout/components/Success/Success.scss
  src/layouts/GenerateAddressLayout/components/Success/Success.vue
  src/layouts/GenerateAddressLayout/index.js
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/mew-test-wallet.crash
  src/partners/dexAg/config/index.js
  src/scss/GlobalVariables.scss
  src/translations/common/en_US.json
  src/translations/dapps-staked/en_US.json
  src/translations/en_US.js
  src/translations/footer/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  vueConfig/connections.js
Labels: Ready, v5

#2700 release/v5.7.15
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/dapps/staked-logo.png
  src/assets/images/icons/dapps/staked-logo.svg
  src/assets/images/icons/dapps/staked-upload-icon.svg
  src/assets/images/icons/dapps/staked.png
  src/builds/configs/base-routes.js
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileMenuContent/MobileMenuContent.vue
  src/dapps/Staked/Staked.scss
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.scss
  src/dapps/Staked/components/Stepper/Stepper.vue
  src/dapps/Staked/components/Stepper/steps/Done/Done.scss
  src/dapps/Staked/components/Stepper/steps/Done/Done.vue
  src/dapps/Staked/components/Stepper/steps/InProgress/InProgress.scss
  src/dapps/Staked/components/Stepper/steps/InProgress/InProgress.vue
  src/dapps/Staked/components/Stepper/steps/Review/Review.scss
  src/dapps/Staked/components/Stepper/steps/Review/Review.vue
  src/dapps/Staked/components/Stepper/steps/SetAmount/SetAmount.scss
  src/dapps/Staked/components/Stepper/steps/SetAmount/SetAmount.vue
  src/dapps/Staked/components/Stepper/steps/Upload/Upload.scss
  src/dapps/Staked/components/Stepper/steps/Upload/Upload.vue
  src/dapps/Staked/configs.js
  src/dapps/Staked/helpers/calculateRewards.js
  src/dapps/Staked/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/directives/AddrResolver.js
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/GenerateAddressLayout/GenerateAddressLayout.scss
  src/layouts/GenerateAddressLayout/GenerateAddressLayout.vue
  src/layouts/GenerateAddressLayout/components/CreatePassword/CreatePassword.scss
  src/layouts/GenerateAddressLayout/components/CreatePassword/CreatePassword.vue
  src/layouts/GenerateAddressLayout/components/MnemonicPhrase/MnemonicPhrase.scss
  src/layouts/GenerateAddressLayout/components/MnemonicPhrase/MnemonicPhrase.vue
  src/layouts/GenerateAddressLayout/components/Success/Success.scss
  src/layouts/GenerateAddressLayout/components/Success/Success.vue
  src/layouts/GenerateAddressLayout/index.js
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/layouts/mew-test-wallet.crash
  src/partners/dexAg/config/index.js
  src/scss/GlobalVariables.scss
  src/translations/common/en_US.json
  src/translations/dapps-misc/en_US.json
  src/translations/dapps-staked/en_US.json
  src/translations/en_US.js
  src/translations/footer/en_US.json
  src/wallets/hardware/bcvault/errorHandler.js
  vueConfig/connections.js
Labels: Ready, Release

#2716 V6/fixes
  package-lock.json
  src/modules/wallets/components/software-access-overlay/SoftwareAccessOverlay.vue
  src/modules/wallets/pages/access/Access.vue
Labels: Ready, v6

#2717 bug/glm-copy
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/mew-test-wallet.crash
  src/translations/dapps-misc/en_US.json
Labels: Bug, Ready

#2708 Merge master back to develop
  package-lock.json
  package.json
Labels: Devop, Ready

#2715 chore: reopen display-alternative-swaps
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapAddressSelector/SwapAddressSelector.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapCurrencyPicker/SwapCurrencyPicker.vue
  src/translations/swap/en_US.json
Labels: Feature, Ready

#2699 Bug/unstoppable ltc validation
  CHANGELOG.md
  package-lock.json
  src/dapps/Unstoppable/containers/ManageCryptoContainer/helpers.js
Labels: Bug, Ready

#2728 chore: fetch gnt values instead of relying on token list
  CHANGELOG.md
  src/dapps/GntMigrator/GntMigrator.vue
Labels: Bug, Ready

#2729 Bug/format array inputs
  CHANGELOG.md
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
Labels: Bug, Ready

#2727 Bug/invalid game address
  CHANGELOG.md
  src/directives/AddrResolver.js
  src/partners/partnersConfig/EthereumTokens.json
Labels: Bug, Ready

#2730 Bug/swap updates btc alternatives fixes
  CHANGELOG.md
  compileBaseSwapOptions.js
  package-lock.json
  package-test.js
  package.json
  src/partners/dexAg/dexAg-calls.js
  src/partners/helpers/utils.js
Labels: Bug, Ready

#2738 chore: exclude packages for now
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#2741 chore: update packages
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#2752 update packages
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/translations/dapps-staked/ru_RU.json
  src/translations/dapps-unstoppable/ru_RU.json
  src/translations/errors-bcvault/ru_RU.json
  src/translations/errors-coolwallet/ru_RU.json
  src/translations/errors-global/ru_RU.json
  src/translations/errors-keepkey/ru_RU.json
  src/translations/errors-ledger/ru_RU.json
  src/translations/errors-trezor/ru_RU.json
  src/translations/mew-cx/ru_RU.json
  src/translations/ru_RU.js
  src/translations/swap/es_ES.json
  src/translations/swap/ja_JP.json
  src/translations/swap/ko_KR.json
  src/translations/swap/ru_RU.json
  src/translations/swap/zh_CN.json
Labels: Bug, Ready

#2745 Bug/cx ens bug
  .github/workflows/build-cx-generate-zip.yml
  ENV_VARS.js
  package.json
  src/builds/mewcx/cxHelpers/backgroundEvents/web3-rpc-request.js
  src/builds/mewcx/cxHelpers/contentScript.js
  src/builds/mewcx/public/popupLoading.html
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.scss
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyWalletInfoForm/VerifyWalletInfoForm.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionFavoritesContainer/ExtensionFavoritesContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionWeb3Popup/components/AddressSelectionComponent/AddressSelectionComponent.vue
  src/store/main/actions.js
  vueConfig/mewcx.js
Labels: Bug, Ready

#2753 fix estimateGas for eth_sighTransaction
  CHANGELOG.md
  package-lock.json
  src/wallets/web3-provider/methods/eth_signTransaction.js
Labels: Bug, Fixed, Ready, v5

#2732 Bug/cx-rewrite-notification
  package-lock.json
  package-test.js
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-send-signed-tx.js
  src/builds/mewcx/cxHelpers/backgroundEvents/web3-sign-tx.js
  src/helpers/ExtensionHelpers.js
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/ExtensionNotification.vue
Labels: Bug, Ready

#2755 bug/token-icon
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Bug, Ready

#2748 Feat/staked status
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/Staked/Staked.scss
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.scss
  src/dapps/Staked/components/Stepper/steps/InProgress/InProgress.scss
  src/dapps/Staked/components/Stepper/steps/Review/Review.vue
  src/dapps/Staked/configs.js
  src/dapps/Staked/containers/Status/Status.scss
  src/dapps/Staked/containers/Status/Status.vue
  src/scss/GlobalVariables.scss
  src/translations/dapps-staked/en_US.json
Labels: Feature, Ready, v5

#2744 release/v5.7.17
  .github/workflows/build-cx-generate-zip.yml
  CHANGELOG.md
  ENV_VARS.js
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/backgroundEvents/mew-cx-send-signed-tx.js
  src/builds/mewcx/cxHelpers/backgroundEvents/web3-rpc-request.js
  src/builds/mewcx/cxHelpers/backgroundEvents/web3-sign-tx.js
  src/builds/mewcx/cxHelpers/contentScript.js
  src/builds/mewcx/public/popupLoading.html
  src/dapps/Staked/Staked.scss
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.scss
  src/dapps/Staked/components/Stepper/steps/InProgress/InProgress.scss
  src/dapps/Staked/components/Stepper/steps/Review/Review.vue
  src/dapps/Staked/configs.js
  src/dapps/Staked/containers/Status/Status.scss
  src/dapps/Staked/containers/Status/Status.vue
  src/helpers/ExtensionHelpers.js
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.scss
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyWalletInfoForm/VerifyWalletInfoForm.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionFavoritesContainer/ExtensionFavoritesContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/ExtensionNotification.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionWeb3Popup/components/AddressSelectionComponent/AddressSelectionComponent.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/scss/GlobalVariables.scss
  src/store/main/actions.js
  src/translations/dapps-staked/en_US.json
  src/translations/dapps-staked/ru_RU.json
  src/translations/dapps-unstoppable/ru_RU.json
  src/translations/errors-bcvault/ru_RU.json
  src/translations/errors-coolwallet/ru_RU.json
  src/translations/errors-global/ru_RU.json
  src/translations/errors-keepkey/ru_RU.json
  src/translations/errors-ledger/ru_RU.json
  src/translations/errors-trezor/ru_RU.json
  src/translations/mew-cx/ru_RU.json
  src/translations/ru_RU.js
  src/translations/swap/es_ES.json
  src/translations/swap/ja_JP.json
  src/translations/swap/ko_KR.json
  src/translations/swap/ru_RU.json
  src/translations/swap/zh_CN.json
  src/wallets/web3-provider/methods/eth_signTransaction.js
  vueConfig/mewcx.js
Labels: Ready, Release
