Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-10, with the labels that each got.

#2606 Feature/lend migrator
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/icons/dapps/lend-migrator.svg
  src/builds/mewcx/cxHelpers/background.js
  src/dapps/LendMigrator/LendMigrator.scss
  src/dapps/LendMigrator/LendMigrator.vue
  src/dapps/LendMigrator/abi/erc20.js
  src/dapps/LendMigrator/abi/lendToAaveMigrator.js
  src/dapps/LendMigrator/routes.js
  src/dapps/Unstoppable/Unstoppable.vue
  src/dapps/Unstoppable/containers/ClaimPendingContainer/ClaimPendingContainer.vue
  src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.scss
  src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.vue
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.scss
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.vue
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.scss
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.vue
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.scss
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.vue
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.scss
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.vue
  src/dapps/index.js
  src/dapps/routes.js
  src/helpers/ExtensionHelpers.js
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.scss
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/ExtensionBrowserAction/components/EditWalletModal/EditWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionFavoritesContainer/ExtensionFavoritesContainer.scss
  src/layouts/ExtensionBrowserAction/containers/ExtensionFavoritesContainer/ExtensionFavoritesContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/ExtensionNotification.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.scss
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.scss
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/translations/common/en_US.json
  src/translations/dapps-aave/en_US.json
  src/translations/dapps-mcd-maker/en_US.json
  src/translations/dapps-unstoppable/en_US.json
Labels: Ready, v5

#2615 release/v5.7.10
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/icons/dapps/lend-migrator.svg
  src/builds/mewcx/cxHelpers/background.js
  src/dapps/LendMigrator/LendMigrator.scss
  src/dapps/LendMigrator/LendMigrator.vue
  src/dapps/LendMigrator/abi/erc20.js
  src/dapps/LendMigrator/abi/lendToAaveMigrator.js
  src/dapps/LendMigrator/routes.js
  src/dapps/Unstoppable/Unstoppable.vue
  src/dapps/Unstoppable/containers/ClaimPendingContainer/ClaimPendingContainer.vue
  src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.scss
  src/dapps/Unstoppable/containers/CompletedContainer/CompletedContainer.vue
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.scss
  src/dapps/Unstoppable/containers/ConfirmContainer/ConfirmContainer.vue
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.scss
  src/dapps/Unstoppable/containers/CryptoContainer/CryptoContainer.vue
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.scss
  src/dapps/Unstoppable/containers/InitialUnstoppableStateContainer/InitialUnstoppableStateContainer.vue
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.scss
  src/dapps/Unstoppable/containers/StripeContainer/StripeContainer.vue
  src/dapps/index.js
  src/dapps/routes.js
  src/helpers/ExtensionHelpers.js
  src/layouts/ExtensionBrowserAction/ExtensionBrowserAction.vue
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.scss
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/ExtensionBrowserAction/components/EditWalletModal/EditWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionFavoritesContainer/ExtensionFavoritesContainer.scss
  src/layouts/ExtensionBrowserAction/containers/ExtensionFavoritesContainer/ExtensionFavoritesContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionNotification/ExtensionNotification.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.scss
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.scss
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.vue
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.scss
  src/layouts/InterfaceLayout/components/DappButtons/DappButtons.vue
  src/translations/common/en_US.json
  src/translations/dapps-aave/en_US.json
  src/translations/dapps-mcd-maker/en_US.json
  src/translations/dapps-unstoppable/en_US.json
Labels: Ready, Release

#2621 devop/sync-develop
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#2624 Bug/cx access and send
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/etc/ethereum_logo.svg
  src/assets/images/etc/twitter_verified_logo.svg
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/contentScript.js
  src/directives/AddrResolver.js
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/RemoveWalletModal/RemoveWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionWeb3Popup/components/AmountInfoComponent/AmountInfoComponent.vue
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.vue
  src/translations/dapps-ens/en_US.json
  src/wallets/web3-provider/cx-web3-methods/eth_sendTransaction.js
Labels: Bug, Ready, v5

#2625 releases/v5.7.11
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/etc/ethereum_logo.svg
  src/assets/images/etc/twitter_verified_logo.svg
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/contentScript.js
  src/directives/AddrResolver.js
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/RemoveWalletModal/RemoveWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionWeb3Popup/components/AmountInfoComponent/AmountInfoComponent.vue
  src/layouts/ExtensionWeb3Popup/containers/AccountAccessContainer/AccountAccessContainer.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/translations/dapps-ens/en_US.json
  src/wallets/web3-provider/cx-web3-methods/eth_sendTransaction.js
Labels: Ready, Release

#2627 fix check to make it an existence check rather than a constant check
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/helpers/misc.js
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
Labels: Bug, Hotfix, Ready, v5

#2634 devop/update-packages
  CHANGELOG.md
  CONTRIBUTING.md
  DAPP_INTEGRATION.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/builds/mewcx/public/README.md
  src/components/DecisionTree/data/md/_Access_Ledger.md
  src/components/DecisionTree/data/md/_Access_Trezor.md
  src/components/DecisionTree/data/md/_Access_file.md
  src/components/DecisionTree/data/md/_Access_key.md
  src/components/DecisionTree/data/md/_Access_other.md
  src/components/DecisionTree/data/md/_Access_phrase.md
  src/components/DecisionTree/data/md/_Cant_scan_access.md
  src/components/DecisionTree/data/md/_Different_address.md
  src/components/DecisionTree/data/md/_Find_CX.md
  src/components/DecisionTree/data/md/_Find_Ledger.md
  src/components/DecisionTree/data/md/_Find_MEWconnect.md
  src/components/DecisionTree/data/md/_Find_MEWwallet.md
  src/components/DecisionTree/data/md/_Find_MM.md
  src/components/DecisionTree/data/md/_Find_Trezor.md
  src/components/DecisionTree/data/md/_Find_file.md
  src/components/DecisionTree/data/md/_Find_key.md
  src/components/DecisionTree/data/md/_Find_other.md
  src/components/DecisionTree/data/md/_Forgot_pass_access.md
  src/components/DecisionTree/data/md/_Forgot_pin_access.md
  src/components/DecisionTree/data/md/_Funds_network.md
  src/components/DecisionTree/data/md/_Given_hash.md
  src/components/DecisionTree/data/md/_No_hash.md
  src/components/DecisionTree/data/md/_Notgiven_hash.md
  src/components/DecisionTree/data/md/_Recognize_address.md
  src/components/DecisionTree/data/md/_Saved_hash.md
  src/components/DecisionTree/data/md/_Using_CX_access.md
  src/components/DecisionTree/data/md/_Using_MM_access.md
  src/components/DecisionTree/data/md/_buy_bug.md
  src/components/DecisionTree/data/md/_changelly.md
  src/components/DecisionTree/data/md/_created_on_MEW.md
  src/components/DecisionTree/data/md/_created_other.md
  src/components/DecisionTree/data/md/_dapp_MakerDAO.md
  src/components/DecisionTree/data/md/_dapp_other.md
  src/components/DecisionTree/data/md/_kyber.md
  src/components/DecisionTree/data/md/_not_listed.md
  src/components/DecisionTree/data/md/_simplex.md
  src/components/DecisionTree/data/md/_suggestions.md
  src/components/DecisionTree/data/md/_swap_error.md
  src/components/DecisionTree/data/md/_tx_bug.md
  src/components/DecisionTree/data/md/_tx_error.md
  src/components/DecisionTree/data/md/_tx_other.md
  src/dapps/LendMigrator/LendMigrator.vue
  src/directives/AddrResolver.js
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/networks/nodes/bsc-mainnet.js
  src/networks/types/BSC.js
  vueConfig/connections.js
  yarn.lock
Labels: Devop, Ready

#2632 convert changelly rep to repv2
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly.js
  yarn.lock
Labels: Bug, Fixed, v5

#2639 Devop/update version
  package-lock.json
  package.json
Labels: Devop, Ready

#2643 Update packages
  package-lock.json
  package.json
Labels: Devop, Ready

#2645 hotfix/bsc
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/networks/nodes/index.js
  src/networks/types/index.js
Labels: Hotfix, Ready
