Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-06, with the labels that each got.

#2411 bug/sentry-fixes-kvhnuke [v5]
  .github/workflows/deploy-live.yml
  CHANGELOG.md
  package-lock.json
  package.json
  release.sh
  src/builds/mewcx/cxHelpers/cxWeb3.js
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/globalErrorHandler.js
  src/main.js
  src/translations/errors-global/en_US.json
  src/translations/errors-ledger/en_US.json
  src/translations/errors-trezor/en_US.json
  src/wallets/hardware/ledger/errorHandler.js
  src/wallets/hardware/trezor/errorHandler.js
Labels: Devop, Ready

#2409 Devop/modify simplex order flow
  CHANGELOG.md
  package-lock.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/CheckoutForm/CheckoutForm.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/CheckoutForm/CheckoutForm.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/partners/simplex/simplex.js
  src/translations/interface/en_US.json
  tests/unit/specs/src/layouts/InterfaceLayout/containers/SwapContainer/components/CheckoutForm/CheckoutForm.spec.js
Labels: Devop, Ready, v5

#2404 Bug/display tokens [v5]
  CHANGELOG.md
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Bug, Ready

#2406 Bug/sentry fixes undefined
  CHANGELOG.md
  src/helpers/notificationFormatters/formatters.js
  src/helpers/responseHandler/responseMatches.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/translations/notifications/en_US.json
Labels: Bug, Ready, v5

#2436 devop/sync-develop
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/cxWeb3.js
Labels: Devop, Ready

#2455 devop/change-menu-color
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/sidemenu/contract.svg
  src/assets/images/sidemenu/dapps.svg
  src/assets/images/sidemenu/dashboard.svg
  src/assets/images/sidemenu/message.svg
  src/assets/images/sidemenu/send.svg
  src/assets/images/sidemenu/swap.svg
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.scss
Labels: Devop, Ready, v5

#2454 bug/remove-view-wallet
  CHANGELOG.md
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
Labels: Bug, Ready, v5

#2453 Fix footer icon issue
  CHANGELOG.md
  package-lock.json
  src/containers/FooterContainer/FooterContainer-desktop.scss
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/translations/interface/en_US.json
Labels: Bug, Ready, v5

#2451 Bug/sentry fixes s
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/notificationFormatters/formatters.js
  src/helpers/responseHandler/responseMatches.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/partners/dexAg/dexAg.js
  src/translations/swap/en_US.json
Labels: Bug, Ready, v5

#2450 bug/sentry-fixes-y
  CHANGELOG.md
  package-lock.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/translations/errors-global/en_US.json
  src/translations/errors-trezor/en_US.json
  src/wallets/hardware/trezor/errorHandler.js
Labels: Bug, Ready, v5

#2412 Feature/ipfs
  CHANGELOG.md
  package-lock.json
  package.json
  src/containers/HeaderContainer/HeaderContainer.scss
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/Unstoppable/containers/ManageCryptoContainer/ManageCryptoContainer.scss
  src/dapps/Unstoppable/containers/ManageCryptoContainer/ManageCryptoContainer.vue
  src/translations/dapps-ens/en_US.json
  src/translations/dapps-unstoppable/en_US.json
  vueConfig/connections.js
Labels: Feature, Ready, v5

#2457 Release/v5.6.6
  CHANGELOG.md
  fetchLists/lists/contracts.json
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/assets/images/sidemenu/contract.svg
  src/assets/images/sidemenu/dapps.svg
  src/assets/images/sidemenu/dashboard.svg
  src/assets/images/sidemenu/message.svg
  src/assets/images/sidemenu/send.svg
  src/assets/images/sidemenu/swap.svg
  src/containers/FooterContainer/FooterContainer-desktop.scss
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/HeaderContainer/HeaderContainer.scss
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.scss
  src/dapps/ManageENS/containers/ManageENSContainer/ManageENSContainer.vue
  src/dapps/Unstoppable/containers/ManageCryptoContainer/ManageCryptoContainer.scss
  src/dapps/Unstoppable/containers/ManageCryptoContainer/ManageCryptoContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceSideMenu/InterfaceSideMenu.scss
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToDisplay/AccountContentToDisplay.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
  src/translations/dapps-ens/en_US.json
  src/translations/dapps-unstoppable/en_US.json
  src/translations/interface/en_US.json
  vueConfig/connections.js
Labels: Ready, Release

#2438 Devop/consolidate node prs
  CHANGELOG.md
  fetchLists/index.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/networks/ewt.svg
  src/assets/images/networks/fuse.svg
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.scss
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/dapps/Aave/Aave.vue
  src/dapps/Aave/ApolloClient.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/components/SummaryTable/SummaryTable.vue
  src/dapps/Aave/components/SummaryTableMobile/SummaryTableMobile.vue
  src/dapps/Aave/components/SwitchInterestModal/SwitchInterestModal.vue
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/dapps/Aave/graphQLHelpers.js
  src/dapps/MakerSai/MakerDai.scss
  src/dapps/MakerSai/MakerDai.vue
  src/dapps/MakerSai/routes.js
  src/dapps/Unstoppable/containers/InitialManageUnstoppableStateContainer/InitialManageUnstoppableStateContainer.vue
  src/dapps/routes.js
  src/directives/AddrResolver.js
  src/helpers/notificationFormatters/formatters.js
  src/helpers/responseHandler/responseMatches.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/Web3WalletModal/Web3WalletModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/networks/nodes/ewt.js
  src/networks/nodes/fuse.js
  src/networks/nodes/index.js
  src/networks/types/EWT.js
  src/networks/types/FUSE.js
  src/networks/types/index.js
  src/partners/dexAg/dexAg.js
  src/scss/Global-desktop.scss
  src/store/main/state.js
  src/translations/common/en_US.json
  src/translations/errors-global/en_US.json
  src/translations/errors-trezor/en_US.json
  src/translations/swap/en_US.json
  src/wallets/hardware/trezor/errorHandler.js
  tests/unit/specs/src/containers/ConfirmationContainer/ConfirmationContainer.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
  vueConfig/connections.js
Labels: Devop, Ready, v5

#2461 Update packages
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
Labels: Devop, Ready

#2458 hotfix/v5.6.6-hotfix.1
  CHANGELOG.md
  fetchLists/index.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/networks/ewt.svg
  src/assets/images/networks/fuse.svg
  src/components/SettingsModal/SettingsModal.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.scss
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/dapps/Aave/Aave.vue
  src/dapps/Aave/ApolloClient.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/components/SummaryTable/SummaryTable.vue
  src/dapps/Aave/components/SummaryTableMobile/SummaryTableMobile.vue
  src/dapps/Aave/components/SwitchInterestModal/SwitchInterestModal.vue
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/dapps/Aave/graphQLHelpers.js
  src/dapps/MakerSai/MakerDai.scss
  src/dapps/MakerSai/MakerDai.vue
  src/dapps/MakerSai/routes.js
  src/dapps/Unstoppable/containers/InitialManageUnstoppableStateContainer/InitialManageUnstoppableStateContainer.vue
  src/dapps/routes.js
  src/directives/AddrResolver.js
  src/helpers/notificationFormatters/formatters.js
  src/helpers/responseHandler/responseMatches.json
  src/layouts/AccessWalletLayout/components/HardwareModal/HardwareModal.vue
  src/layouts/AccessWalletLayout/components/Web3WalletModal/Web3WalletModal.vue
  src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/PrintModal.vue
  src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/networks/nodes/ewt.js
  src/networks/nodes/fuse.js
  src/networks/nodes/index.js
  src/networks/types/EWT.js
  src/networks/types/FUSE.js
  src/networks/types/index.js
  src/partners/dexAg/dexAg.js
  src/scss/Global-desktop.scss
  src/store/main/state.js
  src/translations/common/en_US.json
  src/translations/errors-global/en_US.json
  src/translations/errors-trezor/en_US.json
  src/translations/swap/en_US.json
  src/wallets/hardware/trezor/errorHandler.js
  tests/unit/specs/src/containers/ConfirmationContainer/ConfirmationContainer.spec.js
  tests/unit/specs/src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.spec.js
  vueConfig/connections.js
Labels: Ready, Release

#2473 check gas if only one side of the swap is on ethereum
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
Labels: Bug, Fixed, Ready

#2472 hotfix/revert-mewconnect
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
Labels: Ready, Release

#2475 Devop/sync develop
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
Labels: Devop, Ready, v5

#2471 Devop/update packages
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/arrow.svg
  src/assets/images/icons/mew-wallet-icon.png
  src/assets/images/icons/mew-wallet-icon.svg
  src/assets/images/icons/scan.svg
  src/containers/FooterContainer/FooterContainer.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/ManageENS/supportedTxt.js
  src/dapps/index.js
  src/helpers/misc.js
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-desktop.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/CreateWalletLayout/components/ScanToRedirectQR/ScanToRedirectQR.vue
  src/networks/types/EWT.js
  src/translations/access-wallet/en_US.json
  src/translations/dapps-aave/en_US.json
  vueConfig/connections.js
Labels: Devop, Ready

#2481 Devop/compile node changes
  CHANGELOG.md
  src/networks/types/EWT.js
Labels: Devop, Ready

#2476 Feature/cx download keystore [v5]
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/containers/NotificationsContainer/components/NotificationTypes/SwapNotification/SwapNotification.vue
  src/dapps/MakerDai/MakerCDP/MakerCDP.js
  src/dapps/MakerDai/MakerCDP/MakerCdpBase.js
  src/dapps/MakerDai/MakerCDP/daiMath.js
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/components/DepositModal/DepositModal.scss
  src/dapps/MakerDai/components/PaybackModal/PaybackModal.vue
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/dapps/MakerDai/containers/MakerHome/MakerHome.vue
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/dapps/MakerDai/containers/ManageCDP/ManageCDP.vue
  src/dapps/MakerDai/makerHelpers/locateCdps.js
  src/dapps/MakerDai/makerHelpers/setups.js
  src/helpers/responseHandler/responseMatches.json
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/ImportKeystoreModal/ImportKeystoreModal.vue
  src/layouts/ExtensionBrowserAction/components/ImportMnemonicModal/ImportMnemonicModal.vue
  src/layouts/ExtensionBrowserAction/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.scss
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/partners/dexAg/config/config.js
  src/partners/dexAg/config/index.js
  src/partners/dexAg/dexAg.js
  src/translations/dapps-maker/en_US.json
  src/translations/mew-cx/en_US.json
  src/translations/swap/en_US.json
  tests/unit/specs/src/partners/changelly/changelly.spec.js
Labels: Feature, Ready, v5

#2484 add check for market impact when finalizing swap details
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/responseHandler/responseMatches.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/partners/dexAg/config/config.js
  src/partners/dexAg/config/index.js
  src/partners/dexAg/dexAg.js
  src/translations/swap/en_US.json
Labels: Devop, Ready, v5

#2490 release/v5.7.0
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/arrow.svg
  src/assets/images/icons/mew-wallet-icon.png
  src/assets/images/icons/mew-wallet-icon.svg
  src/assets/images/icons/scan.svg
  src/containers/FooterContainer/FooterContainer.vue
  src/containers/NotificationsContainer/components/NotificationTypes/SwapNotification/SwapNotification.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/MakerDai/MakerCDP/MakerCDP.js
  src/dapps/MakerDai/MakerCDP/MakerCdpBase.js
  src/dapps/MakerDai/MakerCDP/daiMath.js
  src/dapps/MakerDai/MakerDai.vue
  src/dapps/MakerDai/components/DepositModal/DepositModal.scss
  src/dapps/MakerDai/components/PaybackModal/PaybackModal.vue
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/dapps/MakerDai/containers/MakerHome/MakerHome.vue
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/dapps/MakerDai/containers/ManageCDP/ManageCDP.vue
  src/dapps/MakerDai/makerHelpers/locateCdps.js
  src/dapps/MakerDai/makerHelpers/setups.js
  src/dapps/ManageENS/supportedTxt.js
  src/dapps/index.js
  src/helpers/misc.js
  src/helpers/responseHandler/responseMatches.json
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal-desktop.scss
  src/layouts/AccessWalletLayout/components/MewConnectModal/MewConnectModal.vue
  src/layouts/CreateWalletLayout/components/ScanToRedirectQR/ScanToRedirectQR.vue
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/ExtensionBrowserAction/components/ImportKeystoreModal/ImportKeystoreModal.vue
  src/layouts/ExtensionBrowserAction/components/ImportMnemonicModal/ImportMnemonicModal.vue
  src/layouts/ExtensionBrowserAction/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/ExtensionBrowserAction/components/VerifyDetailsModal/VerifyDetailsModal.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.scss
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/networks/types/EWT.js
  src/partners/dexAg/config/config.js
  src/partners/dexAg/config/index.js
  src/partners/dexAg/dexAg.js
  src/translations/access-wallet/en_US.json
  src/translations/dapps-aave/en_US.json
  src/translations/dapps-maker/en_US.json
  src/translations/mew-cx/en_US.json
  src/translations/swap/en_US.json
  tests/unit/specs/src/partners/changelly/changelly.spec.js
  vueConfig/connections.js
Labels: Ready, Release
