Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-11, with the labels that each got.

#2644 Merge back master to develop
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/networks/nodes/index.js
  src/networks/types/index.js
Labels: Devop, Ready

#2650 to lowercase for verify message
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  tests/unit/specs/src/partners/changelly/changelly.spec.js
Labels: Ready, v5

#2652 create PR to test address validation
  CHANGELOG.md
  package-lock.json
Labels: Devop, Ready, v5

#2649 Add allowance check
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/Aave/containers/HomeContainer/HomeContainer.vue
  src/dapps/LendMigrator/LendMigrator.vue
Labels: Ready, v5

#2648 Bugs/misc
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
Labels: Bug, Ready

#2646 update rates and min dai for makerDao
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/MakerDai/MakerCDP/MakerCDP.js
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
Labels: Bug, Ready, v5

#2664 release/v5.7.13
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/components/VerifyMessageInput/VerifyMessageInput.vue
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/dapps/Aave/containers/HomeContainer/HomeContainer.vue
  src/dapps/LendMigrator/LendMigrator.vue
  src/dapps/MakerDai/MakerCDP/MakerCDP.js
  src/dapps/MakerDai/containers/MakerSavings/MakerSavings.vue
  src/helpers/responseHandler/responseMatches.json
  src/layouts/InterfaceLayout/components/InterfaceTokensModal/InterfaceTokensModal.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapConfirmationModal/SwapConfirmationModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapWidget/SwapWidget.vue
  tests/unit/specs/src/partners/changelly/changelly.spec.js
Labels: Ready, Release

#2672 golem token migration
  .github/workflows/add-to-codecov.yml
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/github-release.yml
  .github/workflows/run-on-pr.yml
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/icons/dapps/Golem_Submark_Positive_RGB.svg
  src/dapps/GntMigrator/GntMigrator.vue
  src/dapps/GntMigrator/LendMigrator.scss
  src/dapps/GntMigrator/abi/GntMigratorAgent.js
  src/dapps/GntMigrator/abi/erc20.js
  src/dapps/GntMigrator/abi/oldToken.js
  src/dapps/GntMigrator/routes.js
  src/dapps/index.js
  src/dapps/routes.js
  src/translations/dapps-misc/en_US.json
  src/translations/en_US.js
Labels: Feature, Ready, v5

#2675 Bug/subdomain transfer
  .github/workflows/add-to-develop.yml
  .github/workflows/build-cx-generate-zip.yml
  .github/workflows/deploy-live.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/BuySubdomain/domains.json
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/networks/nodes/music.js
  src/networks/types/GOERLI.js
  src/networks/types/MUSIC.js
Labels: Bug, Ready

#2678 devop: update version on changelog correctly
  CHANGELOG.md
  package-lock.json
Labels: Devop, Ready

#2680 update packages
  package-lock.json
  package.json
Labels: Devop, Ready

#2677 release/v5.7.14
  .github/workflows/add-to-codecov.yml
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/build-cx-generate-zip.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/github-release.yml
  .github/workflows/run-on-pr.yml
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/icons/dapps/Golem_Submark_Positive_RGB.svg
  src/dapps/BuySubdomain/domains.json
  src/dapps/GntMigrator/GntMigrator.vue
  src/dapps/GntMigrator/LendMigrator.scss
  src/dapps/GntMigrator/abi/GntMigratorAgent.js
  src/dapps/GntMigrator/abi/erc20.js
  src/dapps/GntMigrator/abi/oldToken.js
  src/dapps/GntMigrator/routes.js
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/AlreadyOwnedENSContainer/AlreadyOwnedENSContainer.vue
  src/dapps/ManageENS/containers/EnsMultiManager/EnsMultiManager.vue
  src/dapps/index.js
  src/dapps/routes.js
  src/networks/nodes/music.js
  src/networks/types/GOERLI.js
  src/networks/types/MUSIC.js
  src/translations/dapps-misc/en_US.json
  src/translations/en_US.js
Labels: Ready, Release

#2661 V6/update mobile create wallet
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/border-block/BorderBlock.vue
  src/modules/wallets/components/mnemonic-phrase-table/MnemonicPhraseTable.vue
  src/modules/wallets/components/mnemonic-phrase/MnemonicPhrase.vue
  src/plugins/vuetify.js
Labels: Ready, v6
