Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2020-02, with the labels that each got.

#1915 devop/translations-index
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  public/index.html
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.vue
  src/main.js
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/EthereumTokens.json
  src/router/index.js
  src/store/main/actions.js
  src/store/main/mutations.js
  src/translations/getShortCodes.js
Labels: Devop, Ready

#1938 Devop/update packages
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package.json
  src/components/IssueLogModal/IssueLogModal.vue
  src/dapps/ManageENS/ABI/deedContractAbi.js
  src/dapps/ManageENS/ABI/registrarAbi.js
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/TransferRegistrarsContainer.scss
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/TransferRegistrarsContainer.vue
  src/dapps/ManageENS/containers/TransferRegistrarsContainer/index.js
  src/dapps/ManageENS/routes.js
  src/helpers/misc.js
  src/layouts/InterfaceLayout/containers/DappsContainer/DappsContainer.vue
  src/networks/types/ETH.js
  src/partners/changelly/config/currencies.json
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  src/partners/partnersConfig/OtherCoins.json
  src/router/index.js
  src/translations/dapps-ens/en_US.json
  tests/unit/helpers/mockStore.js
Labels: Devop, Ready

#1912 devop/update-web3-packages
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
Labels: Devop, Ready

#1942 release/v5.3.1
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  public/index.html
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/components/MobileLanguageSelector/MobileLanguageSelector.vue
  src/dapps/ScheduleTransaction/containers/ScheduleView.vue
  src/helpers/misc.js
  src/main.js
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/EthereumTokens.json
  src/partners/partnersConfig/OtherCoins.json
  src/router/index.js
  src/store/main/actions.js
  src/store/main/mutations.js
  src/translations/getShortCodes.js
Labels: Ready, Release

#1953 devop/update-team-page
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/assets/images/team/Samantha.jpg
  src/layouts/TeamLayout/TeamLayout.vue
  src/partners/changelly/config/currencies.json
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
Labels: Devop, Ready

#1954 Devop/update packages
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/IssueLogModal/IssueLogModal.scss
Labels: Devop, Ready

#1956 hotfix/cx-calls-fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceNetworkModal/InterfaceNetworkModal.vue
  src/translations/footer/en_US.json
Labels: Ready, Release

#1961 Add community links
  CHANGELOG.md
  src/assets/images/icons/instagram.png
  src/assets/images/icons/mewtopia.png
  src/assets/images/icons/youtube.png
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/HomeLayout/components/Social/Social.vue
  src/translations/home/en_US.json
Labels: Feature, Ready

#1963 Fix links
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/GettingStarted/components/SomeHelpfulTips/SomeHelpfulTips.vue
  src/layouts/HardwaresLayout/HardwaresLayout.vue
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
  tests/unit/specs/src/layouts/HardwaresLayout/HardwaresLayout.spec.js
Labels: Bug, Ready

#1975 hotfix/unstoppable
  CHANGELOG.md
  package-lock.json
  package.json
  src/directives/AddrResolver.js
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
Labels: Ready, Release

#1976 Devop/update packages
  CHANGELOG.md
  package-lock.json
  package.json
  src/directives/AddrResolver.js
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
Labels: Devop, Ready

#1977 Fix dai icon
  CHANGELOG.md
  package-lock.json
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
Labels: Bug, Ready

#1978 bug/token-fetch
  CHANGELOG.md
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/CreateCommitmentContainer/CreateCommitmentContainer.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
Labels: Bug, Ready

#1985 maker dai build proxy contract fix
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/partners/changelly/config/currencies.json
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  src/partners/partnersConfig/OtherCoins.json
Labels: Ready

#1887 Add cad and jpy
  CHANGELOG.md
  package-lock.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/partners/changelly/config/currencies.json
  src/partners/helpers/utils.js
  src/partners/partnersConfig/OtherCoins.json
  src/partners/partnersConfig/currencyDetails.js
  src/partners/simplex/config.js
  src/partners/simplex/simplex-api.js
  src/partners/simplex/simplex.js
  vueConfig/defaultConfigs.js
Labels: Ready

#1994 Devop/update packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#1986 bug/mewcx-current-version
  CHANGELOG.md
  src/builds/mewcx/app.vue
  src/builds/mewcx/cxHelpers/background.js
  src/layouts/ExtensionBrowserAction/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionAddWalletContainer/ExtensionAddWalletContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/networks/index.js
  src/store/main/state.js
  src/translations/mew-cx/en_US.json
Labels: Bug, Ready

#1996 release/v5.3.3
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/images/nft/products/Flowerpatch.png
  src/builds/mewcx/app.vue
  src/builds/mewcx/cxHelpers/background.js
  src/dapps/MakerDai/containers/CreateCDP/CreateCDP.vue
  src/dapps/ManageENS/ManageENS.vue
  src/dapps/ManageENS/containers/CreateCommitmentContainer/CreateCommitmentContainer.vue
  src/layouts/ExtensionBrowserAction/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionAddWalletContainer/ExtensionAddWalletContainer.vue
  src/layouts/ExtensionBrowserAction/containers/ExtensionWalletContainer/ExtensionWalletContainer.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.scss
  src/layouts/InterfaceLayout/containers/DashboardContainer/DashboardContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NFTSideMenu/NFTSideMenu.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftCustomAddModal/NftCustomAddModal.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftProductCard/NftProductCard.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/networks/index.js
  src/partners/changelly/config/currencies.json
  src/partners/helpers/utils.js
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
  src/partners/partnersConfig/OtherCoins.json
  src/partners/partnersConfig/currencyDetails.js
  src/partners/simplex/config.js
  src/partners/simplex/simplex-api.js
  src/partners/simplex/simplex.js
  src/store/main/state.js
  src/translations/dapps-ambrpay/es_ES.json
  src/translations/dapps-ambrpay/ja_JP.json
  src/translations/dapps-ambrpay/ko_KR.json
  src/translations/dapps-ambrpay/ru_RU.json
  src/translations/dapps-ambrpay/zh_CN.json
  src/translations/dapps-ens/es_ES.json
  src/translations/dapps-ens/ja_JP.json
  src/translations/dapps-ens/ko_KR.json
  src/translations/dapps-ens/ru_RU.json
  src/translations/dapps-ens/zh_CN.json
  src/translations/dapps-sub-domain/es_ES.json
  src/translations/dapps-sub-domain/ja_JP.json
  src/translations/dapps-sub-domain/ko_KR.json
  src/translations/dapps-sub-domain/ru_RU.json
  src/translations/dapps-sub-domain/zh_CN.json
  src/translations/home/es_ES.json
  src/translations/home/ja_JP.json
  src/translations/home/ko_KR.json
  src/translations/home/ru_RU.json
  src/translations/home/zh_CN.json
  src/translations/mew-cx/en_US.json
  src/translations/nft-manager/en_US.json
  vueConfig/defaultConfigs.js
Labels: Ready, Release

#1998 Hotfix/remove iosiro
  CHANGELOG.md
  fetchLists/index.js
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/helpers.js
Labels: Hotfix, Ready

#1999 Devop/sync to develop
  CHANGELOG.md
  fetchLists/index.js
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/helpers.js
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
Labels: Devop, Ready

#2000 Change translations
  CHANGELOG.md
  src/translations/mew-cx/en_US.json
Labels: Devop, Ready

#2001 fix nft load issue
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/partners/kyber/config/currenciesETH.json
  src/partners/partnersConfig/EthereumTokens.json
Labels: Ready, Release

#1987 V6 - Update my eth balance chart
  fetchLists/lists/tokens.json
  package.json
  src/Features/Dashboard/EthBalance/EthBalance.vue
  src/Features/Dashboard/TokensValue/TokensValue.vue
  src/assets/charts/1d.json
  src/assets/charts/1m.json
  src/assets/charts/1w.json
  src/assets/charts/1y.json
  src/assets/charts/all.json
  src/components/BlockTitles/BlockTitle1/BlockTitle1.vue
  src/components/BlockTitles/BlockTitle1/index.js
  src/components/Buttons/ButtonGroup1/ButtonGroup1.vue
  src/components/Buttons/ButtonGroup1/index.js
  src/components/Charts/Balance/Balance.vue
  src/layouts/Features/Features.vue
  src/variables.js
Labels: Devop, Ready

#2009 remove keepalive net_version calls
  CHANGELOG.md
  src/wallets/web3-provider/providers/ws-provider.js
Labels: Fixed, Hotfix, Ready

#2003 Devop/desktop icons
  CHANGELOG.md
  src/layouts/HomeLayout/components/Social/Social.scss
  src/layouts/HomeLayout/components/Social/Social.vue
Labels: Devop, Ready

#2012 Devop/sync develop
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/wallets/web3-provider/providers/ws-provider.js
Labels: Devop, Ready

#2015 V6/tokens value
  CHANGELOG.md
  package.json
  src/Features/Dashboard/TokensValue/TokensValue.vue
  src/assets/styles/GlobalStyles.scss
  src/components/Charts/Tiny/Tiny.vue
  src/components/Charts/Tiny/index.js
Labels: Devop, Ready

#2011 Update aave copy
  0
  CHANGELOG.md
  package-lock.json
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/dapps/Aave/Aave.vue
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.scss
  src/dapps/Aave/components/SummaryTable/SummaryTable.scss
  src/dapps/Aave/components/SummaryTable/SummaryTable.vue
  src/dapps/Aave/components/SwitchInterestModal/SwitchInterestModal.scss
  src/dapps/Aave/containers/ActionContainer/ActionContainer.vue
  src/dapps/Aave/routes.js
  src/translations/dapps-aave/en_US.json
  src/translations/dapps-ambrpay/en_US.json
  tests/unit/specs/src/dapps/Aave/Aave.spec.js
Labels: Devop, Ready

#2020 Devop/aave copy
  CHANGELOG.md
  src/dapps/Aave/components/ConfirmationModal/ConfirmationModal.vue
  src/dapps/Aave/containers/HomeContainer/HomeContainer.vue
  src/translations/dapps-aave/en_US.json
Labels: Devop, Ready

#2013 Bug/nft fix transaction fail before send
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/Aave/Aave.scss
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/NFTManagerContainer.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/translations/nft-manager/en_US.json
Labels: Bug, Ready

#2002 Devop/fix exit to fiat notifications
  CHANGELOG.md
  src/containers/NotificationsContainer/components/NotificationTypes/SwapNotification/SwapNotification.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftProductCard/NftProductCard.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapExitToFiat/SwapExitToFiat.vue
  src/partners/bity/bity.js
Labels: Ready

#1997 Bug/keystore download
  CHANGELOG.md
  src/layouts/ExtensionBrowserAction/components/CxFooter/CxFooter.vue
  src/layouts/ViewWalletInfoLayout/ViewWalletInfoLayout.vue
Labels: Bug, Ready

#1972 Fix (Save address button) position in /interface/send-transaction
  CHANGELOG.md
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/partners/changelly/config/currencies.json
  src/partners/partnersConfig/OtherCoins.json
Labels: Ready, UI
