Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-01, with the labels that each got.

#2758 Update bity max
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/partners/bity/config.js
Labels: Devop, Ready, v5

#2763 fix cx build name
  CHANGELOG.md
  ENV_VARS.js
  package-audit.js
  package-lock.json
  package.json
  src/networks/nodes/etc-ethereumclassiccooperative-parity-ws.js
  src/networks/nodes/etc-ethereumclassiccooperative-parity.js
  src/networks/nodes/index.js
  vueConfig/connections.js
  vueConfig/mewcx.js
Labels: Hotfix, Ready

#2766 release/v5.7.18
  CHANGELOG.md
  ENV_VARS.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/dapps/LendMigrator/LendMigrator.vue
  src/networks/nodes/etc-ethereumclassiccooperative-parity-ws.js
  src/networks/nodes/etc-ethereumclassiccooperative-parity.js
  src/networks/nodes/index.js
  src/partners/bity/config.js
  vueConfig/connections.js
  vueConfig/mewcx.js
Labels: Ready, Release

#2718 AddressBook
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/assets/styles/GlobalStyles.scss
  src/components/balance-block/BalanceBlock.vue
  src/components/mobile-table/MobileTable.vue
  src/dapps/name-manager/NameManager.vue
  src/dapps/unstoppable-domains/UnstoppableDomain.vue
  src/modules/tools/components/table-container/TableContainer.vue
  src/modules/wallets/Wallets.vue
  src/modules/wallets/components/confirmation/Confirmation.vue
  src/modules/wallets/components/network/Network.vue
  src/modules/wallets/components/notifications/components/in/In.vue
  src/modules/wallets/components/notifications/components/out/Out.vue
  src/modules/wallets/components/notifications/components/swap/Swap.vue
  src/modules/wallets/components/settings/Settings.vue
  src/modules/wallets/components/settings/components/contact-address/ContactAddress.vue
  src/modules/wallets/components/system-menu/SystemMenu.vue
  src/modules/wallets/components/wallet-card/WalletCard.vue
  src/modules/wallets/pages/dashboard/Dashboard.vue
  src/modules/wallets/pages/send/send-tx/SendTx.vue
  src/modules/wallets/pages/send/send-tx/index.js
  src/modules/wallets/pages/settings/Settings.vue
  src/modules/wallets/pages/settings/components/address-book/AddEditAddress.vue
  src/modules/wallets/pages/settings/components/address-book/AddressBook.vue
  src/modules/wallets/pages/settings/components/export-config/ExportConfig.vue
  src/modules/wallets/pages/settings/components/gas-price/GasPrice.vue
  src/modules/wallets/pages/settings/components/import-config/ImportConfig.vue
  src/modules/wallets/pages/settings/components/notifications/Notifications.vue
  src/store/wallet/actions.js
  src/store/wallet/mutations.js
  src/store/wallet/state.js
  src/translations/common/en_US.json
  src/translations/interface/en_US.json
Labels: Ready, v6

#2743 V6/Update team page
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/backgrounds/bg-left-bubble.png
  src/assets/images/backgrounds/bg-right-bubble.png
  src/assets/images/presskit/logo-dark.png
  src/assets/images/presskit/logo-dark.svg
  src/assets/images/presskit/logo-kid.png
  src/assets/images/presskit/logo-kid.svg
  src/assets/images/presskit/logo-light.png
  src/assets/images/presskit/logo-light.svg
  src/assets/images/presskit/logo-simple.png
  src/assets/images/presskit/logo-simple.svg
  src/assets/images/team/jessica.jpg
  src/assets/styles/GlobalStyles.scss
  src/modules/home/components/footer/Footer.vue
  src/modules/home/components/why-mew/WhyMew.vue
  src/modules/how-it-works/components/swap/Swap.vue
  src/modules/how-it-works/components/tokens/Tokens.vue
  src/modules/press-kit/PressKit.vue
  src/modules/team/Team.vue
  src/router/routes.js
Labels: Ready, v6

#2733 V6/privacy terms
  CHANGELOG.md
  src/modules/home/components/footer/Footer.vue
  src/modules/home/components/header/Header.vue
  src/modules/home/components/menu-desktop/Menu.vue
  src/modules/home/components/menu-desktop/SiteMenu.vue
  src/modules/home/components/menu-mobile/Menu.vue
  src/modules/home/components/menu/Menu.vue
  src/modules/privacy-policy/PrivacyPolicy.scss
  src/modules/privacy-policy/PrivacyPolicy.vue
  src/modules/terms-of-service/TermsOfService.vue
  src/modules/wallets/components/menu-mobile/Menu.vue
  src/modules/wallets/components/side-menu/SideMenu.vue
  src/router/routes.js
  vue.config.js
Labels: Ready, v6

#2720 V6/decision tree
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.vue
  src/assets/images/icons/DecisionTree/home.svg
  src/assets/images/icons/DecisionTree/need-help.svg
  src/assets/images/icons/DecisionTree/question.svg
  src/components/DecisionTree/DecisionTree.scss
  src/components/DecisionTree/DecisionTree.vue
  src/components/DecisionTree/components/MdContainer/MdContainer.scss
  src/components/DecisionTree/components/MdContainer/MdContainer.vue
  src/components/DecisionTree/data/MDIndex.js
  src/components/DecisionTree/data/md/_Access_Ledger.md
  src/components/DecisionTree/data/md/_Access_Trezor.md
  src/components/DecisionTree/data/md/_Access_file.md
  src/components/DecisionTree/data/md/_Access_key.md
  src/components/DecisionTree/data/md/_Access_other.md
  src/components/DecisionTree/data/md/_Access_phrase.md
  src/components/DecisionTree/data/md/_Cant_scan_access.md
  src/components/DecisionTree/data/md/_Different_address.md
  src/components/DecisionTree/data/md/_Find_CX.md
  src/components/DecisionTree/data/md/_Find_Ledger.md
  src/components/DecisionTree/data/md/_Find_MEWconnect.md
  src/components/DecisionTree/data/md/_Find_MEWwallet.md
  src/components/DecisionTree/data/md/_Find_MM.md
  src/components/DecisionTree/data/md/_Find_Trezor.md
  src/components/DecisionTree/data/md/_Find_file.md
  src/components/DecisionTree/data/md/_Find_key.md
  src/components/DecisionTree/data/md/_Find_other.md
  src/components/DecisionTree/data/md/_Forgot_pass_access.md
  src/components/DecisionTree/data/md/_Forgot_pin_access.md
  src/components/DecisionTree/data/md/_Funds_network.md
  src/components/DecisionTree/data/md/_Given_hash.md
  src/components/DecisionTree/data/md/_No_hash.md
  src/components/DecisionTree/data/md/_Notgiven_hash.md
  src/components/DecisionTree/data/md/_Recognize_address.md
  src/components/DecisionTree/data/md/_Saved_hash.md
  src/components/DecisionTree/data/md/_Tokens_custom.md
  src/components/DecisionTree/data/md/_Using_CX_access.md
  src/components/DecisionTree/data/md/_Using_MM_access.md
  src/components/DecisionTree/data/md/_bity.md
  src/components/DecisionTree/data/md/_buy_bug.md
  src/components/DecisionTree/data/md/_changelly.md
  src/components/DecisionTree/data/md/_created_on_MEW.md
  src/components/DecisionTree/data/md/_created_other.md
  src/components/DecisionTree/data/md/_dapp_MakerDAO.md
  src/components/DecisionTree/data/md/_dapp_other.md
  src/components/DecisionTree/data/md/_kyber.md
  src/components/DecisionTree/data/md/_not_listed.md
  src/components/DecisionTree/data/md/_simplex.md
  src/components/DecisionTree/data/md/_suggestions.md
  src/components/DecisionTree/data/md/_swap_error.md
  src/components/DecisionTree/data/md/_tx_bug.md
  src/components/DecisionTree/data/md/_tx_error.md
  src/components/DecisionTree/data/md/_tx_other.md
Labels: Ready, v6

#2714 Update send tx and components
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
Labels: Ready, v6

#2776 use right unit for amount
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/LendMigrator/LendMigrator.vue
Labels: Bug, Ready, v5

#2784 devop/changelly-terms
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/TeamLayout/TeamLayout.scss
  src/layouts/TeamLayout/TeamLayout.vue
  src/translations/swap/en_US.json
Labels: Devop, Ready

#2782 Remove Jack and add Jessica
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/TeamLayout/TeamLayout.vue
Labels: Ready, v5

#2785 release/v5.7.19
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/LendMigrator/LendMigrator.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/TeamLayout/TeamLayout.scss
  src/layouts/TeamLayout/TeamLayout.vue
  src/translations/swap/en_US.json
Labels: Ready, Release, v5

#2789 exclude some packages for release
  package-test.js
Labels: Devop, Ready

#2792 merge master to develop
  package-test.js
Labels: Devop, Ready

#2793 hotfix/aave-frozen
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/dapps/Aave/containers/HomeContainer/HomeContainer.vue
Labels: Ready, Release

#2794 revert aave container change
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/Aave/containers/HomeContainer/HomeContainer.vue
Labels: Devop, Ready

#2774 feature/swap [v6]
  CHANGELOG.md
  connections.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/swap/abi/erc20.js
  src/modules/swap/assets/0x.png
  src/modules/swap/assets/1inch.png
  src/modules/swap/assets/Bancor.png
  src/modules/swap/assets/Bity.png
  src/modules/swap/assets/Changelly.png
  src/modules/swap/assets/Curve.png
  src/modules/swap/assets/Idex.png
  src/modules/swap/assets/Oasis.png
  src/modules/swap/assets/Paradex.png
  src/modules/swap/assets/Sushiswap.png
  src/modules/swap/assets/Synthetix.png
  src/modules/swap/assets/ddex.png
  src/modules/swap/assets/deversiFI.png
  src/modules/swap/assets/kyber.png
  src/modules/swap/assets/uniswap.png
  src/modules/swap/assets/xblaster.png
  src/modules/swap/configs.js
  src/modules/swap/index.js
  src/modules/swap/providers/changelly.js
  src/modules/swap/providers/dex-ag.js
  src/modules/swap/providers/index.js
  src/modules/swap/providers/mew-provider-class.js
  src/modules/swap/providers/one-inch.js
  src/modules/swap/tests/changelly.spec.js
  src/modules/swap/tests/dexag.spec.js
  src/modules/wallets/components/confirmation/Confirmation.vue
  src/modules/wallets/pages/swap/Swap.vue
  src/modules/wallets/pages/swap/components/SwapConfirmation.vue
  src/modules/wallets/pages/swap/components/SwapFromToBlock.vue
  src/router/index.js
  src/store/wallet/state.js
  vue.config.js
Labels: Ready, v6
