Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-09, with the labels that each got.

#3431 chore: 👷 update packages
  changelog/devop-3431.md
  package-lock.json
  package.json
Labels: Devop, Ready

#3423 ui: 🎨 load address at the same time
  changelog/devop-3419.md
  changelog/ui-3422.md
  changelog/ui-3423.md
  package-lock.json
  package.json
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
Labels: Devop, Ready

#3422 ui: 🎨 focus first mnemonic input
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  changelog/devop-3419.md
  changelog/ui-3422.md
  package-lock.json
  package.json
  src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/toast/handler/handlerToast.js
Labels: Devop, Ready

#3418 release: 🔥 v6.0.6
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/toast/handler/handlerToast.js
Labels: Release, Ready

#3407 fix: 🐛 metamask window ethereum on
  changelog/fix-3407.md
  src/views/TheWalletView.vue
Labels: Bug, Ready

#3421 devop: 🔧 hide total when sending tokens
  changelog/devop-3421.md
  changelog/fix-3407.md
  changelog/fix-3426.md
  changelog/fix-3428.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
Labels: Devop, Ready

#3440 fix: 🐛 check for token type and symbols
  changelog/fix-3440.md
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready

#3410 feat: ✨ add intercom
  CHANGELOG.md
  changelog/feat-3410.md
  connections.js
  package-lock.json
  package.json
  public/index.html
  src/app.vue
  src/main.js
  src/utils/networks/types/ETH.js
  vue.config.js
Labels: Feature, Ready

#3443 fix: 🐛 return array if preToken is undefined
  changelog/fix-3440.md
  changelog/fix-3443.md
  package-lock.json
  src/core/store/external/actions.js
Labels: Bug, Ready

#3436 fix: 🐛 only allow numbers on gas price input
  changelog/fix-3436.md
  package-lock.json
  src/modules/settings/components/SettingsGasPrice.vue
Labels: Bug, Ready

#3445 fix: 🐛 token balance for non decimal
  changelog/fix-3445.md
  src/core/store/external/actions.js
Labels: Bug, Ready

#3409 fix: 🐛 adding errors to handlers
  changelog/fix-3409
  src/modules/access-wallet/hardware/handlers/hardwares/bcvault/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/toast/handler/handlerToast.js
Labels: Bug, Ready

#3439 fix: 🐛 rerouting on refresh
  changelog/fix-3439.md
  src/core/components/AppNetworkFee.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/settings/ModuleSettings.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Bug, Ready

#3272 feat: ✨ add 0x dex and paraswap
  changelog/feat-3272.md
  changelog/fix-3439.md
  changelog/fix-3445.md
  package-lock.json
  package.json
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/index.js
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/modules/swap/handlers/providers/paraswap.js
  src/modules/swap/handlers/providers/zerox.js
  src/modules/swap/tests/zerox.spec.js
  src/views/layouts-default/TheTeamLayout.vue
Labels: Ready, v6

#3413 ui: 🎨 finish coolwallet
  CHANGELOG.md
  changelog/feat-3410.md
  changelog/fix-3409.md
  changelog/fix-3435.md
  changelog/fix-3436.md
  changelog/fix-3437.md
  changelog/fix-3439.md
  changelog/fix-3440.md
  changelog/fix-3443.md
  changelog/fix-3445.md
  changelog/ui-3413.md
  connections.js
  package-lock.json
  package.json
  public/index.html
  src/app.vue
  src/assets/images/hardware-wallets/coolwallet-sample.png
  src/core/components/AppNetworkFee.vue
  src/core/store/external/actions.js
  src/main.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletCoolWallet.vue
  src/modules/access-wallet/hardware/components/AccessWalletNetworkAddresses.vue
  src/modules/access-wallet/hardware/handlers/hardwares/bcvault/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/send/ModuleSend.vue
  src/modules/send/handlers/handlerSend.js
  src/modules/settings/ModuleSettings.vue
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/settings/handler/handlerSettings.js
  src/modules/swap/ModuleSwap.vue
  src/modules/toast/handler/handlerToast.js
  src/utils/networks/types/ETH.js
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  vue.config.js
Labels: Devop, Ready

#3404 ui: 🎨 keepkey ui
  changelog/fix-3397.md
  changelog/fix-3412.md
  changelog/ui-3404.md
  changelog/ui-3405.md
  package-lock.json
  package.json
  src/components/mew-super-button-revised/MewSuperButtonRevised.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/access-wallet/hardware/components/AccessWalletKeepkey.vue
  src/modules/access-wallet/hardware/components/AccessWalletPin.vue
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/index.js
  src/modules/global-modals/ModuleGlobalModals.vue
  src/modules/global-modals/components/EnterPinMatrix.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Feature, Ready

#3403 ui: 🎨 ledger ui changes
  changelog/ui-3403.md
  connections.js
  package-lock.json
  package.json
  src/assets/images/hardware-wallets/ledger-graphic.svg
  src/assets/images/icons/icon-checked.svg
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
Labels: Ready, UI

#3406 ui: 🎨 trezor wallet ui
  ISSUE_TEMPLATE.md
  changelog/ui-3406.md
  package-lock.json
  src/assets/images/icons/DecisionTree/home.svg
  src/assets/images/icons/DecisionTree/need-help.svg
  src/assets/images/icons/DecisionTree/question.svg
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
Labels: Ready, UI, v6

#3442 devop: 🔧 update wallet connect library
  changelog/devop-3342.md
  changelog/devop-3442.md
  changelog/feat-3416.md
  changelog/fix-3451.md
  changelog/fix-3454.md
  connections.js
  package-lock.json
  package.json
  src/assets/images/networks/go.svg
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/utils/networks/nodes/gochain-ws.js
  src/utils/networks/nodes/index.js
  src/utils/networks/types/GO.js
  src/utils/networks/types/index.js
  vue.config.js
Labels: Devop, Ready

#3460 devop: 🔧 github action to remove old lokalise branches
  .github/workflows/remove-old-lokalise.yml
  changelog/devop-3460.md
  package.json
  remove-old-lokalise-prs.js
Labels: Devop, Ready

#3450 fix: 🐛 expected public key to be an Uint8Array with length
  changelog/fix-3450.md
  src/views/TheWalletView.vue
Labels: Bug, Ready

#3461 fix: 🐛 add staked filter for unpaid validators
  changelog/devop-3460.md
  changelog/fix-3409
  changelog/fix-3409.md
  changelog/fix-3450.md
  changelog/fix-3461.md
  package-lock.json
  src/dapps/staked-dapp/components/StakedStatus.vue
Labels: Bug, Ready

#3327 feat: ✨ matomo integration
  README.md
  changelog/feat-3327.md
  changelog/fix-3373.md
  connections.js
  package-lock.json
  package.json
  public/index.html
  src/app.vue
  src/components/mew-tools/MewTools.vue
  src/components/theme-switch/ThemeSwitch.vue
  src/core/components/AppNetworkSettingsModal.vue
  src/core/plugins/vuetify.js
  src/core/store/configs.js
  src/core/store/global/actions.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/main.js
  src/main/matomo.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/ModuleAccessWalletMobile.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/access-wallet/common/walletTypes.js
  src/modules/analytics-opt-in/ModuleAnalytics.vue
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/ModuleSwapRates.vue
  src/modules/swap/components/SwapMsgStoreBtcEth.vue
  src/translations/privacy-policy/en_US.json
  src/views/components-default/CompanyCommunity.vue
  src/views/components-default/HomeLanding.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletFooter.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-default/ThePrivacyPolicyLayout.vue
  src/views/layouts-default/TheTermsOfServiceLayout.vue
Labels: Feature, Ready

#3455 ui: 🎨 add svg logo
  changelog/fix-3451.md
  changelog/fix-3454.md
  changelog/fix-3455.md
  src/assets/images/icons/icon-mew-dark.svg
  src/assets/images/icons/icon-mew-logo.svg
  src/assets/images/icons/logo-mew.svg
  src/core/components/AppQrCode.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, UI, v6

#3465 release: 🔥 v6.1.0-hotfix.1
  CHANGELOG.md
  changelog/devop-3465.md
  fetchLists/lists/contracts.json
  package-lock.json
  package.json
  src/app.vue
  src/modules/swap/handlers/providers/mew-provider-class.js
Labels: Release, Ready

#3441 feat: ✨ custom token
  changelog/feat-3441.md
  package-lock.json
  src/core/store/configs.js
  src/core/store/custom/actions.js
  src/core/store/custom/getters.js
  src/core/store/custom/index.js
  src/core/store/custom/mutations.js
  src/core/store/custom/state.js
  src/core/store/index.js
  src/main.js
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/balance/components/TokenDeleteCustom.vue
  src/modules/balance/handlers/abiERC20.js
  src/views/components-default/TheDefaultHeader.vue
Labels: Feature, Ready

#3438 ui: 🎨 provider mentions
  changelog/ui-3438.md
  package-lock.json
  src/assets/images/partners/colored/1inch.png
  src/assets/images/partners/colored/changelly.png
  src/core/plugins/vuetify.js
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/assets/0x.png
  src/modules/swap/assets/1inch.png
  src/modules/swap/assets/Bancor.png
  src/modules/swap/assets/Bity.png
  src/modules/swap/assets/Changelly.png
  src/modules/swap/assets/Curve.png
  src/modules/swap/assets/Idex.png
  src/modules/swap/assets/Oasis.png
  src/modules/swap/assets/Sushiswap.png
  src/modules/swap/assets/Synthetix.png
  src/modules/swap/assets/ddex.png
  src/modules/swap/assets/deversiFI.png
  src/modules/swap/assets/kyber.png
  src/modules/swap/assets/paraswap.png
  src/modules/swap/assets/uniswap.png
  src/modules/swap/assets/xblaster.png
  src/modules/swap/components/SwapProviderMentions.vue
  src/modules/swap/components/SwapProvidersList.vue
Labels: Ready, UI, v6

#3472 fix: 🐛 intercom session not resetting
  changelog/fix-3472.md
  package-lock.json
  package.json
  src/app.vue
  src/main.js
Labels: Bug, Ready

#3469 chore: 👷 silently fail matomo
  changelog/devop-3469.md
  package-lock.json
  src/core/store/global/actions.js
Labels: Bug, Ready

#3471 ui: 🎨 hide token icons
  changelog/ui-3471.md
  package-lock.json
  package.json
  src/modules/balance/ModuleTokensValue.vue
Labels: Ready, UI, v6

#3476 fix: 🐛 low balance not showing up in send tx
  changelog/fix-3476.md
  src/modules/send/ModuleSend.vue
Labels: Bug, Ready

#3466 fix: 🐛 add in additional error handling
  changelog/fix-3466.md
  src/modules/access-wallet/hardware/handlers/hardwares/bcvault/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
  src/modules/contract/ModuleContractInteract.vue
  src/modules/toast/handler/handlerToast.js
  src/translations/errors-bcvault/en_US.json
  src/translations/errors-bitbox/en_US.json
  src/translations/errors-bitbox02/en_US.json
  src/translations/errors-coolwallet/en_US.json
  src/translations/errors-global/en_US.json
  src/translations/errors-keepkey/en_US.json
  src/translations/errors-ledger/en_US.json
  src/translations/errors-trezor/en_US.json
Labels: Bug, Ready

#3452 fix: 🐛 my token value trade button
  changelog/fix-3452.md
  changelog/fix-3466.md
  changelog/fix-3476.md
  changelog/fix-3482.md
  changelog/fix-3483.md
  src/modules/balance/ModuleTokensValue.vue
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready, v6

#3467 ui: 🎨 update address error messages
  changelog/fix-3467.md
  package-lock.json
  package.json
  src/modules/address-book/ModuleAddressBook.vue
Labels: Bug, v6

#3470 fix: 🐛 update address book store to custom and fix some bugs
  changelog/fix-3470.md
  package-lock.json
  package.json
  src/core/store/custom/actions.js
  src/core/store/custom/mutations.js
  src/core/store/custom/state.js
  src/core/store/global/actions.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/settings/ModuleSettings.vue
Labels: Ready, v6

#3473 fix: 🐛 sentry issue #2507644001
  changelog/fix-3473.md
  package-lock.json
  src/modules/contract/ModuleContractDeploy.vue
Labels: Bug, Ready, v6

#3475 fix: 🐛 contract interaction input
  changelog/fix-3475.md
  src/modules/contract/ModuleContractInteract.vue
  src/modules/contract/handlers/common.js
Labels: Bug, Ready

#3485 fix: 🐛 remove rate for amount
  changelog/fix-3485.md
  package-lock.json
  package.json
  src/modules/swap/components/SwapProvidersList.vue
Labels: Bug, Ready

#3474 ui: 🎨 change toggle color
  changelog/fix-3474.md
  changelog/fix-3475.md
  changelog/fix-3485.md
  package-lock.json
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, v6

#3487 chore: 👷 add packages to exclusion for now
  package-test.js
Labels: Devop, Ready

#3477 fix: 🐛 sentry #2505736127
  changelog/fix-3477.md
  package-lock.json
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/mew-provider-class.js
Labels: Bug, Ready
