Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-07, with the labels that each got.

#3195 staked/process UI fix
  src/assets/images/currencies/eth-dark-navy.svg
  src/assets/images/icons/icon-shield-checked.svg
  src/assets/images/icons/icon-shield-crossed.svg
  src/assets/images/icons/icon-shield.svg
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/dapps/staked-dapp/components/staked-stepper/StakedCreatePasswordDialog.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepFourReview.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepThreeUpload.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepTwoGenerate.vue
Labels: Ready

#3203 V6/metamask send
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/index.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/send/ModuleSend.vue
  src/views/TheWalletView.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Devop, Ready, v6

#3192 V6/txs history UI
  src/modules/notifications/helpers/formatNotification.js
  src/modules/transfer-history/ModuleTransferHistory.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Ready, UI, v6

#3206 v6/logout-on-back
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/router/index.js
Labels: Devop, Ready, v6

#3189 V6/card blockie UI
  package-lock.json
  src/core/components/AppAddrQr.vue
  src/core/components/AppQrCode.vue
  src/core/store/global/getters.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/modules/send/components/SendLowBalanceNotice.vue
Labels: Ready, UI, v6

#3199 v6: fixes
  connections.js
  package-lock.json
  package.json
  src/core/store/external/getters.js
  src/main/sentry.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/utils.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/swap/ModuleSwap.vue
  src/utils/web3-provider/methods/utils.js
  vue.config.js
Labels: Ready, v6

#3204 devop: home send section page
  package-lock.json
  package.json
  src/modules/address-book/ModuleAddressBook.vue
  src/views/components-default/HomeFeaturesSend.vue
Labels: Ready, v6

#3216 V6/staked updates
  CHANGELOG.md
  connections.js
  package-lock.json
  package.json
  src/core/components/AppAddrQr.vue
  src/core/components/AppQrCode.vue
  src/core/router/index.js
  src/core/store/external/getters.js
  src/core/store/global/getters.js
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/dapps/staked-dapp/components/StakedStatus.vue
  src/dapps/staked-dapp/components/staked-stepper/StakedCreatePasswordDialog.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepFourReview.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepTwoGenerate.vue
  src/dapps/staked-dapp/handlers/handlerStaked.js
  src/main/sentry.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/utils.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/send/components/SendLowBalanceNotice.vue
  src/modules/swap/ModuleSwap.vue
  src/utils/web3-provider/methods/utils.js
  vue.config.js
Labels: Ready, v6

#3218 ui: add new ui for dapps features
  src/views/components-default/HomeFeaturesDapps.vue
Labels: Ready, UI, v6

#3219 fix: format balance string in address
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
Labels: Ready, v6

#3217 v6/misc-fixes
  package-lock.json
  package.json
  src/app.vue
  src/modules/balance/ModuleBalance.vue
Labels: Devop, Ready, v6

#3194 v6/ui: add renames and text changes for body header etc
  package.json
  src/dapps/DAPP_INTEGRATION.md
  src/modules/access-wallet/ModuleAccessWalletMobile.vue
  src/modules/confirmation/components/ConfirmWithWallet.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
  src/translations/dapps-submission/en_US.json
  src/translations/dapps-submission/es_ES.json
  src/translations/dapps-submission/ja_JP.json
  src/translations/dapps-submission/ko_KR.json
  src/translations/dapps-submission/ru_RU.json
  src/translations/dapps-submission/zh_CN.json
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/translations/home/en_US.json
  src/translations/home/es_ES.json
  src/translations/home/ja_JP.json
  src/translations/home/ko_KR.json
  src/translations/home/ru_RU.json
  src/translations/home/zh_CN.json
  src/translations/interface/en_US.json
  src/translations/mew-cx/en_US.json
  src/translations/mew-cx/es_ES.json
  src/translations/mew-cx/ja_JP.json
  src/translations/mew-cx/ko_KR.json
  src/translations/mew-cx/ru_RU.json
  src/translations/mew-cx/zh_CN.json
  src/views/components-default/HomeFeatures.vue
  src/views/components-default/HomeWhyMew.vue
  src/views/components-default/HowItWorksDappsCenter.vue
  src/views/components-default/HowItWorksMore.vue
  src/views/components-default/HowItWorksSend.vue
  src/views/components-default/HowItWorksSwap.vue
  src/views/components-default/HowItWorksTokens.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-default/TheHowItWorksLayout.vue
Labels: Ready, UI, v6

#3220 v6/ui: make hardware wallets open in new tab and dapps route fix
  package.json
  src/core/components/AppCarousel.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, UI, v6

#3207 V6/fixes network
  src/assets/images/networks/eth.svg
  src/assets/images/networks/matic.svg
  src/assets/images/networks/network.svg
  src/core/components/AppNetworkFee.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletNetworkAddresses.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send/ModuleSend.vue
  src/modules/send/components/SendLowBalanceNotice.vue
  src/modules/swap/ModuleSwap.vue
  src/utils/networks/types/GOERLI.js
  src/utils/networks/types/KOV.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/RIN.js
  src/utils/networks/types/ROP.js
Labels: Devop, Ready, v6

#3202 V6/Add additional changes to the UI
  src/core/components/AppNetworkFee.vue
  src/core/components/AppNetworkSettingsModal.vue
  src/modules/access-wallet/ModuleAccessWalletMobile.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/access-wallet/hardware/components/AccessWalletNetworkAddresses.vue
  src/modules/access-wallet/hardware/components/AccessWalletPaths.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/message/ModuleMessageSign.vue
  src/modules/message/ModuleMessageVerify.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/settings/components/SettingsImportConfig.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapMsgStoreBtcEth.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/translations/access-wallet/en_US.json
  src/translations/interface/en_US.json
  src/translations/interface/es_ES.json
  src/translations/interface/ja_JP.json
  src/translations/interface/ko_KR.json
  src/translations/interface/zh_CN.json
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
Labels: Ready, UI, v6

#3193 V6/more UI text changes
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
Labels: Ready, UI, v6

#3223 V6/remove links and add community bar
  src/assets/images/icons/socials/facebook.png
  src/assets/images/icons/socials/github.png
  src/assets/images/icons/socials/instagram.png
  src/assets/images/icons/socials/medium.png
  src/assets/images/icons/socials/mewtopia.png
  src/assets/images/icons/socials/reddit.png
  src/assets/images/icons/socials/telegram.png
  src/assets/images/icons/socials/twitter.png
  src/assets/images/icons/socials/vkontakte.png
  src/assets/images/icons/socials/youtube.png
  src/views/components-default/HomeSocials.vue
  src/views/components-default/HomeWhyMew.vue
  src/views/layouts-default/TheHomeLayout.vue
Labels: Ready, UI, v6

#3197 v5: prep v5 for v6 release
  .github/workflows/add-to-codecov.yml
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/build-cx-generate-zip.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/github-release.yml
  .github/workflows/run-on-pr.yml
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/containers/HeaderContainer/HeaderContainer.vue
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.scss
  src/containers/HeaderContainer/components/MobileMenu/MobileMenu.vue
Labels: Ready, Release, v5

#3198 v6/txt-records-and-multicoin-issue
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/manage/ManageMulticoins.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTxtRecords.vue
  src/dapps/ens-manager-dapp/components/manage/ManageUploadWebsite.vue
  src/dapps/ens-manager-dapp/handlers/handlerEnsManager.js
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
Labels: Devop, Ready, v6

#3208 V6/staked add divider under stepper
  package-lock.json
  package.json
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/dapps/staked-dapp/components/StakedStatus.vue
  src/dapps/staked-dapp/components/staked-stepper/StakedCreatePasswordDialog.vue
  src/dapps/staked-dapp/components/staked-stepper/StakedStepper.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepFourReview.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepThreeUpload.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepTwoGenerate.vue
  src/dapps/staked-dapp/handlers/handlerStaked.js
Labels: Ready, v6

#3227 bug/readme
  CHANGELOG.md
  README.md
  package-lock.json
  src/assets/images/backgrounds/v6-landing-screen-shot.png
  src/assets/images/temp/cryptokitties1.svg
  src/assets/images/temp/cryptokitties2.svg
  src/assets/images/temp/cryptokitties3.svg
  src/assets/images/temp/qr.png
Labels: Devop, Ready, v6

#3184 V6/add telegram link to the footer
  CHANGELOG.md
  src/assets/images/icons/icon-telegram-circle.svg
  src/assets/images/icons/icon-telegram.svg
  src/views/components-default/TheDefaultFooter.vue
Labels: Ready, v6

#3187 V6/fix my eth balance layout
  package-lock.json
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/tools/components/ToolsTableContainer.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
Labels: Ready, UI, v6

#3226 Fix/v6 workflows
  .github/workflows/add-to-codecov.yml
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/add-to-v6-develop.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/github-release.yml
  .github/workflows/run-on-pr.yml
  .husky/prepare-commit-msg
  CHANGELOG-V5.md
  CHANGELOG.md
  ENV_VARS.js
  package-audit.js
  package-lock.json
  package.json
  vue.config.js
Labels: Ready, v6

#3228 Bug/header dropdown
  package-lock.json
  src/components/mew-tools/MewTools.vue
Labels: Bug, Ready, UI, v6

#3224 v6/graphic-changes-ui
  src/assets/images/icons/button-app-store.svg
  src/assets/images/icons/button-play-store.svg
  src/assets/images/snippets/my-tokens-table.svg
  src/assets/images/snippets/send-tx-page.png
  src/assets/images/snippets/swap-page.png
  src/assets/styles/GlobalStyles.scss
  src/core/components/AppCarousel.vue
  src/core/components/AppGetStarted.vue
  src/modules/access-wallet/hardware/components/AccessWalletQrCode.vue
  src/views/components-default/HowItWorksSend.vue
  src/views/components-default/HowItWorksTokens.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
Labels: Ready, UI, v6

#3230 UI/add partners
  package-lock.json
  src/assets/images/partners/1inchdark.png
  src/assets/images/partners/dexag.png
  src/assets/styles/GlobalStyles.scss
  src/core/components/AppPartnersBlock.vue
Labels: Ready, UI, v6

#3170 V6/swap mewwallet
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/snippets/new-dapps-page.png
  src/core/components/AppNetworkFee.vue
  src/core/components/AppNetworkSettingsModal.vue
  src/core/store/wallet/actions.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/HDWalletInterface.js
  src/modules/access-wallet/common/WalletErrorHandler.js
  src/modules/access-wallet/common/WalletInterface.js
  src/modules/access-wallet/hardware/handlers/hardwares/bcvault/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bcvault/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/access-wallet/hybrid/handlers/MEWconnect/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/MEWconnect/index.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/access-wallet/hybrid/handlers/walletInterface.js
  src/modules/access-wallet/software/handlers/mnemonic/index.js
  src/modules/access-wallet/software/handlers/web3wallet/index.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmWithWallet.vue
  src/modules/confirmation/components/ConfirmationSwapTransactionDetails.vue
  src/modules/name-resolver/tests/name-resolver.spec.js
  src/modules/notifications/ModuleNotifications.vue
  src/modules/settings/handler/gasPriceMixin.js
  src/modules/swap/ModuleSwap.vue
  src/utils/web3-provider/methods/eth_getTransactionCount.js
  src/views/TheWalletView.vue
  src/views/components-default/HomeFeatures.vue
  src/views/components-default/HomeFeaturesTokens.vue
  src/views/components-default/HomeSocials.vue
  src/views/components-default/HomeWhyMew.vue
  src/views/components-default/HowItWorksDappsCenter.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Devop, Ready

#3232 Feat/welcome modal
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/WelcomeModal/WelcomeModal.vue
  src/translations/welcome-message/en_US.json
Labels: Ready, UI, v5

#3231 Bug/routing
  CHANGELOG.md
  package-lock.json
  src/core/router/index.js
  src/core/router/routes-default.js
  src/core/router/routes-wallet.js
  src/dapps/aave-dapp/metainfo.js
  src/dapps/ens-manager-dapp/metainfo.js
  src/dapps/routes-dapps.js
  src/dapps/staked-dapp/metainfo.js
  src/dapps/unstoppable-domains-dapp/metainfo.js
  src/modules/balance/ModuleBalance.vue
  src/modules/notifications/ModuleNotifications.vue
Labels: Bug, Ready, v6

#3233 Feat/team page
  CHANGELOG.md
  package-lock.json
  src/assets/images/team/doggie.jpg
  src/assets/images/team/jessica.jpg
  src/assets/images/team/placeholder.jpg
  src/views/layouts-default/TheTeamLayout.vue
Labels: Ready, UI, v6

#3234 Bug/fix invalid values for swap amount
  package-lock.json
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/handlerSwap.js
Labels: Bug, Ready, UI

#3236 v6: last minute fixes
  CHANGELOG.md
  fetchLists/index.js
  package-lock.json
  src/core/components/AppPartnersBlock.vue
  src/core/store/configs.js
  src/core/store/external/getters.js
  src/core/store/global/getters.js
  src/core/store/global/mutations.js
  src/core/store/notifications/mutations.js
  src/core/store/wallet/actions.js
  src/modules/access-wallet/hybrid/handlers/MEWconnect/index.js
  src/modules/name-resolver/tests/name-resolver.spec.js
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/handlers/handlerNotification.mixin.js
  src/modules/swap/ModuleSwap.vue
  src/views/TheWalletView.vue
Labels: Ready, v6

#3245 fix: 🐛 sentry sourcemaps
  CHANGELOG.md
  devmoji.config.js
  package-lock.json
  package.json
  src/modules/name-resolver/tests/name-resolver.spec.js
  vue.config.js
Labels: Ready, v6

#3243 ui: 🎨 get latest prices for hardware wallets
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
Labels: Ready, UI, v6

#3246 ui: 🎨 replace team photo
  .github/workflows/deploy-live.yml
  CHANGELOG.md
  package-lock.json
  src/assets/images/team/doggie.jpg
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepFourReview.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepThreeUpload.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepTwoGenerate.vue
Labels: Ready, UI, v6

#3239 fix: 🐛 show private key in print
  CHANGELOG.md
  package-lock.json
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/views/TheWalletView.vue
Labels: Bug, Ready

#3248 fix: 🐛 add price change percentage
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/balance/ModuleBalance.vue
Labels: Bug, Ready, UI, v6

#3251 fix: 🐛 contract interaction
  CHANGELOG.md
  src/modules/contract/ModuleContractInteract.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready, v6

#3249 devop: 🔧 prep for upcoming release
  CHANGELOG.md
  checkBranch.sh
  package-lock.json
  package.json
Labels: Devop, Ready

#3253 Release: v6.0.1
  CHANGELOG.md
  checkBranch.sh
  devmoji.config.js
  package-lock.json
  package.json
  src/assets/images/team/doggie.jpg
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepFourReview.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepThreeUpload.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepTwoGenerate.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/name-resolver/tests/name-resolver.spec.js
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/views/TheWalletView.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
  vue.config.js
Labels: Ready, Release

#3240 fix: 🐛 prefilled swap
  CHANGELOG.md
  checkBranch.sh
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready

#3254 devop: 🔧 remove reference to master
  CHANGELOG.md
Labels: Devop, Ready

#3241 fix: 🐛 software routing
  CHANGELOG.md
  src/modules/create-wallet/ModuleCreateWalletSoftware.vue
  src/modules/swap/handlers/providers/mew-provider-class.js
Labels: Bug, Ready

#3259 devop: 🔧 add check if data exists
  CHANGELOG.md
  package-lock.json
  src/modules/notifications/handlers/handlerNotification.mixin.js
Labels: Bug, Ready

#3260 fix: 🐛 use network getter instead of currentNetwork
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/store/global/getters.js
Labels: Bug, Ready

#3273 fix: 🐛 null error
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/settings/ModuleSettings.vue
Labels: Bug, Ready

#3258 fix: 🐛 'change route from watch to verify' and 'fix tools layout'
  CHANGELOG.md
  package.json
  src/modules/message/ModuleMessageVerify.vue
  src/translations/sign-message/en_US.json
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/layouts-default/TheToolsLayout.vue
Labels: Bug, Ready, v6

#3257 devop: 🔧 use v6 mewbuilds
  .github/workflows/add-to-mewbuilds.yml
  CHANGELOG.md
  CODEOWNERS
  checkBranch.sh
  commitlint.config.js
  devmoji.config.js
  package-lock.json
  package-test.js
  package.json
  vue.config.js
Labels: Devop, Ready

#3261 fix: 🐛 nft send button disable if emnpty or invalid address
  CHANGELOG.md
  package-lock.json
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/nft-manager/components/NftManagerSend.vue
  src/modules/nft-manager/handlers/handlerNftManager.js
Labels: Bug, Ready

#3263 fix: 🐛 contract button size
  CHANGELOG.md
  src/modules/contract/ModuleContractDeploy.vue
  src/modules/contract/ModuleContractInteract.vue
Labels: Ready, UI, v6

#3242 fix: 🐛 apollo pending error
  CHANGELOG.md
  src/core/helpers/createApolloClient.js
  src/modules/balance/handlers/handlerBalanceHistory.mixin.js
Labels: Bug, Ready, v6

#3280 fix: 🐛 invalid type notification err message
  CHANGELOG.md
  package-lock.json
  src/modules/notifications/handlers/handlerNotification.js
Labels: Bug, Devop, Ready

#3277 fix: 🐛 check whether connection exists
  CHANGELOG.md
  package-lock.json
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
Labels: Bug, Ready

#3262 fix: 🐛 all duplicate routes
  CHANGELOG.md
  package-lock.json
  src/core/router/index.js
  src/main.js
Labels: Bug, Devop, Ready

#3271 fix: 🐛 wallet change error
  CHANGELOG.md
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
Labels: Bug, Ready

#3265 fix: 🐛 text overflow hd balance
  CHANGELOG.md
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
Labels: Bug, Ready, UI

#3282 fix: 🐛 to addr when transferring tkn
  CHANGELOG.md
  src/modules/confirmation/ModuleConfirmation.vue
Labels: Bug, Ready, v6

#3269 fix: 🐛 reset is not a function
  CHANGELOG.md
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
Labels: Bug, Ready, v6

#3276 fix: 🐛 handle reported toLowerCase issues in sentry
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/store/external/getters.js
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/swap/ModuleSwap.vue
  src/views/TheWalletView.vue
Labels: Bug, Ready

#3286 chore: 👷 update package
  package-lock.json
  package.json
Labels: Devop, Ready

#3287 fix: 🐛 remove functional for now
  CHANGELOG.md
  src/modules/decision-tree/components/MdContainer/MdContainer.vue
Labels: Bug, Ready

#3296 ui: 🎨 fix footer hiding content
  CHANGELOG.md
  package-lock.json
  package.json
  src/views/components-wallet/TheWalletFooter.vue
Labels: Ready, UI, v6

#3295 feat: ✨ mew wallet banner
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/snippets/snippet-mew-wallet-confetti.png
  src/views/TheDefaultView.vue
  src/views/components-default/TheDefaultWalletBanner.vue
Labels: Feature, Ready

#3302 fix: 🐛 mew notification
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/notifications/ModuleNotifications.vue
  src/modules/transfer-history/ModuleTransferHistory.vue
Labels: Bug, Ready

#3300 release: v6.0.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/snippets/snippet-mew-wallet-confetti.png
  src/modules/notifications/ModuleNotifications.vue
  src/modules/transfer-history/ModuleTransferHistory.vue
  src/views/TheDefaultView.vue
  src/views/components-default/TheDefaultWalletBanner.vue
  src/views/components-wallet/TheWalletFooter.vue
Labels: Ready, Release

#3266 v5:fix: 🐛 various issues
  CHANGELOG.md
  fetchLists/index.js
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/containers/ConfirmationContainer/ConfirmationContainer.vue
  src/containers/ConfirmationContainer/components/ConfirmModal/ConfirmModal.vue
  src/helpers/parseTokensData.js
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout-desktop.scss
  src/layouts/InterfaceLayout/InterfaceLayout-mobile.scss
  src/layouts/InterfaceLayout/InterfaceLayout-tablet.scss
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/networks/types/MINTME.js
  src/wallets/hybrid/WalletLink/index.js
  vueConfig/connections.js
Labels: Bug, Ready, v5

#3304 fix: 🐛 add scoped to wallet banner scss
  CHANGELOG.md
  package-lock.json
  package.json
  src/views/components-default/TheDefaultWalletBanner.vue
Labels: Hotfix, Ready, v6

#3306 release: v6.0.3-hotfix.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/views/components-default/TheDefaultWalletBanner.vue
Labels: Ready, Release

#3293 fix: 🐛 givenProvider.request_ is not a function
  CHANGELOG.md
  jest.config.js
  package-lock.json
  package.json
  src/core/store/wallet/actions.js
  src/modules/name-resolver/tests/name-resolver.spec.js
  src/utils/web3-provider/providers/given-provider.js
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Ready, v6

#3292 fix: 🐛 balance error message
  CHANGELOG.md
  src/modules/balance/handlers/handlerBalanceHistory.mixin.js
Labels: Bug, Ready, v6

#3299 fix: 🐛 wallet undefined when catching error
  CHANGELOG.md
  package-lock.json
  package-test.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
Labels: Bug, Ready

#3305 fix: 🐛 add swap to eth token
  CHANGELOG.md
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/configs/configTrendingTokens.js
Labels: Bug, Ready

#3291 fix: 🐛 import routes
  CHANGELOG.md
  package.json
  src/views/components-default/HomeFeaturesSwap.vue
  src/views/components-default/HomeFeaturesTokens.vue
Labels: Bug, Ready

#3311 feat: ✨ refresh icon
  CHANGELOG.md
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/send/ModuleSend.vue
Labels: Feature, Ready

#3317 fix: 🐛 hide language select
  CHANGELOG.md
  src/views/components-wallet/TheWalletFooter.vue
Labels: Ready, UI

#3312 fix: 🐛 polygon gas issue
  CHANGELOG.md
  package-lock.json
  src/modules/settings/handler/gasPriceMixin.js
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/utils/networks/types/ETC.js
  src/utils/networks/types/ETH.js
  src/utils/networks/types/GOERLI.js
  src/utils/networks/types/KOV.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/RIN.js
  src/utils/networks/types/ROP.js
  src/views/TheWalletView.vue
Labels: Ready, v6

#3308 fix: 🐛 wallet header overlapping issue on mobile
  CHANGELOG.md
  src/app.vue
  src/views/TheDefaultView.vue
  src/views/TheWalletView.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-wallet/TheWalletHeader.vue
Labels: Ready, UI, v6

#3337 Fix/tx history layout
  package.json
  src/modules/transfer-history/ModuleTransferHistory.vue
Labels: Bug, UI, v6

#3318 fix: 🐛 add catch on walletconnect and walletlink
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/errorHandler.js
Labels: Bug, Ready

#3315 devop: 🔧 use swaplink on all active ccswap link
  CHANGELOG.md
  src/core/components/AppNetworkFee.vue
  src/modules/balance/components/BalanceEmptyBlock.vue
  src/modules/send/ModuleSend.vue
  src/modules/send/components/SendLowBalanceNotice.vue
  src/modules/swap/ModuleSwap.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready

#3285 fix: 🐛 sanitize hex utils / user lock logout
  CHANGELOG.md
  src/modules/access-wallet/common/utils.js
Labels: Bug, Ready

#3314 fix: 🐛 select rate and checkbox
  CHANGELOG.md
  src/modules/swap/components/SwapProvidersList.vue
Labels: Bug, Ready, UI

#3310 feat: ✨ remove quick help
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.vue
  src/modules/decision-tree/DecisionTree.scss
  src/modules/decision-tree/ModuleDecisionTree.vue
  src/modules/decision-tree/components/MdContainer/MdContainer.scss
  src/modules/decision-tree/components/MdContainer/MdContainer.vue
  src/modules/decision-tree/data/MDIndex.js
  src/modules/decision-tree/data/md/_Access_Ledger.md
  src/modules/decision-tree/data/md/_Access_Trezor.md
  src/modules/decision-tree/data/md/_Access_file.md
  src/modules/decision-tree/data/md/_Access_key.md
  src/modules/decision-tree/data/md/_Access_other.md
  src/modules/decision-tree/data/md/_Access_phrase.md
  src/modules/decision-tree/data/md/_Cant_scan_access.md
  src/modules/decision-tree/data/md/_Different_address.md
  src/modules/decision-tree/data/md/_Find_CX.md
  src/modules/decision-tree/data/md/_Find_Ledger.md
  src/modules/decision-tree/data/md/_Find_MEWconnect.md
  src/modules/decision-tree/data/md/_Find_MEWwallet.md
  src/modules/decision-tree/data/md/_Find_MM.md
  src/modules/decision-tree/data/md/_Find_Trezor.md
  src/modules/decision-tree/data/md/_Find_file.md
  src/modules/decision-tree/data/md/_Find_key.md
  src/modules/decision-tree/data/md/_Find_other.md
  src/modules/decision-tree/data/md/_Forgot_pass_access.md
  src/modules/decision-tree/data/md/_Forgot_pin_access.md
  src/modules/decision-tree/data/md/_Funds_network.md
  src/modules/decision-tree/data/md/_Given_hash.md
  src/modules/decision-tree/data/md/_No_hash.md
  src/modules/decision-tree/data/md/_Notgiven_hash.md
  src/modules/decision-tree/data/md/_Recognize_address.md
  src/modules/decision-tree/data/md/_Saved_hash.md
  src/modules/decision-tree/data/md/_Tokens_custom.md
  src/modules/decision-tree/data/md/_Using_CX_access.md
  src/modules/decision-tree/data/md/_Using_MM_access.md
  src/modules/decision-tree/data/md/_bity.md
  src/modules/decision-tree/data/md/_buy_bug.md
  src/modules/decision-tree/data/md/_changelly.md
  src/modules/decision-tree/data/md/_created_on_MEW.md
  src/modules/decision-tree/data/md/_created_other.md
  src/modules/decision-tree/data/md/_dapp_MakerDAO.md
  src/modules/decision-tree/data/md/_dapp_other.md
  src/modules/decision-tree/data/md/_kyber.md
  src/modules/decision-tree/data/md/_not_listed.md
  src/modules/decision-tree/data/md/_simplex.md
  src/modules/decision-tree/data/md/_suggestions.md
  src/modules/decision-tree/data/md/_swap_error.md
  src/modules/decision-tree/data/md/_tx_bug.md
  src/modules/decision-tree/data/md/_tx_error.md
  src/modules/decision-tree/data/md/_tx_other.md
  src/translations/common/en_US.json
Labels: Feature, Ready, v6

#3290 fix: 🐛 disableNext button on swap
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/store/global/getters.js
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready

#3321 fix: 🐛 remove set IPFS button while processing file
  CHANGELOG.md
  package-lock.json
  src/dapps/ens-manager-dapp/components/manage/ManageUploadWebsite.vue
Labels: Bug, Ready, v6

#3344 devop: 🔧 only require mew component updates when it's not in beta
  CHANGELOG.md
  package-lock.json
  package-test.js
Labels: Devop, Ready

#3320 fix: 🐛 verify message layout
  CHANGELOG.md
  src/modules/message/ModuleMessageVerify.vue
Labels: Ready, UI, v6

#3323 fix: 🐛 tx confirmation mew help center link
  CHANGELOG.md
  src/modules/confirmation/ModuleConfirmation.vue
Labels: Bug, Ready, v6

#3335 fix: 🐛 tx confirmation layout
  CHANGELOG.md
  src/core/components/AppModal.vue
Labels: Ready, UI, v6

#3343 fix: 🐛 transaction confirmation total with fee
  CHANGELOG.md
  src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
Labels: Bug, Ready, UI

#3336 devop: 🔧 create a way to avoid changelog conflicts
  .devcontainer.json
  .github/workflows/add-to-codecov.yml
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/github-release.yml
  .github/workflows/run-on-pr.yml
  CHANGELOG.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  changelog/.gitkeep
  changelog/devop-3336.md
  connections.js
  package-lock.json
  prepChangelog.js
Labels: Devop, Ready

#3348 devop: changelog validator
  .github/workflows/generate-changelog.yml
  .github/workflows/validate-changelog.yml
  CHANGELOG.md
  changelog/devop-3348.md
  prepChangelog.js
  validateChangelog.js
Labels: Ready, v6

#3345 devop: remove remaining decision tree parts from quickhelp
  changelog/devop-3345.md
  src/app.vue
  src/translations/common/es_ES.json
  src/translations/common/ja_JP.json
  src/translations/common/ko_KR.json
  src/translations/common/ru_RU.json
  src/translations/common/zh_CN.json
Labels: Devop, Ready

#3298 fix: 🐛 sentry issue 2507823347
  changelog/fix-3298.md
  package-lock.json
  package.json
  src/utils/web3-provider/providers/ws-provider.js
Labels: Bug, Ready

#3353 ui: 🎨 change refresh icon colors
  changelog/fix-3353.md
  src/modules/balance/ModuleBalanceCard.vue
Labels: Ready, UI

#3352 chore: 👷 updaate unstoppable
  changelog/devop-3352.md
  connections.js
  package-lock.json
  package-test.js
  package.json
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/name-resolver/index.js
  src/modules/name-resolver/resolvers/ens.js
  src/modules/name-resolver/resolvers/uns.js
  src/modules/name-resolver/tests/name-resolver.spec.js
Labels: Devop, Ready
