Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-03, with the labels that each got.

#2861 V6/refactor dashboard
  package-lock.json
  package.json
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/handlers/handlerBalance.js
  src/views/layouts-wallet/TheDashboardLayout.vue
Labels: Ready, v6

#2863 V6/UI wallet layouts with slots
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.vue
  src/assets/styles/GlobalStyles.scss
  src/core/components/TheLayoutWalletGrid.vue
  src/views/TheDefaultView.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletFooter.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/layouts-wallet/TheDashboardLayout.vue
  src/views/layouts-wallet/TheDeployContractLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
  src/views/layouts-wallet/TheNFTManagerLayout.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
Labels: Devop, Ready, v6

#2867 devop: add workflow to set v6 develop domain
  .github/workflows/add-to-v6-develop.yml
  package-lock.json
  package.json
Labels: Devop, Ready, v6

#2868 devop: rename TheLayoutWalletGrid to TheWrapperWallet
  src/core/components/TheWrapperWallet.vue
  src/views/layouts-wallet/TheDashboardLayout.vue
  src/views/layouts-wallet/TheDeployContractLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
  src/views/layouts-wallet/TheNFTManagerLayout.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
Labels: Ready, v6

#2857 Devop/revert resolutions
  package-lock.json
  package.json
Labels: Devop, Ready

#2855 Merge pull request #2854 from MyEtherWallet/develop
  package-lock.json
  package.json
Labels: Devop, Ready, v5

#2864 Bug/coolwallet
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/Staked/components/ExitedPopup/ExitedPopup.scss
  src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/scss/GlobalVariables.scss
  src/translations/errors-coolwallet/en_US.json
  src/wallets/hardware/coolwallet/errorHandler.js
  src/wallets/hardware/coolwallet/index.js
Labels: Bug, Ready

#2872 Bug/aug
  CHANGELOG.md
  LICENSE
  README.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/translations/access-wallet/en_US.json
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ja_JP.json
  src/translations/access-wallet/ko_KR.json
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
Labels: Bug, Ready

#2873 release/v5.7.22
  CHANGELOG.md
  LICENSE
  README.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/Staked/components/ExitedPopup/ExitedPopup.scss
  src/layouts/AccessWalletLayout/components/HardwarePasswordModal/HardwarePasswordModal.vue
  src/layouts/AccessWalletLayout/components/NetworkAndAddressModal/NetworkAndAddressModal.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.scss
  src/scss/GlobalVariables.scss
  src/translations/access-wallet/en_US.json
  src/translations/access-wallet/es_ES.json
  src/translations/access-wallet/ja_JP.json
  src/translations/access-wallet/ko_KR.json
  src/translations/errors-coolwallet/en_US.json
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/ru_RU.json
  src/translations/footer/zh_CN.json
  src/wallets/hardware/coolwallet/errorHandler.js
  src/wallets/hardware/coolwallet/index.js
Labels: Ready, Release

#2869 devop: add in wrapper dapp
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/components/TheWrapperDapp.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
Labels: Ready, v6

#2860 V6/notifications
  CHANGELOG.md
  connections.js
  package-lock.json
  package.json
  src/apollo/queries/notifications/index.js
  src/apollo/queries/notifications/notification.graphql
  src/core/components/AppSwap.vue
  src/core/helpers/parseTokenData.js
  src/core/helpers/timeAgo.js
  src/core/store/configs.js
  src/core/store/external/state.js
  src/core/store/global/actions.js
  src/core/store/global/getters.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/core/store/index.js
  src/core/store/notifications/actions.js
  src/core/store/notifications/getters.js
  src/core/store/notifications/index.js
  src/core/store/notifications/mutations.js
  src/core/store/notifications/state.js
  src/main.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/TransactionBalance.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/components/blockieWithCurrency/BlockieWithCurrency.vue
  src/modules/notifications/components/in/In.vue
  src/modules/notifications/components/out/Out.vue
  src/modules/notifications/components/swap/Swap.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/send/ModuleSend.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/settings/components/SettingsExportConfig.vue
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/settings/components/SettingsImportConfig.vue
  src/modules/settings/handler/handlerSettings.js
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/dex-ag.js
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/modules/swap/handlers/providers/one-inch.js
  src/modules/wallets/pages/access/Access.vue
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Ready, v6

#2835 V6/settings
  CHANGELOG.md
  package-lock.json
  src/core/store/global/getters.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/modules/send/ModuleSend.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/settings/handler/handlerSettings.js
  src/views/TheWalletView.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Ready, v6

#2865 V6/refactor address book
  package-lock.json
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/address-book/modules/ModuleAddressBook.vue
  src/modules/send/ModuleSend.vue
  src/modules/settings/ModuleSettings.vue
Labels: Ready, v6

#2871 V6/update swap provider list
  CHANGELOG.md
  src/core/plugins/vuetify.js
  src/modules/swap/ModuleSwap.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Ready, v6

#2878 Devop/update packages
  package-lock.json
  package.json
Labels: Devop, Ready

#2883 Devop/consolidate node prs
  CHANGELOG.md
  src/assets/images/networks/avax-c.svg
  src/networks/nodes/avax-c-mainnet.js
  src/networks/nodes/avax-c-testnet.js
  src/networks/nodes/index.js
  src/networks/nodes/xdai.js
  src/networks/types/AVAX.js
  src/networks/types/AVAXTEST.js
  src/networks/types/XDAI.js
  src/networks/types/index.js
  src/wallets/bip44/ledgerPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
  src/wallets/hardware/ledger/appPaths.js
  vueConfig/connections.js
Labels: Devop, Ready

#2879 fix gas check bypass for from non ETH currency
  CHANGELOG.md
  package-lock.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
Labels: Bug, Ready, v5

#2892 Bug/remove no balance tokens
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/InterfaceLayout.vue
Labels: Bug, Ready

#2888 Devop/update packages
  CHANGELOG.md
  package-lock.json
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
Labels: Devop, Ready

#2893 devop: change the way we are checking lend balance
  CHANGELOG.md
  package-lock.json
  src/dapps/LendMigrator/LendMigrator.vue
Labels: Devop, Ready, v5

#2887 release/v5.7.23
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/assets/images/networks/avax-c.svg
  src/dapps/LendMigrator/LendMigrator.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/SwapContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/SwapSendToModal/SwapSendToModal.vue
  src/networks/nodes/avax-c-mainnet.js
  src/networks/nodes/avax-c-testnet.js
  src/networks/nodes/index.js
  src/networks/nodes/xdai.js
  src/networks/types/AVAX.js
  src/networks/types/AVAXTEST.js
  src/networks/types/XDAI.js
  src/networks/types/index.js
  src/partners/partners.js
  src/translations/access-wallet/ru_RU.json
  src/translations/access-wallet/zh_CN.json
  src/translations/dapps-staked/es_ES.json
  src/translations/dapps-staked/ja_JP.json
  src/translations/dapps-staked/ko_KR.json
  src/translations/dapps-staked/ru_RU.json
  src/translations/dapps-staked/zh_CN.json
  src/translations/errors-coolwallet/es_ES.json
  src/translations/errors-coolwallet/ja_JP.json
  src/translations/errors-coolwallet/ko_KR.json
  src/translations/errors-coolwallet/ru_RU.json
  src/translations/errors-coolwallet/zh_CN.json
  src/translations/swap/es_ES.json
  src/translations/swap/ja_JP.json
  src/translations/swap/ko_KR.json
  src/translations/swap/ru_RU.json
  src/translations/swap/zh_CN.json
  src/wallets/bip44/ledgerPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
  src/wallets/hardware/ledger/appPaths.js
  vueConfig/connections.js
Labels: Ready, Release

#2894 fix weird issue with token symbols and balance with waay too long of …
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Ready, Release

#2895 V6/wallet mobile header
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/icon-menu.svg
  src/assets/styles/GlobalStyles.scss
  src/core/components/AppBtnMenu.vue
  src/core/plugins/vuetify.js
  src/modules/notifications/ModuleNotifications.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready, v6

#2890 V6/fix no balance block
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/components/BalanceEmptyBlock.vue
Labels: Devop, Ready, v6

#2898 V6/move tokens to state
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/store/wallet/actions.js
  src/core/store/wallet/getters.js
  src/core/store/wallet/mutations.js
  src/core/store/wallet/state.js
  src/modules/balance/ModuleTokens.vue
  src/modules/send/ModuleSend.vue
  src/views/TheWalletView.vue
Labels: Devop, Ready

#2904 Bug/token values
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
Labels: Bug, Ready

#2905 Bug/ledger paths
  CHANGELOG.md
  src/layouts/AccessWalletLayout/components/LedgerAppModal/LedgerAppModal.scss
Labels: Bug, Ready

#2907 add check before passing 0x to bignumber lib
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/AccessWalletLayout/components/LedgerAppModal/LedgerAppModal.scss
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#2916 V6/UI fix merge
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  CHANGELOG.md
  configs.js
  fetchLists/index.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/styles/GlobalStyles.scss
  src/components/menu-mobile/Menu.vue
  src/core/components/AppBtnMenu.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/handlers/handlerCreateWallet.js
  src/translations/interface/en_US.json
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
Labels: Ready, v6

#2891 V6/nfts
  .bash_profile
  CHANGELOG.md
  connections.js
  package-lock.json
  package.json
  src/apollo/queries/tokens721/index.js
  src/apollo/queries/tokens721/tokens721.graphql
  src/core/components/TheWrapperDapp.vue
  src/dapps/aave-dapp/Aave.vue
  src/dapps/ambrpay-dapp/TheAmbrpayLayout.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/makerdao/MakerDAO.vue
  src/dapps/unstoppable-domains/UnstoppableDomain.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/nft-manager/components/NftManagerDetails.vue
  src/modules/nft-manager/components/NftManagerSend.vue
  src/modules/nft-manager/handlers/abi/abiNft.js
  src/modules/nft-manager/handlers/config/configNft.js
  src/modules/nft-manager/handlers/handlerApi.js
  src/modules/nft-manager/handlers/handlerNftCollection.js
  src/modules/nft-manager/handlers/handlerNftInit.js
  src/modules/nft-manager/handlers/handlerNftManager.js
  src/modules/nft-manager/handlers/handlerSend.js
  src/translations/common/en_US.json
  src/views/TheWalletView.vue
  src/views/components-default/HomeFeatures.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/layouts-default/TheHowItWorksLayout.vue
  src/views/layouts-default/TheToolsLayout.vue
  src/views/layouts-wallet/TheNFTManagerLayout.vue
  vue.config.js
Labels: Ready, v6

#2915 updating module token
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/balance/ModuleTokens.vue
Labels: Ready, v6

#2923 devop: fix settings overlay and confirmation tx overlay
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationTransaction.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/settings/components/SettingsExportConfig.vue
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/settings/components/SettingsImportConfig.vue
Labels: Ready, v6

#2930 Bug/send offline
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#2931 release/v5.7.25
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Ready, Release

#2934 V6/feature add mewconnect
  .bash_profile
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/core/plugins/vuetify.js
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/utils/web3-provider/methods/eth_signTransaction.js
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Feature, Ready, v6

#2933 V6/aave table
  package-lock.json
  package.json
  src/dapps/aave-dapp/Aave.vue
  src/dapps/aave-dapp/components/AaveAmountForm.vue
  src/dapps/aave-dapp/components/AaveTable.vue
  src/dapps/aave-dapp/handlers/handlerAave.js
  src/dapps/aave-dapp/handlers/helpers.js
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/views/TheDefaultView.vue
Labels: Feature, v6

#2819 v6/interact with contract
  package-lock.json
  package.json
  src/core/helpers/common.js
  src/core/store/global/actions.js
  src/core/store/global/getters.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/modules/contract/ModuleContractDeploy.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/contract/handlers/common.js
  src/modules/contract/handlers/solidityTypes.js
  src/modules/name-resolver/resolvers/cns.js
  src/views/layouts-wallet/TheDeployContractLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
Labels: Devop, Feature, Ready, v6

#2949 V6/hide switch button and update side menu item
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package.json
  src/modules/balance/ModuleBalanceCard.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, v6

#2943 V6/fix access wallet btn font size
  CHANGELOG.md
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Ready, v6

#2950 fix: logout
  CHANGELOG.md
  package-audit.js
  package-lock.json
  src/core/store/configs.js
  src/core/store/global/state.js
  src/core/store/wallet/actions.js
  src/core/store/wallet/mutations.js
  src/utils/web3-provider/events.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Bug, Ready, v6

#2924 V6/fix-get-started-block
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/core/components/AppGetStarted.vue
Labels: Ready, v6

#2925 V6/update how it works layout
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/views/components-default/HowItWorksDappsCenter.vue
  src/views/components-default/HowItWorksMore.vue
  src/views/components-default/HowItWorksSend.vue
  src/views/components-default/HowItWorksSwap.vue
  src/views/components-default/HowItWorksTokens.vue
  src/views/layouts-default/TheHowItWorksLayout.vue
Labels: Ready, v6

#2944 V6/update tools page
  CHANGELOG.md
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/layouts-default/TheToolsLayout.vue
Labels: Ready, v6

#2935 V6/update home features
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/icon-dapp-aave.png
  src/assets/images/icons/icon-dapp-ambrpay.png
  src/assets/images/icons/icon-dapp-ens-manager.png
  src/assets/images/icons/icon-dapp-eth20.png
  src/assets/images/icons/icon-dapp-golem.png
  src/assets/images/icons/icon-dapp-lend.png
  src/assets/images/icons/icon-dapp-unstoppable.png
  src/components/white-sheet/WhiteSheet.vue
  src/views/components-default/HomeFeatures.vue
  src/views/components-default/HomeFeaturesDapps.vue
  src/views/components-default/HomeFeaturesSend.vue
  src/views/components-default/HomeFeaturesSwap.vue
  src/views/components-default/HomeFeaturesTokens.vue
Labels: Ready, v6

#2940 devop/alchemy-link
  CHANGELOG.md
  package-test.js
  src/containers/FooterContainer/affiliates.js
  src/translations/footer/en_US.json
Labels: Devop, Ready

#2946 code: update component
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/assets/images/ads/1.png
  src/builds/web/app.vue
  src/layouts/HomeLayout/HomeLayout.vue
  src/layouts/HomeLayout/components/HomeModal/HomeModal.vue
  src/layouts/HomeLayout/components/HomeModal/index.js
  src/layouts/HomeLayout/components/WelcomeModal/WelcomeModal.scss
  src/layouts/HomeLayout/components/WelcomeModal/WelcomeModal.vue
  src/layouts/HomeLayout/components/WelcomeModal/index.js
  src/translations/common/en_US.json
Labels: Ready, v5

#2941 fix bsc data on send offline
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/networks/aqua.svg
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/networks/nodes/aqua-conical.js
  src/networks/nodes/aqua-info.js
  src/networks/nodes/index.js
  src/networks/types/AQUA.js
  src/networks/types/BSC.js
  src/networks/types/index.js
  vueConfig/connections.js
Labels: Bug, Ready
