Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-08, with the labels that each got.

#3357 fix: 🐛 sanitize hex all the spots
  changelog/fix-3357.md
  package-lock.json
  package.json
  src/core/helpers/sanitizeHex.js
  src/modules/access-wallet/common/helpers.js
  src/modules/access-wallet/common/utils.js
Labels: Bug, Ready

#3341 devop: 🔧 utilize github actions for lokalise, only call when a push or pr has translation changes
  .github/workflows/generate-changelog.yml
  .github/workflows/github-release.yml
  .github/workflows/upload-translations.yml
  .github/workflows/validate-changelog.yml
  .husky/pre-push
  changelog/devop-3341.md
  package-lock.json
  package.json
  scripts/checkBranch.sh
  scripts/checklockconflicts.sh
  scripts/createLokaliseBranch.js
  scripts/prepChangelog.js
  scripts/release.sh
  scripts/uploadToLokalise.js
  scripts/validateChangelog.js
Labels: Devop, Ready

#3354 fix: 🐛 metamask send
  changelog/fix-3354.md
  changelog/fix-3357.md
  package-lock.json
  src/modules/access-wallet/software/handlers/web3wallet/index.js
  src/utils/web3-provider/methods/eth_getTransactionCount.js
  src/utils/web3-provider/providers/given-provider.js
  src/views/TheWalletView.vue
Labels: Ready, v6

#3279 feat: ✨ add dapp submission form
  .github/workflows/add-to-codecov.yml
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-to-ghpages.yml
  .github/workflows/github-release.yml
  .github/workflows/run-on-pr.yml
  CHANGELOG.md
  changelog/feat-3279.md
  package-lock.json
  package.json
  src/assets/images/icons/icon-sotd.png
  src/assets/images/icons/socials/svg/github.svg
  src/assets/styles/GlobalStyles.scss
  src/core/configs/configRoutes.js
  src/core/plugins/vuetify.js
  src/core/router/routes-default.js
  src/translations/dapps-submission/en_US.json
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheDappSubmissionLayout.vue
Labels: Feature, Ready, v6

#3362 fix: 🐛 missing tokens
  .gitignore
  changelog/fix-3362.md
  package-lock.json
  package-test.js
  package.json
  src/core/helpers/tokenInfo.js
  src/core/store/external/actions.js
  src/utils/networks/types/BSC.js
Labels: Ready, v6

#3368 devop: 🔧 revert mew components, update other package
  changelog/devop-3368.md
  package-lock.json
  package.json
Labels: Devop, Ready

#3358 release: 🔥 v5.8.5
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/InterfaceLayout-mobile.scss
  src/layouts/InterfaceLayout/InterfaceLayout-tablet.scss
  src/wallets/hardware/bitbox/digitalBitboxEth.js
  src/wallets/hardware/bitbox/digitalBitboxUsb.js
Labels: Release, Ready

#3370 fix: 🐛 eip1559 basefee
  changelog/fix-3370.md
  src/views/TheWalletView.vue
Labels: Ready, Hotfix, v6

#3378 fix: 🐛 hasEnough for contracts
  changelog/fix-3378.md
  package-lock.json
  package.json
  src/modules/contract/ModuleContractInteract.vue
Labels: Bug, Ready, v6

#3372 fix: 🐛 my public address overlay layout
  CHANGELOG.md
  changelog/fix-3372.md
  package.json
  src/core/components/AppAddrQr.vue
  src/modules/balance/ModuleBalanceCard.vue
Labels: Bug, Ready, UI, v6

#3377 feat: ✨ allow users to use other unstoppable tlds
  CHANGELOG.md
  changelog/feat-3377.md
  changelog/fix-3289.md
  changelog/fix-3373.md
  connections.js
  package-lock.json
  package-test.js
  package.json
  src/core/helpers/addressUtils.js
  src/core/helpers/normalise.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
  src/dapps/ens-manager-dapp/handlers/handlerTextRecords.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/name-resolver/helpers.js
  src/modules/name-resolver/index.js
  src/modules/nft-manager/components/NftManagerSend.vue
  src/utils/web3-provider/providers/ws-provider.js
Labels: Feature, Ready

#3388 release: v6.0.4-hotfix.1
  CHANGELOG.md
  connections.js
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppAddrQr.vue
  src/core/components/TheWrapperWallet.vue
  src/core/helpers/addressUtils.js
  src/core/helpers/normalise.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
  src/dapps/ens-manager-dapp/handlers/handlerTextRecords.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/name-resolver/helpers.js
  src/modules/name-resolver/index.js
  src/modules/nft-manager/components/NftManagerSend.vue
  src/utils/web3-provider/providers/ws-provider.js
  src/views/TheWalletView.vue
Labels: Release, Ready

#3387 fix: 🐛 swap token symbol undefined
  changelog/fix-3387.md
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready, v6

#3384 Fix/notification submitted type
  changelog/fix-3384.md
  package-lock.json
  package-test.js
  src/modules/notifications/handlers/handlerNotification.js
  src/utils/web3-provider/methods/utils.js
Labels: Bug, Ready

#3382 fix: 🐛 allow decimals in custom gas price
  changelog/fix-3382.md
  package-lock.json
  package.json
  src/modules/settings/components/SettingsGasPrice.vue
Labels: Bug, Ready

#3371 devop: add toasts or error handling for known sentry errors
  changelog/devop-3371
  package.json
  src/core/helpers/createApolloClient.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/software/handlers/errorHandler.js
  src/modules/toast/handler/handlerToast.js
  src/utils/web3-provider/providers/ws-provider.js
Labels: Devop, Ready

#3367 ui: 🎨 update all overlay designs
  changelog/ui-3367.md
  package-lock.json
  package.json
  src/assets/styles/GlobalStyles.scss
  src/dapps/aave-dapp/components/AaveBorrowOverlay.vue
  src/dapps/aave-dapp/components/AaveCollateralOverlay.vue
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/components/AaveRepayOverlay.vue
  src/dapps/aave-dapp/components/AaveSetAprOverlay.vue
  src/dapps/aave-dapp/components/AaveWithdrawOverlay.vue
  src/dapps/ens-manager-dapp/components/manage/ManageMulticoins.vue
  src/dapps/ens-manager-dapp/components/manage/ManageRenew.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTransfer.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTxtRecords.vue
  src/dapps/ens-manager-dapp/components/manage/ManageUploadWebsite.vue
  src/dapps/ens-manager-dapp/components/register/Register.vue
  src/dapps/ens-manager-dapp/components/register/RegisterRequest.vue
  src/dapps/ens-manager-dapp/modules/ModuleManageDomain.vue
  src/dapps/ens-manager-dapp/modules/ModuleRegisterDomain.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/ModuleAccessWalletMobile.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/access-wallet/hardware/components/AccessWalletPassword.vue
  src/modules/access-wallet/hardware/components/AccessWalletPaths.vue
  src/modules/access-wallet/software/components/AccessWalletKeystore.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/access-wallet/software/components/BrowserExtensionOverlay.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationMessage.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/create-wallet/ModuleCreateWalletSoftware.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/swap/components/SwapConfirmation.vue
Labels: Ready, UI

#3383 fix: 🐛 show walletconnect when signing tx
  changelog/fix-3383.md
  connections.js
  package-lock.json
  package.json
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/utils/web3-provider/methods/eth_signTransaction.js
Labels: Bug, Ready

#3400 fix: 🐛 eth_subscription issue
  changelog/fix-3400.md
  package-lock.json
  package.json
  src/core/configs/configRoutes.js
  src/core/router/routes-wallet.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/confirmation/handlers/dataToAction.js
  src/modules/notifications/ModuleNotifications.vue
  src/modules/swap/ModuleSwap.vue
  src/utils/web3-provider/providers/ws-web3-provider.js
Labels: Bug, Ready

#3390 fix: hide swap provider list when there is not enough balance
  changelog/fix-3390.md
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready, v6

#3408 chore: 👷 generate changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#3395 release: 🔥 v6.0.5
  CHANGELOG.md
  connections.js
  package-lock.json
  package-test.js
  package.json
  src/core/configs/configRoutes.js
  src/core/helpers/createApolloClient.js
  src/core/router/helpers.js
  src/core/router/routes-wallet.js
  src/core/store/external/actions.js
  src/dapps/aave-dapp/metainfo.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/dapps/ens-manager-dapp/metainfo.js
  src/dapps/ens-manager-dapp/modules/ModuleRegisterDomain.vue
  src/dapps/routes-dapps.js
  src/dapps/staked-dapp/components/staked-stepper/StakedStepper.vue
  src/dapps/staked-dapp/metainfo.js
  src/dapps/unstoppable-domains-dapp/metainfo.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/access-wallet/software/handlers/errorHandler.js
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/balance/handlers/handlerBalanceHistory.mixin.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/handlers/dataToAction.js
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/toast/handler/handlerToast.js
  src/utils/web3-provider/methods/eth_signTransaction.js
  src/utils/web3-provider/methods/utils.js
  src/utils/web3-provider/providers/ws-provider.js
  src/utils/web3-provider/providers/ws-web3-provider.js
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Release, Ready

#3393 devop: 🔧 remove step 2 for mnemonic, update network and address
  CHANGELOG.md
  changelog/ui-3393.md
  package-lock.json
  package.json
  src/core/configs/configRoutes.js
  src/core/router/routes-wallet.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletKeepkey.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/confirmation/handlers/dataToAction.js
  src/modules/notifications/ModuleNotifications.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/toast/handler/handlerToast.js
  src/utils/web3-provider/providers/ws-web3-provider.js
Labels: Feature, Ready, UI

#3402 release: 🔥v5.8.6
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/directives/AddrResolver.js
Labels: Release, Ready

#3405 fix: 🐛 qr code image
  changelog/ui-3405.md
  src/modules/balance/components/PaperWalletToDisplay.vue
Labels: Ready, UI, v6

#3412 fix: 🐛 wallet access issues
  changelog/fix-3412.md
  package-lock.json
  package.json
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/toast/handler/handlerToast.js
Labels: Bug, Ready, v6

#3397 fix: 🐛 setItem null error
  changelog/fix-3397.md
  src/modules/access-wallet/hybrid/handlers/WalletConnect/errorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/errorHandler.js
Labels: Bug, Ready, v6

#3415 fix: 🐛 reset send form after actually sending
  changelog/fix-3415.md
  package-lock.json
  package-test.js
  package.json
  src/modules/send/ModuleSend.vue
Labels: Bug, Ready

#3414 devop: 🔧 fix swap icons and hide provider list when amount error
  changelog/fix-3414.md
  package-lock.json
  package-test.js
  package.json
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready

#3419 Devop/update release
  PULL_REQUEST_TEMPLATE.md
  changelog/devop-3419.md
  package-lock.json
Labels: Devop, Ready

#3424 fix: 🐛 ledger send
  changelog/fix-3424.md
  package-lock.json
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
Labels: Bug, Ready
