Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-11, with the labels that each got.

#3518 ui: refactor mew-buttons & mew-expand-panels
  changelog/fix-3518.md
  package-lock.json
  package.json
  src/components/mew-tools/MewTools.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/unstoppable-domains-dapp/UnstoppableDomain.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/ModuleAccessWalletMobile.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/send/ModuleSend.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
Labels: Ready, UI, v6

#3528 fix: 🐛 keepkey, update gas price everytime instead of initially
  changelog/fix-3528.md
  package-lock.json
  package-test.js
  package.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/utils.js
  src/views/TheWalletView.vue
Labels: Fix, Ready

#3534 fix: 🐛 address book issue
  changelog/fix-3534.md
  package-lock.json
  src/app.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/swap/components/SwapProvidersList.vue
Labels: Ready, Fixed

#3529 devop: 🔧 add new template for issues and feature requests
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  changelog/devop-3529.md
Labels: Devop, Ready

#3533 fix: 👷 eip1559 signing
  changelog/fix-3533.md
  package-lock.json
  package.json
  src/modules/access-wallet/common/WalletInterface.js
  src/modules/access-wallet/common/helpers.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/utils.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/access-wallet/hybrid/handlers/MEWconnect/index.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/access-wallet/software/handlers/mnemonic/index.js
Labels: Ready, Fixed

#3525 fix: 🐛 failed to fetch and wrong prev session
  changelog/fix-3525.md
  package.json
  src/core/store/external/actions.js
  src/modules/toast/handler/handlerToast.js
Labels: Fix, Ready

#3541 fix: 🐛 exclude packages for release
  package-test.js
Labels: Ready, Hotfix

#3543 chore: 👷 add package exclusion
  package-lock.json
  package-test.js
Labels: Devop, Ready

#3538 devop: release 6.4.0
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/deploy-live.yml
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  changelog/devop-3529.md
  changelog/devop-3538.md
  changelog/fix-3516.md
  changelog/fix-3518.md
  package-lock.json
  package-test.js
  package.json
  src/components/mew-tools/MewTools.vue
  src/core/configs/configRoutes.js
  src/core/router/routes-default.js
  src/dapps/aave-dapp/Aave.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/register/Register.vue
  src/dapps/unstoppable-domains-dapp/UnstoppableDomain.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/ModuleAccessWalletMobile.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/send/ModuleSend.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/modules/tools/components/charts/Charts.vue
  src/modules/tools/components/table/Table.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-default/TheLayoutHeader.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
  src/views/layouts-default/TheConvertUnits.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
Labels: Devop, Ready

#3535 fix: 🐛 trezor popup errors
  changelog/fix-3525.md
  changelog/fix-3535.md
  package-lock.json
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
Labels: Fix, Ready

#3548 fix: :bug: ens and max amount
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-mewbuilds.yml
  .github/workflows/deploy-live.yml
  changelog/fix-3548.md
  package-lock.json
  package.json
  src/core/helpers/gasPriceHelper.js
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/modules/send/ModuleSend.vue
Labels: Ready, v6

#3526 fix: 🐛 add a check for when tokens undefined or empty
  changelog/fix-3526.md
  src/modules/swap/handlers/handlerSwap.js
Labels: Bug, Ready

#3532 fix: 🐛 add connection check
  changelog/fix-3532.md
  src/core/store/wallet/actions.js
Labels: Bug, Ready

#3552 chore: 👷 fix swap when sending with token
  changelog/fix-3552.md
  package-lock.json
  package-test.js
  package.json
  src/modules/swap/ModuleSwap.vue
Labels: Release, Ready

#3527 feat: ✨ ETH Blocks
  changelog/feat-3527.md
  connections.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/icon-dapp-eth-blocks.svg
  src/assets/images/icons/icon-eth-blocks-logo.png
  src/core/components/TheDappHeader.vue
  src/core/components/TheWrapperDapp.vue
  src/core/plugins/vuetify.js
  src/core/store/configs.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/core/store/index.js
  src/dapps/dappsStore.js
  src/dapps/eth-blocks/TheEthBlocksLayout.vue
  src/dapps/eth-blocks/assets/eth-blocks-qrs.svg
  src/dapps/eth-blocks/assets/loading-block.svg
  src/dapps/eth-blocks/components/BlockInfoAlert.vue
  src/dapps/eth-blocks/components/BlockSearch.vue
  src/dapps/eth-blocks/components/BlockSend.vue
  src/dapps/eth-blocks/components/BlocksDropDown.vue
  src/dapps/eth-blocks/components/BlocksLoading.vue
  src/dapps/eth-blocks/components/BlocksSort.vue
  src/dapps/eth-blocks/configsRoutes.js
  src/dapps/eth-blocks/handlers/configs.js
  src/dapps/eth-blocks/handlers/handlerBlock.js
  src/dapps/eth-blocks/handlers/handlerMyBlocks.js
  src/dapps/eth-blocks/handlers/helpers/blockAlertType.js
  src/dapps/eth-blocks/handlers/helpers/common.js
  src/dapps/eth-blocks/handlers/helpers/supportedNetworks.js
  src/dapps/eth-blocks/metainfo.js
  src/dapps/eth-blocks/modules/ModuleEthBlockInfo.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksMint.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksMyBlocks.vue
  src/dapps/eth-blocks/store/actions.js
  src/dapps/eth-blocks/store/configs.js
  src/dapps/eth-blocks/store/getters.js
  src/dapps/eth-blocks/store/index.js
  src/dapps/eth-blocks/store/mutations.js
  src/dapps/eth-blocks/store/state.js
  src/dapps/metainfo-dapps.js
  src/main.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/handlers/dataToAction.js
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/views/TheWalletView.vue
  src/views/components-default/HomeFeaturesDapps.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
Labels: Feature, Ready

#3553 Fix/paths issue
  CHANGELOG.md
  changelog/fix-3526.md
  changelog/fix-3553.md
  package-lock.json
  src/core/store/wallet/actions.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/common/helpers.js
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/access-wallet/hardware/components/AccessWalletKeepkey.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
  src/modules/access-wallet/software/handlers/web3wallet/errorHandler.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationSwapTransactionDetails.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/toast/handler/handlerToast.js
  src/utils/web3-provider/methods/utils.js
  src/utils/web3-provider/providers/ws-provider.js
Labels: Bug, Ready

#3558 Fix/eth blocks
  changelog/fix-3558.md
  package-lock.json
  package.json
  src/dapps/eth-blocks/TheEthBlocksLayout.vue
  src/dapps/eth-blocks/components/BlockInfoAlert.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockInfo.vue
Labels: Bug, Ready, UI

#3566 feat: ✨ eth blocks landing page
  changelog/fix-3558.md
  changelog/fix-3566.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/eth-blocks-3.png
  src/assets/images/icons/eth-blocks-6.png
  src/assets/images/icons/nft/eth-block/block-1.jpeg
  src/assets/images/icons/nft/eth-block/block-2.jpeg
  src/assets/images/icons/nft/eth-block/block-3.jpeg
  src/assets/images/icons/nft/eth-block/block-4.jpeg
  src/assets/images/icons/nft/eth-block/block-5.jpeg
  src/assets/images/icons/nft/eth-block/block-6.jpeg
  src/dapps/eth-blocks/TheEthBlocksLayout.vue
  src/dapps/eth-blocks/components/BlockInfoAlert.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockInfo.vue
  src/views/components-default/HomeEthBlocks.vue
  src/views/layouts-default/TheHomeLayout.vue
Labels: Feature, Ready, v6

#3565 feat: ✨ add survey
  CHANGELOG.md
  changelog/feat-3565.md
  package-lock.json
  package-test.js
  package.json
  src/core/plugins/vuetify.js
  src/core/store/global/actions.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/views/TheWalletView.vue
  src/views/components-default/MewSurvey.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
Labels: Feature, Ready

#3570 release: 🔥 v6.4.1
  CHANGELOG.md
  changelog/fix-3558.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/eth-blocks-3.png
  src/assets/images/icons/eth-blocks-6.png
  src/assets/images/icons/nft/eth-block/block-1.jpeg
  src/assets/images/icons/nft/eth-block/block-2.jpeg
  src/assets/images/icons/nft/eth-block/block-3.jpeg
  src/assets/images/icons/nft/eth-block/block-4.jpeg
  src/assets/images/icons/nft/eth-block/block-5.jpeg
  src/assets/images/icons/nft/eth-block/block-6.jpeg
  src/core/plugins/vuetify.js
  src/core/store/global/actions.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/views/TheWalletView.vue
  src/views/components-default/HomeEthBlocks.vue
  src/views/components-default/MewSurvey.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/layouts-default/TheHomeLayout.vue
Labels: Release, Ready

#3576 devop: 🔧 show private key when printing mnemonic
  changelog/devop-3564.md
  changelog/devop-3573.md
  changelog/devop-3576.md
  changelog/fix-3531.md
  changelog/fix-3561.md
  changelog/fix-3563.md
  changelog/fix-3567.md
  changelog/fix-3574.md
  changelog/fix-3575.md
  fetchLists/index.js
  package-lock.json
  package-test.js
  package.json
  src/core/store/wallet/actions.js
  src/dapps/aave-dapp/components/AaveBorrowOverlay.vue
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/handlers/aaveOverlayMixin.js
  src/dapps/ens-manager-dapp/components/manage/ManageMulticoins.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTxtRecords.vue
  src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/HDWalletInterface.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/handlers/mnemonic/index.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
  src/modules/global-modals/ModuleGlobalModals.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send/ModuleSend.vue
  src/modules/settings/handler/handlerSettings.js
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/translations/errors-ledger/en_US.json
  src/utils/web3-provider/providers/ws-provider.js
  src/utils/web3-provider/providers/ws-web3-provider.js
  src/views/components-default/TheDefaultWalletBanner.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Devop, Ready

#3564 devop: 🔧 migrate to lodash
  changelog/devop-3564.md
  package-lock.json
  package.json
  src/dapps/aave-dapp/components/AaveBorrowOverlay.vue
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/handlers/aaveOverlayMixin.js
  src/dapps/ens-manager-dapp/components/manage/ManageMulticoins.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTxtRecords.vue
  src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/global-modals/ModuleGlobalModals.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send/ModuleSend.vue
  src/modules/settings/handler/handlerSettings.js
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/utils/web3-provider/providers/ws-web3-provider.js
Labels: Devop, Ready

#3574 fix: 🐛 add in another ledger error
  changelog/fix-3574.md
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/translations/errors-ledger/en_US.json
Labels: Bug, Ready

#3575 fix: 🐛 add check for reading disconnects
  changelog/fix-3575.md
  src/core/store/wallet/actions.js
  src/utils/web3-provider/providers/ws-provider.js
Labels: Ready

#3562 fix: 🐛 stabilize all hardware wallet and mnemonic access
  changelog/fix-3558.md
  changelog/fix-3562.md
  package-lock.json
  package.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
Labels: Ready, Fixed

#3581 fix: 🐛 ens commit
  changelog/fix-3581.md
  fetchLists/index.js
  package-lock.json
  package.json
  src/core/components/TheWrapperDapp.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
Labels: Ready, Fixed
