Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-12, with the labels that each got.

#3572 feat: ✨ add in log message on app start
  README.md
  changelog/feat-3572.md
  src/app.vue
Labels: Feature, Ready

#3588 fix: fix create wallet back button
  changelog/fix-3588.md
  src/modules/create-wallet/ModuleCreateWalletSoftware.vue
  src/modules/swap/tests/zerox.spec.js
Labels: Bug, v6

#3586 fix: 🐛 wallet link undefined
  changelog/fix-3586.md
  package-lock.json
  package.json
  src/modules/access-wallet/common/WalletErrorHandler.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/errorHandler.js
Labels: Bug, Ready

#3584 fix: 🐛 missing bitcoin rate for swap
  changelog/fix-3584.md
  package-lock.json
  package.json
  src/modules/swap/handlers/handlerSwap.js
Labels: Bug, Ready

#3593 fix: 🐛 home feature swap undefined
  changelog/fix-3593.md
  package-lock.json
  package.json
  src/views/components-default/HomeFeaturesSwap.vue
Labels: Ready, v6

#3595 fix: 🐛 bitbox access
  changelog/fix-3595.md
  package-lock.json
  package.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
Labels: Ready, Fixed

#3596 devop: 🔧 add 3 weeks release timer for new dapps
  CODEOWNERS
  changelog/devop-3596.md
  package-lock.json
  package.json
  src/dapps/aave-dapp/metainfo.js
  src/dapps/ens-manager-dapp/metainfo.js
  src/dapps/eth-blocks/metainfo.js
  src/dapps/staked-dapp/metainfo.js
  src/dapps/unstoppable-domains-dapp/metainfo.js
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready

#3601 release: 🔥 v6.4.3-hotfix.1
  .github/workflows/add-to-mewbuilds.yml
  CHANGELOG.md
  Dockerfile
  changelog/feat-3572.md
  changelog/feat-3577.md
  connections.js
  fetchLists/fetchMainLists.js
  package-lock.json
  package.json
  src/app.vue
  src/assets/images/team/mew-collage-large.jpg
  src/assets/images/team/mew-collage-small.jpg
  src/core/configs/configRoutes.js
  src/core/plugins/vuetify.js
  src/core/router/routes-default.js
  src/translations/common/en_US.json
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheCareersLayout.vue
  src/views/layouts-default/TheConvertUnitsLayout.vue
Labels: Release, Ready
