Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-04, with the labels that each got.

#2954 release/v5.7.25-majorupdate.1
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/ads/1.png
  src/assets/images/networks/aqua.svg
  src/builds/web/app.vue
  src/containers/FooterContainer/affiliates.js
  src/layouts/HomeLayout/HomeLayout.vue
  src/layouts/HomeLayout/components/HomeModal/HomeModal.vue
  src/layouts/HomeLayout/components/HomeModal/index.js
  src/layouts/HomeLayout/components/WelcomeModal/WelcomeModal.scss
  src/layouts/HomeLayout/components/WelcomeModal/WelcomeModal.vue
  src/layouts/HomeLayout/components/WelcomeModal/index.js
  src/layouts/InterfaceLayout/containers/SendOfflineContainer/SendOfflineContainer.vue
  src/networks/nodes/aqua-conical.js
  src/networks/nodes/aqua-info.js
  src/networks/nodes/index.js
  src/networks/types/AQUA.js
  src/networks/types/BSC.js
  src/networks/types/index.js
  src/translations/common/en_US.json
  src/translations/footer/en_US.json
  vueConfig/connections.js
Labels: Ready, Release

#2951 ui: add no nft msg
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/nft-manager/handlers/handlerNftInit.js
  src/translations/nft-manager/en_US.json
Labels: Ready, v6

#2947 V6/send tx gas price getter issue
  fetchLists/lists/tokens.json
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/send/handlers/handlerSend.js
Labels: Fixed, Ready, v6

#2926 V6/fix access hardware wallet layout
  .husky/.gitignore
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/assets/styles/GlobalStyles.scss
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletBcVault.vue
  src/modules/access-wallet/hardware/components/AccessWalletPassword.vue
  src/modules/access-wallet/hardware/components/AccessWalletPaths.vue
  src/modules/access-wallet/hardware/components/AccessWalletQrCode.vue
Labels: Ready, v6

#2955 devop: update domain taken
  package-lock.json
  package.json
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/register/RegisterRequest.vue
  src/dapps/ens-manager-dapp/modules/ModuleRegisterDomain.vue
Labels: Ready, v6

#2967 V6/mnemonic balance
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/handlers/handlerAccessWalletSoftware.js
Labels: Ready, v6

#2970 V6/batch tx temp modal
  .husky/_/husky.sh
  apollo.config.js
  apolloAave.config.js
  package-lock.json
  package-test.js
  package.json
  src/apollo/global/globalTypes.json
  src/apollo/schemas/api.json
  src/assets/images/currencies/icon-eth-blue.png
  src/core/helpers/createApolloClient.js
  src/core/plugins/vuetify.js
  src/core/store/wallet/actions.js
  src/core/store/wallet/mutations.js
  src/dapps/aave-dapp/Aave.vue
  src/dapps/aave-dapp/apollo/configs.js
  src/dapps/aave-dapp/apollo/global/globalTypes.json
  src/dapps/aave-dapp/apollo/index.js
  src/dapps/aave-dapp/apollo/queries/aave.graphql
  src/dapps/aave-dapp/apollo/queries/queries.js
  src/dapps/aave-dapp/apollo/schemas/api.json
  src/dapps/aave-dapp/components/AaveAmountForm.vue
  src/dapps/aave-dapp/components/AaveBorrowOverlay.vue
  src/dapps/aave-dapp/components/AaveCollateralOverlay.vue
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/components/AaveRepayOverlay.vue
  src/dapps/aave-dapp/components/AaveSelectInterest.vue
  src/dapps/aave-dapp/components/AaveSetAprOverlay.vue
  src/dapps/aave-dapp/components/AaveSummary.vue
  src/dapps/aave-dapp/components/AaveTable.vue
  src/dapps/aave-dapp/components/AaveWithdrawOverlay.vue
  src/dapps/aave-dapp/handlers/aaveOverlayMixin.js
  src/dapps/aave-dapp/handlers/handlerAave.js
  src/dapps/aave-dapp/handlers/helpers.js
  src/dapps/apollo-dapps.js
  src/main/apolloProvider.js
  src/modules/access-wallet/hardware/handlers/hardwares/bcvault/index.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/handlers/handlerAccessWalletSoftware.js
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationBatchTransaction.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/name-resolver/tests/name-resolver.spec.js
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/utils/web3-provider/methods/utils.js
  src/views/TheDefaultView.vue
Labels: Devop, Ready

#2968 V6/fix strings
  src/views/components-default/CompanyCommunity.vue
  src/views/components-default/CompanyOurStory.vue
  src/views/components-default/CompanyWhatIsMew.vue
  src/views/components-default/HomeFeatures.vue
  src/views/components-default/HowItWorksDappsCenter.vue
  src/views/components-default/HowItWorksMore.vue
  src/views/components-default/HowItWorksSend.vue
  src/views/components-default/HowItWorksSwap.vue
  src/views/components-default/HowItWorksTokens.vue
  src/views/layouts-default/TheHowItWorksLayout.vue
Labels: Ready, v6

#2966 V6/Fix buy eth button overflow issue on old Chrome browsers
  CHANGELOG.md
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, v6

#2965 V6/fix: no balance missing balance card
  CHANGELOG.md
  src/core/store/wallet/getters.js
Labels: Ready, v6

#2964 v6fix: interact with contract drop-down
  CHANGELOG.md
  src/modules/contract/ModuleContractInteract.vue
Labels: Ready, v6

#2963 V6/fix hardware wallet links
  CHANGELOG.md
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
Labels: Ready, v6

#2959 V6/fix decision-tree support contact link
  CHANGELOG.md
  src/modules/decision-tree/ModuleDecisionTree.vue
Labels: Ready, v6

#2956 v6/fix paper wallet functionality
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/balance/components/BalanceAddressPaperWallet.vue
Labels: Ready, v6

#2953 V6/fix partners(Ledger) link
  CHANGELOG.md
  src/core/components/AppPartnersBlock.vue
Labels: Ready, UI, v6

#2978 devop: remove contact support in wallet footer, added Help Center Link
  src/views/components-wallet/TheWalletFooter.vue
Labels: Devop, v6

#2975 fix: token balance
  CHANGELOG.md
  package.json
  src/core/helpers/numberFormatHelper.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletNetworkAddresses.vue
  src/modules/access-wallet/hardware/components/AccessWalletPin.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/swap/tests/changelly.spec.js
  src/translations/access-wallet/en_US.json
  src/views/components-default/HomeFeaturesSend.vue
Labels: Ready, v6

#2937 Fix hardware network and address select
  CHANGELOG.md
  package.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletNetworkAddresses.vue
  src/modules/access-wallet/hardware/components/AccessWalletPin.vue
  src/translations/access-wallet/en_US.json
Labels: Ready, v6

#2969 fix: contract address table buttons
  src/modules/settings/ModuleSettings.vue
Labels: Ready, UI, v6

#2976 fix: fix address identicon for send feat on home page
  src/modules/address-book/ModuleAddressBook.vue
  src/views/components-default/HomeFeaturesSend.vue
Labels: Ready, UI, v6

#2977 fix: show empty list after loading, hide buy tokens on other netowrks
  src/modules/balance/ModuleTokens.vue
Labels: Bug, Ready, v6

#2972 V6/balance subscribe
  package-lock.json
  src/apollo/queries/wallets/index.js
  src/apollo/queries/wallets/wallets.graphql
  src/modules/balance/ModuleBalance.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationMessage.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/notifications/ModuleNotifications.vue
  src/views/TheWalletView.vue
Labels: Devop, Ready

#2974 fix: hash break word style implementation
  package-lock.json
  src/modules/notifications/ModuleNotifications.vue
Labels: Ready, UI, v6

#2957 V6/Fix footer CoinMarketCap link
  CHANGELOG.md
  LICENSE
  connections.js
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletFooter.vue
  src/views/layouts-default/TheToolsLayout.vue
Labels: Ready, v6

#2983 Devop/update package version
  package-lock.json
  package.json
  vueConfig/connections.js
Labels: Devop, Ready

#2986 revert
  src/builds/web/app.vue
Labels: Devop, Ready

#2988 build: prevent user from adding own address
  package-lock.json
  src/modules/address-book/components/AddressBookAddEdit.vue
Labels: Ready, v6

#2987 V6/Fix verify message layout
  CHANGELOG.md
  src/views/layouts-wallet/TheVerifyMessageLayout.vue
Labels: Ready, v6

#2990 V6/fix sign message mobile layout
  CHANGELOG.md
  src/views/layouts-wallet/TheSignMessageLayout.vue
Labels: Ready, v6

#2985 fix: import configuration, sign message clear
  CHANGELOG.md
  src/modules/message/ModuleMessageSign.vue
  src/modules/message/ModuleMessageVerify.vue
  src/modules/settings/handler/handlerSettings.js
Labels: Ready, v6

#2991 V6/change mew wallet icon
  src/assets/images/icons/icon-mew-connect.svg
  src/components/mew-tools/MewTools.vue
  src/modules/balance/components/BalanceChart.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Ready, v6

#2989 V6/aave bug
  package-lock.json
  package.json
  src/dapps/aave-dapp/components/AaveTable.vue
  src/dapps/aave-dapp/components/AaveWithdrawOverlay.vue
  src/dapps/aave-dapp/handlers/handlerAave.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/modules/swap/tests/dexag.spec.js
  src/views/components-wallet/TheWalletHeader.vue
Labels: Bug, Ready, v6

#2992 chore: change mewtopia article string
  src/views/components-wallet/TheWalletHeader.vue
Labels: v6

#2995 devop: update packages
  package-audit.js
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#2984 release/v5.7.26
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/builds/web/app.vue
  vueConfig/connections.js
Labels: Ready, Release

#2996 devop: export vuetify theme from mew components
  package-lock.json
  package.json
  src/core/plugins/vuetify.js
Labels: Devop, v6

#3005 re-check estimateGas after estimateGas failure
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
Labels: Bug, v5

#3002 fix mnemomnic import issue with extra word
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/ExtensionHelpers.js
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/wallets/bip44/paths.js
  src/wallets/hardware/ledger/appPaths.js
Labels: Bug, Ready

#3007 release/v5.7.27
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/helpers/ExtensionHelpers.js
  src/layouts/ExtensionBrowserAction/components/AddWalletModal/AddWalletModal.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/wallets/bip44/paths.js
  src/wallets/hardware/ledger/appPaths.js
Labels: Ready, Release

#3000 devop: update mew components
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
Labels: Ready, v6

#3013 fix: checksum address and display correct info
  package-lock.json
  package.json
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
Labels: Bug, Ready, v6

#3016 V6/Fix dapps aave overlay layouts issues
  CHANGELOG.md
  src/assets/styles/GlobalStyles.scss
  src/dapps/aave-dapp/Aave.vue
  src/dapps/aave-dapp/components/AaveAmountForm.vue
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/components/AaveRepayOverlay.vue
  src/dapps/aave-dapp/components/AaveSummary.vue
Labels: Ready, v6

#3021 V6/non-mainnet networks
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/balance/ModuleBalance.vue
  src/modules/swap/ModuleSwapRates.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, v6

#2997 V6/fix ens > manage domain
  CHANGELOG.md
  package-lock.json
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
Labels: Ready, v6

#2998 V6/fix mobile menu logo and max screen size
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/styles/GlobalStyles.scss
  src/views/components-default/TheDefaultMobileNavigation.vue
Labels: Ready, v6

#3006 V6/update mewcard image
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/balance/ModuleBalanceCard.vue
  vue.config.js
Labels: Ready, v6

#3035 update packages, add matic network
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/networks/nodes/index.js
  src/networks/nodes/matic.js
  src/networks/types/MATIC.js
  src/networks/types/index.js
  vueConfig/connections.js
Labels: Devop, Ready

#3037 devop: remove duplicate packages
  package-lock.json
  package.json
Labels: Devop, Ready, v6

#3022 V6/fix no error with invalid keystore file
  CHANGELOG.md
  package-lock.json
  src/modules/access-wallet/software/components/AccessWalletKeystore.vue
  src/modules/wallets/utils/helpers.js
Labels: Ready, v6

#3036 Devop/unstoppable
  CHANGELOG.md
  package-lock.json
  package.json
  src/directives/AddrResolver.js
Labels: Bug, Ready, v5

#3040 devop: only fetch quotes when all inputs are valid
  CHANGELOG.md
  src/modules/swap/ModuleSwap.vue
Labels: Devop, Ready, v6

#3039 V6/swap gas price recalculate
  CHANGELOG.md
  src/modules/swap/ModuleSwap.vue
Labels: Devop, Ready

#3032 V6/tx transaction flow
  src/core/components/AppModal.vue
  src/core/store/wallet/mutations.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmWithWallet.vue
  src/modules/confirmation/components/ConfirmationSwapModal.vue
  src/modules/confirmation/components/ConfirmationTransaction.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/utils/web3-provider/events.js
  src/utils/web3-provider/methods/eth_sendTransaction.js
Labels: Devop, Ready, v6

#3031 V6/chart data loading logic
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/balance/ModuleBalance.vue
Labels: Ready, v6

#3045 Devop/avalanche access
  .gitignore
  package-lock.json
  package.json
  src/wallets/bip44/ledgerPaths.js
  src/wallets/bip44/mnemonicPaths.js
  src/wallets/bip44/paths.js
  src/wallets/hardware/ledger/appPaths.js
  src/wallets/hardware/ledger/index.js
Labels: Devop, Ready

#3025 V6/bug-zero tx fee in notifications
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationTransaction.vue
  src/modules/confirmation/components/TransactionBalance.vue
Labels: Ready, v6

#3043 V6/keystore enter
  CHANGELOG.md
  src/modules/access-wallet/software/components/AccessWalletKeystore.vue
Labels: Devop, Ready, v6

#3041 V6/fix balance card checksum address
  src/modules/balance/ModuleBalanceCard.vue
Labels: Ready, v6

#3017 V6/Fix dapps confirmation layout issues
  CHANGELOG.md
  src/modules/confirmation/components/ConfirmationTransaction.vue
  src/modules/confirmation/components/TransactionAddresses.vue
  src/modules/confirmation/components/TransactionBalance.vue
Labels: Ready, v6

#3042 Devop/switch address
  CHANGELOG.md
  package-lock.json
  src/core/store/wallet/mutations.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletNetworkAddresses.vue
  src/modules/access-wallet/hardware/components/AccessWalletPaths.vue
  src/modules/access-wallet/hardware/components/AccessWalletPin.vue
  src/modules/access-wallet/hardware/handlers/configs/configWallets.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressSwitch.vue
  src/translations/access-wallet/en_US.json
Labels: Devop, Ready, v6

#3030 V6/note below min swaps
  CHANGELOG.md
  package-lock.json
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/providers/changelly.js
Labels: Ready, v6

#3026 V6/load gasPrice from store on initial load
  CHANGELOG.md
  src/views/TheWalletView.vue
Labels: Bug, Ready, v6

#3057 V6/fix access wallet buttons
  fetchLists/lists/tokens.json
  package.json
  src/assets/images/icons/icon-mew-wallet.png
  src/modules/access-wallet/ModuleAccessWalletMobile.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Ready, UI, v6

#3058 V6/fix home banner
  CHANGELOG.md
  package.json
  src/assets/images/backgrounds/bg-home-spaceman-and-dog.svg
  src/assets/images/backgrounds/bg-homepage.svg
  src/views/components-default/HomeLanding.vue
Labels: Ready, UI, v6

#3059 V6/fix landing page paddings and set min width
  CHANGELOG.md
  package.json
  src/assets/styles/GlobalStyles.scss
  src/core/components/AppGetStarted.vue
  src/core/components/AppMewtopiaBlock.vue
Labels: Ready, UI, v6

#3050 V6/fix paper wallet
  CHANGELOG.md
  src/core/helpers/blockies.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/balance/components/PaperWalletToDisplay.vue
  src/modules/balance/components/PaperWalletToPrint.vue
Labels: Bug, Ready, v6
