Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-06, with the labels that each got.

#3105 Bug/one inch decimal bug
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/partners/oneInch/oneInch.js
Labels: Fixed, v5

#3121 update package version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Devop, Ready

#3120 release/v5.8.0
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/layouts/InterfaceLayout/components/InterfaceAddress/InterfaceAddress.vue
  src/partners/oneInch/oneInch.js
Labels: Ready, Release

#3106 v6/fix swap store bit on eth message layouts
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapMsgStoreBtcEth.vue
Labels: Ready, UI, v6

#3110 V6/fix ens icons
  CHANGELOG.md
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
Labels: Ready, UI, v6

#3118 V6/fix swap current balance
  CHANGELOG.md
  package.json
  src/core/components/AppButtonBalance.vue
  src/modules/swap/ModuleSwap.vue
Labels: Ready, UI, v6

#3116 V6/fix swap btn
  CHANGELOG.md
  package.json
  src/assets/images/icons/icon-swap-backup.svg
  src/assets/images/icons/icon-swap.svg
  src/modules/swap/ModuleSwap.vue
  src/views/components-wallet/TheSwapBtn.vue
Labels: Ready, UI, v6

#3115 chore: remove compileBaseSwapOptions.js
  CHANGELOG.md
  compileBaseSwapOptions.js
  package-audit.js
  package-lock.json
  package.json
  src/modules/access-wallet/software/handlers/errorHandler.js
  src/modules/access-wallet/software/handlers/handlerAccessWalletSoftware.js
  src/modules/balance/ModuleBalanceCard.vue
Labels: Devop, Ready

#3051 V6/harmonize software wallet error handling
  src/modules/access-wallet/software/handlers/errorHandler.js
  src/modules/access-wallet/software/handlers/handlerAccessWalletSoftware.js
  src/modules/balance/ModuleBalanceCard.vue
Labels: v6

#3113 V6/swap updates
  package-lock.json
  package-test.js
  package.json
  src/core/mixins/handlerWallet.mixin.js
  src/core/store/wallet/actions.js
  src/core/store/wallet/mutations.js
  src/core/store/wallet/state.js
  src/modules/balance/ModuleTokens.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/modules/swap/handlers/configs/configTrendingTokens.js
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/views/TheWalletView.vue
Labels: Ready, v6

#3112 V6/number formatter
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/core/helpers/numberFormatHelper.js
  src/core/mixins/handlerWallet.mixin.js
  src/core/store/wallet/getters.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/manage/ManageRenew.vue
  src/dapps/ens-manager-dapp/components/register/RegisterRequest.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/settings/handler/gasPriceMixin.js
  src/modules/swap/ModuleSwapRates.vue
  src/modules/tokens-value/ModuleTokensValue.vue
  src/views/components-default/HomeFeaturesSwap.vue
Labels: Devop, Ready, v6

#3104 V6/swap button switch
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
Labels: Ready, v6

#3107 V6/swap remove to from vice versa
  CHANGELOG.md
  package-lock.json
  src/modules/swap/ModuleSwap.vue
Labels: Ready, v6

#3132 V6/swapp app balance button
  package-audit.js
  package-lock.json
  src/core/components/AppButtonBalance.vue
  src/modules/swap/ModuleSwap.vue
Labels: Ready, v6

#3143 V6/gasprice popup
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/components/AppNetworkSettingsModal.vue
  src/modules/swap/ModuleSwap.vue
Labels: Devop, Ready

#3139 V6/swap providers not loading
  CHANGELOG.md
  package-lock.json
  src/core/components/AppNetworkSettingsModal.vue
Labels: Devop, Ready, v6

#3145 ui: add scrollable option to app modal
  CHANGELOG.md
  src/core/components/AppModal.vue
Labels: UI, v6

#3135 V6/swap format selectors
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/images/icons/icon-edit-btn.svg
  src/assets/styles/GlobalStyles.scss
  src/core/components/AppButtonBalance.vue
  src/core/components/AppModal.vue
  src/core/mixins/handlerWallet.mixin.js
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/components/AaveWithdrawOverlay.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapFee.vue
  src/modules/tokens-value/ModuleTokensValue.vue
Labels: Devop, UI, WIP

#3140 V6/swap selector layout
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
Labels: Ready, UI, v6

#3150 devop: add total wallet balance
  package-lock.json
  package.json
  src/core/mixins/handlerWallet.mixin.js
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/components/AaveWithdrawOverlay.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/tokens-value/ModuleTokensValue.vue
Labels: Ready, v6

#3152 ui: fix swap provider list
  CHANGELOG.md
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
Labels: Ready, UI, v6

#3153 v6/cleanup generated files
  fetchLists/configs.js
  fetchLists/fetchMainLists.js
  fetchLists/index.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/aave-dapp/components/AaveTable.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/tokens-value/ModuleTokensValue.vue
  src/utils/networks/types/BSC.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/RIN.js
Labels: Ready, v6

#3124 v6/add bsc and matic
  package-lock.json
  package.json
  src/core/mixins/handlerWallet.mixin.js
  src/dapps/aave-dapp/components/AaveDepositOverlay.vue
  src/dapps/aave-dapp/components/AaveWithdrawOverlay.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/tokens-value/ModuleTokensValue.vue
Labels: Ready

#3154 V6/swap updates
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/modules/swap/handlers/configs/configTrendingTokens.js
Labels: Ready, v6

#3156 V6/swap providers button
  src/modules/swap/components/SwapFee.vue
  src/modules/swap/components/SwapProvidersList.vue
Labels: Devop, UI, v6

#3103 V6/add user error message
  package.json
  src/assets/images/backgrounds/bg-erroe-msg.svg
  src/core/components/AppErrorMsg.vue
Labels: Ready, v6

#3130 V6/styles cleanup
  package-lock.json
  src/assets/styles/GlobalStyles.scss
  src/core/components/AppBlockTitle.vue
  src/core/components/AppGetStarted.vue
  src/core/components/AppMewtopiaBlock.vue
  src/core/components/AppPartnersBlock.vue
  src/dapps/aave-dapp/Aave.vue
  src/dapps/ens-manager-dapp/components/register/Register.vue
  src/dapps/makerdao/MakerDAO.vue
  src/dapps/unstoppable-domains/UnstoppableDomain.vue
  src/dapps/unstoppable-domains/components/UnstoppableDomainBuyOverlay.vue
  src/dapps/unstoppable-domains/components/UnstoppableTransferDomainOverlay.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/swap/components/SwapConfirmation.vue
  src/modules/tokens-value/ModuleTokensValue.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/modules/wallets/components/access-wallet-overlay/HardwareWallets/Bitbox/Bitbox.vue
  src/modules/wallets/pages/send/send-offline/SendOffline.vue
  src/views/components-default/CompanyOurStory.vue
  src/views/components-default/HomeFeatures.vue
  src/views/components-default/HomeLanding.vue
  src/views/components-default/HomeWhyMew.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-default/TheLayoutHeader.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-default/TheHowItWorksLayout.vue
  src/views/layouts-default/ThePressKitLayout.vue
  src/views/layouts-default/ThePrivacyPolicyLayout.vue
  src/views/layouts-default/TheSecurityPolicyLayout.vue
  src/views/layouts-default/TheTeamLayout.vue
Labels: Devop, Ready, UI

#3164 V6/confirmation UI fixes
  package-lock.json
  package.json
  src/assets/images/icons/lottie/swap.json
  src/core/components/AppModal.vue
  src/core/directives/lottie.js
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/tokens-value/ModuleTokensValue.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Devop, UI

#3168 v6/console-errors
  CHANGELOG.md
  package-lock.json
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/swap/ModuleSwap.vue
Labels: Devop, Ready, v6

#3165 V6/fix mobile swap network fee
  package-lock.json
  src/modules/swap/components/SwapFee.vue
Labels: Ready, v6

#3167 v6/hide-no-rates
  CHANGELOG.md
  src/core/components/AppUserMsgBlock.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
Labels: Devop, Ready, v6

#3171 V6/fix fee UI
  package-lock.json
  package.json
  src/core/components/AppModal.vue
  src/core/components/AppNetworkFee.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapFee.vue
Labels: Ready, UI

#3162 V6/fix swap verification / confirmation data field
  CHANGELOG.md
  package-lock.json
  src/core/components/AppModal.vue
  src/core/components/AppScrollBlock.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationValuesContainer.vue
Labels: Ready, UI, v6

#3172 V6/set eth default
  CHANGELOG.md
  package-lock.json
  src/modules/send/ModuleSend.vue
  src/modules/send/handlers/handlerSend.js
Labels: Devop, Ready, v6

#3177 Devop/update packages
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
Labels: Devop, Ready, v5

#3178 release/v5.8.1
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
Labels: Ready, Release

#3176 V6/metamask send
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/modules/send/ModuleSend.vue
Labels: Ready, v6

#3174 V6/create wallet issue
  CHANGELOG.md
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/create-wallet/ModuleCreateWalletSoftware.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
Labels: Bug, Ready, v6

#3181 V6/bugs
  CHANGELOG.md
  connections.js
  src/core/components/AppErrorMsg.vue
  src/main/sentry.js
  src/modules/access-wallet/hybrid/handlers/WalletLink/index.js
  src/modules/balance/ModuleTokens.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/global-modals/ModuleGlobalModals.vue
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready, v6

#3180 devop: disable button on gas estimation error and when gas estimation…
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/send/ModuleSend.vue
Labels: Devop, Ready, v6

#3190 V6/fix UI landing
  CHANGELOG.md
  package-lock.json
  src/core/components/AppPartnersBlock.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
Labels: Ready, UI, v6

#3188 V6/dashboard UI fix
  package-lock.json
  package.json
  src/assets/images/snippets/mobile/mobile-features-dapps.svg
  src/assets/images/snippets/mobile/mobile-features-tokens.svg
  src/components/mew-tools/MewTools.vue
  src/core/components/AppMewtopiaBlock.vue
  src/core/components/AppPartnersBlock.vue
  src/translations/footer/en_US.json
  src/translations/footer/es_ES.json
  src/translations/footer/ja_JP.json
  src/translations/footer/ko_KR.json
  src/translations/footer/zh_CN.json
  src/views/components-default/HomeFeatures.vue
  src/views/components-default/HomeFeaturesDapps.vue
  src/views/components-default/HomeFeaturesSend.vue
  src/views/components-default/HomeFeaturesSwap.vue
  src/views/components-default/HomeFeaturesTokens.vue
  src/views/components-default/HomeWhyMew.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
Labels: Ready, UI, v6
