Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-05, with the labels that each got.

#3060 V6/fix ui issues for dapps and remove unused golbal styles
  CHANGELOG.md
  src/assets/styles/GlobalStyles.scss
  src/components/white-sheet/WhiteSheet.vue
  src/core/components/TheWrapperDapp.vue
  src/modules/balance/components/BalanceEmptyBlock.vue
Labels: Ready, UI, v6

#3065 bug/signing-address-send-offline
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.scss
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/translations/errors-global/en_US.json
Labels: Bug, Ready, v5

#3064 Fix paper wallet blockie color issue
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package.json
  src/components/BlockiePrintable/BlockiePrintable.scss
  src/components/BlockiePrintable/BlockiePrintable.vue
  src/components/BlockiePrintable/index.js
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
Labels: Bug, Ready, v5

#3085 Devop/security policy
  CHANGELOG.md
  package-lock.json
  package.json
  src/containers/FooterContainer/FooterContainer.vue
  src/translations/footer/en_US.json
Labels: Ready, v5

#3090 release/v5.7.9
  .eslintrc.js
  .stylelintrc.json
  CHANGELOG.md
  compileBaseSwapOptions.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/etc/oneinch.png
  src/assets/images/etc/oneinch_gray.png
  src/components/BlockiePrintable/BlockiePrintable.scss
  src/components/BlockiePrintable/BlockiePrintable.vue
  src/components/BlockiePrintable/index.js
  src/containers/FooterContainer/FooterContainer.vue
  src/layouts/InterfaceLayout/components/InterfaceTokens/InterfaceTokens.vue
  src/layouts/InterfaceLayout/components/PrintModal/components/AccountContentToPrint/AccountContentToPrint.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProviderInfoList/ProviderInfoList.vue
  src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProvidersRadioSelector.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.scss
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/partners/changelly/changelly-api.js
  src/partners/changelly/changelly-calls.js
  src/partners/changelly/changelly.js
  src/partners/changelly/config/config.js
  src/partners/helpers/utils.js
  src/partners/index.js
  src/partners/oneInch/config.js
  src/partners/oneInch/index.js
  src/partners/oneInch/oneInch-calls.js
  src/partners/oneInch/oneInch.js
  src/partners/partners.js
  src/translations/errors-global/en_US.json
  src/translations/footer/en_US.json
  src/translations/swap/en_US.json
  vueConfig/connections.js
Labels: Ready, Release

#3093 Bug/send offline
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready

#3096 Develop
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/partners/oneInch/oneInch.js
Labels: Ready, Release

#3081 V6/add top right btn
  CHANGELOG.md
  package.json
  src/core/components/AppTopRightBtn.vue
  src/modules/send/ModuleSend.vue
Labels: Ready, UI, v6

#3079 V6/fix aave layout paddings
  CHANGELOG.md
  src/dapps/aave-dapp/Aave.vue
Labels: Ready, UI, v6

#3100 devop: add security policy
  package-lock.json
  package.json
  src/core/router/routes-default.js
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheSecurityPolicyLayout.vue
Labels: Ready, v6

#3091 V6/fix mew-select border issue
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/mew-tools/MewTools.vue
Labels: Ready, UI, v6

#3072 V6/graphql refactor (wallet and token balance + notifications)
  .gitignore
  connections.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/apollo/configs/configErrorMsgs.js
  src/apollo/global/globalTypes.js
  src/apollo/global/globalTypes.json
  src/apollo/queries/notifications/index.js
  src/apollo/queries/notifications/notification.graphql
  src/apollo/queries/tokens/index.js
  src/apollo/queries/tokens/tokens.graphql
  src/apollo/queries/wallets/index.js
  src/apollo/queries/wallets/wallets.graphql
  src/apollo/schemas/api.json
  src/app.vue
  src/core/configs/configCurrencyTypes.js
  src/core/helpers/createApolloClient.js
  src/core/helpers/notificationFormatters/config.js
  src/core/helpers/notificationFormatters/formatters.js
  src/core/helpers/notificationFormatters/index.js
  src/core/helpers/notificationFormatters/utils.js
  src/core/helpers/numberFormatHelper.js
  src/core/mixins/apollo.js
  src/core/mixins/handlerWallet.mixin.js
  src/core/store/external/actions.js
  src/core/store/external/getters.js
  src/core/store/external/index.js
  src/core/store/external/mutations.js
  src/core/store/external/state.js
  src/core/store/notifications/getters.js
  src/core/store/notifications/mutations.js
  src/dapps/aave-dapp/Aave.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/handlers/handlerBalance.js
  src/modules/balance/handlers/handlerBalanceHistory.mixin.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationBatchTransaction.vue
  src/modules/confirmation/components/ConfirmationSwapModal.vue
  src/modules/confirmation/components/TransactionBalance.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/configs/configTypes.js
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/notifications/handlers/handlerNotification.mixin.js
  src/modules/notifications/helpers/formatNotification.js
  src/modules/send/ModuleSend.vue
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/settings/handler/gasPriceMixin.js
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapFee.vue
  src/modules/transfer-history/ModuleTransferHistory.vue
  src/utils/web3-provider/methods/utils.js
  src/views/TheWalletView.vue
  src/views/components-default/HomeFeaturesSend.vue
Labels: Ready, v6
