Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2021-02, with the labels that each got.

#2807 create handler for create wallet, implement mnemonic create wallet
  package-lock.json
  package.json
  src/modules/create-wallet/ModuleCreateWalletSoftware.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/handlers/handlerCreateWallet.js
  src/modules/create-wallet/handlers/helpers.js
  src/modules/wallets/utils/helpers.js
Labels: Ready, v6

#2797 devop/send-tx-tweaks [v6]
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/balance-block/BalanceBlock.vue
  src/helpers/addressUtils.js
  src/helpers/gasPriceHelper.js
  src/helpers/validateHexString.js
  src/modules/wallets/Wallets.vue
  src/modules/wallets/components/confirmation/transaction-confirmation/TransactionConfirmation.vue
  src/modules/wallets/components/wallet-card/WalletCard.vue
  src/modules/wallets/pages/dashboard/Dashboard.vue
  src/modules/wallets/pages/send/send-tx/SendTx.vue
  src/modules/wallets/pages/send/send-tx/errors.js
  src/modules/wallets/pages/send/send-tx/index.js
  src/modules/wallets/utils/WalletInterface.js
  src/modules/wallets/utils/hardware/bcvault/index.js
  src/modules/wallets/utils/hardware/bitbox/index.js
  src/modules/wallets/utils/hardware/bitbox02/index.js
  src/modules/wallets/utils/hardware/coolwallet/index.js
  src/modules/wallets/utils/hardware/keepkey/index.js
  src/modules/wallets/utils/hardware/ledger/index.js
  src/modules/wallets/utils/hardware/secalot/index.js
  src/modules/wallets/utils/hardware/trezor/index.js
  src/modules/wallets/utils/hybrid/MEWconnect/index.js
  src/modules/wallets/utils/hybrid/WalletConnect/index.js
  src/modules/wallets/utils/hybrid/WalletLink/index.js
  src/modules/wallets/utils/software/mnemonic/index.js
  src/store/global/index.js
  src/store/global/mutations.js
  src/store/global/state.js
  src/store/index.js
  src/store/wallet/actions.js
  src/store/wallet/getters.js
  src/store/wallet/index.js
  src/utils/web3-provider/index.js
  src/utils/web3-provider/methods/eth_accounts.js
  src/utils/web3-provider/methods/eth_coinbase.js
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/utils/web3-provider/methods/eth_signTransaction.js
  src/utils/web3-provider/methods/net_version.js
  src/utils/web3-provider/providers/etherscan-provider.js
  src/utils/web3-provider/providers/etherscan-request-manager.js
  src/utils/web3-provider/providers/given-provider.js
  src/utils/web3-provider/providers/http-provider.js
  src/utils/web3-provider/providers/http-request-manager.js
  src/utils/web3-provider/providers/pocket-provider.js
  src/utils/web3-provider/providers/pocket-request-manager.js
  src/utils/web3-provider/providers/ws-provider.js
  tests/unit/__mocks__/networksMock.js
Labels: Ready, v6

#2814 V6/dashboard
  package-lock.json
  package.json
  src/apollo/queries/tokens/index.js
  src/apollo/queries/wallets/index.js
  src/apollo/queries/wallets/wallets.graphql
  src/assets/images/currencies/dai.png
  src/assets/images/currencies/knc.png
  src/assets/images/currencies/link.png
  src/assets/images/currencies/usdc.png
  src/assets/images/currencies/usdt.png
  src/components/menu-desktop/SiteMenu.vue
  src/components/menu-mobile/Menu.vue
  src/components/swap/Swap.vue
  src/core/router/helpers.js
  src/core/router/routes-wallet.js
  src/core/store/wallet/actions.js
  src/core/store/wallet/getters.js
  src/core/store/wallet/mutations.js
  src/core/store/wallet/state.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
  src/dapps/unstoppable-domains/components/UnstoppableAddOwnedDomainOverlay.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationTransaction.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/decision-tree/data/md/_Notgiven_hash.md
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send/tests/send-tx.spec.js
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/tests/changelly.spec.js
  src/modules/swap/tests/dexag.spec.js
  src/modules/toast/ModuleToast.vue
  src/modules/toast/handler/handlerToast.js
  src/modules/tools/ModuleToolsWatchOnly.vue
  src/views/TheWalletView.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-wallet/TheDashboardLayout.vue
  src/views/layouts-wallet/TheNFTManagerLayout.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Ready, v6

#2773 v6/hardware wallets update
  package-lock.json
  package.json
  src/modules/wallets/components/access-wallet-overlay/AccessWalletOverlay.vue
  src/modules/wallets/components/access-wallet-overlay/HardwareWallets/Ledger/Ledger.vue
  src/modules/wallets/components/hardware-access-overlay/HardwareAccessOverlay.vue
  src/modules/wallets/utils/hardware/keepkey/index.js
Labels: Ready, v6

#2808 Bug/coolwallet pairing issue [v5]
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/wallets/hardware/coolwallet/errorHandler.js
  src/wallets/hardware/coolwallet/index.js
Labels: Bug, Ready, v5

#2796 merge back master to develop
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#2824 Fix Send My CryptoKitties UI issues for Russian language
  CHANGELOG.md
  fetchLists/lists/tokens.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
Labels: Bug, Ready, v5

#2828 Devop/staked status exited
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/Staked/components/ExitedPopup/ExitedPopup.scss
  src/dapps/Staked/components/ExitedPopup/ExitedPopup.vue
  src/dapps/Staked/components/ExitedPopup/index.js
  src/dapps/Staked/containers/Status/Status.scss
  src/dapps/Staked/containers/Status/Status.vue
  src/scss/GlobalVariables.scss
  src/translations/dapps-staked/en_US.json
Labels: Devop, v5

#2830 exclude from update
  package-test.js
Labels: Devop, Ready

#2827 release/v5.7.20
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/components/DropDownAddressSelector/DropDownAddressSelector.scss
  src/components/DropDownAddressSelector/DropDownAddressSelector.vue
  src/dapps/Staked/components/ExitedPopup/ExitedPopup.scss
  src/dapps/Staked/components/ExitedPopup/ExitedPopup.vue
  src/dapps/Staked/components/ExitedPopup/index.js
  src/dapps/Staked/containers/Status/Status.scss
  src/dapps/Staked/containers/Status/Status.vue
  src/layouts/InterfaceLayout/containers/NFTManagerContainer/components/NftDetails/NftDetails.vue
  src/layouts/InterfaceLayout/containers/SendCurrencyContainer/SendCurrencyContainer.vue
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  src/scss/GlobalVariables.scss
  src/translations/dapps-staked/en_US.json
  src/wallets/hardware/coolwallet/errorHandler.js
  src/wallets/hardware/coolwallet/index.js
Labels: Ready, Release, v5

#2834 fix changelog, exclude packages
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.vue
Labels: Devop, Ready

#2832 add canContinue = false on init
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.vue
Labels: v5

#2839 Devop/replace token contract
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/graphQLHelpers.js
  vueConfig/connections.js
Labels: Devop, Ready

#2831 merge back master to develop
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/Staked/Staked.vue
  src/dapps/Staked/components/Stepper/Stepper.vue
Labels: Devop, Ready

#2768 V6/ens
  package-lock.json
  package.json
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/manage/ManageMulticoins.vue
  src/dapps/ens-manager-dapp/components/manage/ManageRenew.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTxtRecords.vue
  src/dapps/ens-manager-dapp/components/manage/ManageUploadWebsite.vue
  src/dapps/ens-manager-dapp/components/register/Register.vue
  src/dapps/ens-manager-dapp/components/register/RegisterComplete.vue
  src/dapps/ens-manager-dapp/components/register/RegisterRequest.vue
  src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
  src/dapps/ens-manager-dapp/handlers/handlerEnsManager.js
  src/dapps/ens-manager-dapp/handlers/handlerMulticoins.js
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/dapps/ens-manager-dapp/handlers/handlerSupportedCoins.js
  src/dapps/ens-manager-dapp/handlers/helpers/helperGetHashFromFile.js
  src/dapps/ens-manager-dapp/handlers/helpers/helperIpfs.js
  src/dapps/ens-manager-dapp/handlers/helpers/helperTld.js
  src/dapps/ens-manager-dapp/handlers/helpers/helperUploadFileToIpfs.js
  src/dapps/ens-manager-dapp/modules/ModuleManageDomain.vue
  src/dapps/ens-manager-dapp/modules/ModuleRegisterDomain.vue
  src/modules/address-book/modules/ModuleAddressBook.vue
  src/translations/dapps-ens/en_US.json
Labels: Ready, v6

#2842 V6/refactor components
  package-lock.json
  package.json
  src/components/ellipsisBlock/EllipsisBlock.vue
  src/components/interface-wrap/InterfaceWrap.vue
  src/components/menu-desktop/Menu.vue
  src/components/menu-desktop/SiteMenu.vue
  src/components/mewSuperButton/MewSuperButton.vue
  src/components/qr-code-modal/QRcode.vue
  src/components/sign-message-overlay/SignMessageOverlay.vue
  src/components/tokenTable/TokenTable.vue
  src/core/components/AppSwap.vue
  src/modules/contract/ModuleContractDeploy.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/notifications/components/in/In.vue
  src/modules/notifications/components/out/Out.vue
  src/modules/notifications/components/swap/Swap.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/modules/tools/components/ToolsTableContainer.vue
  src/modules/wallets/components/hardware-access-overlay/HardwareAccessOverlay.vue
  src/modules/wallets/components/software-access-overlay/SoftwareAccessOverlay.vue
  src/modules/wallets/pages/access/Access.vue
  src/modules/wallets/pages/access/hardware-wallets/HardwareWallets.vue
  src/modules/wallets/pages/access/mobile-apps/MobileApps.vue
  src/modules/wallets/pages/send/send-offline/SendOffline.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-wallet/TheDashboardLayout.vue
  src/views/layouts-wallet/TheDeployContractLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
  src/views/layouts-wallet/TheNFTManagerLayout.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: WIP, v6

#2852 Fix/offline helper ETC [v5]
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
Labels: Bug, Ready, v5

#2840 Reset stepper on init
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/Staked/Staked.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
Labels: Bug, v5

#2854 release/v5.7.21
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/Staked/Staked.vue
  src/layouts/InterfaceLayout/InterfaceLayout.vue
  src/layouts/InterfaceLayout/graphQLHelpers.js
  src/layouts/SendOfflineHelper/SendOfflineHelper.vue
  vueConfig/connections.js
Labels: Ready, Release, v5

#2856 use older npm-force-resolutions
  package-lock.json
  package.json
Labels: Bug, Ready

#2845 v6/devop-commitlint-branch-names
  CHANGELOG.md
  checkBranch.sh
  commitlint.config.js
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#2848 V6/fix wallet layouts
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/styles/GlobalStyles.scss
  src/components/white-sheet/WhiteSheet.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/decision-tree/DecisionTree.scss
  src/modules/send/ModuleSend.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletFooter.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-wallet/TheDashboardLayout.vue
  src/views/layouts-wallet/TheNFTManagerLayout.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Ready, v6

#2809 V6/aave dapps
  package-lock.json
  package.json
  src/dapps/aave-dapp/handlers/graphQLHelpers.js
  src/dapps/aave-dapp/handlers/handlerAave.js
  src/dapps/aave-dapp/handlers/helpers.js
Labels: Feature, Ready, v6
