Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-05, with the labels that each got.

#3748 fix: moonpay ui issues
  changelog/fix-3748.md
  package-lock.json
  package.json
  src/assets/images/backgrounds/bg-party-popper.svg
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
Labels: Devop, UI, v6

#3661 devop: replace ens management header to new dapp header
  changelog/fix-3661.md
  package-lock.json
  package.json
  src/assets/images/icons/icon-dapp-eth-blocks.svg
  src/assets/images/icons/icon-dapp-eth.svg
  src/assets/images/icons/icon-ens-manager-white-bg.svg
  src/core/components/TheWrapperDapp.vue
  src/core/configs/configRoutes.js
  src/core/router/helpers.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/configsRoutes.js
  src/dapps/ens-manager-dapp/handlers/helpers/supportedNetworks.js
  src/dapps/ens-manager-dapp/metainfo.js
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/dapps/staked-dapp/configsRoutes.js
  src/dapps/staked-dapp/handlers/supportedNetworks.js
  src/dapps/staked-dapp/metainfo.js
Labels: Devop, Ready, v6

#3786 fix: 🐛 erc owner balance not an object
  changelog/fix-3786.md
  package-lock.json
  package.json
  src/modules/nft-manager/handlers/handlerNft.mixin.js
Labels: Ready, v6

#3776 Devop: Bluetooth Api
  changelog/devop-3776.md
  package-lock.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/errorHandler.js
Labels: Devop, v6

#3816 fix: 🐛 sentry type error jsonrpc request
  changelog/fix-3816.md
  package-lock.json
  package.json
  src/main/errorHandler.js
Labels: Bug, v6

#3822 chore: 👷 add unit.js converter
  changelog/devop-3822.md
  src/core/helpers/unit.js
Labels: Devop, Ready

#3814 Fix: Sentry four errors
  changelog/fix-3814.md
  package-lock.json
  src/main/errorHandler.js
Labels: Fixed, v6

#3797 Feature/integrate ledger x
  changelog/feature-3797.md
  changelog/fix-3786.md
  changelog/fix-3816.md
  package-lock.json
  package.json
  src/assets/images/hardware-wallets/NanoX_PROD_CAM06.jpg
  src/assets/images/icons/hardware-wallets/LEDGER-WORDMARK-BLACK-RGB.svg
  src/assets/images/icons/hardware-wallets/Ledger nano x.svg
  src/assets/images/icons/hardware-wallets/Ledger-Nano-X-Label-Icon.svg
  src/assets/images/icons/hardware-wallets/Ledger-Nano-X-image.svg
  src/core/store/wallet/actions.js
  src/core/store/wallet/mutations.js
  src/core/store/wallet/state.js
  src/main/errorHandler.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedgerX.vue
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
  src/translations/errors-global/en_US.json
  src/translations/errors-ledger/en_US.json
Labels: Feature, Ready, v6

#3787 fix: 🐛 failed to fetch pool api
  changelog/fix-3787.md
  package-lock.json
  src/dapps/stakewise/handlers/stakewiseHandler.js
Labels: Ready, v6

#3604 devop: 🔧 ethblocks update
  changelog/devop-3604.md
  package-lock.json
  package.json
  src/core/components/TheWrapperDapp.vue
  src/core/plugins/vuetify.js
  src/dapps/eth-blocks/TheEthBlocksLayout.vue
  src/dapps/eth-blocks/components/BlockInfo.vue
  src/dapps/eth-blocks/components/BlockInfoAlert.vue
  src/dapps/eth-blocks/components/BlockQuickViewPopup.vue
  src/dapps/eth-blocks/components/BlockResultComponent.vue
  src/dapps/eth-blocks/components/BlockSearch.vue
  src/dapps/eth-blocks/components/BlocksSort.vue
  src/dapps/eth-blocks/components/DateSelectorPopup.vue
  src/dapps/eth-blocks/configsRoutes.js
  src/dapps/eth-blocks/handlers/handlerBlock.js
  src/dapps/eth-blocks/handlers/helpers/common.js
  src/dapps/eth-blocks/handlers/helpers/multicall.js
  src/dapps/eth-blocks/metainfo.js
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockInfo.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksDateSearch.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksMint.vue
  src/dapps/eth-blocks/store/actions.js
  src/dapps/eth-blocks/store/configs.js
  src/dapps/eth-blocks/store/mutations.js
  src/dapps/eth-blocks/store/state.js
  src/main.js
Labels: Devop, Ready

#3817 fix: 🐛 check public key
  changelog/fix-3817.md
  package-lock.json
  src/modules/access-wallet/common/WalletInterface.js
Labels: Bug, Ready, v6

#3809 fix: 🐛 moonpay fetch handler
  changelog/fix-3809.md
  package-lock.json
  src/modules/moon-pay/components/MoonPaySellComponent.vue
Labels: Bug, Ready, v6

#3612 devop: 🔧 offline build
  .github/workflows/build-offline-zip.yml
  ENV_VARS.js
  builds/defaultConfig.js
  builds/liveConfig.js
  builds/offlineConfig.js
  changelog/devop-3612.md
  changelog/feat-3484.md
  changelog/fix-3713.md
  package-lock.json
  package.json
  src/core/configs/configRoutes.js
  src/core/router/index.js
  src/core/router/routes-offline-default.js
  src/core/router/routes-offline-wallet.js
  src/core/router/routes-wallet.js
  src/core/store/wallet/actions.js
  src/core/store/wallet/mutations.js
  src/core/store/wallet/state.js
  src/main.js
  src/main/errorHandler.js
  src/main/liveMain.js
  src/main/mainApp.vue
  src/main/offlineApp.vue
  src/main/offlineMain.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send-offline/ModuleSendOffline.vue
  src/modules/send-offline/components/SendLowBalanceNotice.vue
  src/modules/send-offline/errors.js
  src/modules/send-offline/handlers/handlerSend.js
  src/modules/send-offline/tests/send-tx.spec.js
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/translations/send-tx/en_US.json
  src/views/TheOfflineDefaultView.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheToolsLayout.vue
  src/views/layouts-wallet/TheSendTransactionOfflineLayout.vue
  vue.config.js
Labels: Devop, Ready, v6

#3823 fix: 🐛 selecting currency in sell crash
  changelog/fix-3823.md
  package-lock.json
  src/modules/moon-pay/components/MoonPaySellComponent.vue
Labels: Bug, Ready, v6

#3824 fix: 🐛 module send error null
  changelog/fix-3824.md
  src/modules/send/ModuleSend.vue
Labels: Bug, Ready, v6

#3825 fix: 🐛 select currency in sell crash
  changelog/fix-3825.md
  package-lock.json
  package.json
  src/modules/moon-pay/components/MoonPaySellComponent.vue
Labels: Bug, v6

#3828 Fix: BSC swap undefined
  builds/liveConfig.js
  builds/offlineConfig.js
  changelog/fix-3787.md
  changelog/fix-3824.md
  changelog/fix-3828.md
  package-lock.json
  src/modules/access-wallet/common/helpers.js
  src/modules/swap/ModuleSwap.vue
Labels: Fixed, v6

#3710 feature: ens-dapp-balance-check
  changelog/fix-3710.md
  changelog/fix-3828.md
  package-lock.json
  package-test.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/manage/ManageRenew.vue
  src/dapps/ens-manager-dapp/components/register/Register.vue
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/dapps/ens-manager-dapp/modules/ModuleManageDomain.vue
  src/dapps/ens-manager-dapp/modules/ModuleRegisterDomain.vue
  src/translations/dapps-ens/en_US.json
  src/v5_translations/dapps-ens/en_US.json
  src/v5_translations/dapps-ens/es_ES.json
  src/v5_translations/dapps-ens/ja_JP.json
  src/v5_translations/dapps-ens/ko_KR.json
  src/v5_translations/dapps-ens/ru_RU.json
  src/v5_translations/dapps-ens/zh_CN.json
Labels: Feature, Ready, v6

#3838 Hotfix/offline
  .github/workflows/build-offline-zip.yml
  .github/workflows/github-release.yml
  .github/workflows/upload-translations.yml
  CHANGELOG.md
  changelog/fix-3838.md
  package-lock.json
  package.json
  scripts/release.sh
  src/modules/tools/ModuleToolsOfflineHelper.vue
Labels: Release, Ready

#3842 release: 🔥 v6.5.4-hotfix.1
  .github/workflows/build-offline-zip.yml
  .github/workflows/github-release.yml
  .github/workflows/upload-translations.yml
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/release.sh
  src/modules/tools/ModuleToolsOfflineHelper.vue
Labels: Release, Ready

#3851 Chore/remove v5
  changelog/chore-3851.md
  package-test.js
  src/views/components-default/TheDefaultHeader.vue
Labels: Devop, Ready

#3831 fix: 🐛 new token table ethereum icon
  changelog/fix-3831.md
  src/assets/images/networks/eth.svg
  src/modules/balance/ModuleTokens.vue
Labels: Ready, UI, v6

#3836 fix: 🐛 wallet card loading animation
  changelog/fix-3836.md
  src/modules/balance/ModuleBalanceCard.vue
Labels: Bug, Ready, UI, v6

#3840 fix: 🐛 offline helper show copy update
  changelog/fix-3840.md
  package-lock.json
  src/modules/tools/ModuleToolsOfflineHelper.vue
Labels: Ready, v6

#3834 Fix: sentry return value not valid
  changelog/fix-3834.md
  package-lock.json
  src/main/errorHandler.js
Labels: Fixed, v6

#3829 Fix: sentry expected private key 32 length
  changelog/fix-3829.md
  src/modules/access-wallet/common/WalletInterface.js
Labels: Fixed, v6

#3827 fix: 🐛 sentry error handler null
  changelog/fix-3827.md
  src/main/errorHandler.js
Labels: Bug, v6

#3855 fix: keystore file button border
  changelog/fix-3827.md
  changelog/fix-3829.md
  changelog/fix-3834.md
  changelog/fix-3840.md
  changelog/fix-3855.md
  package.json
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
Labels: UI, v6

#3850 fix: 🐛 wallet side menu selection bug
  changelog/fix-3850.md
  package-lock.json
  package.json
  src/assets/images/icons/icon-contract-enable.svg
  src/assets/images/icons/icon-dapp-center-enable.svg
  src/assets/images/icons/icon-dashboard-enable.svg
  src/assets/images/icons/icon-logout-enable.svg
  src/assets/images/icons/icon-message-enable.svg
  src/assets/images/icons/icon-nft.svg
  src/assets/images/icons/icon-send-enable.svg
  src/assets/images/icons/icon-setting-enable.svg
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Bug, Ready, UI, v6
