Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-12, with the labels that each got.

#4367 devop: update dashboard placeholder
  changelog/devop-4367.md
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceLoader.vue
Labels: Devop, Ready, UI, v6

#4373 fix: fix download keystore file button
  changelog/fix-4373.md
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
Labels: Bug, Ready, v6

#4387 fix: 🐛 nonce issue
  CHANGELOG.md
  changelog/fix-4387.md
  package-lock.json
  package.json
  src/modules/tools/ModuleToolsOfflineHelper.vue
Labels: Ready, Fixed

#4410 Fix/metamask
  CHANGELOG.md
  package-test.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/TheWalletView.vue
Labels: Ready, Fixed

#4406 release: 🔥 v6.6.11-hotfix.1
  CHANGELOG.md
  changelog/fix-4387.md
  package-lock.json
  package-test.js
  package.json
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/TheWalletView.vue
Labels: Release, Ready

#4415 chore: 👷 update privacy policy
  CHANGELOG.md
  package-lock.json
  package.json
  src/translations/privacy-policy/en_US.json
  src/views/layouts-default/ThePrivacyPolicyLayout.vue
Labels: Devop, Ready

#4417 Devop/sync staging
  CHANGELOG.md
Labels: Devop, Ready

#4416 release: 🔥 v6.6.11-hotfix.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/translations/privacy-policy/en_US.json
  src/views/layouts-default/ThePrivacyPolicyLayout.vue
Labels: Release, Ready

#4384 devop: 🔧 use loadingWalletInfo, finish loading state for balance card
  CHANGELOG.md
  changelog/devop-4367.md
  changelog/fix-4364.md
  changelog/fix-4370.md
  changelog/fix-4387.md
  changelog/fix-4399.md
  changelog/fix-4404.md
  changelog/ui-4384.md
  package-lock.json
  package-test.js
  package.json
  src/core/store/external/actions.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/stakewise/TheStakewiseLayout.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/translations/privacy-policy/en_US.json
  src/views/TheWalletView.vue
  src/views/layouts-default/ThePrivacyPolicyLayout.vue
Labels: Devop, Ready

#4347 fix: 🐛 aave approval flow
  changelog/fix-4347.md
  package-lock.json
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
Labels: Ready, Fixed

#4407 devop/sync-develop
  changelog/devop-4367.md
  changelog/devop-4396.md
  changelog/fix-4347.md
  changelog/fix-4356.md
  changelog/fix-4358.md
  changelog/fix-4364.md
  changelog/fix-4370.md
  changelog/fix-4373.md
  changelog/fix-4379.md
  changelog/fix-4380.md
  changelog/fix-4383.md
  changelog/fix-4388.md
  changelog/fix-4399.md
  changelog/fix-4404.md
  changelog/ui-4384.md
  package-lock.json
  package-test.js
  package.json
  src/core/store/external/actions.js
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTxtRecords.vue
  src/dapps/eth-blocks/components/BlockInfo.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/dapps/stakewise/TheStakewiseLayout.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleBalanceLoader.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/send/ModuleSend.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
  src/utils/networks/types/BSC.js
  src/utils/networks/types/ETC.js
  src/utils/networks/types/ETH.js
  src/utils/networks/types/GO.js
  src/utils/networks/types/GOERLI.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/MINTME.js
  src/utils/networks/types/MOONBEAM.js
  src/utils/networks/types/MOONRIVER.js
  src/utils/networks/types/XDC.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready

#4422 release: 🔥 v6.6.11-hotfix.3
  package-lock.json
  package-test.js
  package.json
  src/translations/terms-of-conditions/en_US.json
  src/views/layouts-default/TheTermsOfServiceLayout.vue
Labels: Release, Ready

#4424 Fix/bitbox issue
  changelog/fix-4424.md
  package-lock.json
  package-test.js
  package.json
  src/core/helpers/matchNetwork.js
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/access-wallet/software/handlers/pathHelper.js
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
  src/translations/terms-of-conditions/en_US.json
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/views/layouts-default/TheTermsOfServiceLayout.vue
Labels: Ready, Fixed

#4431 Devop/build
  package-test.js
Labels: Devop, Ready

#4420 release: 🔥 v6.6.12
  CHANGELOG.md
  changelog/fix-4387.md
  package-lock.json
  package-test.js
  package.json
  src/core/helpers/matchNetwork.js
  src/core/store/external/actions.js
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/manage/ManageTxtRecords.vue
  src/dapps/eth-blocks/components/BlockInfo.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/dapps/stakewise/TheStakewiseLayout.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/software/handlers/pathHelper.js
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleBalanceLoader.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/send/ModuleSend.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
  src/utils/networks/types/BSC.js
  src/utils/networks/types/ETC.js
  src/utils/networks/types/ETH.js
  src/utils/networks/types/GO.js
  src/utils/networks/types/GOERLI.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/MINTME.js
  src/utils/networks/types/MOONBEAM.js
  src/utils/networks/types/MOONRIVER.js
  src/utils/networks/types/XDC.js
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Release, Ready

#4413 fix: moonpay input size
  CHANGELOG.md
  CODEOWNERS
  changelog/devop-4367.md
  changelog/devop-4396.md
  changelog/fix-4347.md
  changelog/fix-4356.md
  changelog/fix-4358.md
  changelog/fix-4364.md
  changelog/fix-4370.md
  changelog/fix-4373.md
  changelog/fix-4375.md
  changelog/fix-4379.md
  changelog/fix-4380.md
  changelog/fix-4383.md
  changelog/fix-4387.md
  changelog/fix-4388.md
  changelog/fix-4395.md
  changelog/fix-4397.md
  changelog/fix-4399.md
  changelog/fix-4404.md
  changelog/fix-4413.md
  changelog/ui-4384.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/components/mew-menu-popup/MewMenuPopup.vue
  src/core/helpers/matchNetwork.js
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/software/handlers/pathHelper.js
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
  src/translations/terms-of-conditions/en_US.json
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/views/layouts-default/TheTermsOfServiceLayout.vue
Labels: Ready, UI, v6

#4397 fix: fix input height on send page
  changelog/fix-4375.md
  changelog/fix-4397.md
  package-lock.json
  src/modules/send/ModuleSend.vue
Labels: Ready, UI, v6

#4335 Devop: Update Buy/Sell ETH Component
  changelog/devop-4335.md
  changelog/devop-4408.md
  changelog/devop-4418.md
  changelog/fix-4389.md
  changelog/fix-4428.md
  changelog/fix-4429.md
  changelog/ui-4425.md
  package-audit.js
  package-lock.json
  package-test.js
  src/core/components/AppNetworkSettingsModal.vue
  src/core/components/AppTransactionFee.vue
  src/core/configs/configRoutes.js
  src/core/mixins/buyMore.mixin.js
  src/core/router/routes-offline-wallet.js
  src/core/router/routes-wallet.js
  src/core/store/global/actions.js
  src/core/store/wallet/actions.js
  src/dapps/aave-dapp/components/AaveTable.vue
  src/dapps/ens-manager-dapp/components/manage/ManageRenew.vue
  src/dapps/ens-manager-dapp/components/register/Register.vue
  src/dapps/eth-blocks/components/BlockInfo.vue
  src/dapps/eth-blocks/components/BlockInfoAlert.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/stakewise/components/StakewiseStaking.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/dapps/unstoppable-domains-dapp/UnstoppableDomain.vue
  src/dapps/unstoppable-domains-dapp/components/UnstoppableDomainBuyOverlay.vue
  src/main/mainApp.vue
  src/modules/balance/components/BalanceEmptyBlock.vue
  src/modules/buy-sell/ModuleBuySell.vue
  src/modules/buy-sell/assets/moonpay-logo.svg
  src/modules/buy-sell/components/BuyComponent.vue
  src/modules/buy-sell/components/BuyProviderComponent.vue
  src/modules/buy-sell/components/SellComponent.vue
  src/modules/buy-sell/components/TokenSelect.vue
  src/modules/buy-sell/components/tokenList.js
  src/modules/buy-sell/handlers/handlerOrder.js
  src/modules/buy-sell/helpers/index.js
  src/modules/network/ModuleNetwork.vue
  src/modules/nft-manager/components/NftManagerSend.vue
  src/modules/notifications/helpers/formatNotification.js
  src/modules/send/ModuleSend.vue
  src/modules/send/components/SendLowBalanceNotice.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/swap/ModuleSwap.vue
  src/utils/networks/types/XDC.js
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: UI, v6

#4435 fix/ui-scrolling
  CHANGELOG.md
  changelog/ui-4433.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/core/store/external/actions.js
  src/core/store/wallet/mutations.js
  src/modules/balance/ModuleTokens.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
Labels: Release, Ready

#4439 release: 🔥 v6.6.12-hotfix.1
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/core/store/external/actions.js
  src/modules/balance/ModuleTokens.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
Labels: Release, Ready

#4444 release: 🔥 v6.6.12-hotfix.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release, Ready
