Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-09, with the labels that each got.

#4157 Devop/release bugs
  .github/workflows/github-release.yml
  changelog/devop-4157.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  scripts/generateOfflineFiles.sh
  scripts/generateReleaseFiles.sh
  scripts/signFiles.sh
  src/core/helpers/blockies.js
  src/core/helpers/isNew.js
  src/core/router/routes-offline-wallet.js
  src/core/router/routes-wallet.js
  src/core/store/global/actions.js
  src/core/store/wallet/actions.js
  src/dapps/aave-dapp/components/overlays/AaveBorrowOverlay.vue
  src/dapps/aave-dapp/metainfo.js
  src/helpers/blockies.js
  src/helpers/copy.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/settings/handler/gasPriceMixin.js
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/ModuleSwapRates.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, Fixed

#4031 devop: ledger prompt
  changelog/devop-4031.md
  changelog/devop-4125.md
  changelog/devop-4138.md
  changelog/devop-4150.md
  changelog/devop-4151.md
  changelog/devop-4154.md
  changelog/fix-4142.md
  changelog/fix-4143.md
  changelog/fix-4146.md
  changelog/fix-4148.md
  changelog/fix-4153.md
  changelog/fix-4155.md
  changelog/fix-4160.md
  changelog/ui-4147.md
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/icon-mew-cx.png
  src/assets/images/icons/icon-mew-logo.png
  src/core/store/custom/actions.js
  src/core/store/custom/mutations.js
  src/core/store/global/actions.js
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/stakewise/modules/ModuleStakewiseRewards.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/config.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/confirmation/handlers/errorHandler.js
  src/modules/send/ModuleSend.vue
  src/views/TheWalletView.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
Labels: Devop, Ready

#4150 devop: track stakewise
  changelog/devop-4150.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/stakewise/modules/ModuleStakewiseRewards.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
Labels: Devop, Ready

#4151 devop: add matomo tracking to aave
  changelog/devop-4151.md
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
Labels: Devop, Ready, v6

#4153 Fix: mnemonic addressbook nickname error
  changelog/fix-4153.md
  package-lock.json
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
Labels: Bug, Fixed, v6

#4154 devop: change placeholder text for staked search bar
  changelog/devop-4154.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
Labels: Devop, Ready, v6

#4155 devop: 🔧 added nonce message
  changelog/fix-4155.md
  src/modules/confirmation/handlers/errorHandler.js
Labels: Bug, v6

#4160 Fix: 🐛 balance shows previous network
  changelog/fix-4160.md
  src/core/store/global/actions.js
Labels: Bug, v6

#4044 chore: 👷 use lodash isNaN
  changelog/sentry-4044.md
  package-lock.json
  package-test.js
  package.json
  src/core/helpers/numberFormatHelper.js
Labels: Devop, Ready

#4133 Fix: undefined swap tooltip
  changelog/devop-4152.md
  changelog/devop-4162.md
  changelog/fix-3952.md
  changelog/fix-4133.md
  changelog/fix-4140.md
  changelog/fix-4163.md
  changelog/fix-4165.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/dapps/aave-dapp/metainfo.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/eth-blocks/components/BlockSearch.vue
  src/dapps/stakewise/modules/ModuleStakewiseRewards.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/views/TheWalletView.vue
Labels: Bug, Fixed, v6

#4152 devop: 🔧 add ens matomo tracking
  changelog/devop-4152.md
  fetchLists/lists/tokens.json
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
Labels: v6

#4181 chore: 👷 add analytics mixin in ens
  changelog/fix-4181.md
  package-test.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
Labels: Devop, Ready

#4128 fix: fix enkrypt button links and add mobile enkrypt buttons
  changelog/fix-4128.md
  src/core/mixins/enkryptMarketing.mixin.js
  src/views/components-default/HomeLanding.vue
Labels: Devop, Ready, UI, v6

#4118 feature: ✨ unstoppable reverse resolver
  changelog/feat-4118.md
  connections.js
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/dapps/unstoppable-domains-dapp/UnstoppableDomain.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/name-resolver/index.js
  src/modules/name-resolver/resolvers/uns.js
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send/ModuleSend.vue
Labels: Bug, v6

#4196 Devop/offline test and build
  .github/workflows/add-offline-build-release-pr.yml
  package-lock.json
  package-test.js
  package.json
  src/modules/send-offline/ModuleSendOffline.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  tests/e2e/specs/offline-access-and-sign-tx.js
  tests/e2e/test-files/generated-offline-tx-1662592753967.json
Labels: Devop, Ready

#4158 Devop: 🔧 Symbol is not editable
  changelog/devop-4158.md
  package-lock.json
  src/modules/balance/components/TokenAddCustom.vue
Labels: Devop, v6

#4179 fix: remove up down buttons for input fields
  changelog/fix-4179.md
  src/assets/styles/GlobalStyles.scss
Labels: Ready, UI, v6

#4191 fix: offline helper network selection bug
  changelog/fix-4191.md
  package-test.js
  src/modules/network/components/NetworkSwitch.vue
Labels: Bug, Ready, v6

#4200 Devop: 🔧 Hide x button
  changelog/devop-4200.md
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/SuccessModal.vue
Labels: Devop, UI, v6

#4201 Devop: 🔧 Added missing req message
  changelog/devop-4201.md
  src/modules/swap/ModuleSwap.vue
Labels: Devop, v6

#4188 fix: 🐛 detect negative input after network switch
  changelog/fix-4188.md
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready, v6

#4193 ui: update buy eth banner
  changelog/fix-4209.md
  changelog/fix-4213.md
  changelog/ui-4193.md
  package-lock.json
  package-test.js
  package.json
  src/core/helpers/matchNetwork.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/views/components-wallet/TheWalletHeader.vue
Labels: Ready, UI

#4218 Fix/develop bugs
  changelog/fix-4218.md
  connections.js
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppQrCode.vue
  src/core/helpers/commonGenerator.js
  src/dapps/eth-blocks/components/DateSelectorPopup.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockInfo.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/message/ModuleMessageSign.vue
  src/modules/message/ModuleMessageVerify.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/views/TheWalletView.vue
  src/views/layouts-default/TheToolsLayout.vue
Labels: Ready, Fixed
