Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-04, with the labels that each got.

#3766 fix: metamask no balance error
  changelog/fix-3766.md
  package-lock.json
  package.json
  src/modules/send/ModuleSend.vue
Labels: Bug, v6

#3758 feat: ✨ eth2 keystore file generator in tools section
  changelog/feat-3758.md
  package-lock.json
  package.json
  src/core/configs/configRoutes.js
  src/modules/access-wallet/software/components/AccessWalletKeystore.vue
  src/modules/tools/ModuleToolsGenerateKeystore/ModuleToolsGenerateKeystore.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/StepOne.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/StepTwo.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheToolsLayout.vue
Labels: Feature, Ready, v6

#3752 fix: 🐛 verify base paths for ledger and keepkey is string
  changelog/fix-3752.md
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/handlers/hardwares/keepkey/index.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/index.js
Labels: Ready, Fixed, v6

#3738 Fix: sentry invalid attempt to iterate
  changelog/fix-3738.md
  package-lock.json
  src/modules/contract/handlers/common.js
Labels: Bug, v6

#3727 chore: 👷 nft-gas-error-send
  changelog/chore-3727.md
  changelog/fix-3727.md
  changelog/fix-3738.md
  package-lock.json
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/nft-manager/components/NftManagerSend.vue
  src/modules/nft-manager/handlers/handlerNftManager.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Bug, Ready, Fixed, v6

#3769 feature: add block explorer links
  changelog/feat-3769.md
  package-lock.json
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
Labels: Feature, Ready, v6

#3740 Sentry: Request String MewAPI
  changelog/devop-3740.md
  package-lock.json
  src/main/errorHandler.js
  src/main/sentry.js
Labels: Bug, Fixed, v6

#3773 Devop: Hardware Stepper
  changelog/devop-3773.md
  package-lock.json
  package.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
Labels: Bug, Fixed, v6

#3721 feat: ✨ stakewise
  changelog/feat-3721.md
  connections.js
  package-audit.js
  package-lock.json
  src/assets/images/icons/icon-dapp-stakewise.svg
  src/assets/images/icons/icon-eth-gray.svg
  src/assets/styles/GlobalStyles.scss
  src/components/white-sheet/WhiteSheet.vue
  src/core/configs/configRoutes.js
  src/core/mixins/stake.mixin.js
  src/dapps/dappsStore.js
  src/dapps/ens-manager-dapp/components/claim/ClaimTokensSnackbar.vue
  src/dapps/metainfo-dapps.js
  src/dapps/stakewise/TheStakewiseLayout.vue
  src/dapps/stakewise/assets/icon-stakewise-green.svg
  src/dapps/stakewise/assets/icon-stakewise-purple.svg
  src/dapps/stakewise/assets/icon-stakewise-red.svg
  src/dapps/stakewise/components/StakewiseApr.vue
  src/dapps/stakewise/components/StakewiseRewards.vue
  src/dapps/stakewise/components/StakewiseStaking.vue
  src/dapps/stakewise/configsRoutes.js
  src/dapps/stakewise/handlers/abi/mewStakedContract.js
  src/dapps/stakewise/handlers/abi/pool.js
  src/dapps/stakewise/handlers/abi/rewardEthToken.js
  src/dapps/stakewise/handlers/abi/stakedEthToken.js
  src/dapps/stakewise/handlers/configs.js
  src/dapps/stakewise/handlers/helpers/supportedNetworks.js
  src/dapps/stakewise/handlers/stakewiseHandler.js
  src/dapps/stakewise/handlers/stakewiseStakeHandler.js
  src/dapps/stakewise/helpers/index.js
  src/dapps/stakewise/metainfo.js
  src/dapps/stakewise/modules/ModuleStakewiseRewards.vue
  src/dapps/stakewise/modules/ModuleStakewiseStake.vue
  src/dapps/stakewise/store/actions.js
  src/dapps/stakewise/store/configs.js
  src/dapps/stakewise/store/getters.js
  src/dapps/stakewise/store/index.js
  src/dapps/stakewise/store/mutations.js
  src/dapps/stakewise/store/state.js
  src/modules/send/ModuleSend.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/components-wallet/WalletPromoPopUp.vue
  src/views/components-wallet/WalletPromoSnackbar.vue
  src/views/layouts-wallet/TheDashboardLayout.vue
  src/views/layouts-wallet/TheDeployContractLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
Labels: Devop, Ready, v6

#3729 feature: ✨ intercom-set
  changelog/feature-3729.md
  package-lock.json
  src/main.js
Labels: Feature, Ready, v6

#3778 fix: 🐛 websocket
  changelog/fix-3778.md
  src/utils/web3-provider/providers/ws-provider.js
Labels: Ready, Fixed

#3782 chore: 👷 add stakewise cleanup
  changelog/fix-3782.md
  src/dapps/stakewise/metainfo.js
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/components-wallet/WalletPromoPopUp.vue
Labels: Ready, Fixed

#3784 release: 🔥 v6.5.2-hotfix.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/dapps/stakewise/metainfo.js
  src/utils/web3-provider/providers/ws-provider.js
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/components-wallet/WalletPromoPopUp.vue
Labels: Release, Ready

#3795 Devop/sync main
  changelog/devop-3795.md
Labels: Devop, Ready

#3764 devop: update new moonpay ui
  changelog/devop-3764.md
  package-lock.json
  package.json
  src/app.vue
  src/assets/images/icons/icon-simplex.svg
  src/assets/images/icons/moonpay/icon-apple-pay.svg
  src/assets/images/icons/moonpay/icon-bank.svg
  src/assets/images/icons/moonpay/icon-master.svg
  src/assets/images/icons/moonpay/icon-visa.svg
  src/main/errorHandler.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/moon-pay/handlers/handlerMoonpay.js
  src/views/components-default/HowItWorksMore.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, UI, v6

#3803 release: 🔥 v6.5.3
  CHANGELOG.md
  changelog/devop-3795.md
  changelog/fix-3804.md
  package-lock.json
  package.json
  src/app.vue
  src/assets/images/icons/icon-simplex.svg
  src/assets/images/icons/moonpay/icon-apple-pay.svg
  src/assets/images/icons/moonpay/icon-bank.svg
  src/assets/images/icons/moonpay/icon-master.svg
  src/assets/images/icons/moonpay/icon-visa.svg
  src/main/errorHandler.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/moon-pay/handlers/handlerMoonpay.js
  src/views/components-default/HowItWorksMore.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Release, Ready

#3770 fix/ hardware-wallet-custom-path
  changelog/fix-3770.md
  package-lock.json
  package.json
  src/core/store/custom/mutations.js
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
Labels: Ready, v6

#3777 Feature: dynamic data for articles
  changelog/feat-3777.md
  changelog/fix-3770.md
  connections.js
  package-lock.json
  src/app.vue
  src/core/store/article/actions.js
  src/core/store/article/getters.js
  src/core/store/article/index.js
  src/core/store/article/mutations.js
  src/core/store/article/state.js
  src/core/store/configs.js
  src/core/store/index.js
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/main.js
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapMsgStoreBtcEth.vue
  src/views/layouts-default/TheTermsOfServiceLayout.vue
Labels: Feature, Ready, v6

#3801 Devop/new nodes
  changelog/devop-3798.md
  changelog/devop-3801.md
  connections.js
  package-lock.json
  package.json
  src/assets/images/networks/xdc.svg
  src/modules/access-wallet/hardware/handlers/bip44/keepkeyPaths.js
  src/modules/access-wallet/hardware/handlers/bip44/ledgerPaths.js
  src/modules/access-wallet/hardware/handlers/bip44/mnemonicPaths.js
  src/modules/access-wallet/hardware/handlers/bip44/trezorPaths.js
  src/modules/access-wallet/hardware/handlers/configs/configPaths.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/appPaths.js
  src/utils/networks/nodes/index.js
  src/utils/networks/nodes/mintme-mew-ws.js
  src/utils/networks/nodes/xdcnetwork-ws.js
  src/utils/networks/types/MINTME.js
  src/utils/networks/types/XDC.js
  src/utils/networks/types/index.js
Labels: Devop, Ready
