Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-06, with the labels that each got.

#3870 devop: 🔧 fix github release generation
  .github/workflows/github-release.yml
  changelog/devop-3870.md
  package-lock.json
  package.json
  scripts/generateOfflineFiles.sh
  scripts/generateReleaseFiles.sh
  scripts/release.sh
Labels: Devop, Ready

#3869 fix: sentry internal json-rpc error
  changelog/fix-3869.md
  src/main/errorHandler.js
Labels: Fixed, v6

#3865 Fix: sentry failed to fetch articles
  changelog/fix-3865.md
  package-lock.json
  package-test.js
  src/core/store/article/actions.js
Labels: Fixed, v6

#3783 Devop/debug dapp browser
  changelog/devop-3783.md
  src/views/TheWalletView.vue
Labels: Ready, Fixed

#3808 fix: 🐛 ledger transport sentry error
  changelog/fix-3808.md
  src/main/errorHandler.js
Labels: Bug, v6

#3875 fix: sentry cannot read null 'getAddressString'
  changelog/fix-3875.md
  src/utils/web3-provider/methods/eth_accounts.js
Labels: Fixed, v6

#3877 fix: sentry invalid argument
  changelog/fix-3877.md
  src/main/errorHandler.js
Labels: Fixed, v6

#3889 devop: 🔧 added safe bn to wei
  changelog/devop-3889.md
  changelog/fix-3808.md
  package-lock.json
  package.json
  src/modules/send/ModuleSend.vue
Labels: Bug, v6

#3874 devop: update sidemenu background color
  changelog/devop-3874.md
  package-lock.json
  package.json
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready, UI

#3856 Fix/dropdown closing
  changelog/fix-3856.md
  src/modules/send/ModuleSend.vue
Labels: Bug, v6

#3883 fix: remove global styles
  changelog/fix-3883.md
  package-lock.json
  src/components/MnemonicPhraseTable.vue
  src/components/mew-super-button-revised/MewSuperButtonRevised.vue
  src/components/theme-switch/ThemeSwitch.vue
  src/core/components/TheWrapperDapp.vue
  src/core/components/TheWrapperWallet.vue
  src/dapps/aave-dapp/Aave.vue
  src/dapps/aave-dapp/components/AaveSelectInterest.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/claim/ClaimBalance.vue
  src/dapps/eth-blocks/components/BlockInfo.vue
  src/dapps/eth-blocks/components/BlockInfoAlert.vue
  src/dapps/eth-blocks/components/BlockResultComponent.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/confirmation/components/ConfirmationMessage.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapConfirmation.vue
  src/modules/swap/components/SwapProviderMentions.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/components-wallet/WalletPromoSnackbar.vue
  src/views/layouts-default/TheCareersLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-wallet/TheDeployContractLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
  src/views/layouts-wallet/TheSendTransactionOfflineLayout.vue
  src/views/layouts-wallet/TheSignMessageLayout.vue
  src/views/layouts-wallet/TheVerifyMessageLayout.vue
Labels: Ready, UI, v6

#3898 release: 🔥 v6.5.6
  .github/workflows/github-release.yml
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  scripts/generateOfflineFiles.sh
  scripts/generateReleaseFiles.sh
  scripts/release.sh
  src/assets/images/icons/hardware-wallets/icon-trezor.svg
  src/components/MnemonicPhraseTable.vue
  src/components/mew-super-button-revised/MewSuperButtonRevised.vue
  src/components/theme-switch/ThemeSwitch.vue
  src/core/components/TheWrapperDapp.vue
  src/core/components/TheWrapperWallet.vue
  src/core/store/article/actions.js
  src/dapps/aave-dapp/Aave.vue
  src/dapps/aave-dapp/components/AaveSelectInterest.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/claim/ClaimBalance.vue
  src/dapps/eth-blocks/components/BlockInfo.vue
  src/dapps/eth-blocks/components/BlockInfoAlert.vue
  src/dapps/eth-blocks/components/BlockResultComponent.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/main/errorHandler.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/confirmation/components/ConfirmationMessage.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapConfirmation.vue
  src/modules/swap/components/SwapProviderMentions.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/utils/web3-provider/methods/eth_accounts.js
  src/views/TheWalletView.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/components-wallet/WalletPromoSnackbar.vue
  src/views/layouts-default/TheCareersLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-wallet/TheDeployContractLayout.vue
  src/views/layouts-wallet/TheInteractContractLayout.vue
  src/views/layouts-wallet/TheSendTransactionLayout.vue
  src/views/layouts-wallet/TheSendTransactionOfflineLayout.vue
  src/views/layouts-wallet/TheSignMessageLayout.vue
  src/views/layouts-wallet/TheVerifyMessageLayout.vue
Labels: Release, Ready

#3846 Fix: Polygon Swap
  changelog/devop-3903.md
  changelog/fix-3846.md
  package-lock.json
  package-test.js
  package.json
  src/main/errorHandler.js
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
Labels: Bug, v6

#3903 Devop/update package
  changelog/devop-3903.md
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#3885 Sentry: NumberFormat currencyDisplay 'narrowSymbol'
  changelog/fix-3885.md
  package-lock.json
  package.json
  src/main/mainApp.vue
Labels: Fixed, v6

#3860 fix: 🐛 remove show-arrows
  changelog/fix-3860.md
  package-lock.json
  package-test.js
  src/core/components/TheWrapperDapp.vue
  src/views/components-wallet/TheWalletHeader.vue
Labels: Bug, v6

#3888 devop: 🔧 Click undefined
  changelog/devop-3888.md
  changelog/fix-3808.md
  package-lock.json
  package-test.js
  package.json
  src/main/errorHandler.js
Labels: Bug, v6

#3925 Fix: QR Code and the sign message copy toast
  changelog/fix-3925.md
  package-lock.json
  src/core/components/AppAddrQr.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/CrossChainConfirmation.vue
Labels: Bug, Fixed, v6

#3916 fix: 🐛 cors nft handler request error
  changelog/fix-3916.md
  package-lock.json
  src/main/errorHandler.js
Labels: Bug, v6

#3918 Fix: sentry json response has no error or result
  changelog/fix-3916.md
  changelog/fix-3918.md
  package-lock.json
  src/main/errorHandler.js
Labels: Bug, Fixed, v6

#3921 Fix: sentry user aborted a request
  changelog/fix-3921.md
  package-lock.json
  src/main/errorHandler.js
Labels: Bug, Fixed, v6

#3908 fix: 🐛 fix mobile paper wallet not opening issue
  changelog/fix-3908.md
  package-lock.json
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Bug, Ready, v6

#3844 Devop: Buy/Sell on Moonpay & Simplex
  changelog/devop-3844.md
  changelog/fix-3900.md
  package-lock.json
  src/main/mainApp.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPayBuyProviderComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/moon-pay/components/tokenList.js
  src/modules/moon-pay/handlers/handlerOrder.js
  src/modules/send/ModuleSend.vue
  src/modules/send/handlers/handlerSend.js
Labels: Devop, Ready, v6

#3866 fix: 🐛 native swap fee currency issue
  changelog/fix-3866.md
  package-lock.json
  src/modules/confirmation/components/ConfirmationSwapTransactionDetails.vue
Labels: Bug, Ready, v6

#3873 fix: 🐛null reading error handler
  changelog/fix-3873.md
  package-lock.json
  src/modules/send/ModuleSend.vue
Labels: Bug, v6

#3896 fix: 🐛 sentry undefined to token amount
  changelog/fix-3896.md
  package-lock.json
  src/modules/swap/ModuleSwap.vue
Labels: Bug, v6

#3878 Sentry: BN Error
  changelog/sentry-3878.md
  package-lock.json
  src/core/helpers/numberFormatHelper.js
  src/modules/nft-manager/ModuleNftManager.vue
Labels: Devop, v6

#3868 fix: 🐛 confirmation window layout and paddings
  changelog/fix-3868.md
  changelog/fix-3873.md
  changelog/fix-3896.md
  changelog/fix-3899.md
  package-lock.json
  src/assets/styles/GlobalStyles.scss
  src/core/components/AppModal.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
Labels: Ready, UI, v6

#3880 fix: 🐛 landing page menu and header
  changelog/fix-3880.md
  package-lock.json
  src/assets/images/icons/icon-grid-dot-green.svg
  src/assets/images/icons/icon-grid-dot-white.svg
  src/assets/images/icons/icon-grid-dot.png
  src/components/mew-menu-popup/MewMenuPopup.vue
  src/components/mew-tools/MewTools.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-default/TheDefaultMobileNavigation.vue
Labels: Ready, UI, v6

#3917 fix: 🐛 failed to fetch pool api type error
  changelog/fix-3917.md
  package-audit.js
  package-lock.json
  package.json
  src/main/errorHandler.js
Labels: Bug, v6

#3935 fix: 🐛 undefined reading value add error handler
  changelog/fix-3935.md
  package-lock.json
  src/main/errorHandler.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
Labels: Bug

#3910 fix: 🐛 fix export configurations btn size
  changelog/fix-3910.md
  package-lock.json
  package.json
  src/modules/settings/components/SettingsExportConfig.vue
Labels: Ready, UI, v6

#3909 fix: 🐛 footer social links and expending blocks
  changelog/fix-3909.md
  package-lock.json
  src/views/components-default/TheDefaultFooter.vue
Labels: Bug, Ready, UI, v6

#3931 fix: 🐛 mobile wallet footer overlap issue
  changelog/fix-3931.md
  package-lock.json
  src/views/TheWalletView.vue
  src/views/components-wallet/WalletPromoSnackbar.vue
Labels: Bug, Ready, UI, v6

#3932 fix: 🐛 ios input field zooming issue
  changelog/fix-3932.md
  public/index.html
Labels: Ready, UI, v6

#3947 fix: 🐛 type error msg undefined
  changelog/fix-3924.md
  changelog/fix-3936.md
  changelog/fix-3941.md
  changelog/fix-3946.md
  changelog/fix-3947.md
  changelog/fix-3948.md
  changelog/fix-3953.md
  changelog/ui-3930.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/dapps/eth-blocks/components/BlockQuickViewPopup.vue
  src/dapps/eth-blocks/components/BlockResultComponent.vue
  src/dapps/eth-blocks/components/BlockSearch.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockInfo.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksDateSearch.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksMint.vue
  src/dapps/stakewise/TheStakewiseLayout.vue
  src/main/errorHandler.js
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Bug, v6

#3924 Fix: eth blocks close button
  changelog/fix-3924.md
  package-lock.json
  src/dapps/eth-blocks/components/BlockQuickViewPopup.vue
  src/dapps/eth-blocks/components/BlockResultComponent.vue
  src/dapps/eth-blocks/components/BlockSearch.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/dapps/eth-blocks/modules/ModuleEthBlockInfo.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksDateSearch.vue
  src/dapps/eth-blocks/modules/ModuleEthBlocksMint.vue
Labels: Bug, Fixed, v6

#3930 UI: replace search bar
  changelog/ui-3930.md
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
Labels: Ready, UI, v6

#3936 Sentry: ENS missing provider
  changelog/fix-3936.md
  package-lock.json
  src/modules/address-book/ModuleAddressBook.vue
Labels: Bug, Fixed, v6

#3946 Sentry: Cannot read properties of undefined (reading 'message')
  changelog/fix-3946.md
  changelog/fix-3947.md
  package-lock.json
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Bug, Fixed, v6

#3953 fix: 🐛 sentry low gas and moonpay quotes
  changelog/fix-3953.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/main/errorHandler.js
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
Labels: Bug, Fixed, v6

#3954 sentry: permission denied error
  changelog/fix-3912.md
  changelog/fix-3942.md
  changelog/fix-3954.md
  changelog/fix-3958.md
  changelog/fix-3959.md
  changelog/sentry-3957.md
  package-lock.json
  package-test.js
  package.json
  src/main/errorHandler.js
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/translations/errors-global/en_US.json
Labels: Fixed, v6

#3912 Fix: BNB Return Values Not Valid
  changelog/fix-3912.md
  package-lock.json
  src/main/errorHandler.js
  src/translations/errors-global/en_US.json
Labels: Fixed, v6

#3942 fix: 🐛 unmerged changes in package-lock
  changelog/fix-3942.md
  package-lock.json
Labels: Fixed, v6
