Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-01, with the labels that each got.

#3603 devop: 🔧 pull main to develop
  .github/workflows/add-to-mewbuilds.yml
  CHANGELOG.md
  Dockerfile
  changelog/devop-3603.md
  connections.js
  fetchLists/fetchMainLists.js
  package-lock.json
  package-test.js
  package.json
  src/app.vue
  src/assets/images/team/mew-collage-large.jpg
  src/assets/images/team/mew-collage-small.jpg
  src/core/configs/configRoutes.js
  src/core/plugins/vuetify.js
  src/core/router/routes-default.js
  src/translations/common/en_US.json
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheCareersLayout.vue
  src/views/layouts-default/TheConvertUnitsLayout.vue
Labels: Devop, Ready

#3611 devop: 🔧 bitbox02
  changelog/devop-3611.md
  changelog/fix-3608.md
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/WalletErrorHandler.js
  src/modules/access-wallet/hardware/components/AccessWalletBitbox.vue
  src/modules/access-wallet/hardware/handlers/configs/configWallets.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
Labels: Devop, Ready

#3613 fix: 🐛 swap rates value not fetching for 1 ETH
  changelog/fix-3613.md
  src/modules/swap/ModuleSwapRates.vue
Labels: Bug, Ready

#3615 fix: 🐛 token swap on swap page
  changelog/fix-3615.md
  package-lock.json
  package.json
  src/modules/balance/ModuleTokens.vue
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready

#3590 devop: 🔧 enable swap unless there's an error
  Dockerfile
  changelog/devop-3264.md
  changelog/devop-3341.md
  changelog/devop-3590.md
  changelog/fix-3584.md
  changelog/fix-3586.md
  changelog/fix-3588.md
  package-lock.json
  package.json
  src/modules/access-wallet/common/WalletErrorHandler.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/swap/ModuleSwap.vue
  src/views/components-wallet/TheSwapBtn.vue
Labels: Devop, Ready

#3619 chore: 👷 update packages, bump version
  changelog/devop-3619.md
  package-lock.json
  package.json
Labels: Devop, Ready

#3616 fix: Duplicate Tokens
  changelog/fix-3616.md
  package-lock.json
  src/modules/balance/ModuleTokens.vue
Labels: Bug, Ready

#3622 fix: 🐛 weird loading fee when toToken is ETH
  changelog/fix-3622.md
  package-lock.json
  package.json
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready

#3610 release: 🔥 v6.4.4
  CHANGELOG.md
  Dockerfile
  changelog/feat-3572.md
  changelog/feat-3577.md
  package-lock.json
  package-test.js
  package.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/WalletErrorHandler.js
  src/modules/access-wallet/hardware/components/AccessWalletBitbox.vue
  src/modules/access-wallet/hardware/handlers/configs/configWallets.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/index.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/ModuleSwapRates.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheSwapBtn.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
Labels: Release, Ready

#3630 fix: 🐛 Cannot read properties of undefined (reading 'minFrom')
  CHANGELOG.md
  changelog/fix-3630.md
  package-lock.json
  package.json
  src/modules/swap/handlers/providers/changelly.js
Labels: Bug, Ready, dependencies

#3637 Fix/calctxfee null
  changelog/fix-3637.md
  package-lock.json
  package.json
  src/modules/settings/components/SettingsGasPrice.vue
Labels: Bug, Ready, dependencies

#3626 fix: 🐛 allow users to select ledger apps
  CHANGELOG.md
  changelog/fix-3626.md
  package-lock.json
  package.json
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hardware/handlers/bip44/ledgerPaths.js
  src/modules/access-wallet/hardware/handlers/configs/configWallets.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/appPaths.js
Labels: Bug, Ready

#3617 feat: ✨ allow test transactions, dont increase nonce when test transaction
  CHANGELOG.md
  changelog/feat-3617.md
  package-lock.json
  package.json
  src/core/store/configs.js
  src/core/store/global/state.js
  src/main.js
  src/utils/web3-provider/methods/eth_sendRawTransaction.js
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/utils/web3-provider/methods/index.js
  src/utils/web3-provider/providers/given-provider.js
  src/utils/web3-provider/providers/ws-provider.js
Labels: Feature, Ready

#3625 Chore/fix imports
  changelog/chore-3623.md
  changelog/chore-3625.md
  src/modules/balance/ModuleTokens.vue
Labels: Devop, Ready

#3642 devop: 🔧 remove survey
  changelog/devop-3642.md
  src/core/store/global/actions.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/views/TheWalletView.vue
  src/views/components-default/MewSurvey.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
Labels: Devop, Ready

#3647 fix: 🐛 value setting for test mode
  changelog/fix-3647.md
  src/main.js
Labels: Ready, Fixed

#3645 feat: ✨ qr code
  changelog/feat-3645.md
  src/assets/images/icons/button-app-store.svg
  src/assets/images/icons/button-play-store.svg
  src/core/configs/configRoutes.js
  src/core/router/routes-default.js
  src/views/layouts-default/TheQrCodeLayout.vue
Labels: Feature, v6

#3652 chore: 👷 update packages
  changelog/chore-3652.md
  package-audit.js
  package-lock.json
  package.json
Labels: Devop, Ready

#3646 release: 🔥 v6.4.5
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package.json
  src/assets/images/icons/button-app-store.svg
  src/assets/images/icons/button-play-store.svg
  src/core/configs/configRoutes.js
  src/core/router/routes-default.js
  src/core/store/configs.js
  src/core/store/global/actions.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/main.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hardware/handlers/bip44/ledgerPaths.js
  src/modules/access-wallet/hardware/handlers/configs/configWallets.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/appPaths.js
  src/modules/balance/ModuleTokens.vue
  src/modules/send/ModuleSend.vue
  src/modules/settings/components/SettingsGasPrice.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/providers/changelly.js
  src/utils/web3-provider/methods/eth_sendRawTransaction.js
  src/utils/web3-provider/methods/eth_sendTransaction.js
  src/utils/web3-provider/methods/index.js
  src/utils/web3-provider/providers/given-provider.js
  src/utils/web3-provider/providers/ws-provider.js
  src/views/TheWalletView.vue
  src/views/components-default/MewSurvey.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/layouts-default/TheQrCodeLayout.vue
Labels: Release, Ready
