Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-03, with the labels that each got.

#3698 devop: 🔧 add correct prop for mew-token-container
  changelog/devop-3698.md
  package-lock.json
  src/modules/confirmation/components/ConfirmationValuesContainer.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/modules/swap/handlers/providers/changelly.js
Labels: Devop, Ready

#3624 fix: dashboard balance skeleton loader
  changelog/fix-3624.md
  package-lock.json
  package.json
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleBalanceLoader.vue
Labels: Ready, UI, v6

#3697 fix: 🐛 fetch tokens when network switches
  changelog/fix-3697.md
  package-lock.json
  src/core/store/global/actions.js
  src/core/store/swap/actions.js
  src/core/store/swap/mutations.js
  src/modules/network/components/NetworkSwitch.vue
  src/modules/swap/ModuleSwap.vue
Labels: Ready, Fixed

#3696 Sentry: Number To BN Error
  changelog/devop-3696.md
  package-lock.json
  package.json
  src/core/helpers/numberFormatHelper.js
  src/core/store/global/actions.js
  src/modules/send/ModuleSend.vue
  src/modules/settings/components/SettingsGasPrice.vue
Labels: Bug, Ready, v6

#3705 fix: 🐛 icons and link in module confirmation
  changelog/fix-3705.md
  package-lock.json
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationValuesContainer.vue
  src/modules/notifications/ModuleNotifications.vue
Labels: Ready, Fixed

#3700 devop: 🔧 update packages from dependabot
  CHANGELOG.md
  LICENSE
  changelog/devop-3700.md
  package-lock.json
  package.json
  src/assets/styles/GlobalStyles.scss
  src/translations/dapps-ens/en_US.json
  src/translations/footer/en_US.json
  src/views/components-wallet/TheWalletFooter.vue
Labels: Devop, Ready

#3701 devop: update team page
  changelog/devop-3701.md
  package-lock.json
  src/assets/images/team/andrew-dao.jpg
  src/assets/images/team/andrew.jpg
  src/assets/images/team/brionne.jpg
  src/assets/images/team/chindalath.jpg
  src/assets/images/team/christian.jpg
  src/assets/images/team/david.jpg
  src/assets/images/team/jason.jpg
  src/assets/images/team/jazmine.jpg
  src/assets/images/team/jessica.jpg
  src/assets/images/team/marcus.jpg
  src/assets/images/team/michael.jpg
  src/assets/images/team/raden.jpg
  src/assets/images/team/russell.jpg
  src/assets/images/team/vince.jpg
  src/views/layouts-default/TheTeamLayout.vue
Labels: Devop, Ready, v6

#3695 Fix/sentry issues
  changelog/fix-3695.md
  package-lock.json
  src/core/store/global/mutations.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/access-wallet/software/handlers/errorHandler.js
  src/modules/access-wallet/software/handlers/mnemonic/errorHandler.js
  src/modules/access-wallet/software/handlers/web3wallet/errorHandler.js
  src/modules/swap/handlers/handlerSwap.js
  src/modules/toast/handler/handlerToast.js
  src/views/TheWalletView.vue
Labels: Ready, Fixed

#3706 fix: 🔧 correctly catch changelly errors
  changelog/fix-3706.md
  package-lock.json
  src/modules/confirmation/components/ConfirmationMessage.vue
  src/modules/swap/ModuleSwapRates.vue
  src/modules/swap/handlers/providers/changelly.js
  src/views/components-default/HomeFeaturesSwap.vue
Labels: Ready, Fixed

#3684 feat: page not found 404 page
  changelog/feat-3684.md
  package-lock.json
  src/assets/images/backgrounds/bg-404.svg
  src/core/configs/configRoutes.js
  src/core/router/index.js
  src/core/router/routes-not-found.js
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/ThePageNotFoundLayout.vue
Labels: Feature, Ready, v6

#3717 devop: 🔧 add meta icons, catch swap tokens with no icons
  changelog/devop-3717.md
  changelog/feat-3684.md
  package-lock.json
  package.json
  public/icons/icon192.png
  public/index.html
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/views/layouts-default/TheTeamLayout.vue
Labels: Devop, Ready

#3726 Sentry: Number to BN Error
  changelog/devop-3726.md
  package-lock.json
  package.json
  src/modules/send/handlers/handlerSend.js
Labels: Bug, Fixed, v6

#3723 devop: 🔧 added check for contracts
  changelog/devop-3723.md
  src/modules/contract/ModuleContractInteract.vue
Labels: Bug, Ready, v6

#3722 chore: 👷 update team page
  changelog/fix-3722.md
  package-lock.json
  package.json
  src/views/layouts-default/TheTeamLayout.vue
Labels: Ready, Fixed

#3715 fix: 🐛 add bitbox error
  changelog/fix-3715.md
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
Labels: Ready, Fixed

#3713 Devop/undefined swap status
  changelog/fix-3713.md
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/handlers/handlerNotification.js
Labels: Ready, Fixed

#3732 release: 🔥 v6.4.8-hotfix.1
  changelog/fix-3732.md
  package-lock.json
  package-test.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/changelly.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, Hotfix

#3736 release: 🔥 v6.4.8-hotfix.1
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/changelly.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Release, Ready, Hotfix

#3739 Fix/moonpay max
  CHANGELOG.md
  changelog/feat-3640.md
  changelog/fix-3739.md
  package-lock.json
  src/modules/moon-pay/components/MoonPaySellComponent.vue
Labels: Ready, Fixed

#3744 Devop/release 6.5.1
  CODEOWNERS
  changelog/devop-3723.md
  changelog/devop-3726.md
  changelog/devop-3744.md
  changelog/fix-3708.md
  changelog/fix-3711.md
  changelog/fix-3713.md
  changelog/fix-3714.md
  changelog/fix-3715.md
  changelog/fix-3722.md
  package-audit.js
  package-lock.json
  package.json
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/handlers/web3wallet/errorHandler.js
  src/modules/contract/ModuleContractInteract.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/send/handlers/handlerSend.js
  src/modules/swap/handlers/handlerSwap.js
  src/modules/toast/handler/handlerToast.js
  src/views/layouts-default/TheTeamLayout.vue
Labels: Devop, Ready

#3524 feat:✨ non chain tokens to eth
  changelog/feat-3524.md
  changelog/fix-3558.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/qr-disabled.png
  src/core/components/AppErrorMsg.vue
  src/core/components/AppModal.vue
  src/core/components/AppTransactionFee.vue
  src/core/store/configs.js
  src/core/store/external/getters.js
  src/core/store/notifications/mutations.js
  src/modules/access-wallet/hardware/handlers/bip44/mnemonicPaths.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationSwapTransactionDetails.vue
  src/modules/confirmation/components/CrossChainConfirmation.vue
  src/modules/confirmation/components/SuccessModal.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/notifications/handlers/nonChainNotification.js
  src/modules/notifications/helpers/formatNonChainNotification.js
  src/modules/notifications/helpers/formatNotification.js
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/ModuleSwapRates.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/modules/swap/handlers/configs/providersConfigs.js
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/modules/transfer-history/ModuleTransferHistory.vue
  src/utils/web3-provider/events.js
  src/views/TheDefaultView.vue
Labels: Feature, Ready

#3734 chore: 👷 sentry-unknown-path
  changelog/chore-3734.md
  package-lock.json
  src/core/router/helpers.js
Labels: Bug, Ready, v6

#3730 fix: 🐛 chore/sentry-type-error-undefined-name
  changelog/fix-3730.md
  package-lock.json
  src/modules/swap/handlers/handlerSwap.js
Labels: Bug, Ready, v6

#3718 fix: disable next button when there is no password
  changelog/fix-3718.md
  package-lock.json
  src/modules/access-wallet/software/components/AccessWalletKeystore.vue
Labels: Bug, Ready, v6

#3753 release: 🔥 v6.5.0-hotfix.1
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/views/TheWalletView.vue
Labels: Release, Ready

#3716 feat: claimable tokens popup
  CHANGELOG.md
  changelog/feat-3640.md
  changelog/feat-3716.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/snippets/claimable-tokens.svg
  src/core/components/AppSimpleDialog.vue
  src/core/helpers/stripQuery.js
  src/core/store/configs.js
  src/dapps/dappsStore.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/claim/ClaimBalance.vue
  src/dapps/ens-manager-dapp/components/claim/ClaimTokensSnackbar.vue
  src/dapps/ens-manager-dapp/store/actions.js
  src/dapps/ens-manager-dapp/store/configs.js
  src/dapps/ens-manager-dapp/store/getters.js
  src/dapps/ens-manager-dapp/store/index.js
  src/dapps/ens-manager-dapp/store/mutations.js
  src/dapps/ens-manager-dapp/store/state.js
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
Labels: Feature, v6

#3747 fix: 🐛 swap, and packages
  changelog/devop-3747.md
  package-lock.json
  package.json
  src/core/components/AppTransactionFee.vue
  src/dapps/ens-manager-dapp/components/claim/ClaimTokensSnackbar.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/CrossChainConfirmation.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/notifications/handlers/nonChainNotification.js
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
Labels: Ready, Fixed

#3746 release: 🔥 v6.5.1
  CHANGELOG.md
  CODEOWNERS
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/icons/qr-disabled.png
  src/assets/images/snippets/claimable-tokens.svg
  src/core/components/AppErrorMsg.vue
  src/core/components/AppModal.vue
  src/core/components/AppSimpleDialog.vue
  src/core/components/AppTransactionFee.vue
  src/core/helpers/stripQuery.js
  src/core/router/helpers.js
  src/core/store/configs.js
  src/core/store/external/getters.js
  src/core/store/notifications/mutations.js
  src/dapps/dappsStore.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/claim/ClaimBalance.vue
  src/dapps/ens-manager-dapp/components/claim/ClaimTokensSnackbar.vue
  src/dapps/ens-manager-dapp/store/actions.js
  src/dapps/ens-manager-dapp/store/configs.js
  src/dapps/ens-manager-dapp/store/getters.js
  src/dapps/ens-manager-dapp/store/index.js
  src/dapps/ens-manager-dapp/store/mutations.js
  src/dapps/ens-manager-dapp/store/state.js
  src/modules/access-wallet/hardware/handlers/bip44/mnemonicPaths.js
  src/modules/access-wallet/hardware/handlers/hardwares/bitbox02/errorHandler.js
  src/modules/access-wallet/software/components/AccessWalletKeystore.vue
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/access-wallet/software/handlers/web3wallet/errorHandler.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/ConfirmationSwapTransactionDetails.vue
  src/modules/confirmation/components/CrossChainConfirmation.vue
  src/modules/confirmation/components/SuccessModal.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/notifications/handlers/handlerNotification.js
  src/modules/notifications/handlers/nonChainNotification.js
  src/modules/notifications/helpers/formatNonChainNotification.js
  src/modules/notifications/helpers/formatNotification.js
  src/modules/send/ModuleSend.vue
  src/modules/send/handlers/handlerSend.js
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/ModuleSwapRates.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/modules/swap/handlers/configs/providersConfigs.js
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/modules/toast/handler/handlerToast.js
  src/modules/transfer-history/ModuleTransferHistory.vue
  src/utils/web3-provider/events.js
  src/views/TheDefaultView.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletPopupPromo.vue
  src/views/layouts-default/TheTeamLayout.vue
Labels: Release, Ready

#3756 fix: 🐛 symbol search for from tokens, price for to tokens
  changelog/fix-3756.md
  src/modules/balance/ModuleBalance.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/views/components-wallet/TheWalletHeader.vue
Labels: Ready, Fixed

#3760 release: 🔥 v6.5.1-hotfix.1
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/modules/balance/ModuleBalance.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/views/components-wallet/TheWalletHeader.vue
Labels: Release, Ready

#3762 chore: 👷 update packages
  changelog/devop-3762.md
  package-lock.json
  package-test.js
  package.json
Labels: Devop, Ready

#3761 fix: currency display error
  changelog/sentry-3761.md
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Ready, v6

#3750 Fix: sentry undefined contract
  changelog/fix-3750.md
  package-lock.json
  src/modules/swap/handlers/handlerSwap.js
Labels: Bug, Ready, v6
