Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-10, with the labels that each got.

#4248 chore: 👷 add to develop build only when merged to staging
  .github/workflows/add-to-staging.yml
  changelog/devop-4248.md
Labels: Devop, Ready

#4214 fix: 🐛 decimal input gets deleted
  changelog/fix-4214.md
  package-lock.json
  package.json
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
Labels: Bug, UI, v6

#4220 devop: matomo buy sell
  changelog/devop-4220.md
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, v6

#4226 fix: 🐛 disable sign button
  changelog/fix-4226.md
  src/modules/message/ModuleMessageSign.vue
Labels: Ready, UI, v6

#4231 fix: fix mint me token icon
  changelog/fix-4231.md
  src/assets/images/networks/mintme.svg
Labels: Ready, UI, v6

#4224 Sentry: Cannot read properties of undefined (reading 'contract')
  changelog/fix-4224.md
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Fixed, v6

#4223 fix: 🐛 moonbeam switch
  changelog/fix-4223.md
  package-lock.json
  package-test.js
  package.json
  src/views/TheWalletView.vue
Labels: Bug, Ready, v6

#4235 Sentry: Cannot read properties of null (reading 'message') on TheWalletView
  changelog/fix-4217.md
  changelog/fix-4219.md
  changelog/fix-4234.md
  changelog/fix-4235.md
  package-lock.json
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/reverse/EnsReverseLookup.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/views/TheWalletView.vue
  src/views/components-default/HomeFeaturesDapps.vue
Labels: Bug, Fixed, v6

#4211 Fix: duplicate DOGE token on swap
  changelog/fix-4211.md
  package-lock.json
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/handlerSwap.js
Labels: Bug, Fixed, v6

#4227 Sentry: undefined (reading 'toLowerCase') on MoonpayBuy
  changelog/fix-4227.md
  package-lock.json
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
Labels: Bug, Fixed, v6

#4257 chore: add migration changes
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/builds/mewcx/cxHelpers/background.js
  src/builds/mewcx/cxHelpers/cxWeb3.js
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/ExtensionBrowserAction/components/WalletInfoComponent/WalletInfoComponent.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
  src/layouts/ExtensionPopup/containers/AccountsContainer/AccountsContainer.vue
  src/layouts/ExtensionPopup/containers/WelcomeContainer/WelcomeContainer.vue
  src/translations/mew-cx/en_US.json
Labels: Devop, Ready

#4261 fix: my wallets
  CHANGELOG.md
  package-lock.json
  package.json
  src/layouts/ExtensionBrowserAction/components/CxHeader/CxHeader.vue
  src/layouts/ExtensionPopup/ExtensionPopup.vue
Labels: Ready, Fixed

#4258 devop: sync develop to staging
  .github/workflows/add-to-staging.yml
  changelog/devop-4220.md
  changelog/devop-4222.md
  changelog/devop-4240.md
  changelog/devop-4244.md
  changelog/devop-4248.md
  changelog/fix-4164.md
  changelog/fix-4206.md
  changelog/fix-4211.md
  changelog/fix-4214.md
  changelog/fix-4217.md
  changelog/fix-4219.md
  changelog/fix-4223.md
  changelog/fix-4224.md
  changelog/fix-4226.md
  changelog/fix-4227.md
  changelog/fix-4231.md
  changelog/fix-4232.md
  changelog/fix-4234.md
  changelog/fix-4235.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/networks/mintme.svg
  src/dapps/aave-dapp/TheAaveLayout.vue
  src/dapps/aave-dapp/components/AaveAmountForm.vue
  src/dapps/aave-dapp/components/AaveSummary.vue
  src/dapps/aave-dapp/components/overlays/AaveBorrowOverlay.vue
  src/dapps/aave-dapp/components/overlays/AaveCollateralOverlay.vue
  src/dapps/aave-dapp/components/overlays/AaveDepositOverlay.vue
  src/dapps/aave-dapp/components/overlays/AaveRepayOverlay.vue
  src/dapps/aave-dapp/components/overlays/AaveSetAprOverlay.vue
  src/dapps/aave-dapp/components/overlays/AaveWithdrawOverlay.vue
  src/dapps/aave-dapp/handlers/handlerAave.mixin.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/reverse/EnsReverseLookup.vue
  src/dapps/eth-blocks/components/BlockResultComponent.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/message/ModuleMessageSign.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/send-offline/ModuleSendOffline.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/handlerSwap.js
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/TheWalletView.vue
  src/views/components-default/HomeFeaturesDapps.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-wallet/TheWalletHeader.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  tests/e2e/functions.js
  tests/e2e/specs/print-wallet-test.js
  tests/e2e/specs/sending-test.js
Labels: Devop, Ready

#4267 Devop/matomo changes
  changelog/devop-4267.md
  package-lock.json
  package.json
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/swap/ModuleSwap.vue
Labels: Devop, Ready

#4275 Devop/matomo changes
  changelog/devop-4267.md
  changelog/devop-4275.md
  package-lock.json
  package-test.js
  package.json
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/ModuleSwapRates.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready

#4255 Devop/kleros integration
  changelog/feat-4255.md
  connections.js
  package-lock.json
  package-test.js
  package.json
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/contract/ModuleContractInteract.vue
Labels: Devop, Ready

#4268 chore: only open enkrypt when updated
  CHANGELOG.md
  package-lock.json
  package.json
  src/builds/mewcx/cxHelpers/background.js
Labels: Ready, Fixed

#4280 devop: staging fix input e
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
Labels: Ready, Fixed, v6

#4260 devop: 🔧 e2e test for swap eth to erc token
  changelog/devop-4260.md
  src/core/components/AppButtonBalance.vue
  src/modules/swap/ModuleSwap.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  tests/e2e/specs/eth-erc-swap-test.js
Labels: Devop, v6

#4251 Sentry: address null (src/core/helpers/addressUtils)
  changelog/fix-4251.md
  package-lock.json
  src/modules/address-book/ModuleAddressBook.vue
Labels: Bug, Ready, v6

#4252 Sentry: null reading meta (ModuleBalanceCard)
  changelog/fix-4252.md
  src/modules/balance/ModuleBalanceCard.vue
Labels: Bug, Fixed, v6

#4263 Devop/e2e-contract-interaction
  changelog/devop-4263.md
  src/modules/contract/ModuleContractInteract.vue
  tests/e2e/specs/contract-interact.js
Labels: Devop, Ready, v6

#4079 fix: matic promise error handling
  changelog/fix-4079.md
  src/modules/access-wallet/common/WalletInterface.js
  src/modules/swap/handlers/providers/changelly.js
  src/modules/swap/handlers/providers/mew-provider-class.js
Labels: Bug, Fixed

#4228 fix: 🐛 check for null when adding custom alias
  changelog/fix-4228.md
  package-lock.json
  src/modules/access-wallet/hardware/components/AccessWalletDerivationPath.vue
Labels: UI, v6

#3813 fix: 🐛 type error minmax minfrom
  changelog/fix-3813.md
  package-lock.json
  src/modules/swap/handlers/providers/mew-provider-class.js
Labels: Bug, v6

#4036 devop: update mobile tools page
  changelog/devop-4036.md
  package-lock.json
  package-test.js
  package.json
  src/modules/tools/ModuleToolsGenerateKeystore/ModuleToolsGenerateKeystore.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/layouts-default/TheToolsLayout.vue
Labels: Devop, Ready, UI, v6

#3589 feat: ✨ add cool wallet pro
  changelog/devop-4249.md
  changelog/devop-4288.md
  changelog/feat-3589.md
  changelog/fix-4237.md
  changelog/fix-4264.md
  changelog/fix-4270.md
  changelog/fix-4272.md
  changelog/fix-4279.md
  changelog/fix-4289.md
  changelog/fix-4293.md
  changelog/fix-4301.md
  package-lock.json
  package.json
  src/assets/images/icons/icon-arrow-top-right-green.svg
  src/assets/images/icons/wallets/coolwalletpro.svg
  src/core/components/AppCopyBtn.vue
  src/core/components/AppTable.vue
  src/dapps/aave-dapp/TheAaveLayout.vue
  src/main/mainApp.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletCoolWallet.vue
  src/modules/access-wallet/hardware/components/AccessWalletKeepkey.vue
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/index.js
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/software/components/AccessWalletKeystore.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/components/BalanceTable.vue
  src/modules/balance/components/TokenEditCustom.vue
  src/modules/global-modals/ModuleGlobalModals.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/settings/components/SettingsAddressTable.vue
  src/modules/swap/ModuleSwap.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Feature, Ready

#4289 Fix: swap double confirmation
  changelog/fix-4289.md
  package-lock.json
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
Labels: Bug, v6

#4293 Fix: buy page cant select crypto
  changelog/fix-4293.md
  package-lock.json
  package.json
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
Labels: Bug, Fixed, v6

#4301 Sentry: currencyName is undefined
  changelog/fix-4301.md
  package-lock.json
  package.json
  src/modules/address-book/ModuleAddressBook.vue
Labels: Bug, Fixed, v6

#4296 fix: 🐛 moonpay supported fiat symbol undefined
  changelog/fix-4296.md
  package-lock.json
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
Labels: Bug, v6

#4321 Devop/update lists
  fetchLists/lists/tokens.json
  package-audit.js
  package-test.js
  src/core/store/external/getters.js
Labels: Devop, Ready

#4323 Devop/release bugs v6.6.9
  connections.js
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppBtnRow.vue
  src/main/errorHandler.js
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/balance/components/BalanceTable.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
Labels: Devop, Ready, v6

#4330 revert: ⏪️ fetch main token:
  src/core/store/external/getters.js
Labels: Devop, Ready
