Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-08, with the labels that each got.

#4071 fix: 🐛 token loading when switching network
  README.md
  changelog/fix-4071.md
  public/index.html
  src/components/mew-tools/MewTools.vue
  src/core/mixins/enkryptMarketing.mixin.js
  src/views/TheWalletView.vue
  src/views/components-default/HomeEnkrypt.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/layouts-default/TheSecurityPolicyLayout.vue
Labels: Ready, Fixed

#4072 Fix/banner ad intercom
  changelog/fix-4072.md
  package-lock.json
  package.json
  public/index.html
  public/intercom.js
  src/components/mew-tools/MewTools.vue
  src/core/components/AppCarousel.vue
  src/core/configs/configRoutes.js
  src/core/router/index.js
  src/dapps/aave-dapp/handlers/handlerAave.js
  src/main/liveMain.js
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Ready, Fixed

#4077 devop: 🔧 change link, fix develop
  changelog/devop-4077.md
  package-test.js
  src/core/components/AppCarousel.vue
  src/core/mixins/enkryptMarketing.mixin.js
  src/views/components-default/TheDefaultHeader.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Devop, Ready

#4075 release: 🔥 v6.6.3-hotfix.1
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  public/index.html
  src/components/mew-tools/MewTools.vue
  src/core/components/AppCarousel.vue
  src/core/configs/configRoutes.js
  src/core/mixins/enkryptMarketing.mixin.js
  src/core/router/index.js
  src/dapps/aave-dapp/handlers/handlerAave.js
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/views/components-default/TheDefaultHeader.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Release, Ready

#4086 Fix/sell popups
  changelog/fix-4034.md
  changelog/fix-4086.md
  package-lock.json
  package-test.js
  package.json
  src/modules/analytics-opt-in/ModuleAnalytics.vue
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/send/ModuleSend.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/EnkryptPromoSnackbar.vue
Labels: Ready, Fixed

#4090 release: 🔥 v6.6.3-hotfix.2
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/modules/analytics-opt-in/ModuleAnalytics.vue
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/send/ModuleSend.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/EnkryptPromoSnackbar.vue
Labels: Release, Ready

#4091 fix: 🐛 added checks for missing properties
  changelog/devop-4096.md
  changelog/fix-4091.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppTransactionFee.vue
  src/core/mixins/handlerWallet.mixin.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/views/TheWalletView.vue
Labels: Bug, v6

#4101 release: 🔥 v6.6.3-hotfix.3
  CHANGELOG.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppTransactionFee.vue
  src/core/mixins/handlerWallet.mixin.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/views/TheWalletView.vue
Labels: Release

#4081 fix: mew-tooltip word wrap issue
  changelog/fix-4081.md
  fetchLists/lists/tokens.json
  src/components/MewTooltip/MewTooltip.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
Labels: Bug, Ready, UI, v6

#3854 devop: 🔧 metamask network init
  changelog/devop-3854.md
  package-lock.json
  src/core/helpers/matchNetwork.js
  src/core/store/global/actions.js
  src/core/store/global/getters.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/handlers/errorHandler.js
  src/modules/network/ModuleNetwork.vue
  src/modules/network/components/NetworkSwitch.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, v6

#4012 Fix: swap error 404
  changelog/fix-4012.md
  package-lock.json
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Fixed, v6

#4058 Fix: buy tooltip daily limit
  changelog/fix-4058.md
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
Labels: Bug, Fixed, v6

#4059 fix: Error message for invalid mnemonic
  changelog/fix-4059.md
  src/translations/create-wallet/en_US.json
  src/translations/create-wallet/ru_RU.json
  src/translations/en_US.js
  src/translations/ru_RU.js
Labels: Bug, Fixed, v6

#4063 Fix: Moonpay sell dollar values
  changelog/fix-4063.md
  src/modules/moon-pay/components/MoonPaySellComponent.vue
Labels: Bug, Fixed, v6

#4064 Fix: Swap endless loading on token value change
  changelog/fix-4064.md
  src/modules/swap/ModuleSwap.vue
Labels: Bug, Fixed, v6

#4068 Fix: MetaMask login error message
  changelog/fix-4068.md
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Fixed, v6

#4070 Fix: ledger access wallet back button
  changelog/fix-4070.md
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Bug, Fixed, v6

#4055 Fix: send max tokens by default
  changelog/devop-4102.md
  changelog/fix-4055.md
  changelog/fix-4082.md
  changelog/fix-4097.md
  changelog/fix-4098.md
  changelog/fix-4103.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/SuccessModal.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/utils/networks/types/BSC.js
  src/utils/networks/types/ETC.js
  src/utils/networks/types/ETH.js
  src/utils/networks/types/GO.js
  src/utils/networks/types/GOERLI.js
  src/utils/networks/types/KOV.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/MINTME.js
  src/utils/networks/types/MOONBEAM.js
  src/utils/networks/types/MOONRIVER.js
  src/utils/networks/types/RIN.js
  src/utils/networks/types/ROP.js
  src/utils/networks/types/XDC.js
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-default/TheTeamLayout.vue
Labels: Bug, Fixed, v6

#4082 fix: view on etherscan/ network text
  changelog/fix-4082.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/SuccessModal.vue
  src/utils/networks/types/BSC.js
  src/utils/networks/types/ETC.js
  src/utils/networks/types/ETH.js
  src/utils/networks/types/GO.js
  src/utils/networks/types/GOERLI.js
  src/utils/networks/types/KOV.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/MINTME.js
  src/utils/networks/types/MOONBEAM.js
  src/utils/networks/types/MOONRIVER.js
  src/utils/networks/types/RIN.js
  src/utils/networks/types/ROP.js
  src/utils/networks/types/XDC.js
Labels: Bug, v6

#4110 fix: eth block quick view popup
  changelog/fix-4110.md
  src/core/components/AppModal.vue
  src/dapps/eth-blocks/components/BlockQuickViewPopup.vue
Labels: Ready, UI, v6

#4116 fix: network switch hardware
  changelog/fix-4116.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/network/components/NetworkSwitch.vue
Labels: Bug, v6

#4119 fix: 🐛 release build fixes
  changelog/fix-4109.md
  changelog/fix-4119.md
  changelog/fix-4121.md
  package-lock.json
  package.json
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/swap/ModuleSwap.vue
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Bug, v6

#4111 release: 🔥 v6.6.4
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  src/components/MewTooltip/MewTooltip.vue
  src/core/components/AppModal.vue
  src/core/helpers/matchNetwork.js
  src/core/store/global/actions.js
  src/core/store/global/getters.js
  src/core/store/global/mutations.js
  src/core/store/global/state.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/eth-blocks/components/BlockQuickViewPopup.vue
  src/dapps/eth-blocks/metainfo.js
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepOneAmount.vue
  src/dapps/stakewise/metainfo.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/confirmation/components/SuccessModal.vue
  src/modules/confirmation/handlers/errorHandler.js
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/moon-pay/components/MoonPaySellComponent.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/translations/create-wallet/en_US.json
  src/translations/create-wallet/ru_RU.json
  src/translations/dapps-ens/en_US.json
  src/translations/en_US.js
  src/translations/ru_RU.js
  src/utils/networks/types/BSC.js
  src/utils/networks/types/ETC.js
  src/utils/networks/types/ETH.js
  src/utils/networks/types/GO.js
  src/utils/networks/types/GOERLI.js
  src/utils/networks/types/KOV.js
  src/utils/networks/types/MATIC.js
  src/utils/networks/types/MINTME.js
  src/utils/networks/types/MOONBEAM.js
  src/utils/networks/types/MOONRIVER.js
  src/utils/networks/types/RIN.js
  src/utils/networks/types/ROP.js
  src/utils/networks/types/XDC.js
  src/v5_translations/dapps-ens/en_US.json
  src/views/TheWalletView.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  src/views/layouts-default/TheTeamLayout.vue
Labels: Release, Ready

#4130 Sentry: check for baseList undefined
  changelog/fix-4130.md
  package-lock.json
  package.json
  src/modules/swap/handlers/handlerSwap.js
Labels: Bug, Fixed, v6

#4057 Devop: Kleros name tags integration for address book
  changelog/devop-4057.md
  connections.js
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/views/TheWalletView.vue
Labels: Devop, Ready, v6

#4127 fix: Mnemonic Phrase network changing
  changelog/fix-4127.md
  src/views/TheWalletView.vue
Labels: Bug, Fixed, v6

#4129 chore: 👷 reenable tracking popup as is
  .github/workflows/github-release.yml
  CHANGELOG.md
  package-lock.json
  package-test.js
  package.json
  scripts/generateOfflineFiles.sh
  scripts/generateReleaseFiles.sh
  src/core/components/AppTransactionFee.vue
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/balance/ModuleBalance.vue
  src/modules/balance/ModuleTokens.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/swap/ModuleSwap.vue
  src/views/TheWalletView.vue
  src/views/layouts-wallet/TheSwapLayout.vue
Labels: Devop, Ready

#4156 fix: 🐛 build
  package-test.js
Labels: Ready, Fixed
