Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-02, with the labels that each got.

#3657 V5/bitbox fix
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/wallets/hardware/bitbox/digitalBitboxUsb.js
Labels: Release, Ready

#3662 fix: 🐛 unstoppable layer2 resolver
  changelog/fix-3662.md
  package-lock.json
  package.json
  src/modules/name-resolver/resolvers/uns.js
Labels: Bug, Ready

#3654 Sentry: Unidentified prop type
  changelog/fix-3644.md
  changelog/sentry-3654.md
  package-lock.json
  package-test.js
  package.json
  src/core/store/global/getters.js
Labels: Fixed, v6

#3658 fix: 🐛 Handle Text Overflow
  changelog/ui-3658.md
  src/modules/balance/ModuleTokens.vue
Labels: UI, v6

#3659 Devop: 🔧 Added Gas Switch Tracker
  changelog/devop-3659.md
  src/core/components/AppNetworkSettingsModal.vue
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
Labels: Devop, v6

#3663 fix: 🐛 trezor popup
  changelog/fix-3663.md
  package-lock.json
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
Labels: Fixed, v6

#3650 fix: hide intercom button when users reach the footer
  changelog/fix-3650.md
  package-lock.json
  package-test.js
  package.json
  src/app.vue
Labels: Bug, UI, v6

#3670 fix: 🐛 bsc popup
  changelog/fix-3670.md
  src/core/components/AppAddrQr.vue
  src/translations/interface/en_US.json
Labels: Bug, Ready

#3675 release: 🔥 v6.4.5-hotfix.1
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/dapps/DAPP_INTEGRATION.md
Labels: Release, Ready

#3679 chore: exclude packages
  changelog/chore-3679.md
  package-test.js
Labels: Devop, Ready

#3669 release: 🔥 v6.4.6
  CHANGELOG.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/app.vue
  src/core/components/AppAddrQr.vue
  src/core/components/AppNetworkSettingsModal.vue
  src/core/components/AppTransactionFee.vue
  src/core/store/addressBook/state.js
  src/core/store/global/getters.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/dapps/staked-dapp/components/staked-stepper/StakedStepper.vue
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/errorHandler.js
  src/modules/analytics-opt-in/handlers/configs/configCategories.js
  src/modules/analytics-opt-in/handlers/handlerAnalytics.mixin.js
  src/modules/balance/ModuleTokens.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/name-resolver/resolvers/uns.js
  src/modules/send/handlers/handlerSend.js
  src/translations/interface/en_US.json
Labels: Release, Ready

#3672 devop: update team name
  changelog/devop-3672.md
  package.json
  src/views/layouts-default/TheTeamLayout.vue
Labels: Devop, Ready, v6

#3677 devop: 🔧 mew components update
  changelog/devop-3677.md
  package-lock.json
  package.json
  src/dapps/staked-dapp/components/staked-stepper/StakedCreatePasswordDialog.vue
  src/dapps/staked-dapp/components/staked-stepper/staked-steps/StepFourReview.vue
Labels: Devop, Ready, v6

#3688 devop: 👷 minor change to career ui so we can add more optional fields
  changelog/devop-3688.md
  package-audit.js
  package-lock.json
  package.json
  src/views/layouts-default/TheCareersLayout.vue
Labels: Devop, Ready

#3689 devop: 👷 fix providers order, attempt to fix empty response from changelly
  changelog/devop-3672.md
  changelog/devop-3674.md
  changelog/devop-3689.md
  package-lock.json
  package-test.js
  package.json
  src/modules/swap/handlers/handlerSwap.js
  src/modules/swap/handlers/providers/changelly.js
Labels: Devop, Ready

#3691 fix: 🐛 issue with tokens with 0 decimals
  changelog/fix-3691.md
  package-lock.json
  package.json
  src/modules/send/ModuleSend.vue
Labels: Ready, Fixed
