Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-11, with the labels that each got.

#4339 devop: 🔧 add new tracking methods for matomo
  changelog/devop-4339.md
  changelog/fix-4327.md
  package-lock.json
  src/main/mainApp.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/utils/web3-provider/methods/eth_sendTransaction.js
Labels: Devop, Ready

#4341 Fix/staging
  changelog/fix-4314.md
  package-lock.json
  package-test.js
  package.json
  src/core/components/TheDappHeader.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/eth-blocks/components/DateSelectorPopup.vue
  src/modules/access-wallet/software/handlers/mnemonic/errorHandler.js
  src/modules/balance/components/BalanceAddressPaperWallet.vue
  src/modules/toast/handler/handlerToast.js
  src/modules/tools/ModuleToolsOfflineHelper.vue
Labels: Ready, Fixed

#4346 fix: 🐛 aave amount
  src/dapps/aave-dapp/components/overlays/AaveRepayOverlay.vue
Labels: Ready, Fixed

#4294 Fix: Dont own token error when token decimals are 0
  CHANGELOG.md
  changelog/devop-4302.md
  changelog/devop-4308.md
  changelog/devop-4315.md
  changelog/devop-4332.md
  changelog/devop-4339.md
  changelog/devop-4354.md
  changelog/feat-4233.md
  changelog/fix-4239.md
  changelog/fix-4273.md
  changelog/fix-4284.md
  changelog/fix-4287.md
  changelog/fix-4290.md
  changelog/fix-4294.md
  changelog/fix-4295.md
  changelog/fix-4297.md
  changelog/fix-4300.md
  changelog/fix-4304.md
  changelog/fix-4306.md
  changelog/fix-4307.md
  changelog/fix-4314.md
  changelog/fix-4318.md
  changelog/fix-4327.md
  connections.js
  package-audit.js
  package-lock.json
  package.json
  src/core/components/TheDappHeader.vue
  src/core/configs/configRoutes.js
  src/core/router/routes-wallet.js
  src/core/store/external/actions.js
  src/dapps/aave-dapp/components/overlays/AaveRepayOverlay.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/eth-blocks/components/DateSelectorPopup.vue
  src/modules/access-wallet/software/handlers/mnemonic/errorHandler.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModulePaperWallet.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/send/ModuleSend.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/modules/toast/handler/handlerToast.js
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/TheWalletView.vue
Labels: Bug, Fixed, v6

#4344 fix: 🐛 disable compounding on stakewise on goerli
  changelog/fix-4344.md
  package-lock.json
  src/dapps/stakewise/modules/ModuleStakewiseRewards.vue
  src/modules/access-wallet/common/helpers.js
  src/modules/toast/handler/handlerToast.js
Labels: Ready, Fixed

#4357 release: 🔥 v6.6.10-hotfix.1
  CHANGELOG.md
  connections.js
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/core/store/external/actions.js
  src/modules/network/components/NetworkSwitch.vue
  src/views/TheWalletView.vue
Labels: Devop, Ready

#4325 fix: 🐛 revert select network
  changelog/fix-4325.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/modules/network/ModuleNetwork.vue
Labels: Bug, v6

#4309 fix: footer submenu icons
  changelog/fix-4309.md
  connections.js
  package-lock.json
  src/views/TheWalletView.vue
  src/views/components-default/TheDefaultFooter.vue
Labels: UI, v6

#4298 fix: 🐛 history notification overlap
  changelog/devop-4324.md
  changelog/fix-4298.md
  changelog/fix-4322.md
  changelog/fix-4326.md
  changelog/fix-4328.md
  changelog/fix-4338.md
  changelog/ui-4336.md
  package-lock.json
  src/assets/images/icons/dapps/icon-dapp-aave.svg
  src/assets/images/icons/dapps/icon-dapp-ensmanager.svg
  src/assets/images/icons/dapps/icon-dapp-ethblocks.svg
  src/assets/images/icons/dapps/icon-dapp-stake.svg
  src/assets/images/icons/dapps/icon-dapp-stakewise.svg
  src/components/MewBadge/MewBadge.vue
  src/components/MewBlockie/MewBlockie.vue
  src/components/MewNotification/MewNotification.vue
  src/components/MewTokenContainer/MewTokenContainer.vue
  src/components/MewTransformHash/MewTransformHash.vue
  src/core/components/TheDappHeader.vue
  src/core/helpers/blockies.js
  src/core/helpers/copy.js
  src/dapps/aave-dapp/TheAaveLayout.vue
  src/dapps/aave-dapp/handlers/supportedNetworks.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/manage/ManageUploadWebsite.vue
  src/dapps/eth-blocks/TheEthBlocksLayout.vue
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/dapps/stakewise/TheStakewiseLayout.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/transfer-history/ModuleTransferHistory.vue
  src/views/components-default/HomeFeaturesSwap.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
  src/views/layouts-default/TheSecurityPolicyLayout.vue
Labels: UI, v6

#4225 fix: 🐛 dapp button capitalization on mew btn
  changelog/fix-4225.md
  changelog/fix-4236.md
  changelog/fix-4348.md
  package-lock.json
  src/components/MewButton/MewButton.vue
  src/modules/dapps-center/ModuleDappsCenter.vue
  src/modules/swap/ModuleSwapRates.vue
Labels: Bug, UI, v6

#4368 fix: add tooltip to show full address on address table
  changelog/fix-4368.md
  src/modules/settings/components/SettingsAddressTable.vue
Labels: Devop, Ready, v6

#4333 fix: fix dashboard table text content size
  CODEOWNERS
  changelog/fix-4333.md
  changelog/fix-4361.md
  changelog/fix-4371.md
  changelog/fix-4372.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/config.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceTable.vue
  src/utils/networks/types/XDC.js
Labels: Bug, UI, v6

#4371 Fix: 'Address verified' message displaying without verifying on Trezor
  changelog/fix-4371.md
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/balance/ModuleBalanceCard.vue
Labels: Bug, Fixed, v6

#4372 Fix: cannot read properties 'mintData' on ETH Blocks
  changelog/fix-4372.md
  fetchLists/lists/tokens.json
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
Labels: Bug, Fixed, v6

#4360 Fix: 'Add token' button active when symbol is empty
  changelog/fix-4360.md
  package-lock.json
  src/modules/balance/components/TokenAddCustom.vue
  src/views/layouts-default/TheToolsLayout.vue
Labels: Bug, Fixed, v6

#4382 sync to staging
  CODEOWNERS
  changelog/fix-4333.md
  changelog/fix-4360.md
  changelog/fix-4361.md
  changelog/fix-4368.md
  changelog/fix-4371.md
  changelog/fix-4372.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/config.js
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/hardware/handlers/hardwares/trezor/index.js
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/components/BalanceTable.vue
  src/modules/balance/components/TokenAddCustom.vue
  src/modules/settings/components/SettingsAddressTable.vue
  src/utils/networks/types/XDC.js
  src/views/layouts-default/TheToolsLayout.vue
Labels: Devop, Ready

#4385 fix: 🐛 matomo events for web3 wallet, ledger switching button to gree…
  changelog/fix-4385.md
  package-lock.json
  package.json
  src/modules/confirmation/ModuleConfirmation.vue
Labels: Devop, Ready
