Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2022-07, with the labels that each got.

#3906 fix: fix ethblocks tx fee popup
  changelog/fix-3905.md
  changelog/fix-3906.md
  changelog/fix-3945.md
  fetchLists/index.js
  package-lock.json
  package-test.js
  package.json
  src/dapps/eth-blocks/modules/ModuleEthBlockBatchMinting.vue
  src/modules/send/ModuleSend.vue
Labels: Ready, Fixed, v6

#3905 fix: 🐛 gas estimate max bug
  changelog/fix-3905.md
  package-lock.json
  src/modules/send/ModuleSend.vue
Labels: Bug, v6

#3967 Devop/nightwatch
  .gitignore
  builds/defaultConfig.js
  fetchLists/index.js
  nightwatch.conf.js
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppAddrQr.vue
  src/core/components/AppGetStarted.vue
  src/core/mixins/stake.mixin.js
  src/dapps/ens-manager-dapp/components/manage/ManageMulticoins.vue
  src/dapps/ens-manager-dapp/handlers/helpers/supportedNetworks.js
  src/dapps/ens-manager-dapp/metainfo.js
  src/dapps/staked-dapp/components/StakedStatus.vue
  src/dapps/staked-dapp/handlers/supportedNetworks.js
  src/dapps/staked-dapp/metainfo.js
  src/dapps/stakewise/handlers/configs.js
  src/dapps/stakewise/helpers/index.js
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/software/components/AccessWalletPrivateKey.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/swap/ModuleSwap.vue
  src/utils/web3-provider/methods/utils.js
  src/views/components-default/HomeLanding.vue
  src/views/components-default/TheDefaultWalletBanner.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/components-wallet/WalletPromoPopUp.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  tests/e2e/.eslintrc.js
  tests/e2e/custom-assertions/elementCount.js
  tests/e2e/custom-commands/customExecute.js
  tests/e2e/custom-commands/openHomepage.js
  tests/e2e/custom-commands/openHomepageClass.js
  tests/e2e/globals.js
  tests/e2e/page-objects/homepage.js
  tests/e2e/specs/access-wallet.js
  tests/e2e/specs/create-wallet-test.js
  tests/e2e/specs/sanity-test.js
  tests_output/CHROME_103.0.5060.66_Windows_access-wallet.xml
  tests_output/access-wallet.xml
Labels: Devop, Ready

#3911 fix: 🐛 tools items title
  changelog/devop-3968.md
  changelog/fix-3911.md
  changelog/fix-3966.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppPartnersBlock.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/modules/tools/ModuleToolsGenerateKeystore/ModuleToolsGenerateKeystore.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/translations/about-us/en_US.json
  src/translations/about-us/ru_RU.json
  src/translations/careers/en_US.json
  src/translations/en_US.js
  src/translations/home/en_US.json
  src/translations/how-it-works/en_US.json
  src/translations/ru_RU.js
  src/translations/team/en_US.json
  src/views/components-default/CompanyCommunity.vue
  src/views/components-default/CompanyOurStory.vue
  src/views/components-default/CompanyWhatIsMew.vue
  src/views/components-default/HomeEthBlocks.vue
  src/views/components-default/HomeFeaturesDapps.vue
  src/views/components-default/HomeFeaturesTokens.vue
  src/views/components-default/HomeSocials.vue
  src/views/components-default/HowItWorksDappsCenter.vue
  src/views/components-default/HowItWorksMore.vue
  src/views/components-default/HowItWorksSend.vue
  src/views/components-default/HowItWorksSwap.vue
  src/views/components-default/HowItWorksTokens.vue
  src/views/layouts-default/TheCareersLayout.vue
  src/views/layouts-default/TheCompanyLayout.vue
  src/views/layouts-default/TheTeamLayout.vue
Labels: Ready, UI, v6

#3966 Sentry: undefined property isActive
  changelog/fix-3966.md
  package-lock.json
  src/modules/swap/components/SwapProvidersList.vue
Labels: Bug, Fixed, v6

#3984 Sentry: Rate limit exceeded 429 error
  .gitignore
  changelog/devop-3993.md
  changelog/devop-3998.md
  changelog/devop-4000.md
  changelog/feat-3933.md
  changelog/fix-3977.md
  changelog/fix-3979.md
  changelog/fix-3982.md
  changelog/fix-3983.md
  changelog/fix-3984.md
  package-lock.json
  package-test.js
  package.json
  src/assets/images/hardware-wallets/Bluetooth.svg
  src/assets/images/hardware-wallets/CoolwalletMEW_new.png
  src/assets/images/hardware-wallets/Ledger_Device_main.svg
  src/assets/images/hardware-wallets/USB.svg
  src/assets/images/partners/buitl-w-rivet-dark-bg.svg
  src/assets/images/partners/buitl-w-rivet-light-bg.svg
  src/core/components/AppPartnersBlock.vue
  src/main/errorHandler.js
  src/modules/access-wallet/ModuleAccessWalletHardware.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedgerX.vue
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/address-book/handlers/handlerMulticoins.js
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/message/ModuleMessageVerify.vue
  src/modules/swap/ModuleSwap.vue
  src/views/layouts-default/TheBuyHardwareWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  tests/e2e/functions.js
  tests/e2e/specs/access-wallet.js
  tests/e2e/specs/create-wallet-test.js
  tests/e2e/specs/sanity-test.js
  tests_output/CHROME_103.0.5060.66_Windows_access-wallet.xml
  tests_output/access-wallet.xml
Labels: Bug, Fixed, v6

#3979 Fix: address book validation
  changelog/fix-3979.md
  package-lock.json
  package.json
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/address-book/handlers/handlerMulticoins.js
Labels: Bug, Fixed, v6

#4002 devop: offline build actually run offline build
  changelog/devop-4006.md
  changelog/fix-3970.md
  changelog/fix-4001.md
  changelog/fix-4002.md
  fetchLists/lists/tokens.json
  nightwatch.conf.js
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppGetStarted.vue
  src/core/components/AppNetworkSettingsModal.vue
  src/core/components/AppTransactionFee.vue
  src/core/router/routes-offline-default.js
  src/core/router/routes-offline-wallet.js
  src/main/offlineApp.vue
  src/modules/access-wallet/ModuleAccessWalletSoftware.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/components/CreateWalletSoftwareOverview.vue
  src/modules/message/ModuleMessageVerify.vue
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/components/MoonPayBuyComponent.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/notifications/ModuleNotifications.vue
  src/modules/tools/ModuleToolsConvert.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/StepOne.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/TheWalletView.vue
  src/views/components-default/HomeFeaturesSend.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletSideMenu.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
  src/views/layouts-default/TheCreateWalletLayout.vue
  tests/e2e/specs/create-wallet-mnemonic-test.js
  tests/e2e/specs/footer-tools.js
Labels: Devop, Ready

#4006 Devop: Nightwatch Tool Tests
  changelog/devop-4006.md
  package-audit.js
  src/modules/message/ModuleMessageVerify.vue
  src/modules/tools/ModuleToolsConvert.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/GenerateKeystoreDialog.vue
  src/modules/tools/ModuleToolsGenerateKeystore/components/StepOne.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/components-default/TheDefaultFooter.vue
  tests/e2e/specs/footer-tools.js
Labels: Devop, v6

#3991 devop: 🔧 disable swap for cool wallet
  changelog/feat-3884.md
  changelog/fix-3808.md
  changelog/fix-3991.md
  fetchLists/lists/tokens.json
  package-lock.json
  package.json
  src/core/components/TheWrapperDapp.vue
  src/core/store/global/getters.js
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/ens-manager-dapp/components/register/Register.vue
  src/dapps/ens-manager-dapp/components/reverse/EnsReverseLookup.vue
  src/dapps/ens-manager-dapp/configsRoutes.js
  src/dapps/ens-manager-dapp/handlers/abi/abiBaseRegistrar.js
  src/dapps/ens-manager-dapp/handlers/abi/abiRegistrarController.js
  src/dapps/ens-manager-dapp/handlers/abi/abiRegistry.js
  src/dapps/ens-manager-dapp/handlers/abi/abiResolver.js
  src/dapps/ens-manager-dapp/handlers/handlerENSManagerInterface.js
  src/dapps/ens-manager-dapp/handlers/handlerEnsManager.js
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/dapps/ens-manager-dapp/metainfo.js
  src/dapps/ens-manager-dapp/modules/ModuleRegisterDomain.vue
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/common/walletTypes.js
  src/modules/access-wallet/hardware/handlers/hardwares/coolwallet/index.js
  src/modules/address-book/ModuleAddressBook.vue
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/name-resolver/index.js
  src/modules/name-resolver/resolvers/ens.js
  src/modules/name-resolver/resolvers/uns.js
Labels: Ready, v6

#4014 fix: undefined tx data
  changelog/feat-4021.md
  changelog/fix-3980.md
  changelog/fix-3986.md
  changelog/fix-4008.md
  changelog/fix-4010.md
  changelog/fix-4014.md
  changelog/fix-4017.md
  changelog/fix-4023.md
  changelog/fix-4024.md
  changelog/fix-4033.md
  changelog/fix-4035.md
  changelog/fix-4039.md
  changelog/fix-4043.md
  changelog/fix-4045.md
  connections.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/team/kealii.png
  src/modules/access-wallet/common/components/AccessWalletAddressNetwork.vue
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hardware/handlers/hardwares/ledger/errorHandler.js
  src/modules/access-wallet/software/handlers/mnemonic/index.js
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/create-wallet/components/CreateWalletKeystore.vue
  src/modules/create-wallet/components/CreateWalletMnemonicPhrase.vue
  src/modules/create-wallet/handlers/handlerCreateWallet.js
  src/modules/moon-pay/ModuleMoonPay.vue
  src/modules/moon-pay/handlers/handlerOrder.js
  src/modules/send/ModuleSend.vue
  src/modules/settings/ModuleSettings.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/components/SwapProvidersList.vue
  src/views/layouts-default/TheTeamLayout.vue
Labels: Ready, v6

#3986 fix: 🐛 update team page
  changelog/fix-3986.md
  connections.js
  fetchLists/lists/tokens.json
  package-audit.js
  package-lock.json
  package.json
  src/assets/images/team/kealii.png
  src/views/layouts-default/TheTeamLayout.vue
Labels: v6

#4008 Fix: contact address invalid prop error
  changelog/fix-4008.md
  package-lock.json
  package.json
  src/modules/address-book/components/AddressBookAddEdit.vue
  src/modules/settings/ModuleSettings.vue
Labels: Bug, Fixed, v6

#4023 fix: buy/sell after changing language
  changelog/fix-4023.md
  package-lock.json
  package.json
  src/modules/moon-pay/handlers/handlerOrder.js
Labels: Bug, Fixed, v6

#4043 Fix: Address book allows more than 10 contacts
  changelog/fix-4043.md
  src/modules/settings/ModuleSettings.vue
Labels: Bug, v6

#4013 feature: ✨ add enkrypt extension home btns
  changelog/feat-4013.md
  package-lock.json
  package.json
  src/assets/images/icons/apple google.svg
  src/views/components-default/HomeLanding.vue
Labels: Feature, v6
