Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2023-01, with the labels that each got.

#4411 Devop: update tokens value module
  CHANGELOG.md
  changelog/devop-4411.md
  changelog/feat-4412.md
  package-audit.js
  package-lock.json
  package-test.js
  package.json
  src/core/store/external/actions.js
  src/modules/balance/ModuleTokens.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/buy-sell/components/BuyComponent.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/nft-manager/components/NftManagerDetails.vue
  src/modules/nft-manager/components/NftManagerSend.vue
  src/modules/nft-manager/handlers/abi/abiERC1155.js
  src/modules/nft-manager/handlers/config/configNft.js
  src/modules/nft-manager/handlers/handlerNftManager.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready, v6

#4434 Fix: NFTs with no names
  changelog/fix-4427.md
  changelog/fix-4434.md
  changelog/fix-4449.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/nft-manager/components/NftManagerDetails.vue
Labels: Bug, Fixed, v6

#4419 Sentry: undefined symbol buy module
  changelog/fix-4419.md
  package-lock.json
  src/modules/buy-sell/components/BuyComponent.vue
Labels: Bug, Fixed, v6

#4452 Fix: Buy crypto selection margin
  changelog/fix-4452.md
  package-lock.json
  package.json
  src/modules/buy-sell/components/BuyComponent.vue
Labels: Bug, Fixed, v6

#4432 Ui: export json button too big
  changelog/devop-4445.md
  changelog/fix-4440.md
  changelog/fix-4441.md
  changelog/fix-4443.md
  changelog/fix-4450.md
  changelog/fix-4451.md
  changelog/ui-4432.md
  changelog/ui-4437.md
  changelog/ui-4456.md
  package-lock.json
  package.json
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/buy-sell/components/BuyProviderComponent.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/message/ModuleMessageSign.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Ready, UI, v6

#4437 UI: Tx confirmation module spelling
  changelog/ui-4437.md
  fetchLists/lists/tokens.json
  package-lock.json
  src/modules/confirmation/ModuleConfirmation.vue
Labels: Ready, UI, v6

#4467 ui: 🎨 buy/sell module alignment
  changelog/ui-4465.md
  package-lock.json
  package-test.js
  package.json
  src/modules/buy-sell/components/BuyComponent.vue
Labels: Ready, UI

#4468 Devop/network coingecko typo
  package-test.js
  src/dapps/aave-dapp/components/AaveAmountForm.vue
  src/dapps/aave-dapp/components/AaveTable.vue
  src/dapps/aave-dapp/components/overlays/AaveRepayOverlay.vue
  src/dapps/aave-dapp/components/overlays/AaveWithdrawOverlay.vue
  src/modules/balance/ModuleBalanceCard.vue
  src/modules/balance/ModuleTokensValue.vue
  src/modules/buy-sell/ModuleBuySell.vue
  src/modules/buy-sell/components/SellComponent.vue
  src/modules/buy-sell/components/TokenSelect.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/nft-manager/components/NftManagerDetails.vue
  src/modules/transfer-history/ModuleTransferHistory.vue
  src/utils/networks/nodes/etc-ethereumclassiccooperative-parity-ws.js
  src/utils/networks/types/GO.js
  src/utils/networks/types/MOONBEAM.js
  src/utils/networks/types/MOONRIVER.js
  src/utils/networks/types/XDC.js
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Devop, Ready

#4469 Fix: Clear button not clearing extra word
  changelog/fix-4469.md
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
Labels: Bug, Fixed, v6

#4498 fix: 🐛 staging build
  package-test.js
Labels: Ready, Fixed

#4504 Fix/staging
  package-lock.json
  package-test.js
  src/dapps/ens-manager-dapp/components/reverse/EnsReverseLookup.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
Labels: Ready, Fixed

#4494 release: 🔥 v6.6.14
  CHANGELOG.md
  builds/defaultConfig.js
  package-lock.json
  package-test.js
  package.json
  src/core/components/AppQrCode.vue
  src/core/router/routes-offline-wallet.js
  src/dapps/ens-manager-dapp/components/reverse/EnsReverseLookup.vue
  src/dapps/ens-manager-dapp/handlers/handlerPermanentName.js
  src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
  src/modules/access-wallet/hybrid/handlers/WalletConnect/index.js
  src/modules/access-wallet/software/components/AccessWalletMnemonic.vue
  src/modules/balance/ModulePaperWallet.vue
  src/modules/balance/components/PaperWalletToPrint.vue
  src/modules/buy-sell/components/BuyProviderComponent.vue
  src/modules/confirmation/ModuleConfirmation.vue
  src/modules/contract/ModuleContractInteract.vue
  src/modules/message/ModuleMessageSign.vue
  src/modules/network/ModuleNetwork.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/swap/handlers/providers/mew-provider-class.js
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/translations/home/en_US.json
  src/views/components-default/TheDefaultFooter.vue
  src/views/components-wallet/TheWalletSideMenu.vue
Labels: Release, Ready
