Repository MyEtherWallet/MyEtherWallet, pull requests merged in 2024-10, with the labels that each got.

#5012 Feat/dapps help links
  .gitignore
  CHANGELOG.md
  builds/defaultConfig.js
  changelog/feat-5012.md
  fetchLists/lists/tokens.json
  package-lock.json
  package-test.js
  package.json
  src/dapps/TheDappHeader.vue
  src/dapps/TheWrapperDapp.vue
  src/dapps/coinbase-staking/TheCoinbaseStakingLayout.vue
  src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
  src/dapps/eth-blocks/TheEthBlocksLayout.vue
  src/dapps/staked-dapp/TheStakedLayout.vue
  src/dapps/stakewise/TheStakewiseLayout.vue
  src/views/components-default/AdBanner.vue
  src/views/components-default/TheDefaultHeader.vue
  src/views/components-default/TheLayoutHeader.vue
Labels: Devop, Feature

#5011 Fix/my tokens img
  changelog/fix-5011.md
  connections.js
  package-lock.json
  src/core/store/wallet/getters.js
  src/modules/balance/ModuleTokensValue.vue
  src/utils/networks/types/HOLESKY.js
  src/utils/networks/types/SEPOLIA.js
Labels: Ready, Fixed

#5018 release: 🔥 v6.9.15
  CHANGELOG.md
  builds/defaultConfig.js
  connections.js
  package-lock.json
  package-test.js
  package.json
  src/assets/images/providers/icon-coinbase.webp
  src/assets/images/providers/icon-moonpay-white.svg
  src/assets/images/providers/icon-simplex-light.svg
  src/assets/images/providers/icon-topper-dark.svg
  src/modules/analytics-opt-in/handlers/configs/buySell.js
  src/modules/buy-sell/ModuleBuySell.vue
  src/modules/buy-sell/components/BuyProviderComponent.vue
  src/modules/buy-sell/components/SellComponent.vue
  src/modules/buy-sell/components/TokenSelect.vue
  src/modules/network/components/NetworkSwitch.vue
  src/modules/nft-manager/ModuleNftManager.vue
  src/modules/nft-manager/components/NftManagerDetails.vue
  src/modules/swap/ModuleSwap.vue
  src/modules/tools/ModuleToolsOfflineHelper.vue
  src/utils/networks/nodes/klaytn-ws.js
  src/views/components-wallet/DashboardBanner.vue
  src/views/layouts-default/TheAccessWalletLayout.vue
Labels: Release, Ready

#5020 Devop/remove amplitude remote
  changelog/devop-5020.md
  package-lock.json
  package.json
  patches/@amplitude+plugin-autocapture-browser+1.0.3.patch
Labels: Ready, Fixed
